### ISSUE TITLE
Finder.app gets confused when multiple datasets exist with the same short name

### ISSUE THREAD

**Issue by dch** [openzfsonosx/zfs#112]
I mentioned this on IRC, and think I nailed it down. Imagine we have:

```
zpool tank
tank/src/freebsd
        /osx
    /vms/freebsd
        /osx
```

Then OSX will display e.g. on Desktop, or in Finder's left hand sidebar, all 4 volumes aka zfs datasets even though the short names are identical.

Since the last 10.9.1 Mavericks update (I think), if 2 datasets exist with the same short name (volume name)  Finder gets very confused, including:
- files in the directory are displayed with the name of the dataset, not the actual file
- clicking on the dataset becomes an infinite recursion 
- flashing quickly, alternating between the correct name and the parent dataset name

This also seemed to break itunes for me, even though itunes itself didn't have duplicate names, itunes would fail to start at all, giving `the itunes application could not be opened an unknown error occurred 13014`.

I might be wrong, but this should be easy enough to duplicate. Since removing all duplicate volume names, this issue has disappeared completely at least for today.

**Comment by JMoVS** [comment]
fully resolved by issue166_lite being merged - set `com.apple.devdisk=on` for the datasets in question or the whole pool
