### ISSUE TITLE
Implement the other 57% of vdev_disk.c

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#134]
illumos 940 lines
https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/fs/zfs/vdev_disk.c

FreeBSD 940 lines
https://github.com/freebsd/freebsd/blob/master/sys/cddl/contrib/opensolaris/uts/common/fs/zfs/vdev_disk.c

ZOL 842 lines
https://github.com/zfsonlinux/zfs/blob/master/module/zfs/vdev_disk.c

OpenZFS on OS X 402 lines
https://github.com/openzfsonosx/zfs/blob/master/module/zfs/vdev_disk.c

**Comment by lundman** [comment]
This is done, and went beyond, since evansus ported over ldi as well.
