### ISSUE TITLE
Detect and handle legacy vdev_disk_io_start change

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#139]
https://github.com/openzfsonosx/zfs/commit/9761d702a12d6adceb22f02da4699061a1d2cf4d

https://github.com/openzfsonosx/zfs/commit/907b60106042c0e825ac9b35a951bf9d855d407d

**Comment by JMoVS** [comment]
What are these ashift-logic commits and is this bug still relevant, @lundman ?

**Comment by lundman** [comment]
Not relevant now, LDI was ported over from illumos so we look quite different now.
