### ISSUE TITLE
Mount volumes from internal drives to be non-ejectable

### ISSUE THREAD

**Issue by glessard** [openzfsonosx/zfs#142]
Currently volumes mounted by OpenZFS appear in the Finder with an associated eject button. Some software treats OpenZFS-mounted volumes differently, possibly for this reason. For example: the backup service Backblaze; upon switching from zevo to openzfs, it stopped backing up my zfs data. I suspect Backblaze mistakenly thinks the volumes are network-mounted.

**Comment by dabrahams** [comment]
What’s the secret? The link is dead! 

Thanks

**Comment by alexwasserman** [comment]
It was a while ago, but, try setting com.apple.mimic_hfs on.
