### ISSUE TITLE
Create override for treating device as non-virtual/whole_disk

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#158]
We now properly treat Core Storage (cannot be partitioned since 10.8.5 and up), ZVOLs, and disk images as "virtual" devices in the ZFS sense.

https://github.com/openzfsonosx/zfs/commit/2ce2fe99033267b2b064c956b8cb29fc588c33aa
(Temporarily lurking in iokitext branch)
[Update: has been merged to master]

However, sometimes it may be desirable to override this. Not sure what a nice syntax per-device would be in the create command. Perhaps an xml/plist or ini file could be specified indicating how each device should be interpreted? Or maybe a global sysctl would be enough?

```
$ cat zpool-devices.conf
#device is_whole_disk
"/dev/disk3" 1
"/Users/joe/zfsdev.bin" 0
"/dev/disk4" 0
```

ZFS on Linux currently has something somewhat similar with their /etc/zfs/vdev_id.conf http://zfsonlinux.org/faq.html#HowDoISetupVdevIdConf

**Comment by JMoVS** [comment]
I think in the last 4 years, we didn't run into the problem of needing this. Closing for now
