### ISSUE TITLE
A situation in which zpool import wired all memory then crashed

### ISSUE THREAD

**Issue by alanruttenberg** [openzfsonosx/zfs#171]
I have discussed this somewhat with @ilovezfs and @evansus .

The situations is that I have several zvols that will become unreadable due to the block size 8192 commit. The proposed repair was to be to copy them to zvols with blocksize 512, update my ZFS, and then copy them to -b 8192 zvols.

Somewhere in that process zpool import started crashing my machine after wiring all memory.

A fix was to boot from a LiveCD that had ZFS 0.6.2 - After several failures, I was able to boot from USB with PCBSD10.0.1-RELEASE-03-13-2014-x64-DVD-USB.iso (I might have booted from DVD, but my writer decided *now* was a good time to fail)

From there I was able to zpool import -f -N <pool>

Guessing that the 512s were the problem I zpool destroyed them and the rebooted into OSX.

Then I was able to zpool import -f <pool> without the pathological memory behavior.

This was with 16G, 3 x mirrored 1.5TB disks + log + cache, total 4.5TB total space, 1.9TB free.

The zpools I was trying to migrate to -b 512 were 100G and 300G

zfs git status # HEAD detached at 459a09b
spl git status # HEAD detached at 2550a8a

For future reference, Sabayon_Linux_14.05_amd64_Minimal.iso, and Sabayon_Linux_14.05_amd64_GNOME.iso booted but didn't agree with my display (scrambled it)

I did not have luck with sysresccd-4.0.1_zfs_0.6.2.iso, wheezy-live-rescue-zfsdaily-20140306-jgoerzen-1.2.iso, ZFSguru-LiveCD-9.2-001-amd64-normal.iso (failed to boot from usb)
I also tried oi-dev-151a8-live-x86.usb, oi-dev-151a8-text-x86.usb - these booted but turned out to be 32bit and so couldn't deal with my larger disks.

For the successful image I converted to .img with 
hdiutil convert -format UDRW -o PC.img PCBSD10.0.1-RELEASE-03-13-2014-x64-DVD-USB.iso then copied to USB with
sudo dd  bs=1048576 if=PC.img.dmg of=/dev/rdisk6

FWIW My machine is a QUO-based hackintosh, 16G ram, i7-3770 @ 3.5Ghz, external Dell 24" monitor, 1920x1200, using Intel integrated graphics. OSX 10.9.2

**Comment by ilovezfs** [comment]
Closing as stale. The memory model has entirely changed since this was reported.
