### ISSUE TITLE
nfs server ... not responding vs zfs mount -a

### ISSUE THREAD

**Issue by rottegift** [openzfsonosx/zfs#179]
In head/master today:

$ zfs import -N Dual
$ zfs mount -a
nfs server ...: not  responding
nfs server ...: not  responding
...

and in another terminal:

$ zfs mount
[hangs for several minutes then]
nfs server ...: not  responding
...

When the NFS server eventually returns, the zfs mount -a completes.

I am reasonably sure that this is new behaviour (somewhere in the range of 6-8 May).
1. Shouldn't "zfs mount -a" work even if an NFS filesystem isn't responding?
2. Shouldn't "zfs mount" give details independent of all other VFSes' issues?

**Comment by JMoVS** [comment]
Hope this is not affecting @rottegift nowadays anymore :D
