### ISSUE TITLE
Hangs on shutdown fairly consistently

### ISSUE THREAD

**Issue by NoEffex** [openzfsonosx/zfs#180]
I have 2 1TB hard drives on a striped zpool called tank (-o ashift=12 -O normalization=formD -O casesensitivity=insensitive) and from there I have 2 subvolumes or datasets or whatever they are specifically called (named Thunder and Lightning mounted on /Thunder and /Lightning). Spotlight indexing is disabled for both of them.

When I have my computer on for any decent amount of time this happens, it seems like it shuts down properly if I haven't yet had many applications open, and it doesn't _seem_ to matter which ones I've had open because I've manually closed everything and it still happens. I don't get any interesting error messages other than,

5/9/14 12:17:55.174 AM com.apple.kextd[14]: Error reconsidering volume /Lightning.
5/9/14 12:17:55.175 AM com.apple.kextd[14]: Error reconsidering volume /Thunder.

followed by 

5/9/14 12:17:55.175 AM shutdown[3140]: halt by _netbios: 
5/9/14 12:17:55.000 AM kernel[0]: Kext loading now disabled.
5/9/14 12:17:55.000 AM kernel[0]: Kext unloading now disabled.
5/9/14 12:17:55.175 AM shutdown[3140]: SHUTDOWN_TIME: 1399619875 174841
5/9/14 12:17:55.000 AM kernel[0]: Kext autounloading now disabled.
5/9/14 12:17:55.000 AM kernel[0]: Kernel requests now disabled.
5/9/14 12:17:55.185 AM Dock[314]: XPC error messaging com.apple.IconServicesAgent: Connection interrupted
5/9/14 12:17:55.185 AM Dock[314]: XPC error messaging com.apple.IconServicesAgent: Connection invalid

It hangs (i.e. thing spins forever) when I'm shutting down and when I hold the button it's like blah blah issues like it does when you lose power or something.

**Comment by jwilliams108** [comment]
I still experience this issue using 1.3.0 - about 75% of the time shutdown or restart hangs, with messages in the log 'Error reconsidering volume' for all of my ZFS volumes.

**Comment by ilovezfs** [comment]
@jwilliams108 please try the 1.3.1 rc

**Comment by lundman** [comment]
1.3.0 is indeed where this bug is, and has long since been fixed. I would suggest trying 1.3.1RC5

**Comment by jwilliams108** [comment]
That was so quick! I'll try the latest RC - please ignore my other new issue on the same problem. Thanks!
