### ISSUE TITLE
Resize zvol?

### ISSUE THREAD

**Issue by alanruttenberg** [openzfsonosx/zfs#198]
I'm not sure how to do this. Is there documentation?

From: https://openzfsonosx.org/forum/viewtopic.php?f=26&t=569 joining a thread on different initial topic.

Alan:
Can you say how to use diskutil to do this[resize the zvol after increasing the size with zfs]? I changed the size of a zvol from 100G to 200G as follows:

zfs set volsize=200G zfsroot/mydisk
zfs list shows the increased amount
Before: zfsroot/mydisk 103G 1.38T 42.2G -
After: zfsroot/mydisk 206G 1.38T 42.2G -

However I don't see how to increase the size of the HFS+ partition. There isn't free space, for example, when viewed in Disk Utility

Lundman:
You should at least run "diskutil resizeVolume" but I don't remember if you have to grow the partition too

Alan:
So diskutil resizeVolume can report how much you can change the size. When I ask for that it doesn't suggest I can increase the size.

diskutil resizeVolume /dev/disk12s2 limits
->
For device disk12s2 mydisk:
Current size: 107.0 GB (107030208512 Bytes)
Minimum size: 69.8 GB (69836181504 Bytes)
Maximum size: 107.0 GB (107030208512 Bytes)

**Comment by dhiltonp** [comment]
I'm using a deduped and compressed zvol for my time machine backup to a portable usb drive (thanks to @jeff-dagenais in #66.

Initially, I:

1. created the zvol
2. set dedup and compression
3. partitioned and formatted (HFS+ Journaled) via disk utility
4. set the time machine destination 'sudo tmutil setdestination /Volumes/zvol'

The initial dedup ratio was about 1.05 and compression was about 1.15. After a week's use, I had a dedup ratio of 1.45 (I'm doing development and have many VMs). I estimated the time machine would start deleting data older than about a month, as I hit storage limitations.

1. change the zvol size by about 10x: 'sudo zfs set volsize=5T tank/tm'
2. export/import the zpool
3. discover the /dev/diskXsY via 'mount'

from http://blog.kyodium.net/2010/11/increase-disk-and-partition-size-in.html:
```
$ 'diskutil unmount /Volumes/tm/'
$ sudo gpt show /dev/diskX (note the desired partition's starting block and size)
$ sudo gpt destroy /dev/diskX
$ sudo gpt create -f /dev/diskX
$ sudo gpt add -b starting_block -s size /dev/diskX
$ sudo diskutil resizeVolume diskXs1 R  # note that the slice may have changed - I had a junk partition that I chose not to recreate. 
```

I wish I had initially created the zvol in tank/zvol/tm so I could set a quota for the disk usage, but I didn't and I don't want to re-deduplicate everything. I think 'tm' would still be accessible if 'zfs set canmount=off tank/zvol' were used, but I'm not sure.

**Comment by JMoVS** [comment]
this issue has been stale for roughly 4 years now
