### ISSUE TITLE
4873 zvol unmap calls can take a very long time for larger datasets

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#207]
@evansus Do you think we could benefit from this?

From the OpenZFS Developer mailing list
http://reviews.csiden.org/r/45/
http://reviews.csiden.org/r/22/

http://lists.open-zfs.org/pipermail/developer/2014-June/000659.html
http://lists.open-zfs.org/pipermail/developer/2014-June/000660.html
http://lists.open-zfs.org/pipermail/developer/2014-July/000709.html
http://lists.open-zfs.org/pipermail/developer/2014-July/000710.html
http://lists.open-zfs.org/pipermail/developer/2014-July/000711.html

**Comment by rottegift** [comment]
See commit https://github.com/openzfsonosx/zfs/commit/96b12c676b954b375dce00b6105977ac5d44835d
