### ISSUE TITLE
Cannot securely empty trash on ZFS

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#222]
(Reported by dmilith.)

Although secure erase itself is of dubious utility on ZFS, we still should fix whatever the underlying cause is.

```
The Finder can't complete the operation because some data
in “” can't be read or written.
(Error code -36)
```

http://s.verknowsys.com/5ce88374169236f3c977e5d30d10d068854c8728.png

**Comment by ilovezfs** [comment]
Closing as stale.

**Comment by cbreak-black** [comment]
Securely erasing on a CoW filesystem isn't possible anyway. The only way to properly do it is to use encryption from the start and forget the key.
