### ISSUE TITLE
Cannot empty trash on zfs filesystem

### ISSUE THREAD

**Issue by jameh** [openzfsonosx/zfs#229]
What I did:
* "Move to trash" a folder on my zfs filesystem `zfsdatapool/media` from Finder
* "Empty trash" from dock

Finder says "Emptying the Trash" but hangs forever:
![screen shot 2014-09-06 at 6 44 30 am](https://cloud.githubusercontent.com/assets/1538657/4174949/df05b30c-35b3-11e4-86cd-02de3d3fe0e0.png)

I can't `ls` into `.Trashes/1000/music_orig/GarageBand/` after relaunching Finder:
![screen shot 2014-09-06 at 6 48 58 am](https://cloud.githubusercontent.com/assets/1538657/4174953/06393aca-35b4-11e4-9f57-c2cf8f399a9c.png)

I can't really find anything helpful in the logs, but this is from the time of the crash:
```
Sep  6 06:44:50 Jamies-MacBook-Pro.local loginwindow[72] <Warning>: *** WARNING: -[NSImage compositeToPoint:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
Sep  6 06:44:50 Jamies-MacBook-Pro.local loginwindow[72] <Warning>: *** WARNING: -[NSImage compositeToPoint:fromRect:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
Sep  6 06:44:52 Jamies-MacBook-Pro com.apple.launchd.peruser.1000[316] (com.apple.Finder[350]) <Notice>: Exited: Terminated: 15
 ```

**Comment by ilovezfs** [comment]
Closing as stale.
