### ISSUE TITLE
/zfs/.zfs/snapshot is a file

### ISSUE THREAD

**Issue by vallon** [openzfsonosx/zfs#232]
My /zfs/.zfs/snapshot directory has turned into a file.

```
$ stat -x /zfs/.zfs
  File: "/zfs/.zfs"
  Size: 0            FileType: Directory
  Mode: (0555/dr-xr-xr-x)         Uid: (    0/    root)  Gid: (    0/   wheel)
Device: 45,3   Inode: 3    Links: 1
Access: Thu Sep 18 15:43:52 2014
Modify: Tue Sep 16 23:07:35 2014
Change: Tue Sep 16 23:07:35 2014

# Ok so far

$ stat -x /zfs/.zfs/snapshot
  File: "/zfs/.zfs/snapshot"
  Size: 446598       FileType: Regular File
  Mode: (0600/-rw-------)         Uid: (  502/  justin)  Gid: (   20/   staff)
Device: 1,9   Inode: 624657901    Links: 1
Access: Thu Sep 18 15:19:25 2014
Modify: Tue Oct 29 14:30:42 2013
Change: Tue Oct 29 14:30:42 2013

# oops, snapshot is a file, owned by me

# here is the real file:

$ stat -x /.../175497.emlx 
  File: "/.../175497.emlx"
  Size: 446598       FileType: Regular File
  Mode: (0600/-rw-------)         Uid: (  502/  justin)  Gid: (   20/   staff)
Device: 1,9   Inode: 624657901    Links: 1
Access: Thu Sep 18 15:19:25 2014
Modify: Tue Oct 29 14:30:42 2013
Change: Tue Oct 29 14:30:42 2013

$ diff /zfs/.zfs/snapshot /.../175497.emlx 
(no diffs)
```

OpenZFS on OS X 1.3.0, MacOS 10.9, Intel Mac. I just installed ZFS a few days ago, and have been creating filesystems, etc, so hard to say what operation (or when) this happened. I have had 2 kernel panics as well. I have used (tested) snapshots, so I know the snapshots are working.

Rebooting crashed (kernel panic).

After reboot, the .snapshot dir is a dir again:

```
$ stat -x /zfs/.zfs          
  File: "/zfs/.zfs"
  Size: 0            FileType: Directory
  Mode: (0555/dr-xr-xr-x)         Uid: (    0/    root)  Gid: (    0/   wheel)
Device: 44,3   Inode: 3    Links: 1
Access: Fri Sep 19 12:53:35 2014
Modify: Fri Sep 19 12:52:50 2014
Change: Fri Sep 19 12:52:50 2014
$ stat -x /zfs/.zfs/snapshot
  File: "/zfs/.zfs/snapshot"
  Size: 2            FileType: Directory
  Mode: (0555/dr-xr-xr-x)         Uid: (    0/    root)  Gid: (    0/   wheel)
Device: 44,3   Inode: 4    Links: 2
Access: Fri Sep 19 12:53:58 2014
Modify: Fri Sep 19 12:52:50 2014
Change: Fri Sep 19 12:52:50 2014
```

**Comment by rottegift** [comment]
Just happened with https://github.com/openzfsonosx/zfs/commit/cdfafd4bc97526a7988385ad2531fbd67f87afc7 and https://github.com/openzfsonosx/spl/commit/54857586823c75d4df389f952b6993738d407a6e

Did nothing special to trigger it.   Will edit comment to show workaround (gonna try unmount/remount and then reboot if that fails).

**Comment by dhiltonp** [comment]
This bug is biting me, too.

**Comment by dhiltonp** [comment]
Export/Import is enough to reset it, but I've been hitting the bug frequently.

**Comment by lundman** [comment]
Yes, the .zfs snapshot dir code is definitely suspect. I would recommend you run with snapdir=hidden until we can get to fixing it

**Comment by dhiltonp** [comment]
That's not exactly an option, given that I've been playing with this all weekend: https://github.com/dhiltonp/zhist

**Comment by lundman** [comment]
`snapdir=hidden` simply removes the entry from directory listings, it is still there, and can be accessed as normal. ie `cd .zfs` will work fine (albeit blind). With some care, zhist could still work.

Meanwhile, the priority to fix ctldir is being bumped higher.

**Comment by dhiltonp** [comment]
Thanks!

**Comment by jason-green-io** [comment]
I'm also getting this issue, I can't reliably mount snapshots, at any given time seems the snapshot will begin pointing to seemingly random places in the filesystem. snapdir=hidden doesn't help, happens anyway.

**Comment by ilovezfs** [comment]
try https://openzfsonosx.org/wiki/File:O3x-1011-signed-spl-12a3476-zfs-af351b2.pkg

**Comment by dhiltonp** [comment]
I can't try it; I'm still on 10.10, and the installer requires 10.11.

**Comment by jason-green-io** [comment]
This worked for a few days, now the snapdir is a file again

**Comment by jason-green-io** [comment]
Still an issue in1.5.2

**Comment by ilovezfs** [comment]
No code was changed with snapdir. Just use read only clones since they don't rely on broken magic.

**Comment by jason-green-io** [comment]
Gotcha.. Use boring un-magical readonly=on clones.

**Comment by JMoVS** [comment]
no popups of new cases fpr 3 years, closing for now
