### ISSUE TITLE
Pool won't import if there is a device waiting for IO.

### ISSUE THREAD

**Issue by nixcamic** [openzfsonosx/zfs#244]
Pools don't seem to import if there is a block device that's waiting on IO. 

For example I have two external DVD drives on my computer, and until they've either spun up and read the disk or timed out (on a bad disk) I can't import any pools. (And no, I don't have a ZFS pool on the DVD drive :)

This normally isn't an issue as I'm not putting disks in and out while importing pools but my home folder is on ZFS and I have to make sure I wait for my DVD drive to finish spinning up before logging in, which if I leave a scratched DVD in the drive can take quite a while.

**Comment by lundman** [comment]
We have added code to skip optical media https://github.com/openzfsonosx/zfs/commit/748a695828ce4630a181a1d137945d2f06006ac8

**Comment by ilovezfs** [comment]
And https://github.com/openzfsonosx/zfs/commit/bac481f6351f89c3b419bfc78f0b1ac26080ae8a

**Comment by claunia** [comment]
Would that commit prevent intentionally importing ZFS pool on optical drives?

**Comment by lundman** [comment]
Definitely. but if you really want a pool on optical, just make a symlink to the /dev/diskX node and import -d.

**Comment by claunia** [comment]
so, symlink /dev/disk2 (e.g.) to /dev/whatever to be able to do zpool import MyOpticalPool ? just to be sure to update my article about ZFS cool storage on optical drives on my blog to adjust to the new situation

**Comment by ilovezfs** [comment]
Right, though you ought to try it to be sure it works as expected.
