### ISSUE TITLE
Desktop icon lingers in Yosemite's Finder after pool is exported

### ISSUE THREAD

**Issue by CharlesJS** [openzfsonosx/zfs#246]
In OS X Yosemite, when a ZFS pool which contains a ZFS filesystem (haven't tried it with a straight ZFS pool with no additional filesystems on it) is exported, and the Finder is set to show disks on the desktop, the ZFS pool's icon remains on the desktop even after the pool has been exported. Double-clicking on the Desktop icon at this point causes it to disappear, but until that time it appears that the ZFS pool is imported when in fact it is not.

**Comment by mruepp** [comment]
This I can not confirm: With 1.3.1-rc5 and r2 the Eject from the Finder as well as the zfs unmount command as well as zpool export tank always removed the dataset and subdatasets properly and left never any folder on the desktop. The mountpoint of thank has to be /Volumes/tank and all subdatasets should inherit this property so everything works as expected.

**Comment by CharlesJS** [comment]
If you look at the timestamp on this issue, it is before version 1.3.1 was released. 1.3.0 suffered from this, but AFAICT it seems to be fixed in 1.3.1.
