### ISSUE TITLE
Machine hangs/panics? on AFP

### ISSUE THREAD

**Issue by jollyjinx** [openzfsonosx/zfs#250]
I've moved from ZEVO to O3X. I'm using ZFS on a mac mini 2012 (10.8), 2x256 internal SSDs (caches) and  5x 2TB WD Passport drives ( 4xUSB3.0, 1XFW800) in raidz2 configuration. I have a HDMI screendongle attached to the machine so screensharing works fast), as no real screen is attached to the machine. I haven't had problems with the machine for the last two years and I'm doing a scrub every two weeks.

I use the machine to record Sat>IP television streams so I have a lot of tv shows on the machine. After switching form ZEVO to O3X I had now three kernel panics with HEAD . I can REPLICATE the kernel panic by doing the following:

I mount the ZFS dataset via AFP on a MacBook ( both connected via gigabit)
then I do a zsh commandline:

	KRO>cd /Volumes/media/Media/TV/Tatort/
	KRO>for i in */*.mp4
	for> do
	for> dd if=$i of=/dev/null bs=10m
	for> done

So it's just reading the gigabtye large episodes via dd over AFP. After about 40 to 70 GBytes the dd has a input/output error and following that are Socket not connected errors:

	774222764 bytes transferred in 10.133685 secs (76400910 bytes/sec)
	111+1 records in
	111+1 records out
	1171012259 bytes transferred in 14.534614 secs (80567138 bytes/sec)
	  dd: Lenz/1987.01.25-Lenz-Die Macht des Schicksals.mp4: Input/output error
	240+0 records in
	240+0 records out
	2516582400 bytes transferred in 220.603747 secs (11407705 bytes/sec)
	dd: Lutz/1978.01.01-Lutz-Rot  rot  tot.mp4: Socket is not connected
	dd: Lürsen/2013.06.09-Luersen-Er wird toeten.mp4: Socket is not connected
	dd: Lürsen/2014.05.18-Luersen-Alle meine Jungs.mp4: Socket is not connected
	dd: Markowitz/1991.07.07-Markowitz-Tini.mp4: Socket is not connected
	dd: Markowitz/1993.04.25-Markowitz-Tod einer alten Frau.mp4: Socket is not connected

I was able to reproduce that error three times in a row and the machines were not doing anything at the time I think it's clear that there is problem.
I'm not seeing what has happend as I'm no longer able to connect to the machine  - a ping works, but a ssh does not. Open ssh connections are dead at that time as well and I can't find any kernel panic logs.

I'm switching back to ZEVO for now - luckily the crash happend just before I wanted to upgrade the pool as it's still version 28 so I have a way back.

The third try I did with the latest commit b7b42569a57e12a02c91bd88d1d9f4b8135f4282

**Comment by lundman** [comment]
I believe we fought this valiantly and slayed it, took selfies, etc. Please reopen if it gets resurrected.
