### ISSUE TITLE
unlinked_drain: panic in zap_cursor_retrieve

### ISSUE THREAD

**Issue by lundman** [openzfsonosx/zfs#255]
O3X has been running without unlinked_drain since 1.3.0, and we recently turned it on. We have seen pools with number of unlinked-list entries from 67k to 1.3M. The issue is, sometimes this list contains entries that are bad.

For the ones I have looked at, they are XATTR dirs, where we try to iterate the entries with zap to delete them, but something goes wrong.

Panic reports look like

```
0xffffff81ec333640 : 0xffffff800343a443 mach_kernel : _return_from_trap + 0xe3
0xffffff81ec333660 : 0xffffff7f83e9519c net.lundman.zfs : _zap_leaf_lookup_closest + 0x8c
0xffffff81ec333790 : 0xffffff7f83e927f4 net.lundman.zfs : _fzap_cursor_retrieve + 0x174
0xffffff81ec333810 : 0xffffff7f83e9a754 net.lundman.zfs : _zap_cursor_retrieve + 0x164
0xffffff81ec3338b0 : 0xffffff7f83ea9853 net.lundman.zfs : _zfs_purgedir + 0x73
0xffffff81ec333a80 : 0xffffff7f83ea941c net.lundman.zfs : _zfs_rmnode + 0x7c
0xffffff81ec333ae0 : 0xffffff7f83ee8e16 net.lundman.zfs : _zfs_zinactive + 0x136
0xffffff81ec333b10 : 0xffffff7f83edbb2c net.lundman.zfs : _zfs_vnop_reclaim + 0x1ec
0xffffff81ec333b90 : 0xffffff800354b870 mach_kernel : _vfs_addtrigger + 0xf70
0xffffff81ec333c10 : 0xffffff800354b35a mach_kernel : _vfs_addtrigger + 0xa5a
0xffffff81ec333c60 : 0xffffff80035458f4 mach_kernel : _vflush + 0x274
0xffffff81ec333cd0 : 0xffffff800355089a mach_kernel : _dounmount + 0x37a
0xffffff81ec333d70 : 0xffffff80035502bb mach_kernel : _unmount + 0x17b
```

```
<lundman> zap_get_leaf_byblk (in zfs) (zap.c:529)
<lundman> zap_deref_leaf (in zfs) (zap.c:585)
<lundman> fzap_cursor_retrieve (in zfs) (zap.c:1181)
<lundman> zap_cursor_retrieve (in zfs) (zap_micro.c:1278)
<lundman> zfs_purgedir (in zfs) (zfs_dir.c:594)
<lundman> zfs_rmnode (in zfs) (zfs_dir.c:667)
```

```
0xffffff80be89b000 : 0xffffff7f8a36211c net.lundman.zfs : _zap_leaf_lookup_closest + 0x8c
0xffffff80be89b130 : 0xffffff7f8a35f774 net.lundman.zfs : _fzap_cursor_retrieve + 0x174
0xffffff80be89b1b0 : 0xffffff7f8a3676d4 net.lundman.zfs : _zap_cursor_retrieve + 0x164
0xffffff80be89b250 : 0xffffff7f8a3767d3 net.lundman.zfs : _zfs_purgedir + 0x73
0xffffff80be89b420 : 0xffffff7f8a37639c net.lundman.zfs : _zfs_rmnode + 0x7c
0xffffff80be89b480 : 0xffffff7f8a3b5db6 net.lundman.zfs : _zfs_zinactive + 0x136
0xffffff80be89b4b0 : 0xffffff7f8a3a8acc net.lundman.zfs : _zfs_vnop_reclaim + 0x
```

```
panic(cpu 3 caller 0xffffff7f97482512): "rwlock 0xffffff80b0a4d080 not initialised\n"@spl-rwlock.c:74
Backtrace (CPU 3), Frame : Return Address
0xffffff80b68bac60 : 0xffffff8015b3a811 mach_kernel : _panic + 0xd1
0xffffff80b68bace0 : 0xffffff7f97482512 net.lundman.spl : _rw_enter + 0x32
0xffffff80b68bad10 : 0xffffff7f9755f843 net.lundman.zfs : _zap_get_leaf_byblk + 0xb3
0xffffff80b68bad70 : 0xffffff7f9755d3cc net.lundman.zfs : _zap_deref_leaf + 0xbc
0xffffff80b68bade0 : 0xffffff7f9755ef3a net.lundman.zfs : _fzap_cursor_retrieve + 0x11a
0xffffff80b68bae60 : 0xffffff7f97566ef4 net.lundman.zfs : _zap_cursor_retrieve + 0x164
0xffffff80b68baf00 : 0xffffff7f97575fb3 net.lundman.zfs : _zfs_purgedir + 0x73
0xffffff80b68bb0d0 : 0xffffff7f97575bbc net.lundman.zfs : _zfs_rmnode + 0x7c
0xffffff80b68bb130 : 0xffffff7f975b4fe8 net.lundman.zfs : _zfs_zinactive + 0xe8
0xffffff80b68bb160 : 0xffffff7f975a7d78 net.lundman.zfs : _zfs_vnop_reclaim + 0x258
```

The annoying thing is that `zfs_unlinked_drain()` is called at mount time, and it just iterates the list calling `zget()`. 

Sometime later, when the kernel decides to call `vnop_reclaim()` on them do we crash. It can be never on a completely unused system, hours on mostly idle, and minutes on a busy pool. And not related to the task that was performed at the time.

We could go back to not processing unlinked-drain list, but there is a fair bit of space being lost, more some on Apple where XATTRs are used more frequently.

I added a kstat switch `zfs_vnop_skip_unlinked_drain` so to skip the unlinked drain, and use the pool without (a delayed) panic.

https://github.com/openzfsonosx/zfs/commit/4ea7019efd4d9941794edacec1876561cbb95b73

sysctl -w kstat.zfs.darwin.tunable.skip_unlinked_drain=1

**Comment by lundman** [comment]
Never figured out how it corrupts exactly, no. We only found it happened, not how to trigger it. I was toying with the idea that it could be related to the order of processing. When processing the unlinked-list on IllumOS, they call zget, followed by VN_RELE.  It is my guess that reclaim happens from VN_RELE on IllumOS, and so, the order would be maintained. (The order they were added by)

On OSX, reclaim happens from vnode_create(), and it picks "a likely candidate" for reuse. This means the actual reclaim happens at random time, and in a random order. I am unsure when ZOL reclaims would trigger.

In OSX and FreeBSD, the xattr dirs are always placed on the unlinked-list, instead of the shortcut in vnop `zfs_remove`, and all corrupt entries that I have seen, so far, have been XATTR dirs.

The stab-in-the-dark-guess I was considering was, could the order of unlinking the xattr dir, and its content, matter, since one should always be released before the other, but what if the reverse happened?

When I tried releasing out of order, I couldn't trigger the problem, so it is still a mystery. We have only experienced this from pools used by OSX and ZOL, so it is possible we share the cause of this issue, but lets be honest, I don't have the userbase to really know if FBSD or IllumOS are affected. :)

Part of the fix I did, was to explicitly call `vnode_recycle` on OSX, to ensure the order is maintained. Plus the extra logic to detect corrupt ZAP problem and simply remove it from the unlinked list. Stops the panic at least, but could potentially leak some tiny amount of pool space.

**Comment by lundman** [comment]
Worth noting the `rw_lock` hackery isn't needed and was removed. Only needed to test against ZAP_MAGIC and return EIO to detect it. The patch could be cleaned up if wanted.

**Comment by behlendorf** [comment]
Under Linux the reclaim happens asynchronously at some latter point too.  Basically we just rebuild the inode cache taking the needed references and then let the standard unlink logic recycle the objects.  However, I don't think that matters much in this case.

What worries me is that somehow the ZAPs have gotten damaged but have valid checksums.  __Or...__ perhaps more likely we're mistakenly treating a non-ZAP object as a ZAP, in this case as an xattr directory object.  That would help explain two things.

1) Why the xattr directory object is a fat ZAP.  To trigger the usage of a fat ZAP either there are 2000+ xattrs on this object, or a long key name (~53 characters), _or_ the object isn't really a ZAP and it's being misinterpreted.

2) How a fat ZAP leaf could be damaged like this.  If I understand correctly your patch just checks for leaves with invalid magic values.  This  is something which would cause an ASSERT if these checks were enabled.

Have you tried using zdb to manually inspect the suspect xattr directory ZAPs?  What do they look like?

**Comment by danmcd** [comment]
We've seen this in illumos with heavy CIFS users.  My ZAP that panics per above is all zeros.  Someone mentioned that maybe you fixed this in ZoL with a fix 
https://github.com/zfsonlinux/zfs/commit/4254acb05743dc2175ae76f6e15b0785d4b688fd

We have illumos bug https://www.illumos.org/issues/5833  open for this.

**Comment by behlendorf** [comment]
@danmcd you should take a look at these two related fixes from ZoL as well which are applicable to illumos.  Our users have proven very good about finding these sorts of things!  The first one addresses an issue which can cause a corrupted delete queue.  The second one attempts to do what we can to deal with a system which has had this happen to it.

zfsonlinux/zfs@f5f087e Make xattr dir truncate and remove in one tx
zfsonlinux/zfs@29572cc Fix empty xattr dir causing lockup

**Comment by danmcd** [comment]
So all three should be upstreamed, no?  Do you have someone in ZoL-land who does upstreaming?  Or should I try?  (No wrong answer here, I just don't want to step on someone's toes...)

**Comment by behlendorf** [comment]
Yes, I think they should definitely go upstream.

Speaking for ZoL we've historically never had someone familiar enough with illumos development process to port, build, test, then advocate for the patches to get them included.  We're just not equipped for it, and we certainly don't want to be pushing you untested changes for illumos even if they have been in our tree for a long time.  From my perspective it would be welcome if you could work on upstreaming these patches.

@lundman sorry about hijacking your issue tracker!

**Comment by lundman** [comment]
Ah apologies for my absence, dealing with house moving.  We have all three mentioned patches running as well, but I don't think I can take any credit for the work. :)
