### ISSUE TITLE
Cannot unmount

### ISSUE THREAD

**Issue by fumoboy007** [openzfsonosx/zfs#259]
Sometimes when I do `zpool export MyPoolName`, I get `cannot unmount ‘/MyPoolName’: umount failed`.

`lsof | grep MyPoolName` shows nothing. How can I go about debugging this?

**Comment by lundman** [comment]
Sometimes, spotlight takes a while to unmount, so retrying umount after a few seconds will generally work. If it is persistent, then most likely it is actually issue #260
