### ISSUE TITLE
ARC release bug triggered

### ISSUE THREAD

**Issue by stefarossi** [openzfsonosx/zfs#260]
Hello. I'm running RC2 on OSX 10.8.5.
I have two pools; the first one (with 2-3 datasets) is running fine, while the second one (with ~ 25 datasets), when imported gives me some problems. iTunes refuses to start saying that 'The folder containing "iTunes Library" cannot be found' (earlier it kept complaining on the iTunes Extras file being locked; after moving that file I'm getting that error).
If I try to unmount and export the pool some of the datasets are unmounted correctly, while a few of them get stuck. In Console.app I can see this error:
```
12/12/14 6:50:24.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff811c68b160 (8)-- sorry
[...]
12/12/14 6:58:11.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8125d564f0 (7)-- sorry
```
The pool that is giving me problems was recently upgraded; it was created a while ago on ZOL.

Please let me know if you need me to provide more information.

**Comment by stefarossi** [comment]
Sorry for my late reply. Yes, it is most certainly repeatable. It used to happen for each reboot. I had to use the  ```zfs set mountpoint=none``` command on some of my datasets, and now I can use the other datasets in the pool. However, every time I try to unmount the datasets and export the pool, the error appears again:
```
1/4/15 3:11:18.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:11:23.451 PM WindowServer[147]: dict count after removing entry for window 0x39 is 0
1/4/15 3:11:31.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:11:44.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:11:57.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:11:59.000 PM kernel[0]: macx_swapoff SUCCESS
1/4/15 3:12:11.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:12:24.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:12:37.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:12:50.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:13:03.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:13:16.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:13:29.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
1/4/15 3:13:42.264 PM Dock[330]: no information back from LS about running process
1/4/15 3:13:42.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff8122a564f8 (10)-- sorry
```

**Comment by stefarossi** [comment]
Still happening with 1.3.1-RC5.
```
1/20/15 11:59:26.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
1/20/15 11:59:39.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
1/20/15 11:59:52.000 PM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
1/21/15 12:00:05.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
1/21/15 12:00:18.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
1/21/15 12:00:31.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
1/21/15 12:00:44.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
1/21/15 12:00:57.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
1/21/15 12:01:10.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
1/21/15 12:01:23.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff81103e1670 (18)-- sorry
```
Could somebody please have a look at this? Thank you.

**Comment by lundman** [comment]
I will take a look at this today, could you go through your /var/log/system_log and show me the corresponding

```
ZFS: Loaded module v1.3.0-399_g44c5948, ZFS pool version 5000, ZFS filesystem version 5
```

line for me, just to double check we are looking at latest.

**Comment by ilovezfs** [comment]
pkgutil --pkgs | grep zfs | xargs -I "#" pkgutil --info "#" ; syslog -k Sender kernel | grep "Loaded"

**Comment by stefarossi** [comment]
Here you are:
```
$ pkgutil --pkgs | grep zfs | xargs -I "#" pkgutil --info "#" ; syslog -k Sender kernel | grep "Loaded"
package-id: net.lundman.openzfs.108.pkg
version: 5.0
volume: /
location: 
install-time: 1421793809
Jan 17 19:20:49 localhost kernel[0] <Debug>: SPL: Loaded module v1.3.1-1_g367a110, (ncpu 2, memsize 8589934592, pages 2097152)
Jan 17 19:20:49 localhost kernel[0] <Debug>: ZFS: Loaded module v1.3.1-1_g96c4b5c, ZFS pool version 5000, ZFS filesystem version 5
Jan 18 01:22:34 lenny kernel[0] <Debug>: SPL: Loaded module v1.3.1-1_g367a110, (ncpu 2, memsize 8589934592, pages 2097152)
Jan 18 01:22:34 lenny kernel[0] <Debug>: ZFS: Loaded module v1.3.1-1_g96c4b5c, ZFS pool version 5000, ZFS filesystem version 5
Jan 18 01:32:10 lenny kernel[0] <Debug>: vmci: Loaded @ 0xffffff7f825775bd: Info 0xffffff7f82582a88 Name com.vmware.kext.vmci Version 90.6.3 build-2075534 at Aug 25 2014 17:23:24
Jan 18 01:32:10 lenny kernel[0] <Debug>: vsock: Loaded @ 0xffffff7f82587844: Info 0xffffff7f825923b0 Name com.vmware.kext.vsockets Version 90.6.0 build-2075534 at Aug 25 2014 17:23:26
Jan 18 01:32:10 lenny kernel[0] <Debug>: vmnet: Loaded @ 0xffffff7f82597aaf: Info 0xffffff7f8259f110 Name com.vmware.kext.vmnet Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:28
Jan 18 01:32:10 lenny kernel[0] <Debug>: vmmon: Loaded @ 0xffffff7f825a080d: Info 0xffffff7f825ab068 Name com.vmware.kext.vmx86 Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:22
Jan 18 01:32:12 lenny kernel[0] <Debug>: vmioplug: Loaded @ 0xffffff7f825afcdf: Info 0xffffff7f825b3e20 Name com.vmware.kext.vmioplug.14.1.3 Version 14.1.3 build-2075534 at Aug 25 2014 17:23:30
Jan 19 17:02:25 lenny kernel[0] <Debug>: SPL: Loaded module v1.3.1-1_g367a110, (ncpu 2, memsize 8589934592, pages 2097152)
Jan 19 17:02:25 lenny kernel[0] <Debug>: ZFS: Loaded module v1.3.1-1_g96c4b5c, ZFS pool version 5000, ZFS filesystem version 5
Jan 19 17:06:46 lenny kernel[0] <Debug>: vmci: Loaded @ 0xffffff7f825775bd: Info 0xffffff7f82582a88 Name com.vmware.kext.vmci Version 90.6.3 build-2075534 at Aug 25 2014 17:23:24
Jan 19 17:06:46 lenny kernel[0] <Debug>: vsock: Loaded @ 0xffffff7f82587844: Info 0xffffff7f825923b0 Name com.vmware.kext.vsockets Version 90.6.0 build-2075534 at Aug 25 2014 17:23:26
Jan 19 17:06:46 lenny kernel[0] <Debug>: vmnet: Loaded @ 0xffffff7f82597aaf: Info 0xffffff7f8259f110 Name com.vmware.kext.vmnet Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:28
Jan 19 17:06:46 lenny kernel[0] <Debug>: vmmon: Loaded @ 0xffffff7f825a080d: Info 0xffffff7f825ab068 Name com.vmware.kext.vmx86 Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:22
Jan 19 17:06:48 lenny kernel[0] <Debug>: vmioplug: Loaded @ 0xffffff7f825afcdf: Info 0xffffff7f825b3e20 Name com.vmware.kext.vmioplug.14.1.3 Version 14.1.3 build-2075534 at Aug 25 2014 17:23:30
Jan 20 23:39:27 lenny kernel[0] <Debug>: SPL: Loaded module v1.3.1-1_g367a110, (ncpu 2, memsize 8589934592, pages 2097152)
Jan 20 23:39:27 lenny kernel[0] <Debug>: ZFS: Loaded module v1.3.1-1_g96c4b5c, ZFS pool version 5000, ZFS filesystem version 5
Jan 20 23:43:29 lenny kernel[0] <Debug>: SPL: Loaded module v1.3.1-1_g367a110, (ncpu 2, memsize 8589934592, pages 2097152)
Jan 20 23:43:29 lenny kernel[0] <Debug>: ZFS: Loaded module v1.3.1-56_g63a9a59, ZFS pool version 5000, ZFS filesystem version 5
Jan 20 23:45:18 lenny kernel[0] <Debug>: SPL: Loaded module v1.3.1-1_g367a110, (ncpu 2, memsize 8589934592, pages 2097152)
Jan 20 23:45:18 lenny kernel[0] <Debug>: ZFS: Loaded module v1.3.1-56_g63a9a59, ZFS pool version 5000, ZFS filesystem version 5
Jan 20 23:52:44 lenny kernel[0] <Debug>: vmci: Loaded @ 0xffffff7f825875bd: Info 0xffffff7f82592a88 Name com.vmware.kext.vmci Version 90.6.3 build-2075534 at Aug 25 2014 17:23:24
Jan 20 23:52:44 lenny kernel[0] <Debug>: vsock: Loaded @ 0xffffff7f82562844: Info 0xffffff7f8256d3b0 Name com.vmware.kext.vsockets Version 90.6.0 build-2075534 at Aug 25 2014 17:23:26
Jan 20 23:52:44 lenny kernel[0] <Debug>: vmnet: Loaded @ 0xffffff7f82598aaf: Info 0xffffff7f825a0110 Name com.vmware.kext.vmnet Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:28
Jan 20 23:52:44 lenny kernel[0] <Debug>: vmmon: Loaded @ 0xffffff7f825a180d: Info 0xffffff7f825ac068 Name com.vmware.kext.vmx86 Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:22
Jan 20 23:52:45 lenny kernel[0] <Debug>: vmioplug: Loaded @ 0xffffff7f825b0cdf: Info 0xffffff7f825b4e20 Name com.vmware.kext.vmioplug.14.1.3 Version 14.1.3 build-2075534 at Aug 25 2014 17:23:30
Jan 21 00:04:05 localhost kernel[0] <Debug>: SPL: Loaded module v1.3.1-1_g367a110, (ncpu 2, memsize 8589934592, pages 2097152)
Jan 21 00:04:05 localhost kernel[0] <Debug>: ZFS: Loaded module v1.3.1-56_g63a9a59, ZFS pool version 5000, ZFS filesystem version 5
Jan 21 00:07:04 lenny kernel[0] <Debug>: vmci: Loaded @ 0xffffff7f825775bd: Info 0xffffff7f82582a88 Name com.vmware.kext.vmci Version 90.6.3 build-2075534 at Aug 25 2014 17:23:24
Jan 21 00:07:04 lenny kernel[0] <Debug>: vsock: Loaded @ 0xffffff7f82587844: Info 0xffffff7f825923b0 Name com.vmware.kext.vsockets Version 90.6.0 build-2075534 at Aug 25 2014 17:23:26
Jan 21 00:07:04 lenny kernel[0] <Debug>: vmnet: Loaded @ 0xffffff7f82597aaf: Info 0xffffff7f8259f110 Name com.vmware.kext.vmnet Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:28
Jan 21 00:07:04 lenny kernel[0] <Debug>: vmmon: Loaded @ 0xffffff7f825a080d: Info 0xffffff7f825ab068 Name com.vmware.kext.vmx86 Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:22
Jan 21 00:07:06 lenny kernel[0] <Debug>: vmioplug: Loaded @ 0xffffff7f825afcdf: Info 0xffffff7f825b3e20 Name com.vmware.kext.vmioplug.14.1.3 Version 14.1.3 build-2075534 at Aug 25 2014 17:23:30
Jan 21 17:38:34 localhost kernel[0] <Debug>: SPL: Loaded module v1.3.1-1_g367a110, (ncpu 2, memsize 8589934592, pages 2097152)
Jan 21 17:38:34 localhost kernel[0] <Debug>: ZFS: Loaded module v1.3.1-56_g63a9a59, ZFS pool version 5000, ZFS filesystem version 5
Jan 21 17:41:49 lenny kernel[0] <Debug>: vmci: Loaded @ 0xffffff7f825875bd: Info 0xffffff7f82592a88 Name com.vmware.kext.vmci Version 90.6.3 build-2075534 at Aug 25 2014 17:23:24
Jan 21 17:41:49 lenny kernel[0] <Debug>: vsock: Loaded @ 0xffffff7f82562844: Info 0xffffff7f8256d3b0 Name com.vmware.kext.vsockets Version 90.6.0 build-2075534 at Aug 25 2014 17:23:26
Jan 21 17:41:49 lenny kernel[0] <Debug>: vmnet: Loaded @ 0xffffff7f82598aaf: Info 0xffffff7f825a0110 Name com.vmware.kext.vmnet Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:28
Jan 21 17:41:49 lenny kernel[0] <Debug>: vmmon: Loaded @ 0xffffff7f825a180d: Info 0xffffff7f825ac068 Name com.vmware.kext.vmx86 Version 0207.55.34 build-2075534 at Aug 25 2014 17:23:22
Jan 21 17:41:50 lenny kernel[0] <Debug>: vmioplug: Loaded @ 0xffffff7f825b0cdf: Info 0xffffff7f825b4e20 Name com.vmware.kext.vmioplug.14.1.3 Version 14.1.3 build-2075534 at Aug 25 2014 17:23:30
```

**Comment by stefarossi** [comment]
I don't know if this can help you, but I'd like to point out that my system, when using ZFS, is extremely slow and unresponsive.
My home folder is located on my first pool. Loading a page in Google Chrome can take minutes; the only way to speed it up is to move the ~/Library/Caches folder to an HFS filesystem and to replace it with a symlink.
It's also impossible to empty the trash, which contains some elements from my second pool. The process hangs forever and is impossible to stop. The Finder often shows a weird behavior (sometimes it becomes unresponsive, sometimes it shows .logicx files with PowerPoint icons).

**Comment by lundman** [comment]
You are indeed running RC5 so that is interesting. Not sure why you are having such speed issues, I assume you haven't changed the dataset cache properties or something. Now, we do need to find the trigger of your ARC bug. But then, if emptying the trash hangs, I can imagine you will get ARC bug from it.

Perhaps you can try to chase down what event triggers the bug. Ie

```
import pool
do thing X
export pool
```
until you find the X that causes ARC bug. However, if your home directory in on ZFS, it could be tricky indeed. Is it dataset1 or 2 which triggers the ARC bug?

You could also try halving the ARC max memory "kstat.zfs.darwin.tunable.zfs_arc_max" using
```
sysctl kstat.zfs.darwin.tunable.zfs_arc_max
and
sysctl -w kstat.zfs.darwin.tunable.zfs_arc_max=12345   (<-change number here)
```

**Comment by stefarossi** [comment]
To clarify things a bit: I have two pools, namely 'RAID1' and 'RAID2' (though the pool named 'RAID1' is not actually a RAID configuration).
```
 zpool status
  pool: RAID1
 state: ONLINE
  scan: scrub canceled on Wed Jan  7 01:49:13 2015
config:

	NAME        STATE     READ WRITE CKSUM
	RAID1       ONLINE       0     0     0
	  disk5     ONLINE       0     0     0

errors: No known data errors

  pool: RAID2
 state: ONLINE
  scan: scrub canceled on Tue Dec  9 00:47:38 2014
config:

	NAME        STATE     READ WRITE CKSUM
	RAID2       ONLINE       0     0     0
	  disk6     ONLINE       0     0     0
	  disk7     ONLINE       0     0     0

errors: No known data errors
```
The RAID1 pool is for my home directory. No ARC bugs are logged when using it.
When I import RAID2, if all the datasets have a mountpoint different than 'none', when they get mounted I immediately get the ARC bug, upon importing. If I set the mountpoint of some of the datasets to 'none', I can use the pool without any problems (performance issues aside). I always get the ARC bug when unmounting the datasets stored in RAID2, or when exporting RAID2.
Trying to empty the trash hangs, but does not log any ARC bug error.

This is the ARC max memory value by default. My computer has 8GB of RAM.
```
$ sysctl kstat.zfs.darwin.tunable.zfs_arc_max     
kstat.zfs.darwin.tunable.zfs_arc_max: 5368709120
```
I had already tried lowering that value, trying to decrease RAM usage, down to 1342177280, but I didn't see any effect.
```
$ sudo sysctl -w kstat.zfs.darwin.tunable.zfs_arc_max=1342177280
kstat.zfs.darwin.tunable.zfs_arc_max: 5368709120 -> 1342177280
```
I also set 'primarycache' to 'none'. I first tried 'metadata', then 'none':
```
$ zfs get primarycache RAID1 RAID2
NAME   PROPERTY      VALUE         SOURCE
RAID1  primarycache  none          local
RAID2  primarycache  none          local
```
It's not entirely clear to me what should I do next. Should I move my home directory to an HFS partition, to make debugging easier? And then, what should I do?

**Comment by lundman** [comment]
Ok, you might want to set primarycache (and secondary if you have fiddled with it) back to 'all', otherwise it will be painfully slow.

Just to double check, you are aware that you have no redundancy in either pool right?

Now then, I wonder if the ARC bug really happens that easily, can you
```
import -N RAID2
zfs mount RAID2/datasetnamehere
zfs unmount RAID2/datasetnamehere
```
where you change the datasetnamehere for each different dataset, and see if a specific dataset will cause the issue.   import -N tells it not to mount anything.

**Comment by lundman** [comment]
Also worth noting, I just discovered today that any filesystem marked readonly would fail on unmount, and generally lead to "ARC release bug". But if you don't use readonly, it would not affect you.

https://github.com/openzfsonosx/zfs/commit/14b50f258e5b17bdbd72cb0dd2755a8c75302558

**Comment by stefarossi** [comment]
Hi. Sorry it took me so much.
Setting primarycache and secondarycache back to 'all' improved performance quite a lot, thank you. However, I notice a huge RAM usage during high I/O loads (sometimes kernel_task reaches 4GB or more).
I know that I have no redundancy in my pool at the moment. Sadly I can't afford the mirror disks at the moment, but I'll buy them soon, as I know that my pool configuration is a bit risky. Thanks for double checking.

I found the dataset which is causing problems. It's a 1.98T dataset with a bunch of big files, mostly ranging from 4GB to 12GB (yes, it's my movies dataset). What should I do with it? Should I create a new dataset, move the files and destroy the old one? Or can it helpful for you to debug?

Anyway, regarding your last message, I have a few datasets set to read-only, but apparently they have no problems unmounting...

I also noted that if you mount two datasets with the same name (for example, pool/dataset and pool/test/dataset) weird things happen. I once mounted a dataset with the same name as the dataset holding my home folder, and that crashed a few applications.

**Comment by lundman** [comment]
You can tell the ARC to use less memory if you want to. ZFS is told to use as much memory it can in caches to make things faster for you.  Get current value

sysctl kstat.zfs.darwin.tunable.zfs_arc_max

and set it to a new value:

sysctl -w kstat.zfs.darwin.tunable.zfs_arc_max=1234567890


RC5 definitely had a bug with readonly unmounting, it would say it unmounted, but "umount" process would still be in the processlist, and you'd not be able to export/reboot. It is more likely that this is the problem you have, as opposed to a corrupt pool triggering ARC release bug.

The same dataset name thing is well known, and will be fixed when #116  is done.

**Comment by stefarossi** [comment]
Yes, I know about the sysctl thing (see the previous comments). I notice a huge RAM usage even after lowering that value. Anyway, do you know if it's possible to make it persistent across reboots?

Now I set 'readonly' to 'off' for all my datasets. The dataset which gave problems, however, wasn't readonly.

**Comment by stefarossi** [comment]
OK, now all the datasets in the pool mount and unmount just fine. I think this issue can be closed, since it appears to be fixed with 14b50f2.

By the way, I noticed a lot of these in the logs. Are they normal?
```
2/13/15 2:34:44.000 AM kernel[0]: ZFS: Waiting for reclaim to drain: 0 + 1
```

Thanks a lot for your help!

**Comment by lundman** [comment]
Yes, they are just giving status for how the export is going. Once both lists are 1, it continues.

Persistent settings has been added with zsysctl, but it was not part of RC5. Next version will feature it.

**Comment by lundman** [comment]
Lets also keep an eye on https://github.com/zfsonlinux/zfs/issues/2034 in case the same test case triggers problems for us.

**Comment by stefarossi** [comment]
I'd like to report that I'm still getting these errors, even with 1.3.1-r2.
```
5/3/15 4:04:29.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff8106d4d7f0 (37)-- sorry
5/3/15 4:04:42.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff8106d4d7f0 (37)-- sorry
5/3/15 4:04:55.000 AM kernel[0]: dnode: ARC release bug triggered: 0xffffff8106d4d7f0 (37)-- sorry
```
Now it happens much less often, and I'm sometimes able to export the pool. Sometimes, when the "normal" export fails, exporting with -f succeeds. But not all of the time. I'd suggest reopening this issue.

**Comment by stefarossi** [comment]
Is anybody looking into this?

**Comment by lundman** [comment]
We are aware it is still happening, but not found a way to trigger it reliably so I can work on fixing it. The latest upstream-20150409 branch has newer code in this area as well, so it will be worth trying once we get that pushed out.

**Comment by stefarossi** [comment]
Is there a way I can help? On my machine it happens constantly, and it's a very serious bug for me since it doesn't allow me to shut down the computer properly.

**Comment by lundman** [comment]
If you were running master then that would be interesting. We are under the impression that it is better there :)

**Comment by stefarossi** [comment]
I just started using master today. I’ll try it for a few days, and I’ll let you know!
