### ISSUE TITLE
Invariant disk leftover?

### ISSUE THREAD

**Issue by alanruttenberg** [openzfsonosx/zfs#265]
9 out of 11 disks (including cache)  are listed with long ids in zpool status. Is this a problem? Also notice that diskutil lists the same UUID for 3 of the s9 "make osx happy" partitions are the same.

Below outputs of: 
zpool status
/var/run/disk/by-id  ; ls -lt 
diskutil list 
zdb
diskutil | grep s9

	NAME                                                                STATE     READ WRITE CKSUM
	zfsroot                                                             ONLINE       0     0     0
	  mirror-0                                                          ONLINE       0     0     0
	    /var/run/disk/by-id/media-6B902AD6-2C40-9149-BA59-D0932839B0A8  ONLINE       0     0     0
	    /var/run/disk/by-id/media-EA501A27-DBF9-BA4C-98A1-E529B7207B87  ONLINE       0     0     0
	  mirror-1                                                          ONLINE       0     0     0
	    /var/run/disk/by-id/media-109599AD-3569-4E46-900A-00E1FF67FAE6  ONLINE       0     0     0
	    /var/run/disk/by-id/media-AF717696-FBF3-2748-9BF4-520B97407D36  ONLINE       0     0     0
	  mirror-2                                                          ONLINE       0     0     0
	    /var/run/disk/by-id/media-E2222E9D-96D6-F840-B09B-DF21A03496B9  ONLINE       0     0     0
	    /var/run/disk/by-id/media-40AB1C3F-11F6-9B44-8453-CF57563CA186  ONLINE       0     0     0
	  mirror-3                                                          ONLINE       0     0     0
	    /var/run/disk/by-id/media-456F45ED-660A-7541-B674-BD81A2AECB1D  ONLINE       0     0     0
	    disk10                                                          ONLINE       0     0     0	

	cd /var/run/disk/by-id/ % ls -lt
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-10B76D76-C6FD-4A3A-94DA-A34981EFEF16@ -> /dev/disk0s1
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-7EAA6392-23A9-7849-81B2-F9FEF8A36D3D@ -> /dev/disk1s1
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-BCAE1F11-A58B-40C7-86D4-B20176AD6DB5@ -> /dev/disk0s2
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-F7A1FD16-7C5A-47AB-B86E-8CDBDD744F19@ -> /dev/disk0s3
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-CF7F0444-2BAF-326A-B1F2-1D32C10C578E@ -> /dev/disk0s2
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-C5282F8E-0CF1-33F0-AB25-A3AB738DED70@ -> /dev/disk0s3
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-26CA2897-2BDB-4FA5-ACF8-0ED8F086B53E@ -> /dev/disk2s3
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-4828A0DA-F1D1-4226-BCD6-31C4CA0C1A80@ -> /dev/disk2s1
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-BAB06DFA-5573-490C-8BCE-2E1D6E46FED8@ -> /dev/disk2s2
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-24E90788-D085-3C5F-BF45-6DF4C021A483@ -> /dev/disk2s3
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-79325C20-7570-3F6F-8D92-D676B23067F6@ -> /dev/disk2s2
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-079EC5EB-CDBD-4A1F-AD37-FDCFD72B2301@ -> /dev/disk3s1
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-E28296BC-FA10-459B-B9CA-E759E2F3744D@ -> /dev/disk3s2
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-6403A91D-78D3-37BA-BE63-FCF7FB9576D7@ -> /dev/disk3s2
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-40AB1C3F-11F6-9B44-8453-CF57563CA186@ -> /dev/disk4s1
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-738011D2-1B13-554C-9164-2E07E45653DD@ -> /dev/disk4s9
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-7002670D-9D65-3904-BAAB-8EF91AAAAC9B@ -> /dev/disk4s9
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-456F45ED-660A-7541-B674-BD81A2AECB1D@ -> /dev/disk5s1
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-C643C013-D0C9-AD42-A5A6-744E2BE2F327@ -> /dev/disk5s9
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-00AF586E-8F9F-3643-97CB-CEB34C37C35A@ -> /dev/disk6s9
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-AF717696-FBF3-2748-9BF4-520B97407D36@ -> /dev/disk6s1
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-5A1BE7DF-BFB1-3173-8B79-FE000E419F11@ -> /dev/disk6s9
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-EA501A27-DBF9-BA4C-98A1-E529B7207B87@ -> /dev/disk7s1
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-F4E1C162-26E2-5C46-ABCE-E2DE4F1CD09E@ -> /dev/disk7s9
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-226B6FA0-64AA-34EF-97BF-B056231294F2@ -> /dev/disk7s9
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-54A9D977-406F-8A4D-A939-4952CE014688@ -> /dev/disk8s9
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-6B902AD6-2C40-9149-BA59-D0932839B0A8@ -> /dev/disk8s1
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-5F00D7BD-C18B-3D1C-9080-727991301836@ -> /dev/disk8s9
	
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-109599AD-3569-4E46-900A-00E1FF67FAE6@ -> /dev/disk9s1
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 media-5F6CB2E3-E3AF-2042-A7BF-7A958948E093@ -> /dev/disk9s9
	lrwxr-xr-x  1 root  daemon  12 Dec 27 14:34 volume-2D8C5E10-221E-38FB-BA39-734258620E75@ -> /dev/disk9s9
	
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:34 media-1FB68C24-FB9C-A14E-80F4-D80FE00BA438@ -> /dev/disk10s1
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:34 media-BE73722D-AAB4-D549-AD93-AB1A5B1D1458@ -> /dev/disk10s9
	
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:34 media-930E798A-BCC9-E445-9FE3-43E311485D2B@ -> /dev/disk11s9
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:34 media-E2222E9D-96D6-F840-B09B-DF21A03496B9@ -> /dev/disk11s1
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:34 volume-E0CF8EA7-4F4F-3B67-8B3E-2E2D08037753@ -> /dev/disk11s9
	
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:34 media-1ED9020C-8B89-4A7F-B7A0-32BAFD5A7ECE@ -> /dev/disk12s1
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:34 media-E78697D4-59E2-4DED-BD59-2EA18FA02664@ -> /dev/disk12s2
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:34 volume-B2D13404-796F-3370-8F84-2D4A0F6CEE75@ -> /dev/disk12s2
	
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:35 volume-C0E1E95C-D29E-3CFA-BAEF-ED91C61A95C5@ -> /dev/disk13s2
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:35 media-06DA32C1-CC05-4D0E-9750-9EA842A40851@ -> /dev/disk13s2
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:35 media-FFA6FDC6-19C4-41D6-A26E-B75599769D57@ -> /dev/disk13s1
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:35 volume-C0E1E95C-D29E-3CFA-BAEF-ED91C61A95C5@ -> /dev/disk13s2
	
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:47 media-432C0A9E-C7CD-46BE-8247-80B2DA0C0BB3@ -> /dev/disk14s2
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:35 media-4FA95E12-7C31-46BF-A1ED-01940CF34A46@ -> /dev/disk14s1
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:47 volume-A2AD294F-74FA-3A15-ABE0-5354B9C82AC2@ -> /dev/disk14s2
	
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:35 media-0181BCC0-E673-4FE8-8655-156851AFA749@ -> /dev/disk15s2
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:35 media-0A70221C-204E-427F-B2AE-CC5265B85324@ -> /dev/disk15s1
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:35 volume-0E239BC6-F960-3107-89CF-1C97F78BB46B@ -> /dev/disk15s1
	lrwxr-xr-x  1 root  daemon  13 Dec 27 14:35 volume-D3EC6A29-A293-3E18-B767-2B92A4A53C40@ -> /dev/disk15s2
	
	
	% diskutil list
	
	/dev/disk0
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *128.0 GB   disk0
	   1:                        EFI EFI                     209.7 MB   disk0s1
	   2:                  Apple_HFS LivingRoom              127.2 GB   disk0s2
	   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
	/dev/disk1
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *120.0 GB   disk1
	   1:                        ZFS                         120.0 GB   disk1s1
	   2: 6A945A3B-1DD2-11B2-99A6-080020736631               8.4 MB     disk1s9
	/dev/disk2
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *256.1 GB   disk2
	   1:                        EFI EFI                     209.7 MB   disk2s1
	   2:                  Apple_HFS Desk                    255.2 GB   disk2s2
	   3:                 Apple_Boot Recovery HD             650.0 MB   disk2s3
	/dev/disk3
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *500.1 GB   disk3
	   1:                        EFI EFI                     209.7 MB   disk3s1
	   2:                  Apple_HFS Upper Shelf             499.8 GB   disk3s2
	/dev/disk4
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *1.5 TB     disk4
	   1:                        ZFS                         1.5 TB     disk4s1
	   2:       Microsoft Basic Data                         8.4 MB     disk4s9
	/dev/disk5
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *3.0 TB     disk5
	   1:                        ZFS                         3.0 TB     disk5s1
	   2: 6A945A3B-1DD2-11B2-99A6-080020736631               8.4 MB     disk5s9
	/dev/disk6
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *1.5 TB     disk6
	   1:                        ZFS                         1.5 TB     disk6s1
	   2:       Microsoft Basic Data                         8.4 MB     disk6s9
	/dev/disk7
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *2.0 TB     disk7
	   1:                        ZFS                         2.0 TB     disk7s1
	   2:       Microsoft Basic Data                         8.4 MB     disk7s9
	/dev/disk8
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *2.0 TB     disk8
	   1:                        ZFS                         2.0 TB     disk8s1
	   2:       Microsoft Basic Data                         8.4 MB     disk8s9
	/dev/disk9
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *1.5 TB     disk9
	   1:                        ZFS                         1.5 TB     disk9s1
	   2:       Microsoft Basic Data                         8.4 MB     disk9s9
	/dev/disk10
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *3.0 TB     disk10
	   1:                        ZFS                         3.0 TB     disk10s1
	   2: 6A945A3B-1DD2-11B2-99A6-080020736631               8.4 MB     disk10s9
	/dev/disk11
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *1.5 TB     disk11
	   1:                        ZFS                         1.5 TB     disk11s1
	   2:       Microsoft Basic Data                         8.4 MB     disk11s9
	/dev/disk12
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *17.6 TB    disk12
	   1:                        EFI EFI                     209.7 MB   disk12s1
	   2:                  Apple_HFS Drobo                   17.6 TB    disk12s2
	/dev/disk13
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *214.7 GB   disk13
	   1:                        EFI EFI                     209.7 MB   disk13s1
	   2:                  Apple_HFS iPhoto                  214.4 GB   disk13s2
	/dev/disk14
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *536.9 GB   disk14
	   1:                        EFI EFI                     209.7 MB   disk14s1
	   2:                  Apple_HFS Time Machine 2          536.5 GB   disk14s2
	/dev/disk15
	   #:                       TYPE NAME                    SIZE       IDENTIFIER
	   0:      GUID_partition_scheme                        *322.1 GB   disk15
	   1:                        EFI EFI                     209.7 MB   disk15s1
	   2:                  Apple_HFS iTunes                  321.8 GB   disk15s2
	
	% diskutil list | grep s9
	   2: 6A945A3B-1DD2-11B2-99A6-080020736631               8.4 MB     disk1s9
	   2:       Microsoft Basic Data                         8.4 MB     disk4s9
	   2: 6A945A3B-1DD2-11B2-99A6-080020736631               8.4 MB     disk5s9
	   2:       Microsoft Basic Data                         8.4 MB     disk6s9
	   2:       Microsoft Basic Data                         8.4 MB     disk7s9
	   2:       Microsoft Basic Data                         8.4 MB     disk8s9
	   2:       Microsoft Basic Data                         8.4 MB     disk9s9
	   2: 6A945A3B-1DD2-11B2-99A6-080020736631               8.4 MB     disk10s9
	   2:       Microsoft Basic Data                         8.4 MB     disk11s9
	% zdb
	zfsroot:
	    version: 5000
	    name: 'zfsroot'
	    state: 0
	    txg: 160800026
	    pool_guid: 11525599921928347233
	    errata: 0
	    hostid: 3660128869
	    hostname: 'localhost'
	    vdev_children: 4
	    vdev_tree:
	        type: 'root'
	        id: 0
	        guid: 11525599921928347233
	        children[0]:
	            type: 'mirror'
	            id: 0
	            guid: 11659360043872116845
	            metaslab_array: 38
	            metaslab_shift: 34
	            ashift: 12
	            asize: 2000384688128
	            is_log: 0
	            create_txg: 4
	            children[0]:
	                type: 'disk'
	                id: 0
	                guid: 12789527930152168946
	                path: '/private/var/run/disk/by-id/media-6B902AD6-2C40-9149-BA59-D0932839B0A8'
	                phys_path: '/dev/diskid/DISK-Y3CN2DTGSp1'
	                whole_disk: 1
	                DTL: 912
	                create_txg: 4
	            children[1]:
	                type: 'disk'
	                id: 1
	                guid: 9631193934027935819
	                path: '/private/var/run/disk/by-id/media-EA501A27-DBF9-BA4C-98A1-E529B7207B87'
	                phys_path: '/dev/diskid/DISK-Y3CN2E0GSp1'
	                whole_disk: 1
	                DTL: 911
	                create_txg: 4
	        children[1]:
	            type: 'mirror'
	            id: 1
	            guid: 1750213957219736340
	            metaslab_array: 36
	            metaslab_shift: 33
	            ashift: 12
	            asize: 1500287336448
	            is_log: 0
	            create_txg: 4
	            children[0]:
	                type: 'disk'
	                id: 0
	                guid: 5592394544075990067
	                path: '/private/var/run/disk/by-id/media-109599AD-3569-4E46-900A-00E1FF67FAE6'
	                phys_path: '/dev/diskid/DISK-S2HEJX0C900305p1'
	                whole_disk: 1
	                DTL: 910
	                create_txg: 4
	            children[1]:
	                type: 'disk'
	                id: 1
	                guid: 3468705898681880350
	                path: '/private/var/run/disk/by-id/media-AF717696-FBF3-2748-9BF4-520B97407D36'
	                phys_path: '/dev/diskid/DISK-S2HEJX0CA00263p1'
	                whole_disk: 1
	                DTL: 909
	                create_txg: 4
	        children[2]:
	            type: 'mirror'
	            id: 2
	            guid: 18401647215779754242
	            metaslab_array: 34
	            metaslab_shift: 33
	            ashift: 12
	            asize: 1500287336448
	            is_log: 0
	            create_txg: 4
	            children[0]:
	                type: 'disk'
	                id: 0
	                guid: 5069286759723677467
	                path: '/private/var/run/disk/by-id/media-E2222E9D-96D6-F840-B09B-DF21A03496B9'
	                phys_path: '/dev/diskid/DISK-S2HEJ1DB302077p1'
	                whole_disk: 1
	                DTL: 908
	                create_txg: 4
	            children[1]:
	                type: 'disk'
	                id: 1
	                guid: 12133104694213597855
	                path: '/private/var/run/disk/by-id/media-40AB1C3F-11F6-9B44-8453-CF57563CA186'
	                phys_path: '/dev/diskid/DISK-S2HEJ1DB302082p1'
	                whole_disk: 1
	                DTL: 907
	                create_txg: 4
	        children[3]:
	            type: 'mirror'
	            id: 3
	            guid: 4298004881386479977
	            metaslab_array: 121
	            metaslab_shift: 34
	            ashift: 9
	            asize: 3000578342912
	            is_log: 0
	            create_txg: 5970670
	            children[0]:
	                type: 'disk'
	                id: 0
	                guid: 17267457061317676638
	                path: '/private/var/run/disk/by-id/media-456F45ED-660A-7541-B674-BD81A2AECB1D'
	                whole_disk: 1
	                DTL: 913
	                create_txg: 5970670
	            children[1]:
	                type: 'disk'
	                id: 1
	                guid: 5489192103311484783
	                path: '/dev/disk10s1'
	                whole_disk: 1
	                DTL: 906
	                create_txg: 5970670
	    features_for_read:
	        com.delphix:hole_birth
	        com.delphix:embedded_data
                whole_disk: 1
                DTL: 907
                create_txg: 4
        children[3]:
            type: 'mirror'
            id: 3
            guid: 4298004881386479977
            metaslab_array: 121
            metaslab_shift: 34
            ashift: 9
            asize: 3000578342912
            is_log: 0
            create_txg: 5970670
            children[0]:
                type: 'disk'
                id: 0
                guid: 17267457061317676638
                path: '/private/var/run/disk/by-id/media-456F45ED-660A-7541-B674-BD81A2AECB1D'
                whole_disk: 1
                DTL: 913
                create_txg: 5970670
            children[1]:
                type: 'disk'
                id: 1
                guid: 5489192103311484783
                path: '/dev/disk10s1'
                whole_disk: 1
                DTL: 906
                create_txg: 5970670
    features_for_read:
        com.delphix:hole_birth
        com.delphix:embedded_data

**Comment by alanruttenberg** [comment]
@ilovezfs - cache shows invariant path now. Will report back if that changes later.

**Comment by ilovezfs** [comment]
This works as designed.  /dev is last in the set of default import paths because it is least safe. So when ZFS cannot find a renumbered disk, it will look in the InvariantDisks directories first.
https://github.com/openzfsonosx/zfs/blob/4d4da21ada6e5c910077dd70bfd22e0768da963d/lib/libzfs/libzfs_import.c#L1011-1026

**Comment by alanruttenberg** [comment]
The question is, why can't it find a renumbered disk. Here's the situation. I exported my pool, updated zfs (zfsadm, then sudo make install in spl and zfs). The pool came back fine. I started a scrub. For other reasons I restarted the computer. When it came back up 1/2 the disks (1/2 of each of 4 mirrors) weren't found and my pool was degraded. Rebooted again, same thing. Finally I went through the steps of your comment of Dec 29th and things went back to normal. 

If the that's the design, then I'd say it needs revision.

**Comment by ilovezfs** [comment]
Did this occur with or without https://github.com/openzfsonosx/zfs/commit/e2c409fb8098a22bebf512f98d94f88cce23c018

**Comment by alanruttenberg** [comment]
Looks like with, I checked out head yesterday - 8dc38beacb806b4fa7f13a8907db47d19ba4f285

**Comment by ilovezfs** [comment]
1. Please check.
grep TIMEOUT /usr/libexec/zfs/launchd.d/zpool-import-all.sh 

2. What does, "For other reasons I restarted the computer," mean? What was the reason? How long did the boot take?

3. We need a pastebin of the relevant o3x log files.
wgetpaste -s dpaste /private/var/log/org.openzfsonosx.zpool-import-all.err
wgetpaste -s dpaste /private/var/log/org.openzfsonosx.zpool-import-all.log

4. Pastebin of syslog (from Console.app) during that boot would also possibly be useful.

**Comment by alanruttenberg** [comment]
1.
    export TIMEOUT_SECONDS=60
    export MAXIMUM_SLEEP_ITERATIONS=$((${TIMEOUT_SECONDS} * 10))
    echo "Waiting up to ${TIMEOUT_SECONDS} seconds for the InvariantDisks idle file ${INVARIANT_DISKS_IDLE_FILE} to exist"
	echo "File ${INVARIANT_DISKS_IDLE_FILE} not found within ${TIMEOUT_SECONDS} seconds"

2. I don't recall the specific reason. I had been awake for 10 days and decided to reboot it. I don't recall how long it took to boot. 

3. Neither of those files exist. There is /private/var/log/org.openzfsonosx.zed.log (empty) and /private/var/log/org.openzfsonosx.zed.err (http://pastebin.com/g0rhrVKH)

4. There is a lot of information in syslog and I don't want to review it for privacy leaks. Could you please narrow down what might be of use? For a start there are no occurrences of the strings: "zfs", "zpool", "import", "export", "invariant", "disk", " zed"

**Comment by ilovezfs** [comment]
What is the output of
```
sudo launchctl list | grep org.openzfsonosx
```

**Comment by alanruttenberg** [comment]
33	0	org.openzfsonosx.zed
27	0	org.openzfsonosx.InvariantDisks
-	0	org.openzfsonosx.zpool-import-all
-	0	org.openzfsonosx.zed.service

**Comment by ilovezfs** [comment]
zed.service is old and should be removed from /Library/LaunchDaemons and /usr/libexec/zfs/launch.d

I'm not understanding why you don't have log files for zpool import all. Sounds like your launchd may be messed up.

**Comment by alanruttenberg** [comment]
If there's something i can check, let me know. I'll remove zed.service. Also, please consider adding some cleanup of old stuff to make install.

Is it possible that zed.service being still installed caused what I reported?

**Comment by alanruttenberg** [comment]
I see 

    /usr/lib/systemd/system/zed.service
    /usr/libexec/zfs/launchd.d/zed.service.sh

Should both be removed?

**Comment by ilovezfs** [comment]
The first one is a vestigial ZFS on Linux file.
The second one, yes.
