### ISSUE TITLE
xattr rewrite support probably buggy (OS X >= 10.9 can set tags only once)

### ISSUE THREAD

**Issue by lucid-dreams** [openzfsonosx/zfs#266]
Problem: 
1. use finder to set some tags on a file in a zfs pool  (works)
2. use finder to change the tags on said file  (OSStatus error -8058.)

However, after cleaning xattrs with 'xattr -c' setting tags using finder works again (once).

I suspect the problem is the rewrite semantics of zfs-on-osx: currently rewriting an xattr merely overwrites the existing entry, i.e. without terminating the entry.

E.g.:

> xattr -l fwStore\ Report.pdf

    com.apple.metadata:_kMDItemUserTags:
    00000000  62 70 6C 69 73 74 30 30 A2 01 02 54 63 61 73 6B  |bplist00...Tcask|
    00000010  53 70 6B 67 08 0B 10 00 00 00 00 00 00 01 01 00  |Spkg............|
    00000020  00 00 00 00 00 00 03 00 00 00 00 00 00 00 00 00  |................|
    00000030  00 00 00 00 00 00 14                             |.......|

> xattr -w com.apple.metadata:_kMDItemUserTags blubb fwStore\ Report.pdf

> xattr -l fwStore\ Report.pdf

    com.apple.metadata:_kMDItemUserTags:
    00000000  62 6C 75 62 62 74 30 30 A2 01 02 54 63 61 73 6B  |blubbt00...Tcask|
    00000010  53 70 6B 67 08 0B 10 00 00 00 00 00 00 01 01 00  |Spkg............|
    00000020  00 00 00 00 00 00 03 00 00 00 00 00 00 00 00 00  |................|
    00000030  00 00 00 00 00 00 14

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs/commit/c4318e8ccdacd8d8e0196d9c426ecf9dedc03ff4

Please try with this patch, if possible

**Comment by lucid-dreams** [comment]
I tried the patch and the truncation issue is gone; but tags still don't work, same problem as before.
Hadn't had the time to look further into the issue yet. I can only speculate that maybe OSX needs one vfs-action to create a new xattr and another for rewriting thee xattr. Maybe only one is implemented at the moment or one has a bug?

please reopen.

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs/commit/8ec26ebaf9e3c52285474850ebdf9f9420e4d1f1
