### ISSUE TITLE
Unusually high kernel-memory consumption ? (using OS X 10.10.1)

### ISSUE THREAD

**Issue by Byron** [openzfsonosx/zfs#270]
A few days ago I have installed OpenZFS on my system, running a setup as follows:

* Use `sparsebundle` virtual disk device in a single pool
* create one filesystem with compression enabled

No openZFS settings have been altered, all other settings I could think of have been appended to the bottom of this issue.

Usually I have observed `kernel_task` memory sizes arund 1.5GB, yet now it seems that whenever ZFS gets involved, it goes up to between 5GB and 6.5GB even without me actually accessing data contained on ZFS filesystems (but pool is imported and filesystem is mounted). Please see the screenshot for a live-view:

![screen shot 2015-01-27 at 13 28 43](https://cloud.githubusercontent.com/assets/63622/5918568/5e6d1234-a62a-11e4-8132-10de52fc05e6.png)

The reason why I actually started to look into this is that when I first created the my sparsebundle based ZFS filesystem and copied 40GB into it using the finder (100 thousands of small files), while doing other IO and possibly transcoding video, my system crashed hard, and that after an uptime of more than 60 days.

After the reboot, my `kernel_task` size was back to 1.2GB, but when I imported the pool, I could watch it rise. All that happens without me doing anything with the mounted ZFS filesystem.

Maybe you have an idea what this could be - perhaps it's related to some parameter I can tweak to make it use less 'cache' memory. As I use ZFS privately just to have a compressed, dynamically growing live-drive on a fast SSD, I'd rather leave the RAM to other tasks and have ZFS do a few more IOPs.

Thanks for your help

### Additional Information
* **openzfs version information**
```bash
kextstat | grep -i lundman
  120    1 0xffffff7f80a75000 0x21c      0x21c      net.lundman.kernel.dependencies (10.0.0)
  121    1 0xffffff7f80a76000 0x15000    0x15000    net.lundman.spl (1.0.0) <120 7 5 4 3 1>
  122    1 0xffffff7f80a8b000 0x20b000   0x20b000   net.lundman.zfs (1.0.0) <121 16 7 5 4 3 1>
```

* **Output of `hdiutil info`**
```
[...]
================================================
image-path      : [...]/dev-ext.sparseimage
image-alias     : [...]/dev-ext.sparseimage
shadow-path     : <none>
icon-path       : /System/Library/PrivateFrameworks/DiskImages.framework/Resources/CDiskImage.icns
image-type      : sparse disk image
system-image    : false
blockcount      : 200001824
blocksize       : 512
writeable       : TRUE
autodiskmount   : TRUE
removable       : TRUE
image-encrypted : false
mounting user   : byron
mounting mode   : <unknown>
process ID      : 610
/dev/disk3	Apple_partition_scheme	
/dev/disk3s1	Apple_partition_map	
/dev/disk3s2	Apple_Driver43	
/dev/disk3s3	Apple_Driver43	
/dev/disk3s4	Apple_Driver_ATA	
/dev/disk3s5	Apple_Driver_ATA	
/dev/disk3s6	Apple_FWDriver	
/dev/disk3s7	Apple_Driver_IOKit	
/dev/disk3s8	Apple_Patches	
/dev/disk3s9	Apple_HFS	
```

* **Various ZFS information**
```bash
steelbook:~ root# zpool status
  pool: zfs-p100gb
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        zfs-p100gb  ONLINE       0     0     0
          disk3s9   ONLINE       0     0     0

errors: No known data errors
steelbook:~ root# zpool list
NAME         SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
zfs-p100gb    95G  20.7G  74.3G    21%  1.00x  ONLINE  -
```
```
steelbook:~ root# zfs list
NAME             USED  AVAIL  REFER  MOUNTPOINT
zfs-p100gb      20.7G  72.8G  1.22M  /zfs-p100gb
zfs-p100gb/ext  20.7G  72.8G  20.7G  /zfs-p100gb/ext
steelbook:~ root# zfs get  all zfs-p100gb/ext
NAME            PROPERTY               VALUE                  SOURCE
zfs-p100gb/ext  type                   filesystem             -
zfs-p100gb/ext  creation               Mon Jan 26 10:18 2015  -
zfs-p100gb/ext  used                   20.7G                  -
zfs-p100gb/ext  available              72.8G                  -
zfs-p100gb/ext  referenced             20.7G                  -
zfs-p100gb/ext  compressratio          1.81x                  -
zfs-p100gb/ext  mounted                yes                    -
zfs-p100gb/ext  quota                  none                   default
zfs-p100gb/ext  reservation            none                   default
zfs-p100gb/ext  recordsize             128K                   default
zfs-p100gb/ext  mountpoint             /zfs-p100gb/ext        default
zfs-p100gb/ext  sharenfs               off                    default
zfs-p100gb/ext  checksum               on                     default
zfs-p100gb/ext  compression            gzip-9                 local
zfs-p100gb/ext  atime                  on                     default
zfs-p100gb/ext  devices                on                     default
zfs-p100gb/ext  exec                   on                     default
zfs-p100gb/ext  setuid                 on                     default
zfs-p100gb/ext  readonly               off                    default
zfs-p100gb/ext  zoned                  off                    default
zfs-p100gb/ext  snapdir                hidden                 default
zfs-p100gb/ext  aclmode                discard                default
zfs-p100gb/ext  aclinherit             restricted             default
zfs-p100gb/ext  canmount               on                     default
zfs-p100gb/ext  xattr                  on                     default
zfs-p100gb/ext  copies                 1                      default
zfs-p100gb/ext  version                5                      -
zfs-p100gb/ext  utf8only               off                    -
zfs-p100gb/ext  normalization          none                   -
zfs-p100gb/ext  casesensitivity        insensitive            -
zfs-p100gb/ext  vscan                  off                    default
zfs-p100gb/ext  nbmand                 off                    default
zfs-p100gb/ext  sharesmb               off                    default
zfs-p100gb/ext  refquota               none                   default
zfs-p100gb/ext  refreservation         none                   default
zfs-p100gb/ext  primarycache           all                    default
zfs-p100gb/ext  secondarycache         all                    default
zfs-p100gb/ext  usedbysnapshots        0                      -
zfs-p100gb/ext  usedbydataset          20.7G                  -
zfs-p100gb/ext  usedbychildren         0                      -
zfs-p100gb/ext  usedbyrefreservation   0                      -
zfs-p100gb/ext  logbias                latency                default
zfs-p100gb/ext  dedup                  off                    default
zfs-p100gb/ext  mlslabel               none                   default
zfs-p100gb/ext  sync                   standard               default
zfs-p100gb/ext  refcompressratio       1.81x                  -
zfs-p100gb/ext  written                20.7G                  -
zfs-p100gb/ext  logicalused            36.6G                  -
zfs-p100gb/ext  logicalreferenced      36.6G                  -
zfs-p100gb/ext  snapdev                hidden                 default
zfs-p100gb/ext  com.apple.browse       on                     default
zfs-p100gb/ext  com.apple.ignoreowner  off                    default
```

**Comment by ilovezfs** [comment]
Please try the release candidate.

**Comment by Byron** [comment]
When attempting to export my pool, the process would hang. Rebooting hung as well which forced me to do a hard-reset. Right after the system came up, the kernel used ~970MB, and after importing my pool that number went up to 1.12GB.
After browsing the files a bit, the number didn't rise initially. 

A good thing seems to be that I am able to export pools now, which previously would always hang. After exporting, kernel memory usage went down to 1.08GB. This is just for your information, maybe this indicates leakage, maybe it's expected.

As the reboot is just 10 minutes old, I will have to monitor this value and will let you know if anything changes or becomes unusual.

**Comment by brendonhumphrey** [comment]
Byron,

Your memory use looks totally normal to me. ZFS uses the ARC to cache filesystem data and metadata to improve its performance. It will use as much memory as it can in the machine, and release memory back to the OS when the machine experiences memory pressure (thats the 1.3.1-RC code, 1.3.0 will use ~40% of the machine).

The arc size can be set by:

1.3.0 ->
sysctl -w zfs.arc_max=<desired arc size in bytes>

1.3.1 RC ->
sysctl -w kstat.zfs.darwin.tunable.zfs_arc_max=<desired arc size in bytes>

This should be done shortly after the kexts are loaded (or your pools are imported). The timing is not all that critical. The setting is not persistent and must be repeated at boot. We plan to support persistent settings in a future release.

I will leave the issue open while your hang on export issue is explored.

**Comment by lundman** [comment]
There is a bug in 1.3.1RC1-RC5 where readonly mounts would deadlock on unmount.

There are export delays when Spotlight is a dissenter to unmount, usually put into /var/log/system_log if that is the case. (try again later).

If you unload zfs and spl kext, after export, you will get all your memory back, and spl will report any leaks. Which I believe should be 0.

```
bash-4.3# kextunload -b net.lundman.zfs
Jan 28 12:04:07 icgi-vip kernel[0]: ZFS: Unloaded module v1.3.0-399_g44c5948
Jan 28 12:04:07 icgi-vip kernel[0]: ZFS: Unloaded module
bash-4.3# kextunload -b net.lundman.spl
Jan 28 12:04:10 icgi-vip kernel[0]: SPL: stop memory monitor
Jan 28 12:04:10 icgi-vip kernel[0]: SPL: bsd_untimeout
Jan 28 12:04:10 icgi-vip kernel[0]: SPL: wait for taskqs to empty
Jan 28 12:04:10 icgi-vip kernel[0]: SPL: destroy taskq
Jan 28 12:04:11 icgi-vip kernel[0]: SPL: Released 38 slabs
Jan 28 12:04:11 icgi-vip kernel[0]: SPL: Released 524288 bytes from vmem_seg_arena
Jan 28 12:04:11 icgi-vip kernel[0]: SPL: Unloaded module. (os_mem_alloc: 0)
```

**Comment by Byron** [comment]
Hi,

The hang I encountered happened with the older version (1.2.8 I think), which apparently used 40% of my available memory by default. So far, I didn't have any issues with 1.3.1RC5. Even without setting the arc, it didn't consume any additional memory.
When setting the arc, it appears that the previous zfs_arc_max value was at 14GB on a 16GB system.

Thanks for your excellent help so far - next time (if there is one) anything comes up, I will update to the latest version beforehand.

Cheers
