### ISSUE TITLE
Filter out more devices from zpool_find_import_impl (especially com.digidesign.semiface/com_digidesign_semiface)

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#272]
This has bitten us at least twice now by causing import hangs on com_digidesign_semiface
https://openzfsonosx.org/forum/viewtopic.php?f=15&t=2166
https://openzfsonosx.org/forum/viewtopic.php?f=24&t=2021

"turns out that Avid / Protools has a kext with a device called com.digidesign.semiface [or com_digidesign_semiface] which is set by DigiDal.kext. not sure what it does, and i can run several flavors of Protools 10 & 11 after removing it from /Library/Extensions & /System/Library/Extensions"

One proposed solution was

"so i don't see any other /dev's with "com" prefixes, and in the zpool_find_import_impl() method in <libzfs_import.c> i'd perhaps insert"
```
(strncmp(name, "com", 3) == 0) ||
```

and there are probably more prefixes beyond just "com" that we should also filter out on OS X.

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs/commit/748a695828ce4630a181a1d137945d2f06006ac8

**Comment by ilovezfs** [comment]
And now skipping /dev/pty* too
https://github.com/openzfsonosx/zfs/commit/7d58ea5cea30cacaec951369c0f5c0cc08757a64
