### ISSUE TITLE
Improper eject breaks zpool

### ISSUE THREAD

**Issue by Synchro** [openzfsonosx/zfs#277]
If you eject a ZFS disk (single pool on USB) from the finder *without* a zpool export, disconnect the disk, then reconnect it (i.e. business as usual for an external drive), all zpool commands (even simple things like `zpool list`) hang and can't be killed. I suspect this is because the reconnected disk doesn't necessarily get the same disk number, so zpool is waiting for a non-existent device.

I know that the correct solution is to always export before device removal, however, zpool shouldn't break so fatally. If I had any other pools, I would be completely cut off from them from this simple error.

**Comment by ilovezfs** [comment]
This is the point of importing by-id or by-serial or by-path, and why InvariantDisks was implemented. So I'd say this is solely a documentation issue at this point.

**Comment by ilovezfs** [comment]
Duplicates:
https://github.com/openzfsonosx/zfs/issues/167
https://github.com/openzfsonosx/zfs/pull/258
Related:
https://github.com/openzfsonosx/zfs/issues/178

**Comment by Synchro** [comment]
I'm not disputing that that's the proper way to do it, but zpool breaking (apparently unrecoverably) for any reason surely isn't a documentation issue?

**Comment by ilovezfs** [comment]
With respect to improper eject issues not related to disk renumbering,
https://github.com/openzfsonosx/zfs/issues/285

**Comment by Synchro** [comment]
I've since found that this problem not only breaks zpool, but also breaks any attempt to mount any other file system too - for example plugging in an HFS+ flash drive does not work after ejecting a zfs disk without exporting it. I fail to see how rendering the entire system unusable is a documentation issue. #258 mentions a timeout, but I'm not seeing any timeout behaviour - I've had zpool hang for several days.

**Comment by ilovezfs** [comment]
@Synchro The documentation issue is how to prevent disk renumbering, which is a separate issue from the consequences of eject without export. If you have new observations beyond what was reported in #285 then please comment there.

The timeout values used by InvariantDisks and zpool-import-all.sh have nothing to do with improper ejects.

You should try setting failmode=continue as I mentioned in the other issue to see if it affects the behavior subsequent to improper eject.

**Comment by ilovezfs** [comment]
As I mentioned here https://github.com/openzfsonosx/zfs/issues/285#issuecomment-91141003, this should now be fixed by https://github.com/openzfsonosx/zfs/commit/8c55b29781836f8cb63e5aab361d1647e221f097. Note that this commit is included in 1.3.1/1.3.1-r2.

**Comment by Synchro** [comment]
Great news, thanks.
