### ISSUE TITLE
With O3X 1.3.1-RC5 for ~ (home directory), Spotlight in Mail fails for mailbox-specific searches

### ISSUE THREAD

**Issue by grahamperrin** [openzfsonosx/zfs#278]
This bug also affects some types of smart mailbox, but should not be confused with #90, which was truly a duplicate (of #84) at the time of closure. 

# Reproduction and workaround

### Actions

1. with Mail in Yosemite, OS X 10.10.2 
2. select a mailbox – an Inbox, for example
3. observe the listed messages
4. use the search field of Mail to seek something that is listed

### Expected

 5. a list of matching messages

### Actual results

 5. nothing is listed

### Workaround

 6. search all mailboxes.

## Reference

[Mac Basics: Mail (OS X Mountain Lion)](http://web.archive.org/web/20130509083457/http://support.apple.com/kb/HT5361), 2013-05-09

> … Mail has a very easy and power Spotlight-based search …

## Postscript

The bug might be: 
- reproducible with Mavericks, OS X 10.9.x
- not reproducible with Mountain Lion, OS X 10.8.x

**Comment by ilovezfs** [comment]
Is Spotlight enabled on the file system?
mdutil -v -s /Volumes/…

**Comment by grahamperrin** [comment]
Yes, Spotlight is enabled; the workaround works.

**Comment by ilovezfs** [comment]
Is this reproducible in a clean user in a new pool

**Comment by grahamperrin** [comment]
First production of the bug was with a clean user in a new pool. 

(I have not attempted reproduction with another new user with another new pool.)

Quitting then relaunching does not work around, and so on. 

If no-one can reproduce the bug, please let me know. (I can not boot my at-home test installation of Yosemite, which has O3X, without a shutdown of my everyday system. Off to work now …)

**Comment by ilovezfs** [comment]
I do wonder whether the all mail search is doing a server-side search.

**Comment by brendonhumphrey** [comment]
Guys,

Have just followed Grahams steps, works fine for me.

Brendon

**Comment by ilovezfs** [comment]
Then if anything it sounds like it could be a Yosemite bug.

**Comment by brendonhumphrey** [comment]
I run yosemite

**Comment by ilovezfs** [comment]
Right. I just mean if there's some intermittent bug that gets Mail.app into a dysfunctional state that it's much more likely to be 10.10 than anything to do with ZFS. Will be interesting to see if anyone reports this on 10.8 and/or 10.9.

**Comment by brendonhumphrey** [comment]
one possibility is that my mailboxes were migrated from an HFS setup a year ago, so not created on ZFS. I could create a fresh user and see if that is ok.

(You may recall that I am probably the first and longest user of ZFS as homedir)

- Brendon

**Comment by grahamperrin** [comment]
I forgot to note: the new pool was created by ZEVO. 

I'll see whether the bug is reproducible with a version 28 pool created by O3X.

**Comment by grahamperrin** [comment]
> … whether the bug is reproducible with a version 28 pool created by O3X.

Yes. 

First create the pool, create the home directory and change ownership: 

    sudo zpool create -o version=28 -O normalization=formD -O casesensitivity=insensitive o3x-278 /dev/disk2
    sudo mkdir /Volumes/o3x-278/o3x
    sudo chown o3x /Volumes/o3x-278/o3x

With the *Users & Groups* pane of *System Preferences*, set the home directory for account `o3x` to `/Volumes/o3x-278/o3x` then with the fast user switching menu, select that account. 

Login, start Mail, add an account, allow time for indexing to complete then reproduce the bug. 

Example screenshots attached. 

![screen shot 2015-02-10 at 21 59 34](https://cloud.githubusercontent.com/assets/192271/6137711/09e937c0-b173-11e4-8080-7408ed76d0cd.png)

![screen shot 2015-02-10 at 22 00 32](https://cloud.githubusercontent.com/assets/192271/6137724/2669470a-b173-11e4-9546-7057ad1b8ba8.png)

**Comment by ilovezfs** [comment]
I believe we already determined not all directories are made when you use the above method, even if the external volume is HFS+. You should repeat the procedure not involving ZFS at all.

**Comment by grahamperrin** [comment]
Reproduced following an upgrade of the pool. 

	bash-3.2$ zpool upgrade o3x-278
	This system supports ZFS pool feature flags.

	Successfully upgraded 'o3x-278' from version 28 to feature flags.
	Enabled the following features on 'o3x-278':
	  async_destroy
	  empty_bpobj
	  lz4_compress
	  spacemap_histogram
	  enabled_txg
	  hole_birth
	  extensible_dataset
	  embedded_data
	  bookmarks

	bash-3.2$ zpool status
	  pool: o3x-278
	 state: ONLINE
	  scan: none requested
	config:

		NAME        STATE     READ WRITE CKSUM
		o3x-278     ONLINE       0     0     0
		  disk2     ONLINE       0     0     0

	errors: No known data errors
	bash-3.2$ zpool get all o3x-278
	NAME     PROPERTY                    VALUE                       SOURCE
	o3x-278  size                        149G                        -
	o3x-278  capacity                    0%                          -
	o3x-278  altroot                     -                           default
	o3x-278  health                      ONLINE                      -
	o3x-278  guid                        9408247117354402637         default
	o3x-278  version                     -                           default
	o3x-278  bootfs                      -                           default
	o3x-278  delegation                  on                          default
	o3x-278  autoreplace                 off                         default
	o3x-278  cachefile                   -                           default
	o3x-278  failmode                    wait                        default
	o3x-278  listsnapshots               off                         default
	o3x-278  autoexpand                  off                         default
	o3x-278  dedupditto                  0                           default
	o3x-278  dedupratio                  1.00x                       -
	o3x-278  free                        149G                        -
	o3x-278  allocated                   470M                        -
	o3x-278  readonly                    off                         -
	o3x-278  ashift                      0                           default
	o3x-278  comment                     -                           default
	o3x-278  expandsize                  -                           -
	o3x-278  freeing                     0                           default
	o3x-278  fragmentation               -                           -
	o3x-278  leaked                      0                           default
	o3x-278  feature@async_destroy       enabled                     local
	o3x-278  feature@empty_bpobj         enabled                     local
	o3x-278  feature@lz4_compress        active                      local
	o3x-278  feature@spacemap_histogram  active                      local
	o3x-278  feature@enabled_txg         active                      local
	o3x-278  feature@hole_birth          active                      local
	o3x-278  feature@extensible_dataset  enabled                     local
	o3x-278  feature@embedded_data       active                      local
	o3x-278  feature@bookmarks           enabled                     local
	bash-3.2$ 

Then a restart of the OS, login as the affected user, allow time for indexing to complete and reproduce the bug: 

![screen shot 2015-02-10 at 22 37 38](https://cloud.githubusercontent.com/assets/192271/6138109/48298ea6-b176-11e4-83a1-ad24c3be19dc.png)

![screen shot 2015-02-10 at 22 38 18](https://cloud.githubusercontent.com/assets/192271/6138112/50f58242-b176-11e4-99fc-d2ba0547656b.png)

![screen shot 2015-02-10 at 22 38 39](https://cloud.githubusercontent.com/assets/192271/6138114/56e7bed6-b176-11e4-92fb-d470290d9796.png)

**Comment by ilovezfs** [comment]
To repeat myself, I believe we already determined not all directories are made when you use the above method, even if the external volume is HFS+. You should repeat the procedure not involving ZFS at all.

**Comment by grahamperrin** [comment]
> To repeat myself

Crossed paths by one minute; please be patient whilst I restart the OS (the pool will not export).

**Comment by grahamperrin** [comment]
> … repeat the procedure not involving ZFS at all.

Done, with the same physical device. The bug is not reproducible with HFS Plus. 

----

Destruction of the test pool: 

	Mashemite:~ grahamperrin$ diskutil unmount /Volumes/o3x-278/
	Unmount successful for /Volumes/o3x-278/
	Mashemite:~ grahamperrin$ sudo zpool destroy o3x-278

Then Disk Utility creation of a single HFS Plus partition, followed by creation of the home directory and the change of ownership: 

	Mashemite:~ grahamperrin$ mount
	/dev/disk4 on / (hfs, local, journaled)
	devfs on /dev (devfs, local, nobrowse)
	map -hosts on /net (autofs, nosuid, automounted, nobrowse)
	map auto_home on /home (autofs, automounted, nobrowse)
	/dev/disk3s2 on /Volumes/PC-BSD (msdos, local, nodev, nosuid, noowners)
	/dev/disk3s3 on /Volumes/10.9.5 (hfs, local, nodev, nosuid, journaled, noowners)
	/dev/disk3s5 on /Volumes/Graham (hfs, local, nodev, nosuid, journaled, noowners)
	/dev/disk2s2 on /Volumes/hfs-plus-278 (hfs, local, nodev, nosuid, journaled, noowners)
	Mashemite:~ grahamperrin$ sudo mkdir /Volumes/hfs-plus-278/o3x
	Mashemite:~ grahamperrin$ sudo chown o3x /Volumes/hfs-plus-278/o3x/

Logout, login to the new home directory on HFS Plus, start Mail, add the account, select a mailbox, seek something in that mailbox. 

Mail presents matching items – without switching to *All*:

![screen shot 2015-02-10 at 23 01 03](https://cloud.githubusercontent.com/assets/192271/6138570/2e622470-b17a-11e4-92fd-6f9c76728f67.png)

**Comment by ilovezfs** [comment]
OK. @lundman can you please have a look at this.

**Comment by brendonhumphrey** [comment]
Confirmed as described.

My mail client defaults to search all, so thats why I get results.

mdfind can find the relevant content in mail files immediately after download, there is no "wait for index" period.

Debug logs supplied to lundman.

-Brendon

**Comment by grahamperrin** [comment]
> … Debug logs supplied to lundman.

Thanks :)

> … My mail client defaults to search all …

Here, that behaviour occurs when no mailbox is selected. I sometimes observe *no selection* after Mail launches. There's also manual deselection (Command-Click the selection). 

Is there another way of causing Spotlight in Mail to behave in that way?

----

Back to the opening post: 

> This bug also affects some types of smart mailbox …

You might find the bug reproducible with a smart mailbox such as this, which specifies the Inbox (or the Inbox collection): 

![screen shot 2015-02-11 at 09 35 16](https://cloud.githubusercontent.com/assets/192271/6144876/faa3cd5a-b1d3-11e4-902b-5687e20043a5.png)

(That screenshot shows the criteria, not the bug; HFS Plus is in use.)

Thanks again

**Comment by lundman** [comment]
OK this bug is proving to be quite persistent.

For future reference, the different between a Mail search is a filter like:

    mdfind 'kMDItemContentType=="com.apple.mail.emlx"'

and a subfolder search:

    mdfind '_kMDQueryScope==/Users/lundman/Library/Mail/V2/IMAP-accountused/$UUID/INBOX.mbox/Data/Messages/*&&kMDItemContentType=="com.apple.mail.emlx"'

Note that by simply using _kMDQueryScope, even with _kMDQueryScope==/* it will not list any ZFS entries at all. HFS volumes, including those on ZVOL, will be fine.

I have verified our correctness is countless areas, as well as, attempted to lie and pretend we are HFS, but none of these hacks have had any success. It is still uncertain which criteria kMDQueryScope invokes.

Inspecting SpotlightIndex, we find that in `finishRegisterQuery()` it tests for kMDQueryScope and if used, calls `si_resolve_query_scopes()` which in turn calls `SIPersistentIDStoreGetRealPathForOid()` and `db_query_tree_apply_block()`. Unfortunately, the former simply accesses entry 0x28 in an unknown structure as return value.

I have opened Apple DTS ticket #619066023 but I have had little success with DTS in the past.

For the time being, I have explored everything I can think of, (at least debugging blindly), and suggest people use searching of "All", or find some search string which might work in place. :)

**Comment by lundman** [comment]
I have had minor success with https://github.com/openzfsonosx/zfs/commit/077397419a69b679b39b9d634bfd523a4a8f56fc

```
 mdfind '_kMDQueryScope==/Volumes/BOOM/*&&kMDItemContentType=="com.apple.mail.emlx"'
/Volumes/BOOM/Mail/V2/IMAP-lundman@imap.gmo.jp/Sent Messages.mbox/842DB037-2803-4B10-8FC9-66B726ADFF0C/Data/Messages/2.emlx

```

I had to rebuild the index though (mdutil -E /Volumes/BOOM)

**Comment by grahamperrin** [comment]
Thanks, if I can get any other relevant information I'll add it here.

**Comment by ilovezfs** [comment]
@grahamperrin @lundman is saying it is possible the entire issue may now be fixed, if that was not clear.

**Comment by grahamperrin** [comment]
Thanks

**Comment by brendonhumphrey** [comment]
looks to be working for me.

Brendon

**Comment by grahamperrin** [comment]
Fix reaffirmed. Working for me. Thanks.
