### ISSUE TITLE
zpool import hangs on readonly media

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#279]

**Comment by daDnaK** [comment]
isn't that solved with the 1.3.1? Or is that something different referenced in the release notes?

**Comment by ilovezfs** [comment]
https://github.com/openzfsonosx/zfs/commit/2492acbb9a8d415aa5ca9ef21ee3be01b6766612
https://github.com/openzfsonosx/zfs/commit/4ba31c093f6e88014b32542fae8ef97d18c26029
