### ISSUE TITLE
Parallels suspended virtual machines memory corruption?

### ISSUE THREAD

**Issue by ylluminate** [openzfsonosx/zfs#281]
I'm having an odd issue wherein I get an error about corrupted memory.  The actual error is:  "An error occurred when working with this virtual machine physical memory."

If I hard stop the virtual machine and then restart the entire OS it resolves the issue.  Apparently the memory file stored during the suspend becomes corrupted sometimes.  So far I have really been shooting blanks at reproducing (it is very intermittent) this issue and tracking down the source.

The only thing I've really been able to be sure of so far is that this is on a ZFS volume with compression turned off (I had it on and was getting this issue, then turned off the property to see if it would stop the issue).

Any thoughts on tracking this down?  My next step is going to be to run this VM on an HFS+ volume to see if this occurs anymore, but I wanted to get this started here as a placeholder at the very least and to see if anyone else has seen anything like this.

**Comment by emory** [comment]
Is it only occurring in one particular VM? Are there other VMs that exhibit the same behavior? If so, are they the same platform?  *(I'm wondering if it's related to the hypervisor and/or Host, or specifically the Guest itself doing something.)*

**Comment by ilovezfs** [comment]
Closing as stale. Please let us know if you see this happen again.
