### ISSUE TITLE
kext_version kstats not working on 10.8 and 10.9

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#283]
Josephs-MacBook-Pro:~ joe$ sysctl -a | grep kext
debug.kextlog: 4083
Josephs-MacBook-Pro:~ joe$

**Comment by lundman** [comment]
It is the only entry that is of type string, which I threw in there. Probably related to the issue.

**Comment by lundman** [comment]
https://github.com/openzfsonosx/spl/commit/11633069c22846a9d8770a4f3365a8def1f6bcd4

https://github.com/openzfsonosx/zfs/commit/c49f8a6787be0df442cc7b69639084e5bbc133cd


still broken, work around
