### ISSUE TITLE
Hangs on shutdown

### ISSUE THREAD

**Issue by fehlerteufel** [openzfsonosx/zfs#290]
Hi,

I am using version 1.3.1-RC5 on a MacBook Pro Mid 2014 running on OS X Yosemite 10.10.2.

My hard disk is encrypted, and I have a sparse bundle which holds my ZFS file system. I have some subvolumes, enabled compression on all of them and also dedup on one of the subvolumes.

When I shutdown the MacBook, at hangs almost every time, and I have to switch it off by holding the power button.

I do not have a lot of other software installed - in fact only Parallels for my virtual machines.

Here are some log entries:
25.03.15 14:54:31,654 sharingd[268]: 14:54:31.654 : SIGTERM received, shutting down.
25.03.15 14:54:31,654 com.apple.xpc.launchd[1]: (com.apple.ImageCaptureExtension2.15652[330]) Service exited due to signal: Terminated: 15
25.03.15 14:54:31,654 com.apple.xpc.launchd[1]: (com.apple.coreservices.uiagent[224]) Service exited due to signal: Killed: 9
25.03.15 14:54:31,656 lsuseractivityd[297]: [SFActivityAdvertiser] ERROR: lost XPC connection
25.03.15 14:54:31,657 lsuseractivityd[297]: [SFContinuityScanManager] ERROR: lost XPC connection
25.03.15 14:54:31,744 sessionlogoutd[1427]: sessionlogoutd Launched
25.03.15 14:54:31,751 sessionlogoutd[1427]: DEAD_PROCESS: 66 console
25.03.15 14:54:31,818 sharingd[1426]: 14:54:31.817 : Starting Up...
25.03.15 14:54:31,821 sharingd[1426]: 14:54:31.821 : Device Capabilities (Handoff:YES, Instant Hotspot:YES, AirDrop:YES, Legacy AirDrop:YES, Remote Disc:YES)
25.03.15 14:54:31,845 com.apple.kextd[19]: Error reconsidering volume /Volumes/tank.
25.03.15 14:54:31,845 com.apple.kextd[19]: Error reconsidering volume /Volumes/tank/Company.
25.03.15 14:54:31,845 com.apple.kextd[19]: Error reconsidering volume /Volumes/tank/Privat.
25.03.15 14:54:31,845 com.apple.kextd[19]: Error reconsidering volume /Volumes/tank/VMs.
25.03.15 14:54:31,845 shutdown[1429]: halt by jk: 
25.03.15 14:54:31,000 kernel[0]: Kext loading now disabled.
25.03.15 14:54:31,000 kernel[0]: Kext unloading now disabled.
25.03.15 14:54:31,000 kernel[0]: Kext autounloading now disabled.
25.03.15 14:54:31,000 kernel[0]: Kernel requests now disabled.
25.03.15 14:54:31,845 shutdown[1429]: SHUTDOWN_TIME: 1427291671 845284

This seems to correspond to bugs like #180 and #268, which are already closed. As far as I understand, the RC5 should already include the fixes for this problem.

**Comment by lundman** [comment]
There are a few more fixes towards this in master, are you able to build from source at all, or would you prefer a early binary to test? You might need to change boot-args to have "-v" so you can see the messages during shutdown (they do not go into system.log unfortunately).

**Comment by fehlerteufel** [comment]
I think that I am not skilled enough to build it myself correctly, so if it is possible I would prefer a early binary to test it.

**Comment by ilovezfs** [comment]
@fehlerteufel here you go https://www.dropbox.com/s/exta7saagx2bmlo/rw-131gm-r0.dmg.zip

**Comment by fehlerteufel** [comment]
Thanks for the DMG. Now I can shutdown the Mac if I unmount the ZFS volumes and the tank in Finder before shutting down. This was not possible with RC5.
But if I do not unmount the volumes, I still get the hang at shutdown.

For me this is a fine workaround. Still, I would be happy to help if you want to find the reason and need any logs or tests.

**Comment by ilovezfs** [comment]
You're welcome. Does the hang at shutdown happen every time or only sometimes? If you leave an ssh session from another computer logged in, then you may be able to run sudo spindump when it hangs.

**Comment by fehlerteufel** [comment]
Yes, the hang at shutdown happens every time (when ZFS volumes are mounted).
Unfortunately, the SSH connection is closed before the hang occurs, so I could not run the spindump command.

**Comment by ilovezfs** [comment]
OK. And this is a pool inside a sparsebundle? Does it happen if you use real drive(s)?

**Comment by fehlerteufel** [comment]
I tested it with an USB flash drive. Short version: it does not happen if use the drive directly.

Test 1: ZFS directly on flash drive:
Disk Utility Program: Partition - 1 Partition - Format as free space
sudo zpool create -f -o ashift=13 -O normalization=formD testtank /dev/disk2
sudo zfs create testtank/test1
sudo zfs create testtank/test2
sudo zfs create testtank/test3
--> shutdown works

Test 2: ZFS on sparsebundle on flash drive:
Disk Utility Program: Partition - 1 Partition - Format as Mac OS Extended (Journaled)
cd /Volumes/FlashDrive
hdiutil create -size 2g -volname ZFS -type SPARSEBUNDLE -layout NONE ZFS
hdiutil attach -nomount ZFS.sparsebundle
sudo zpool create -f -o ashift=13 -O normalization=formD testtank /dev/disk2
sudo zfs create testtank/test1
sudo zfs create testtank/test2
sudo zfs create testtank/test3
-->  shutdown hangs

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs/commit/94ba2657a47053b3c707a7260b560d52d709bae5

**Comment by ilovezfs** [comment]
@fehlerteufel This is fixed in the 1.3.1 release https://openzfsonosx.org/wiki/Downloads#1.3.1

**Comment by simonpie** [comment]
I dont think its fixed :
```
[labanque:: 15:13] [~] % sysctl {spl,zfs}.kext_version
spl.kext_version: 1.4.5-1
zfs.kext_version: 1.4.5-1
[labanque:: 15:14] [~] % 
```

and here is what happens when I reboot.  Two pools, on real physical disk :
```
Apr  9 13:47:11 labanque sudo[79967]:    Admin : TTY=ttys005 ; PWD=/Users/Admin ; USER=root ; COMMAND=/sbin/reboot
Apr  9 13:47:11 labanque com.apple.kextd[81]: Error reconsidering volume /Volumes/tank.
Apr  9 13:47:11 labanque com.apple.kextd[81]: Error reconsidering volume /Coffre.
Apr  9 13:47:11 labanque com.apple.kextd[81]: Error reconsidering volume /SP.
Apr  9 13:47:11 labanque com.apple.kextd[81]: Error reconsidering volume /Volumes/StudioSon.
Apr  9 13:47:11 labanque com.apple.kextd[81]: Error reconsidering volume /Volumes/voute.
Apr  9 13:47:11 labanque com.apple.kextd[81]: Error reconsidering volume /Volumes/voute/DBCom-Back.
Apr  9 13:47:11 labanque reboot[79968]: rebooted by Admin
Apr  9 13:47:11 labanque reboot[79968]: SHUTDOWN_TIME: 1460224031 942908
Apr  9 13:47:11 labanque kernel[0]: Kext loading now disabled.
Apr  9 13:47:11 labanque kernel[0]: Kext unloading now disabled.
Apr  9 13:47:11 labanque kernel[0]: Kext autounloading now disabled.
Apr  9 13:47:11 labanque kernel[0]: Kernel requests now disabled.
```
And the machine takes about 15 minutes to reboot after that.

**Comment by ilovezfs** [comment]
Try https://openzfsonosx.org/wiki/File:O3x-1011-signed-spl-e755917-zfs-c4fe048.pkg

**Comment by simonpie** [comment]
Well, that warning kind of suppress the envy to try it :

>  Warning: This file type may contain malicious code. By executing it, your system may be compromised.

**Comment by ilovezfs** [comment]
Well yes...that's what wiki will say for an executable ;)

**Comment by simonpie** [comment]
Here is the stupid question then.  This is a production machine, I am not sure I want to try that.  How safe is this version ?  How long before the fix make it to mainstream ?

**Comment by ilovezfs** [comment]
It's safe. Definitely better than 1.4.5

**Comment by simonpie** [comment]
Sorry to bug you.  There are no instructions.  I just install and reboot.  What if it breaks my setup ?

**Comment by ilovezfs** [comment]
@simonpie export your pools, install, wait a couple of minutes for the kextcache to rebuild, reboot.

**Comment by ilovezfs** [comment]
@simonpie everything work out all right for you?

**Comment by simonpie** [comment]
No, I have not tried it.  I might try it today.

**Comment by simonpie** [comment]
Seems to work, 2 to 3 minutes reboot time.  How come this is not yet on the main download page ?

**Comment by simonpie** [comment]
@ilovezfs Sorry to bug you with this again.  Has this fix been integrated in the latest version ?
https://openzfsonosx.org/wiki/Changelog#OpenZFS_on_OS_X_1.5.2.dmg_2016-04-29

Reading the changelog, I'm really not sure.

**Comment by ilovezfs** [comment]
Yep.

**Comment by simonpie** [comment]
Thanks.
