### ISSUE TITLE
Contents of ZFS mounted datset not shown in Dock stack

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#291]
I mounted a ZFS dataset to ~/Downloads and my Downloads stack in the right side of the dock correctly opens it when I click on "open in Finder". It does bounce when Firefox downloaded something but clicking on it doesn't show the contents of the folder although there really are some contents in it.

OpenZFS 1.3.1 RC5 on OS X 10.10.2

**Comment by daDnaK** [comment]
ok this is strange. I don't know at what point they appeared but now they are shown - am investigating

**Comment by ilovezfs** [comment]
@daDnaK Did you figure out what was wrong?

**Comment by daDnaK** [comment]
nope. It just appeared. Maybe only after the first zip was extracted into the folder

**Comment by daDnaK** [comment]
actually this behavior happens after mounting a dataset to ~/Downloads but can be fixed via 
```` killall Dock````

**Comment by daDnaK** [comment]
happens on every boot - don't know whether this is a Dock issue or a OpenZFS issue

**Comment by schafdog** [comment]
I am seeing something similar. Mounting a sparsebundle with sudo on /testtank. Not showing anything in the mounted testtank. If I open do open . from the folder it self them the content is shown. This is with 1.3.1. Am I doing something wrong?

**Comment by schafdog** [comment]
Deleted last comment. Error 40 (inch from screen)

**Comment by daDnaK** [comment]
or maybe it's an issue that the ZFS dataset gets mounted later than the Dock process watching for the contents and then not being notified of changed contents.

**Comment by ilovezfs** [comment]
Try introducing a delay.

```
sudo defaults write /Library/Preferences/com.apple.loginwindow StartupDelay -int 30
```

**Comment by daDnaK** [comment]
does the 30 mean 30 seconds? ^^ Or what is the time unit we're talking about here?

**Comment by ilovezfs** [comment]
yup.

**Comment by daDnaK** [comment]
nope, didn't help. I'll just include killall Dock in my "start" routine which starts all cloud clients. I call it when I see that all ZFS volumes are mounted

**Comment by JMoVS** [comment]
is only happening when user is whole zfs homedir, if only donwloads folder is on ZFS, it works as expected
