### ISSUE TITLE
No official support from Apple for OpenZFS

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#293]
It is clear that O3X is way better than HFS+ so it should be considered a bug that Apple is not officially handing file system development to the O3X team and stops developing their own fs. In future OS X releases, O3X should be automatically included.
- April 1st, 2015

**Comment by grahamperrin** [comment]
I submitted an enhancement request (ER) to Apple in June 2013 whilst testing pre-release build 13A497d of OS X 10.9.0,

**OS X should include support for ZFS**

The essence of the request: 

> Please 
> 
> The operating system should include support for ZFS: 
> * now or as soon as possible in Mavericks, as an option for users with a basic understanding of the pros and cons
> * not yet as a default for newly created file systems (the "HFS everywhere" motto, which I might have heard from a past WWDC, can remain true if required)
> * not yet for booting (that can be a milestone for the future).
> 
> Use of ZFS need not preclude use of Core Storage, and vice versa. The two can be complementary (example: I have used Core Storage to encrypt my ZFS home directory, and more, very happily for over a year). …
