### ISSUE TITLE
Photos.app cannot store library on ZFS file system

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#296]
https://twitter.com/maartenthomas/status/585908713627774978

![ccgq3ufwaaey8zw](https://cloud.githubusercontent.com/assets/5268928/7060622/7ce8fc2c-de39-11e4-9c37-55bd71d95a26.jpg)

Google Translate translation: "The library cannot be opened. The Library 'Foto's-bibliotheek' is stored on a disk with a structure that is not supported. Copy the library to an internal drive of your Mac or another drive with a supported structure to provide access to the library."

**Comment by lundman** [comment]
With `zfs set com.apple.mimic_hfs=on` I managed to use Photos on ZFS. Interestingly, when I try to export a photo to ZFS I got an error, this was due to export trying to save the file in the root of the dataset, then renamed it down to the destination. (My dataset root was not writable at the time). Fixing those permissions allowed Export to work as well.

I have created BugID 20479016 with Apple for using static string test of `hfs` instead of Apple's quite-nice API for querying file-system capabilities.

**Comment by ilovezfs** [comment]
8:31 PM <shumancw> So it looks like server cache will accept zfs with mimic_hfs. Photos app seems a little wonky. I'll probably have to some more testing before I move to Photos.
8:31 PM <ilovezfs_> symptoms?
8:32 PM <shumancw> Photos - unable to revert to original image after making mods.
8:32 PM <shumancw> Some interface weirdness that isn't directly attributable to zfs.
8:33 PM <lundman> could be they use vnop we dont have
8:33 PM <lundman> turn debug on, and see :)
8:33 PM <shumancw> Too early for photos anyway. Too many photos, faces, tags to risk on beta anyway.
8:34 PM <lundman> thats the spirit, leave it to future shumancw to handle
8:34 PM <shumancw> lol
8:35 PM <shumancw> No, that's wait for more mature code and bug fixes before turning over the only pictures of my kids that I have to Apple.
8:35 PM <ilovezfs_> wonder if it's this
8:35 PM <ilovezfs_> https://github.com/openzfsonosx/zfs/issues/152
8:36 PM <shumancw> That was the first thing I thought of when Photos didn't work and iPhoto does.
8:36 PM <lundman> or vnop_exchange maybe
8:36 PM <ilovezfs_> but it's new and beta
8:36 PM <lundman> true
8:36 PM <ilovezfs_> and i thought that vnop exchange was deprecated
8:36 PM <lundman> yeh
8:37 PM <ilovezfs_> k

**Comment by lundman** [comment]
`< shumancw >  Photos - unable to revert to original image after making mods.`

After setting mimic, and making sure I can write to the root of the dataset, I clicked Edit on a photo, then cropped it, clicked Done.
Then clicked Edit again, Revert to original, and Done. 

Possibly this problem has already been fixed, please retest.

**Comment by brendonhumphrey** [comment]
I did some basic tests in a simple zfs home directory setup. With his Muniz enabled it seems to work ok worth a few photos imported. I was able to edit and revert some changes. I've not had the time to check it out beyond that.

**Comment by ilovezfs** [comment]
https://twitter.com/maartenthomas/status/586254697381683200
Maarten Thomas –  ‏@maartenthomas

"@openzfsonosx thanks a lot for the feedback. Enabling com.apple.mimic_hfs=on seems to make Photos.app indeed happy."
12:49 PM - 9 Apr 2015

**Comment by bighungry** [comment]
I ran into the same Photos.app problem so I just tried running this command and here's what happened:
﻿﻿1030familyroom:~ tvmac$ sudo zfs set com.apple.mimic_hfs=on FiveByFive/TheMedia
Password:
cannot set property for 'FiveByFive/TheMedia': invalid property 'com.apple.mimic_hfs'

From reading these posts, it seems like this was fixed...did I miss something somewhere?

**Comment by ilovezfs** [comment]
@bighungry your version is probably too old

**Comment by bighungry** [comment]
I'm running 1.3.1, but I see that's not the latest release. Is there
anything special that needs to be done to install the latest version? In
the FAQ there are some specific steps that need to be done in order to
upgrade a source install, but it doesn't say anything about upgrading from
the pkg installer. Thanks.

**Comment by ilovezfs** [comment]
Just export any pools you have currently imported before running the pkg installer.
