### ISSUE TITLE
Can't copy downloaded files to ZFS volume using Finder when xattr=off

### ISSUE THREAD

**Issue by wilchak** [openzfsonosx/zfs#297]
When I try to drag and drop a file with extended attributes (com.apple.metadata:kMDItemWhereFroms, com.apple.quarantine, etc) onto a ZFS dataset that has xattr=off, Finder errors out with this message: "The operation can’t be completed because you don’t have permission to access some of the items."

Note: I can see the file copy over just fine- it looks like Finder does the copy, tries to copy the xattrs, fails, throws up the error message, and deletes the (perfectly fine otherwise) copy. 

Same behavior regardless of com.apple.mimic_hfs or com.apple.ignoreowner being off or on.

Obviously OS X uses xattrs for a lot of things- why do I care? Because with xattrs off, file listings in Finder are much faster, and I don't use Tags or care about the quarantine bit or use Spotlight comments. Ideally, O3X would support xattr=sa (http://www.nerdblog.com/2013/10/zfs-xattr-tuning-on-linux.html) and that would solve the performance issue, but until then it seems that xattr=off makes a big difference, at least for me. Unfortunately it's not so useful if I can no longer copy files to my storage.

Running latest 1.3.1-r2 on 10.10.3. Thanks!

**Comment by ilovezfs** [comment]
As a workaround you can use rsync-2.6.9 and not pass -E or use rsync-3.1.1 (Homebrew) and not pass -X.

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs/commit/50044196c917

**Comment by ilovezfs** [comment]
@wilchak You may want to give this build a try so that you can use lundman's fix above:
https://openzfsonosx.org/forum/viewtopic.php?f=26&t=2257#p5456
