### ISSUE TITLE
Unity project on ZFS

### ISSUE THREAD

**Issue by aukaost** [openzfsonosx/zfs#301]
I tried creating a [Unity](http://unity3d.com/)(4.6.4p4) project on ZFS and ended up with puzzling results. Unity did not seem to be able to find any assets and assets once created using Unity seem to vanish from the project despite them being present in the file system.
I wonder how I could debug this curiosity?
Thanks for any hints.

**Comment by aukaost** [comment]
`zfs set com.apple.mimic_hfs=on` does not seem to help

**Comment by lundman** [comment]
I have installed Unity, and created a project on ZFS, but I am unsure what I am looking for, or how to check for it, having never used the software :)

**Comment by ilovezfs** [comment]
Are we sure this isn't a simple permissions problem?

**Comment by elaberge** [comment]
I have the same issue, and it is not a permission problem.
Reproduced with 1.3.2-RC1 and mimic_hfs turned on.
Unity logs this error in the console: "Refresh: detecting if any assets need to be imported or removed ... error getting directory contents Assets/"

Creating a new project or opening an existing one exhibits the problem on ZFS pools.
Creating or opening a project on top of a (case insensitive) HFS disk image hosted on a ZFS pool works, however.
Unity usually complains when opening or creating a project on top of a case-sensitive HFS filesystem, however.

I've noticed something fishy with the way ZFS reports its case sensitivity that could be related, though. I will open an issue about that.

**Comment by elaberge** [comment]
I don't know if it helps, as I don't really have experience reading "dtruss" output, but here is some logging captured when trying to open a test project:
```
42115/0x932ea:  write_nocancel(0x4, "Refresh: detecting if any assets need to be imported or removed ... \0", 0x44)		 = 68 0
42115/0x932ea:  open_nocancel(".\0", 0x0, 0x4)		 = 24 0
42115/0x932ea:  fstat64(0x18, 0xBFFFDD78, 0x4)		 = 0 0
42115/0x932ea:  fcntl_nocancel(0x18, 0x32, 0xFFFFFFFFBFFFDF16)		 = 0 0
42115/0x932ea:  close_nocancel(0x18)		 = 0 0
42115/0x932ea:  stat64("/Volumes/SDD/Users/eric/Projects/test\0", 0xBFFFDD08, 0xFFFFFFFFBFFFDF16)		 = 0 0
42115/0x932ea:  open_nocancel(".\0", 0x1100004, 0x6)		 = 24 0
42115/0x932ea:  fstatfs64(0x18, 0xBFFFD9F0, 0x6)		 = 0 0
42115/0x932ea:  getdirentries64(0x18, 0x99F6000, 0x1000)		 = 200 0
42115/0x932ea:  close_nocancel(0x18)		 = 0 0
42115/0x932ea:  stat64("/Volumes/SDD/Users/eric/Projects/test/Assets\0", 0xBFFFE2B8, 0x1000)		 = 0 0
42115/0x932ea:  open_nocancel(".\0", 0x1100004, 0x6)		 = 24 0
42115/0x932ea:  fstatfs64(0x18, 0xBFFFD9F0, 0x6)		 = 0 0
42115/0x93477:  __semwait_signal(0xD07, 0x0, 0x1)		 = -1 Err#60
42115/0x932ea:  getdirentries64(0x18, 0x99F6000, 0x1000)		 = 200 0
42115/0x932ea:  close_nocancel(0x18)		 = 0 0
42115/0x932ea:  statfs64(0x179AD8BC, 0xBFFFDA70, 0x1000)		 = 0 0
42115/0x932ea:  getattrlist("/Volumes/SDD\0", 0xBFFFDA50, 0xBFFFDA30)		 = 0 0
42115/0x932ea:  open("Assets\0", 0x0, 0x0)		 = 24 0
42115/0x932ea:  getdirentriesattr(0x18, 0xBFFFDA50, 0xBFFFC2E8)		 = -1 Err#45
42115/0x932ea:  write_nocancel(0x4, "error getting directory contents Assets/\nmeObject>\0", 0x29)		 = 41 0
42115/0x932ea:  close(0x18)		 = 0 0
```

**Comment by lundman** [comment]
If you can run my dtruss, I added the decoding of the getattrlist flags as well as a few other options

http://www.lundman.net/dtruss2

**Comment by aukaost** [comment]
https://gist.github.com/aukaost/905e4d3ff4e99d809ec1

**Comment by lundman** [comment]
Ah oh, its not getattrlist, 
```
getdirentriesattr(0x3A, 0x7FFF5FBFAD90, 0x7FFF5FBFB670)          = -1 Err#45
```

We don't have that implemented, but rely on VFS to use compat code. Clearly that is going wrong. You could try with it compiled in again, although we need to update our versions. We could also look at updating dtruss2 to show the flags requested.

**Comment by lundman** [comment]
```
include//sys/zfs_vfsops.h:/* #define WITH_READDIRATTR */
```

**Comment by elaberge** [comment]
I modified the dtruss2 script to dump more infos about "getdirentriesattr", and got the following:
```getdirentriesattr(FD=0x1E, attrList=0xBFFFD110, attrBuf=0xBFFFB9A8, attrBufSize=5888, count=0xBFFFB9A0 (64), basep=0xBFFFB99C (277383193484), newState=0xBFFFB998 (10760123759630203336), options=0x0) <commonattr 0x40409, volattr 0x0, dirattr 0x0, fileattr 0x0, forkattr 0x0>		 = -1 Err#45```

The "commonattr" flags would indicate a request for ```ATTR_CMN_FLAGS | ATTR_CMN_MODTIME | ATTR_CMN_OBJTYPE | ATTR_CMN_NAME```

Here is the modified script: https://gist.github.com/elaberge/cb6ba736310d293abeb9

**Comment by lundman** [comment]
We really should check it into the repo, maybe under tools or something, I also cooked together a `decode_getattrlist.c` just to expand the bitfields, so you can pipe to it from truss, (Actually did the bit fields in dtrace initially, but it was a bit too heavy).

But that aside, with `#define WITH_READDIRATTR` commented out, we just return ENOTSUPP in that handler. Which is indeed Err#45. I'm more surprised that it actually seems to call it directly, as the VFS layer intercepts those calls when the fs claims not to support it, to replace with iterative versions. But I guess if the app is insistant on calling it, they can. So, we should uncomment `#define WITH_READDIRATTR` and confirm it works. There may be bitfields that are newer than our code, if so, we will simply implement them.

**Comment by elaberge** [comment]
Uncommenting ```#define WITH_READDIRATTR``` made Unity working properly (ran in a VM, did not test much).

"getdirentriesattr" seems to work enough:
```
41866/0xd882:  getdirentriesattr(FD=0x17, attrList=0xBFFFDB70, attrBuf=0xBFFFC408, attrBufSize=5888, count=0xBFFFC400 (4), basep=0xBFFFC3FC (17179869184), newState=0xBFFFC3F8 (2350241137), options=0x0) <commonattr 0x40409, volattr 0x0, dirattr 0x0, fileattr 0x0, forkattr 0x0>		 = 1 0

             0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f  0123456789abcdef
         0: 30 00 00 00 18 00 00 00 14 00 00 00 01 00 00 00  0...............
        10: 8d 66 6e 55 18 fa 5d 21 00 80 00 00 55 6e 74 69  .fnU..]!....Unti
        20: 74 6c 65 64 2e 75 6e 69 74 79 2e 6d 65 74 61 00  tled.unity.meta.
        30: 28 00 00 00 18 00 00 00 0b 00 00 00 02 00 00 00  (...............
        40: 87 66 6e 55 90 00 67 03 00 00 00 00 4e 65 77 20  .fnU..g.....New 
        50: 46 6f 6c 64 65 72 00 69 2c 00 00 00 18 00 00 00  Folder.i,.......
        60: 0f 00 00 00 01 00 00 00 8d 66 6e 55 38 3e bf 1f  .........fnU8>..
        70: 00 00 00 00 55 6e 74 69 74 6c 65 64 2e 75 6e 69  ....Untitled.uni
        80: 74 79 00 6d 2c 00 00 00 18 00 00 00 10 00 00 00  ty.m,...........
        90: 01 00 00 00 82 66 6e 55 a8 25 fd 16 00 80 00 00  .....fnU.%......
        a0: 4e 65 77 20 46 6f 6c 64 65 72 2e 6d 65 74 61 00  New Folder.meta.
        b0: 40 80 8a 0d 00 80 8a 0d 00 00 00 00 00 00 00 00  @...............
        c0: 08 c5 ff bf 8c 6b 5e 96 00 80 8a 0d 94 ff ff ff  .....k^.........
        d0: 1d 00 00 00 00 00 00 00 48 c5 ff bf 00 00 00 00  ........H.......
        e0: 00 00 00 00 00 04 00 00 00 00 00 00 08 00 00 00  ................
        f0: 01 82 af 84 dc ff 00 00 f8 cb ff bf 90 d6 ff bf  ................
       100: 58 c5 ff bf 93 e2 6b 96 94 ff ff ff 1c 00 00 00  X.....k.........
       (snip)
```

**Comment by lundman** [comment]
Ok, so the plan will be to dust off the readdirattr, and perhaps also fix up the getattrlistbulk branch while we are at it.

**Comment by JMoVS** [comment]
no new activity since 2015 here
