### ISSUE TITLE
Unable to shutdown and/or unmount Filesystems with error: ARC release bug triggered: 0xffffff83d7153e48 (67)

### ISSUE THREAD

**Issue by mruepp** [openzfsonosx/zfs#303]
If I mount my Filesystems and let the machine running for a while (1-2h), I am not longer able to unmount the filesystems or reboot/shutdown.
I experienced the memory fills up after a while with ARC, I had Disk Activity despite doing nothing, It is mdworker.

The ZFS hangs with (always the same HEX) message:
29.04.15 22:53:07,000 kernel[0]: dnode: ARC release bug triggered: 0xffffff83d7153e48 (67)-- sorry

sunrise:~ michael$ sudo zfs unmount -f tank/projects
Running process: '/usr/sbin/diskutil' 'unmount' 'force' '/Volumes/tank/projects' 
Unmount failed for /Volumes/tank/projects
cannot unmount '/Volumes/tank/projects': umount failed

kstat.zfs.darwin.tunable.zfs_arc_max: 0 -> 11811160064
kstat.zfs.darwin.tunable.zfs_arc_meta_limit: 0 -> 8858370048

Apr 29 11:21:32 localhost kernel[0]: ZFS: Loaded module v1.3.1-2, ZFS pool version 5000, ZFS filesystem version 5
Apr 29 11:21:32 localhost kernel[0]: ZFS filesystem version: 5

**Comment by lundman** [comment]
This is indeed a bug we have been hunting forever, and we have yet to find a reliable way to trigger it. If you know of a sequence that makes it happen that would be interesting.

Out of curiosity what is process 
```
lsof: WARNING -- child process 8318 may be hung.
```

In this situation? A particular program you run?

I change this a little bit in HEAD, but someone else has also reported it still happens.

**Comment by mruepp** [comment]
I don´t know what this process was, but I actually have nothing running on the zfs filesystems. I guess it´s mdworker, doing indexreading. All I experience is the wired memory piling up with time. When I try to shutdown after a while, I am not able to and the error occures in the logs. 
Just tell me what kind of debugging you want me to deliver. If you want to RA to the system, just send me a PM.

**Comment by lundman** [comment]
Are you able to build from sources? Be interesting to see if the new code changes the messages you get, and if you can trigger it easily.

If you can't build easily from sources, we do have temporary debug head builds lying around

**Comment by mruepp** [comment]
Now am able to build, have now the latest head installed.
With the 1.3.2 RC1 I reduced the Arc-Cache to 6GB/4GB Meta and experienced a sudden reboot after I tried to unmount my fs after an amount of utilization.
I do a recent backup overnight then I am able to stick with debugging, just tell me what to do. 
keepsyms is enabled.

**Comment by mruepp** [comment]
Ok, what I observe now with the new master branch is, if I unmount the Datasets via Finder Mouse - Eject tank, I see an instant RESET of the System. The Arc-release bug was triggered by the unmount like this (or by cli). A pool export by cli is still possible.

**Comment by lundman** [comment]
Oh? The eject from finder is not allowed, and we spent quite some time trying to figure out how to get rid of that eject icon but to no avail.

Normal cli zpool export, or, just a system reboot/shutdown should not see ARC release bug we hope

**Comment by mruepp** [comment]
Ok, in the release 1.3.1-r2 and rc5, at least there was no System reset, the unmount worked (if the filesystem was not under use before). If the filesystem was under use an amount of time, it was just for that dataset and the parent dataset (for instance tank/testdataset) not possible to eject (by mouse or command+E) and the ARC Bug appeared. It was also not possible to zfs unmount the dataset and its parent, even not with -f option and ARC Bug appeared. Also a reboot or shutdown was not possible without a hard reset.

**Comment by mruepp** [comment]
Not observed anymore
