### ISSUE TITLE
Readme.md references it being mainly tested on OS X Mavericks

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#307]
Does that still hold true, as we are in the middle of the support cycle of 10.10 already?

**Comment by ilovezfs** [comment]
No, most testing is currently on 10.10 (and 10.8) now.

**Comment by JMoVS** [comment]
BTW: It's README.marldown, nevertheless, for the next commit, this can be changed ;-)

**Comment by ilovezfs** [comment]
https://github.com/openzfsonosx/spl/commit/cbfa496afa6682443eeaba2ee8df2f070424b110
https://github.com/openzfsonosx/zfs/commit/0dec63b4de29dec8caafbb5bf97e0d76e556c15f
