### ISSUE TITLE
use sensible date format to display resilvering progress of 'zpool status'

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#311]
When a pool is resilvering, the current date format output to show the beginning of the resilvering process looks like this:

````resilver in progress since Thu May 14 10:00:15 2015````

This is peculiar in a manigfold of ways:
1. It's a mixture of american date format (https://twitter.com/html5_yoda/status/545129883438166016)
2. and a time suddenly in the middle of it

it's DD (in words) MM (in words) dd (now in numbers) HH:MM:SS (<- this is fine) YYYY (at the end?)

I propose:

````resilver in progress since Thu, 14.05.15 at 10:00:15````

**Comment by ilovezfs** [comment]
This is more of an upstream issue (illumos), than an OpenZFS on OS X issue. The code is just calling the standard C function <code>ctime</code>:
https://github.com/illumos/illumos-gate/blob/master/usr/src/cmd/zpool/zpool_main.c#L3819
https://github.com/openzfsonosx/zfs/blob/master/cmd/zpool/zpool_main.c#L4132

 <code>ctime</code> is explained here:
http://en.cppreference.com/w/c/chrono/ctime
https://www-s.acm.illinois.edu/webmonkeys/book/c_guide/2.15.html#ctime
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/ctime.3.html

You could use <code>strftime</code> to achieve the result you requested:
http://en.cppreference.com/w/c/chrono/strftime
https://www-s.acm.illinois.edu/webmonkeys/book/c_guide/2.15.html#strftime
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/strftime.3.html

**Comment by JMoVS** [comment]
how could I myself achieve that? Fork it upstream and compile myself? Or file a bug there that they change that to strftime? ^^

**Comment by ilovezfs** [comment]
If you want it changed upstream, you can make your proposal here: https://www.illumos.org/projects/site/issues

Another option is to solicit feedback on the openzfs mailing list: http://open-zfs.org/wiki/Mailing_list

If you just want to get it working for yourself, you can make the change locally and install from source.
