### ISSUE TITLE
xattr=sa support

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#315]
Right now O3X can create a dataset with xattr=sa (https://github.com/zfsonlinux/zfs/commit/82a37189aac955c81a59a5ecc3400475adb56355), but zfs get then returns xattr=off (temporary). Actual behavior appears to currently be the same as xattr=off. On ZoL, a dataset created by O3X with xattr=sa is reported as such.

O3X:
```
Josephs-MacBook-Pro:vms joe$ sudo zfs create -o xattr=sa myfp/xattrsa
Josephs-MacBook-Pro:~ joe$ zfs get xattr myfp/xattrsa 
NAME          PROPERTY  VALUE  SOURCE
myfp/xattrsa  xattr     off    temporary
```

ZoL (same pool):
```
openzfs ~ # zfs get xattr myfp/xattrsa
NAME          PROPERTY  VALUE  SOURCE
myfp/xattrsa  xattr     sa     local
```

So we should probably either enable xattr=sa support, or at least disallow creation of xattr=sa datasets.

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs/commit/a539ee79f1d0

**Comment by ilovezfs** [comment]
https://github.com/openzfsonosx/zfs/commit/6a06ef26abc87c6ede9bec8246713dc94c98fa78
