### ISSUE TITLE
System reports case insensitive filesystem as case sensitive

### ISSUE THREAD

**Issue by elaberge** [openzfsonosx/zfs#321]
While trying to find out more infos on issue #301, I found out that the "info" panel for a mimic_hfs-enabled pool reports its format as a case sensitive Mac partition. This struck me odd, as I remembered following the tutorial which had the case insensitive option as recommended.

Double checking the settings:
```
zfs get casesensitivity HDD
NAME  PROPERTY         VALUE        SOURCE
HDD   casesensitivity  insensitive  -
```
It seems case sensitivity is somehow not reported correctly to the system. I did some Google-fu and came up with this simple utility:
```
#include <sys/param.h>
#include <sys/mount.h>
#include <unistd.h>
#include <stdio.h>

int main(int argc, char*argv[])
{
  struct statfs volinfo;
  if(statfs(argv[1], &volinfo) != 0)
  {
    perror("statfs");
    return -1;
  }

  printf("%s:%s,", argv[1], volinfo.f_fstypename);

  long enabled;
  enabled = pathconf(argv[1], _PC_CASE_SENSITIVE);
  printf("%s,", enabled < 0 ? "Sensitivity unknown" : (enabled == 0 ? "Not case sensitive" : "Case sensitive"));

  enabled = pathconf(argv[1], _PC_CASE_PRESERVING);
  printf("%s", enabled < 0 ? "Preserving unknown" : (enabled == 0 ? "Not case preserving" : "Case preserving"));

  return 0;
}
```
My bootable partition reports:
```/:hfs,Not case sensitive,Case preserving```
The zfs one reports:
```/Volumes/HDD:zfs,Case sensitive,Case preserving```
And turning on mimic_hfs:
```/Volumes/HDD:hfs,Case sensitive,Case preserving```

This is on OSX 10.10.4 and build 1.3.2-RC1

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs/commit/f23bc05a759fda6d6b83c045245eb63447bef112

How many ways do OSX need to check case-sensitivity :)

Thanks for the thorough report and sample, once I knew you were talking about pathconf it was easy to fix.

It is also possible that we have to report the statfs subtype for HFS for certain things to be happy.
