### ISSUE TITLE
zdb -Z hangs

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#324]
The test/zfs-tests/tests/functional/cli_root/zdb contains a number of tests that stimulate zdb with various command line arguments.

The final test zdb -Z hangs zdb. Can be reproduced from command line.

I have disabled the test case, please re-enable when addressed.

**Comment by lundman** [comment]
```
#ifdef __APPLE__
		case 'Z':
			zdb_forever = 1;
```

Wouldn't it be a failure if -Z returned?

**Comment by brendonhumphrey** [comment]
All I know is that the tests expect it to exit.

Nothing saying that the tests are 100% correct mind you, but this seem cut and dried.

**Comment by BjoKaSH** [comment]
zdb not returning is exactly what is expected.  This option was added in the old MacZFS to allow attaching a debugger after initialization.  A similar option exists in MacZFS' version of  ztest.  The goal was to debug strange behavior when ztest runs zdb, i.e let both initialize and fork their worker(s) and then wait in both until GDB attached and set the variables zdb_forever  and ztest_forever to zero.  
The commit which introduced this is f55da7b (April 13, 2013).
