### ISSUE TITLE
`zpool list` not showing pools?

### ISSUE THREAD

**Issue by ylluminate** [openzfsonosx/zfs#327]
I have been having this issue for a few months and had hoped that the last update I made about a month ago would resolve it:

```
$ zpool list
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
-         -      -      -      -      -       -  -
-         -      -      -      -      -       -  -
-         -      -      -      -      -       -  -
```

Any idea what's going on here? 

Additionally, lately I've not had any luck at force unmounting volumes for an update and have to reboot, login as root and then unmount the zfs volumes before removing the kext and updating.  I wanted to try another build before I report that here, but thought that I'd at least mention it.

**Comment by brendonhumphrey** [comment]
sudo zpool list
flatmac2:~ brendy$ sudo zpool list
Password:
NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
backups  2.72T  2.21T   524G         -    25%    81%  1.00x  ONLINE  -
tank     9.06T  4.26T  4.80T         -    15%    47%  1.00x  ONLINE  -
flatmac2:~ brendy$ 

Perhaps you could provide a little more detail?

**Comment by lundman** [comment]
Indeed, maybe he just needs to use `sudo`

**Comment by ylluminate** [comment]
No unfortunately guys `sudo zpool list` and running as root all yield the same thing.  This has been going on for some time and frankly there's not much else of use to report.  It literally gives me:

```
$ sudo zpool list 
Password:
NAME   SIZE  ALLOC   FREE    CAP  DEDUP  HEALTH  ALTROOT
-         -      -      -      -      -       -  -
-         -      -      -      -      -       -  -
-         -      -      -      -      -       -  -
```

Obviously I know what pools are ZFS and can therefore attempt exports on them (which, as noted, fails until I reboot and login as root), but I thought that this was odd and should seek some input.

**Comment by lundman** [comment]
Neat. I guess the next question would be, if the userland binaries and libraries, might not be the same version as the kext.

Could we get output from:

```
# which zpool
# ls -l `which zpool`
# otool -L `which zpool`
```

**Comment by ylluminate** [comment]
Holy rusted metal Batman, there's another copy of `zpool` floating around on me from an old install before either I or `zfsadm` changed the path about 10 months ago!  Thanks for reminding me to check that.  I had assumed that the paths had not changed. :shipit:

**Comment by lundman** [comment]
Awesome! These are the best kind of tickets!
