### ISSUE TITLE
SA_LOOKUP called with NULL bulk[i].sa_addr

### ISSUE THREAD

**Issue by lundman** [openzfsonosx/zfs#33]
When importing ZEVO volumes (in particular), if we attempt to chown a file we will receive an error (even though technically the chown worked - but due to failure is not committed, and we end up in an inconsistent state).

Note that setattr receiving an error, leaving dmu_tx confused. Possibly we don't clean up properly after failures. This should also be looked at.

However, that we call SA_LOOKUP with a NULL `sa_addr` feels incorrect.

zfs_vnops.c:3618
```
		err = zfs_acl_chown_setattr(zp);
		ASSERT(err == 0);
		if (attrzp) {
			err = zfs_acl_chown_setattr(attrzp);
			ASSERT(err == 0);
		}

        /*
         * When importing ZEVO volumes, and 'chown' is used, we end up calling
         * SA_LOOKUP with 'sa_addr' == NULL. Unsure why this happens, for
         * now, we shall stick a plaster over this open-fracture
         */
        if (err == 2) {
            printf("setattr: triggered SA_LOOKUP == NULL problem\n");
            err = 0;
        }

```

Has been added as a temporary fix. We ignore the error=2 from SA_LOOKUP/sa_addr=NULL, and chown works as expected. Even when using ZEVO pools.

The error is returned from;

sa.c:392
```
		switch (data_op) {
		case SA_LOOKUP:
			if (bulk[i].sa_addr == NULL)
				return (ENOENT);
```

**Comment by ilovezfs** [comment]
This has been patched upstream: https://github.com/zfsonlinux/zfs/pull/2061
