### ISSUE TITLE
Default mount point for Mac (/Volumes) breaks test contract

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#330]
The ZFS test suite assumes default ZFS behaviour of mounting in /. For the Mac platform a design decision has been made to move the default mount point to /Volumes. 

This issue requests that a configuration mechanism be provided to enable swapping between the legacy and platform behaviour.

This will please some users, and prevent mass refactoring of the test suite.

O3X should default to the Mac platform behaviour i.e. use /Volumes unless otherwise configured.

relevant discussion:

10:49 AM <ilovezfs_> illumos has environment variable __ZFS_POOL_RESTRICT specifically for test suite
10:55 AM <ilovezfs_> so choices are
10:55 AM <ilovezfs_> (1) binary sysctl (just turn /Volumes on and off)
10:56 AM <ilovezfs_> (2) getenv ZFS_MAIN_MOUNTPOINT_DIR and use /Volumes if unset, sysadmins/users problem to get the environment variable fed in
10:56 AM <ilovezfs_> (3) same as (2), but have zfs always read in a generic zfs environment runcom file /etc/zfs/zfs.rc
10:56 AM <ilovezfs_> (4) compile time change only
10:56 AM <ilovezfs_> (5) something else

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs/commit/b55c6da26e3769950d6ae0095f195d7656bec568

```
# export __ZFS_MAIN_MOUNTPOINT_DIR="/"
# zpool import BOOM
BOOM            38Gi  108Mi   38Gi     1%    6900 80385216    0%   /BOOM
```
