### ISSUE TITLE
duplicate pointer in arc_buf_t

### ISSUE THREAD

**Issue by evansus** [openzfsonosx/zfs#331]
https://github.com/openzfsonosx/zfs/blob/5d0472b9d3870fca2fd8a3e51e91ebc9cd085993/include/sys/arc.h#L64

Looks like we wound up with a duplicate pointer for kmutex_t * in the arc_buf_t struct. b_data_pointer should have been renamed b_evict_lock, instead we wound up having both.
git grep b_data_lock showed it only remains in this header file.

Not a major issue, but every arc_buf_t has 8 bytes of overhead.

**Comment by evansus** [comment]
#332

**Comment by lundman** [comment]
Thanks for the work you did on this
