### ISSUE TITLE
Cannot backup ZFS volumes via Time Machine

### ISSUE THREAD

**Issue by TheMacMini09** [openzfsonosx/zfs#335]
As the title says. The volumes are automatically excluded in Time Machine, and attempting to remove them fails (select volumes, click "-", click "Save", click "Options..." volumes are back). I can't seem to find anything anywhere suggesting a fix (or that this is intended) - any help would be appreciated.

**Comment by brendonhumphrey** [comment]
Duplicate of #66, this is a known issue. Thanks for the report.

**Comment by Fnuxus** [comment]
> As the title says. The volumes are automatically excluded in Time Machine, and attempting to remove them fails (select volumes, click "-", click "Save", click "Options..." volumes are back). I can't seem to find anything anywhere suggesting a fix (or that this is intended) - any help would be appreciated.

See if https://openzfsonosx.org/forum/viewtopic.php?f=11&t=3408 works for you.
