### ISSUE TITLE
Kindly welcome "Possible unresolved transaction race -110/(Music/iTunes Music/Music/Eagles/Hell Freezes Over,(null)) again in 12.2

### ISSUE THREAD

**Issue by mruepp** [openzfsonosx/zfs#339]
After Updating to Yosemite 10.10.4 and Itunes 12.2, the bug gets reintroduced.

**Comment by mruepp** [comment]
Bug disappeared with Itunes 12.3. I do not observe it anymore. Anyone?

**Comment by jonasjonas** [comment]
I had this problem today on Yosemite 10.10.5 and iTunes 12.3.0.44 while consolidating the library:

iTunes[93216]: Possible unresolved transaction race -178/(Music/King Crimson/In the Court of the Crimson King (Expanded Edition),(null))

**Comment by mruepp** [comment]
Still existing in 1.4.5. Itunes is unavailable for a night after disable/enable icloud music (former itunes match)

**Comment by mruepp** [comment]
I observe the Issue with 1.4.5 as well. I did a Instruments trace of the file activities and a system trace and a spindump. I am not able to upload a zip here. I upload it on the forum.

**Comment by ilovezfs** [comment]
Commented here: https://github.com/openzfsonosx/zfs/issues/394#issuecomment-154643032

**Comment by mruepp** [comment]
Close this issue as dublicate of https://github.com/openzfsonosx/zfs/issues/394
