### ISSUE TITLE
kernel panic on _put_nvlist

### ISSUE THREAD

**Issue by reznikmm** [openzfsonosx/zfs#341]
try of `zpool list` (or `zpool create`) causes kernel panic:

    mac:~ max$ sysctl -a | grep kext_version
    spl.kext_version: 1.3.1-2
    zfs.kext_version: 1.3.1-2

    Anonymous UUID:       9C43B0D5-DDF0-127D-3163-F52E4C4F3D4A

    Thu Jul  2 10:33:28 2015

    *** Panic Report ***
    panic(cpu 0 caller 0xffffff8006c17cc2): Kernel trap at 0xffffff800690e058, type 14=page fault, registers:
    CR0: 0x0000000080010033, CR2: 0x00007ff629802c00, CR3: 0x00000001bdedb0a5, CR4: 0x00000000003627e0
    RAX: 0xffffff8126a7ffa8, RBX: 0xffffff812667b000, RCX: 0x0000000000000002, RDX: 0x0000000000000010
    RSP: 0xffffff8110d8ba38, RBP: 0xffffff8110d8ba40, RSI: 0xffffff8126a7ffa8, RDI: 0x00007ff629802c00
    R8:  0x0000000000000000, R9:  0x0000000000000010, R10: 0x0000000007fc0935, R11: 0x0000000000080000
    R12: 0x0000000000000000, R13: 0xffffff7f873f61d8, R14: 0xffffff81269fffa0, R15: 0xffffff8126a7ffa8
    RFL: 0x0000000000010202, RIP: 0xffffff800690e058, CS:  0x0000000000000008, SS:  0x0000000000000010
    Fault CR2: 0x00007ff629802c00, Error code: 0x0000000000000003, Fault CPU: 0x0 SMAP fault

    Backtrace (CPU 0), Frame : Return Address
    0xffffff8110d8b6e0 : 0xffffff8006b2bda1 mach_kernel : _panic + 0xd1
    0xffffff8110d8b760 : 0xffffff8006c17cc2 mach_kernel : _kernel_trap + 0x8d2
    0xffffff8110d8b920 : 0xffffff8006c34b73 mach_kernel : _return_from_trap + 0xe3
    0xffffff8110d8b940 : 0xffffff800690e058
    0xffffff8110d8ba40 : 0xffffff7f87319ae5 net.lundman.zfs : _put_nvlist + 0x55
    0xffffff8110d8ba70 : 0xffffff7f8731b85d net.lundman.zfs : _zfs_ioc_pool_configs + 0x29
    0xffffff8110d8ba90 : 0xffffff7f87319734 net.lundman.zfs : _zfsdev_ioctl + 0x36d
    0xffffff8110d8bb30 : 0xffffff8006d80fb9 mach_kernel : _spec_ioctl + 0x179
    0xffffff8110d8bb80 : 0xffffff8006d6f7f6 mach_kernel : _VNOP_IOCTL + 0x176
    0xffffff8110d8bc10 : 0xffffff8006d64693 mach_kernel : _vn_pathconf + 0xbe3
    0xffffff8110d8be00 : 0xffffff8006fae84b mach_kernel : _fo_ioctl + 0x7b
    0xffffff8110d8be30 : 0xffffff8006fed7c4 mach_kernel : _ioctl + 0x554
    0xffffff8110d8bf50 : 0xffffff800704ba86 mach_kernel : _unix_syscall64 + 0x296
    0xffffff8110d8bfb0 : 0xffffff8006c35376 mach_kernel : _hndl_unix_scall64 + 0x16
          Kernel Extensions in backtrace:
             net.lundman.zfs(1.3.1)[0A0974C1-DAF6-31E2-AC90-1DAFD34649D1]@0xffffff7f872ab000->0xffffff7f87459fff
                dependency: com.apple.iokit.IOStorageFamily(2.0)[76E50D45-C97B-3ED1-97C5-94E6E0EB4514]@0xffffff7f87247000
                dependency: net.lundman.spl(1.3.1)[C6AC8C88-D1A1-329A-B4BA-359F129DE859]@0xffffff7f87276000

    BSD process name corresponding to current thread: zpool
    Boot args: -v keepsyms=y kext-dev-mode=1

    Mac OS version:
    14D136

    Kernel version:
    Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64
    Kernel UUID: 4B3A11F4-77AA-3D27-A22D-81A1BC5B504D
    Kernel slide:     0x0000000006800000
    Kernel text base: 0xffffff8006a00000
    __HIB  text base: 0xffffff8006900000
    System model name: MacBookAir7,2 (Mac-937CB26E2E02BB01)

    System uptime in nanoseconds: 33503697785
    last loaded kext at 5370095360: org.virtualbox.kext.VBoxNetAdp   4.3.28 (addr 0xffffff7f893e2000, size 28672)
    loaded kexts:
    org.virtualbox.kext.VBoxNetAdp   4.3.28
    org.virtualbox.kext.VBoxNetFlt   4.3.28
    org.virtualbox.kext.VBoxUSB   4.3.28
    org.virtualbox.kext.VBoxDrv   4.3.28
    net.lundman.zfs   1.3.1
    net.lundman.spl   1.3.1
    com.apple.filesystems.autofs   3.0
    ...

**Comment by lundman** [comment]
can you check your userland binary matches that of the kernel version? We see these sort of panics if the binaries are not ours (zevo) or very old version of ours.

# which zpool
and
# ls -l `which zpool`

**Comment by reznikmm** [comment]
I have fresh installed OpenZFS_on_OS_X_1.3.1-r2.dmg

    # which zpool
    /usr/sbin/zpool
    # ls -l `which zpool`
    -rwxr-xr-x  1 root  wheel  121772 Apr  8 22:18 /usr/sbin/zpool

    # xcrun atos -arch x86_64 -l 0xffffff7f87276000 -o /Library/Extensions/zfs.kext/Contents/MacOS/zfs 0xffffff7f87319ae5 0xffffff7f8731b85d 0xffffff7f87319734
zprop_register_impl (in zfs) + 207
0x000a585d (in zfs)
zpool_prop_init (in zfs) + 798

**Comment by lundman** [comment]
Oh its SMAP fault, like https://github.com/openzfsonosx/zfs/issues/288 thought we fixed that

**Comment by reznikmm** [comment]
Indeed! After building from source all works fine! Thanks a lot!
