### ISSUE TITLE
cant zpool create using a file in /var/tmp

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#344]
If one creates a zfs dataset and arranges for it to be mounted at /var/tmp/child_dir, then mkfiles a file /var/tmp/child_dir/file, and then sudo zpool create -f tt /var/tmp/child_dir/file, the create will fail.

if the same dataset is mounted elsewhere (say /opt/tmp) the operation will succeed.

**Comment by lundman** [comment]
f6584e3008e0bb0948c7fcca51e784b886984654
