### ISSUE TITLE
OS X Caching Server Destination

### ISSUE THREAD

**Issue by TheMacMini09** [openzfsonosx/zfs#355]
This may be linked to the Time Machine issue #66 and possibly #116. For those you aren't familiar, the Caching Server is built in to OS X Server and is used for caching locally downloaded iTunes/App Store content (such as updates). It's very useful on a network where many people will be downloading the same thing. However, ZFS volumes are not available to be selected for caching. The only workaround is to symlink the caching directory onto the ZVol somewhere, which is a little hacky.

**Comment by brendonhumphrey** [comment]
you have to turn on the com.apple.mimic_hfs property for this to work - OS X server is one of the many applications that does not work on non-hfs filesystems - totally out of our control.

Cheers
Brendon

**Comment by TheMacMini09** [comment]
Thanks! Compiling from source was a breeze with the script on the wiki, as was enabling com.apple.mimic_hfs. Caching now works great!
