### ISSUE TITLE
Cannot backup ZFS volumes via Time Machine

### ISSUE THREAD

**Issue by noberasco** [openzfsonosx/zfs#356]
As the title says. The volumes are automatically excluded in Time Machine, and attempting to remove them fails (select volumes, click "-", click "Save", click "Options..." volumes are back). I can't seem to find anything anywhere suggesting a fix (or that this is intended) - any help would be appreciated.

Note that this is NOT a duplicate of #66.
#66 is about using ZFS as a Time Machine destination.

This one is about being able to back up ZFS volumes using Time Machine.

**Comment by brendonhumphrey** [comment]
Unfortunately this is not supported.

**Comment by noberasco** [comment]
Thanks for your reply.

It is a pity that on a mac we are forced to use 2 different backup systems (assuming I don't want to ditch Time Machine in favor of rsync).

In the end I did the following:
- created HFS system partition
- created ZFS data partition
- created ZPOOL on backup disk with a large ZFS volume and a smaller HFS volume
- (above HFS, ZFS and ZPOOL are encrypted using FileVault)
- backed up system partition to HFS volume within ZPOOL using time machine
- backed up data partition to backup ZFS volume using ZFSTimeMachine

Further steps:
- add a mirror device to backup disk ZPOOL

Sounds sensible?

**Comment by stigkj** [comment]
@brendonhumphrey: why would a OpenZFS volume need to support directory hardlinks when it is the source? I see why it would be needed if it was the destination.

**Comment by brendonhumphrey** [comment]
Because thats how time machine is implemented in the client!

- Brendon

**Comment by noberasco** [comment]
you are right @stigkj, directory hard links need to be supported on the *destination* volume, not on the *source* volume.

However, I have since solved my issue by adopting one of the available backup scripts for ZFS (https://github.com/jollyjinx/ZFS-TimeMachine.git) and configuring it to mimick Time Machine behavior in terms of scheduling and backup history. This solution makes use of native ZFS features (sending snapshots to the destination volume). In my own experience this ends up being more robust than Time Machine, and possibly faster, too.

@brendonhumphrey now that I'm a bit more knowledgeable on ZFS, in my opinion the fix for this issue is not on the ZFS side: I'm pretty sure that Time Machine checks whether the source volume is a HFS volume and prevents it from being backup up if it is not.

**Comment by ilovezfs** [comment]
@noberasco Also note that a similar tool called "znapzend" is now available in Homebrew: https://github.com/Homebrew/homebrew-core/blob/master/Formula/znapzend.rb

**Comment by noberasco** [comment]
I remember trying both ZFS-TimeMachine and znapsend before settling on the former. There was a technical reason behind my choice, but honestly I don't remember it ;-)

In any case both projects are essentially glorified shell scripts that run periodically.

**Comment by JMoVS** [comment]
I think this issue can be closed as this is no longer the case when using a combination of com.apple.devdisk and mimic_hfs

**Comment by Fnuxus** [comment]
Apparently I have found a way to solve this problem (see https://openzfsonosx.org/forum/viewtopic.php?f=11&t=3408).

I’d like to hear if it works for you, too.

**Comment by noberasco** [comment]
@Fnuxus this may well work.

However, in the mean while I discovered that using native ZFS snapshots as a backup means is a better solution in any case, if only for the vastly improved backup times.

**Comment by Fnuxus** [comment]
> @Fnuxus this may well work.
> 
> However, in the mean while I discovered that using native ZFS snapshots as a backup means is a better solution in any case, if only for the vastly improved backup times.

ZFS on macOS will only reach a significant user base if it integrates seamlessly into macOS. It is not sufficient for ZFS to be used by a few hackers, we need to reach the power users next, if we don’t want ZFS for macOS to be killed in future generations macOS.

**Comment by noberasco** [comment]
> ZFS on macOS will only reach a significant user base if it integrates seamlessly into macOS.

True, but in this particular use case (backing up data) I would say that what is needed is making the native ZFS backup capabilities more accessible instead of shoehorning a way to backup ZFS volumes using Time Machine.

Let me explain.

Time Machine on HFS+ volumes works by searching for differences between the file system on your main volume against the most recent backup on your your backup volume. It works, but it takes a lot of time and resources.

Time Machine on APFS Volumes works by creating and transferring volume snapshots. Creating a snapshot is almost instantaneous.

The performance improvement here is similar to using a SSD drive versus a traditional hard drive.

ZFS volume snapshots are conceptually very similar to APFS volume snapshots.

Enabling Time Machine like you suggested would force Time Machine to use 'search for differences' to perform backups, an approach which even Apple has moved away from.

A real solution would be to make Time Machine capable of working with ZFS snapshots in addition to APFS snapshots.

Or, alternatively, to provide user-friendly tools to manage ZFS snapshots. This would be easier than direct integration with Time Machine (which is not open source). Existing tools such as [ZnapZend](https://github.com/oetiker/znapzend/blob/master/README.md) can provide an excellent starting point for such a project...

**Comment by rjhind** [comment]
> Time Machine on APFS Volumes works by creating and transferring volume snapshots. Creating a snapshot is almost instantaneous.
> 

APFS takes local snapshots but I thought they can't be backed up as snapshots yet can they?  https://support.apple.com/en-gb/guide/mac-help/mh15139/mac suggests not.

TimemMachine to an APFS formatted drive isn't implemented so you have to reformat the backiup drive as HFS+ and then use standard 'searching' TimeMachine.

**Comment by noberasco** [comment]
You are right @aabc123, shame on me for not spotting that when I checked the documentation before answering @Fnuxus. Since I moved my production systems away from Time Machine a long time ago, I no longer have first-hand experience.

Well, this is one more reason to ditch Time Machine and make ZFS snapshotting more user friendly! Backing up by transferring ZFS snapshots to an external drive really only takes the time needed for the changed data to copy from one drive to the other, there is no 'searching' involved.

**Comment by Fnuxus** [comment]
Let’s assume, what’s normal, and what’s normal is that Mac users, especially experienced Mac users, have Time Machine backups reaching back for years, which they won’t be ready to give up in favour of ZFS snapshots that start from scratch, especially if they don’t know if they can trust ZFS and if they don’t know if ZFS snapshots allow user-friendly full text search like spotlight and allows you to find a file that has been renamed or moved to another folder. (Do they?)

Mac users are usually considered about productivity, and productivity is usually the reason why they use a Mac in the first place. 

Remember the O3X FAQ?: _Q) So if I use O3X, that means I don't need to back up, right?
A) Wrong. Wrong. Wrong._ – But how is a ZFS newbie going to back up, if Time Machine does not work?

If it’s not possible to backup ZFS volumes with Time Machine, this is a deal breaker for prospect ZFS users. – It is really important that this problem is now solved.
