### ISSUE TITLE
Regularly System Resets and Panics

### ISSUE THREAD

**Issue by mruepp** [openzfsonosx/zfs#359]
When shutting down, every thing seems like normal, but when rebooting I get the error that there was a Panic and a Stack Trace:
Anonymous UUID: 9893AABC-597E-BD5E-6C74-A90C1075093C

Wed Aug 19 16:16:08 2015

**\* Panic Report ***
panic(cpu 6 caller 0xffffff8000416df2): Kernel trap at 0xffffff7f80cc5803, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000055d487d7, CR3: 0x00000017c1156001, CR4: 0x00000000000626e0
RAX: 0x0000000055d487d7, RBX: 0x0000000000000000, RCX: 0x000000004c750a38, RDX: 0x0000000055d487d7
RSP: 0xffffff8af341bac0, RBP: 0xffffff8af341bac0, RSI: 0x0fffffffffffff01, RDI: 0x0000000055d487d7
R8: 0x0000000000000000, R9: 0x0000000000000000, R10: 0x0000000059931e50, R11: 0xffffff80d74515a0
R12: 0x0000000000080000, R13: 0xffffff81008b4cd0, R14: 0xffffff80d0f6ce20, R15: 0xffffff7f80e54bc0
RFL: 0x0000000000010206, RIP: 0xffffff7f80cc5803, CS: 0x0000000000000008, SS: 0x0000000000000010
Fault CR2: 0x0000000055d487d7, Error code: 0x0000000000000000, Fault CPU: 0x6

Backtrace (CPU 6), Frame : Return Address
0xffffff8af341b770 : 0xffffff800032ad21 mach_kernel : _panic + 0xd1
0xffffff8af341b7f0 : 0xffffff8000416df2 mach_kernel : _kernel_trap + 0x8d2
0xffffff8af341b9b0 : 0xffffff8000433ca3 mach_kernel : _return_from_trap + 0xe3
0xffffff8af341b9d0 : 0xffffff7f80cc5803 net.lundman.spl : _avl_first + 0xd
0xffffff8af341bac0 : 0xffffff7f80d66f87 net.lundman.zfs : _zfsctl_umount_snapshots + 0xbd
0xffffff8af341bb40 : 0xffffff7f80d7b161 net.lundman.zfs : _zfs_vfs_unmount + 0xac
0xffffff8af341bcb0 : 0xffffff800054b95c mach_kernel : _dounmount + 0x3bc
0xffffff8af341bd50 : 0xffffff8000547263 mach_kernel : _vfs_addtrigger + 0x18e3
0xffffff8af341bd80 : 0xffffff8000541fc4 mach_kernel : _vfs_iterate + 0x1f4
0xffffff8af341bdf0 : 0xffffff80007d54fe mach_kernel : _boot + 0x5de
0xffffff8af341bec0 : 0xffffff80007e6609 mach_kernel : _reboot + 0x119
0xffffff8af341bf50 : 0xffffff800084b376 mach_kernel : _unix_syscall64 + 0x296
0xffffff8af341bfb0 : 0xffffff80004344a6 mach_kernel : _hndl_unix_scall64 + 0x16
Kernel Extensions in backtrace:
net.lundman.spl(1.3.1)[F39CB967-69DD-3DD8-BB03-6C96821413A2]@0xffffff7f80cc5000->0xffffff7f80cfbfff
net.lundman.zfs(1.3.1)[B7BBB4A0-A975-37F2-A571-ADBD1760A87E]@0xffffff7f80cfc000->0xffffff7f80f36fff
dependency: com.apple.iokit.IOStorageFamily(2.0)[D0ABB996-2084-3A05-A166-5951D925EF80]@0xffffff7f80a47000
dependency: net.lundman.spl(1.3.1)[F39CB967-69DD-3DD8-BB03-6C96821413A2]@0xffffff7f80cc5000

BSD process name corresponding to current thread: launchd
Boot args: arch=x86_64 slide=0 dart=0 darkwake=no npci=0x3000 nvda_drv=1 kext-dev-mode=1 keepsyms=y 

Mac OS version:
14F27

Kernel version:
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Kernel UUID: 58F06365-45C7-3CA7-B80D-173AFD1A03C4
__HIB text base: 0xffffff8000100000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)

System uptime in nanoseconds: 3978903713993
last loaded kext at 36256894388: com.apple.driver.AudioAUUC 1.70 (addr 0xffffff7f8206e000, size 32768)
last unloaded kext at 3111990353728: com.avast.PacketForwarder  2.0 (addr 0xffffff7f82631000, size 12288)
loaded kexts:
com.github.osxfuse.filesystems.osxfusefs    2.7.5
com.nvidia.CUDA 1.1.0
net.lundman.zfs 1.3.1
net.lundman.spl 1.3.1
com.nvidia.web.GeForceWeb   10.0.5
com.nvidia.web.NVDAGK100HalWeb  10.0.5
com.nvidia.web.NVDAResmanWeb    10.0.5
com.intel.driver.EnergyDriver   2.0
org.hwsensors.driver.GPUSensors 1372
com.Areca.ArcSAS    2.0.4
at.obdev.nke.LittleSnitch   4246
org.hwsensors.driver.CPUSensors 1372
org.netkas.driver.FakeSMC   1372
com.apple.driver.AppleBluetoothMultitouch   85.3
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport 4.3.6f3
com.apple.filesystems.autofs    3.0
com.apple.iokit.IOUserEthernet  1.0.1
com.apple.driver.AppleUpstreamUserClient    3.6.1
com.apple.iokit.IOBluetoothSerialManager    4.3.6f3
com.apple.Dont_Steal_Mac_OS_X   7.0.0
com.apple.driver.AppleHWAccess  1
com.apple.driver.AppleHV    1
com.apple.driver.AppleOSXWatchdog   1
com.apple.driver.AppleBacklight 170.7.4
com.apple.driver.AppleLPC   1.7.3
com.apple.driver.Apple16X50ACPI 3.2
com.apple.driver.AppleIntelSlowAdaptiveClocking 4.0.0
com.apple.driver.AppleMCCSControl   1.2.12
com.apple.driver.ACPI_SMC_PlatformPlugin    1.0.0
com.apple.driver.AppleIntelMCEReporter  107
com.apple.iokit.SCSITaskUserClient  3.7.5
com.apple.driver.XsanFilter 404
com.apple.iokit.IOAHCIBlockStorage  2.7.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless 1.0.0d1
com.apple.driver.AppleUSBXHCI   710.4.11
com.apple.driver.AppleFWOHCI    5.5.2
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0
com.apple.BootCache 36
com.apple.driver.AppleUSBHub    705.4.2
com.apple.iokit.AppleIntelI210Ethernet  2.2.0b1
com.apple.driver.AppleAHCIPort  3.1.2
com.apple.driver.AppleUSBEHCI   705.4.14
com.apple.driver.AppleACPIButtons   3.1
com.apple.driver.AppleHPET  1.8
com.apple.driver.AppleRTC   2.0
com.apple.driver.AppleSMBIOS    2.1
com.apple.driver.AppleIntelCPUPowerManagementClient 218.0.0
com.apple.driver.AppleAPIC  1.7
com.apple.nke.applicationfirewall   161
com.apple.security.quarantine   3
com.apple.security.TMSafetyNet  8
com.apple.driver.AppleIntelCPUPowerManagement   218.0.0
com.apple.driver.IOBluetoothHIDDriver   4.3.6f3
com.apple.driver.AppleMultitouchDriver  264.6
com.apple.iokit.IOSCSIMultimediaCommandsDevice  3.7.5
com.apple.iokit.IOBDStorageFamily   1.7
com.apple.iokit.IODVDStorageFamily  1.7.1
com.apple.iokit.IOCDStorageFamily   1.7.1
com.apple.iokit.IOAHCISerialATAPI   2.6.1
com.apple.iokit.IOBluetoothHostControllerUSBTransport   4.3.6f3
com.apple.driver.AppleUSBHIDKeyboard    176.2
com.apple.driver.AppleHIDKeyboard   176.2
com.apple.kext.triggers 1.0
com.apple.iokit.IOUSBUserClient 705.4.0
com.apple.iokit.IOUSBHIDDriver  705.4.0
com.apple.iokit.IOSurface   97.4
com.apple.iokit.IOBluetoothFamily   4.3.6f3
com.apple.iokit.IOAcceleratorFamily2    156.16
com.apple.AppleGraphicsDeviceControl    3.10.25
com.apple.iokit.IOFireWireIP    2.2.6
com.apple.driver.AppleBacklightExpert   1.1.0
com.apple.iokit.IONDRVSupport   2.4.1
com.apple.driver.AppleHDAController 272.18.1
com.apple.iokit.IOHDAFamily 272.18.1
com.apple.driver.AppleUSBMergeNub   705.4.0
com.apple.driver.Apple16X50Serial   3.2
com.apple.iokit.IOSerialFamily  11
com.apple.iokit.IOSlowAdaptiveClockingFamily    1.0.0
com.apple.driver.AppleSMBusController   1.0.13d1
com.apple.iokit.IOSMBusFamily   1.1
com.apple.iokit.IOGraphicsFamily    2.4.1
com.apple.driver.AppleSMC   3.1.9
com.apple.driver.IOPlatformPluginLegacy 1.0.0
com.apple.driver.IOPlatformPluginFamily 5.9.1d7
com.apple.driver.AppleUSBAudio  295.23
com.apple.iokit.IOAudioFamily   203.3
com.apple.vecLib.kext   1.2.0
com.apple.iokit.IOSCSIBlockCommandsDevice   3.7.5
com.apple.iokit.IOUSBMassStorageClass   3.7.2
com.apple.driver.AppleUSBComposite  705.4.9
com.apple.iokit.IOFireWireFamily    4.5.8
com.apple.iokit.IOSCSIParallelFamily    3.0.0
com.apple.iokit.IOSCSIArchitectureModelFamily   3.7.5
com.apple.iokit.IOEthernetAVBController 1.0.3b3
com.apple.driver.mDNSOffloadUserClient  1.0.1b8
com.apple.iokit.IOAHCIFamily    2.7.5
com.apple.iokit.IOUSBFamily 720.4.4
com.apple.iokit.IONetworkingFamily  3.2
com.apple.driver.AppleEFINVRAM  2.0
com.apple.iokit.IOHIDFamily 2.0.0
com.apple.driver.AppleEFIRuntime    2.0
com.apple.security.sandbox  300.0
com.apple.kext.AppleMatch   1.0.0d1
com.apple.driver.AppleKeyStore  2
com.apple.driver.AppleMobileFileIntegrity   1.0.5
com.apple.driver.AppleCredentialManager 1.0
com.apple.driver.DiskImages 398
com.apple.iokit.IOStorageFamily 2.0
com.apple.iokit.IOReportFamily  31
com.apple.driver.AppleFDEKeyStore   28.30
com.apple.driver.AppleACPIPlatform  3.1
com.apple.iokit.IOPCIFamily 2.9
com.apple.iokit.IOACPIFamily    1.4
com.apple.kec.corecrypto    1.0
com.apple.kec.Libm  1
com.apple.kec.pthread   1
Model: MacPro6,1, BootROM MP61.0116.B04, 16 processors, 2.60 GHz, 96 GB, SMC 2.2f18
Graphics: NVIDIA GeForce GTX 770, NVIDIA GeForce GTX 770, PCIe, 2047 MB
Memory Module: BANK0/DIMM0, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK1/DIMM0, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK0/DIMM0, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK1/DIMM0, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK0/DIMM1, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK1/DIMM1, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK0/DIMM1, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK1/DIMM1, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: Intel 7 Series Chipset Family SATA Controller, AHCI Controller, Built In
Serial ATA Device: Samsung SSD 840 Series, 250,06 GB
Serial ATA Device: Crucial_CT500MX200SSD1, 500,11 GB
Serial ATA Device: TSSTcorp CDDVDW SH-224DB
USB Device: Hub
USB Device: Hub
USB Device: USB2.0 Hub
USB Device: Mass Storage Device
USB Device: Hub
USB Device: Hub
USB Device: USB2223
USB Device: Hub
USB Device: Keyboard Hub
USB Device: BCM20702A0
USB Device: Apple Keyboard
USB Device: PS/2+USB Mouse
USB Device: io|2
Thunderbolt Bus:

**Comment by mruepp** [comment]
When sending and receiving snapshots to external USB HD, Panic:

Aug 19 20:24:59 localhost kernel[0] <Notice>: ZFS: Loaded module v1.3.1-374_g3cf7efc, ZFS pool version 5000, ZFS filesystem version 5
Aug 19 20:24:59 localhost kernel[0] <Notice>: SPL: Total memory 103079215104
Aug 19 20:24:59 localhost kernel[0] <Notice>: SPL: Loaded module v1.3.1-29_g0ea00ce, (ncpu 16, memsize 103079215104, pages 25165824) 

Commands I used:
sudo zfs send -v tank/media@full-snap | sudo zfs recv -dvu zBackup02/BackTank
(to zpool)
sudo zfs send -v tank/projects@full-snap | gzip > /Volumes/BigBackup02/zfsBackups/tank/projects-full-snap.img.gz
(to the same harddrive but hfs+ formatted)


Anonymous UUID: 9893AABC-597E-BD5E-6C74-A90C1075093C

Wed Aug 19 20:24:59 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff800085bb96): "A kext releasing a(n) IOSCSIParallelInterfaceDevice has corrupted the registry."@/SourceCache/xnu/xnu-2782.40.9/libkern/c++/OSObject.cpp:219
Backtrace (CPU 0), Frame : Return Address
0xffffff909b47bba0 : 0xffffff800032ad21 mach_kernel : _panic + 0xd1
0xffffff909b47bc20 : 0xffffff800085bb96 mach_kernel : __ZNK8OSObject13taggedReleaseEPKvi + 0xc6
0xffffff909b47bc70 : 0xffffff7f80ae6d93 com.apple.iokit.IOSCSIArchitectureModelFamily : __ZN22IOSCSIProtocolServices20ProcessCompletedTaskEP8OSObject19SCSIServiceResponse14SCSITaskStatus + 0x1fb
0xffffff909b47bcc0 : 0xffffff7f80ae6df4 com.apple.iokit.IOSCSIArchitectureModelFamily : __ZN22IOSCSIProtocolServices16CommandCompletedEP8OSObject19SCSIServiceResponse14SCSITaskStatus + 0x42
0xffffff909b47bcf0 : 0xffffff7f80b16f82 com.apple.iokit.IOSCSIParallelFamily : __ZN29IOSCSIParallelInterfaceDevice15SendSCSICommandEP8OSObjectP19SCSIServiceResponseP14SCSITaskStatus + 0x1c4
0xffffff909b47bd30 : 0xffffff7f80ae6a10 com.apple.iokit.IOSCSIArchitectureModelFamily : __ZN22IOSCSIProtocolServices22SendSCSITasksFromQueueEv + 0x13a
0xffffff909b47bd90 : 0xffffff7f80ae6ecd com.apple.iokit.IOSCSIArchitectureModelFamily : __ZN22IOSCSIProtocolServices14ExecuteCommandEP8OSObject + 0xab
0xffffff909b47bdc0 : 0xffffff7f80ae47e2 com.apple.iokit.IOSCSIArchitectureModelFamily : __ZN27IOSCSIPrimaryCommandsDevice11SendCommandEP8OSObjectj + 0x11c
0xffffff909b47be00 : 0xffffff7f80aebb46 com.apple.iokit.IOSCSIArchitectureModelFamily : __ZN18IOSCSITargetDevice25VerifyLogicalUnitPresenceEPh + 0x66
0xffffff909b47be50 : 0xffffff7f80aea63b com.apple.iokit.IOSCSIArchitectureModelFamily : __ZN18IOSCSITargetDevice4PingEv + 0x71
0xffffff909b47be70 : 0xffffff7f80aeeffc com.apple.iokit.IOSCSIArchitectureModelFamily : __ZL9LUNRescanP8OSObjectP18IOTimerEventSource + 0xde
0xffffff909b47bea0 : 0xffffff80008da023 mach_kernel : __ZN18IOTimerEventSource17timeoutAndReleaseEPvS0_ + 0x133
0xffffff909b47bf00 : 0xffffff800035d6d9 mach_kernel : _thread_call_isactive + 0x1559
0xffffff909b47bfb0 : 0xffffff80004116e7 mach_kernel : _call_continuation + 0x17
Kernel Extensions in backtrace:
com.apple.iokit.IOSCSIArchitectureModelFamily(3.7.5)[7D261E88-9CEB-3E90-B503-748D5859EB3A]@0xffffff7f80ae2000->0xffffff7f80b12fff
com.apple.iokit.IOSCSIParallelFamily(3.0)[C30D0739-E5AA-3366-BFA9-4EB56BBFA6A7]@0xffffff7f80b13000->0xffffff7f80b23fff
dependency: com.apple.iokit.IOSCSIArchitectureModelFamily(3.7.5)[7D261E88-9CEB-3E90-B503-748D5859EB3A]@0xffffff7f80ae2000

BSD process name corresponding to current thread: kernel_task
Boot args: arch=x86_64 slide=0 dart=0 darkwake=no npci=0x3000 nvda_drv=1 kext-dev-mode=1 keepsyms=y 

Mac OS version:
14F27

Kernel version:
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Kernel UUID: 58F06365-45C7-3CA7-B80D-173AFD1A03C4
__HIB text base: 0xffffff8000100000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)

System uptime in nanoseconds: 14881214567157
last loaded kext at 11575491869515: com.apple.driver.AppleUSBCDC	4.3.3b1 (addr 0xffffff7f82660000, size 20480)
last unloaded kext at 11648197396389: com.apple.driver.AppleUSBCDC	4.3.3b1 (addr 0xffffff7f82660000, size 16384)
loaded kexts:
com.github.osxfuse.filesystems.osxfusefs	2.7.5
com.nvidia.CUDA	1.1.0
net.lundman.zfs	1.3.1
net.lundman.spl	1.3.1
com.nvidia.web.NVDAGK100HalWeb	10.0.5
com.nvidia.web.GeForceWeb	10.0.5
com.nvidia.web.NVDAResmanWeb	10.0.5
com.intel.driver.EnergyDriver	2.0
org.hwsensors.driver.GPUSensors	1372
com.Areca.ArcSAS	2.0.4
at.obdev.nke.LittleSnitch	4246
org.hwsensors.driver.CPUSensors	1372
org.netkas.driver.FakeSMC	1372
com.apple.driver.AppleBluetoothMultitouch	85.3
com.apple.filesystems.autofs	3.0
com.apple.iokit.IOBluetoothSerialManager	4.3.6f3
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleOSXWatchdog	1
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.driver.AppleBacklight	170.7.4
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.Apple16X50ACPI	3.2
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.driver.AppleIntelMCEReporter	107
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.iokit.SCSITaskUserClient	3.7.5
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AppleFWOHCI	5.5.2
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.iokit.AppleIntelI210Ethernet	2.2.0b1
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.driver.IOBluetoothHIDDriver	4.3.6f3
com.apple.driver.AppleMultitouchDriver	264.6
com.apple.kext.triggers	1.0
com.apple.iokit.IOSCSIMultimediaCommandsDevice	3.7.5
com.apple.iokit.IOBDStorageFamily	1.7
com.apple.iokit.IODVDStorageFamily	1.7.1
com.apple.iokit.IOCDStorageFamily	1.7.1
com.apple.iokit.IOSurface	97.4
com.apple.iokit.IOAcceleratorFamily2	156.16
com.apple.AppleGraphicsDeviceControl	3.10.25
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOBluetoothFamily	4.3.6f3
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleHDAController	272.18.1
com.apple.iokit.IOHDAFamily	272.18.1
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.iokit.IOAHCISerialATAPI	2.6.1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.Apple16X50Serial	3.2
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.driver.AppleUSBHIDKeyboard	176.2
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.driver.AppleUSBAudio	295.23
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.iokit.IOFireWireFamily	4.5.8
com.apple.iokit.IOSCSIParallelFamily	3.0.0
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.iokit.IOEthernetAVBController	1.0.3b3
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1
com.apple.kec.pthread	1
Model: MacPro6,1, BootROM MP61.0116.B04, 16 processors, 2.6 GHz, 96 GB, SMC 2.2f18
Graphics: NVIDIA GeForce GTX 770, NVIDIA GeForce GTX 770, PCIe, 2047 MB
Memory Module: BANK0/DIMM0, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK1/DIMM0, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK0/DIMM0, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK1/DIMM0, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK0/DIMM1, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK1/DIMM1, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK0/DIMM1, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: BANK1/DIMM1, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: Intel 7 Series Chipset Family SATA Controller, AHCI Controller, Built In
Serial ATA Device: Samsung SSD 840 Series, 250,06 GB
Serial ATA Device: Crucial_CT500MX200SSD1, 500,11 GB
Serial ATA Device: TSSTcorp CDDVDW SH-224DB
USB Device: Hub
USB Device: Hub
USB Device: Hub
USB Device: io|2
USB Device: PS/2+USB Mouse
USB Device: Hub
USB Device: USB2223
USB Device: Hub
USB Device: Keyboard Hub
USB Device: BCM20702A0
USB Device: Apple Keyboard
USB Device: USB2.0 Hub
USB Device: Mass Storage Device
USB Device: Elements 107C
Thunderbolt Bus:

**Comment by lundman** [comment]
We are aware of the `_zfsctl_umount_snapshots` and it has infact been fixed in HEAD. Your second problem is news to us, and confusingly, doesn't even have ZFS in the stack. The only IOKit work we do is with ZVOLs, do you have those?

**Comment by mruepp** [comment]
Unfortunately not, the only thing which I could think off is the Driver of the Areca ARC-1320iX.

**Comment by mruepp** [comment]
Got System Reset when deleting folder with large amount of files/directories:

App. 50.000 Folders, and 4Mio small files.

1. Put Parent folder into Trash
2. Trash takes forever
3. Stopped Trash, stopping took forever, so I Force Quit Finder, did a logout and login.
4. Did a sudo rm -rf Folder in tank/Filesystem/.Trashes/501/Trashedfolder
5. Reset occured. No Panic Report.

**Comment by JMoVS** [comment]
feel free to reopen if this still occurs
