### ISSUE TITLE
Lower default arc max

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#363]
In the interest of more sensible defaults, we should set an initial arc max that is appropriate for a typical desktop (as opposed to server) system and that isn't "scary" to a new user who observes kernel_task's memory usage in Activity Monitor.

Currently, the value is max(x-3, x/4) and we've discussed making it simply x/4 instead, where x is total system memory.

System memory / Arc max (current) / Arc max (proposed)
4G, 8G, 16G, 32G, 64G / 1G, 5G, 13G, 29G, 61G / 1G, 2G, 4G, 8G, 16G

Please comment if you think some other default formula would be more sensible.

**Comment by lundman** [comment]
Those look decent to me.

**Comment by brendonhumphrey** [comment]
https://github.com/openzfsonosx/zfs/commit/d30ef37ca3f296ffb77efb40d4d83511662aa59f

**Comment by brendonhumphrey** [comment]
We are about to revert this change...obvious regression in stability for one heavy user.

**Comment by ilovezfs** [comment]
This has been un-reverted and we've restored the lowered arc max.
