### ISSUE TITLE
Filesystem blocks all writes

### ISSUE THREAD

**Issue by gigq** [openzfsonosx/zfs#365]
Keep getting into this condition on a 10.10.5 system running a build from master (36c957661e79cb55777dbce1caff97aa15736ce4).  Was happening before with the release build but was told to upgrade to what was head of master at the time.

The system will still respond to reads but all writes are blocked and hang the process.  Here is a dump from spindump at the time that it happens:

https://gist.githubusercontent.com/anonymous/bb9788b03b5daacfa762/raw/e5ae665d402e5852ceb047ccc25311432638f58d/gistfile1.txt

**Comment by lundman** [comment]
Phew, talk about endless spindump.

I would guess this is the thread that is stalled
```
               *996  zfs_vnop_write + 174 (zfs + 1015502) [0xffffff7f80ba8ece]
                 *996  zfs_write + 4271 (zfs + 964207) [0xffffff7f80b9c66f]
                   *996  update_pages + 273 (zfs + 966513) [0xffffff7f80b9cf71]
                     *996  ubc_create_upl + 237 (kernel + 6278125) [0xffffff80007fcbed]
```

which stalls all UBC calls, and dmu_tx. Which is pretty much what all other threads are in waiting for.

**Comment by gigq** [comment]
Anything options / patch I can rebuild with to prevent it, getting tired of bouncing my media server every few days.

**Comment by lundman** [comment]
If you are able to build yourself, can you try out the "pageoutv2" branch as I believe I may have fixed some write deadlocks. If not, just hang tight as we go through the testing phase.

**Comment by gigq** [comment]
Looks like that branch was merged into master, I'll try recompiling from there and see if it fixes my issue.

**Comment by gigq** [comment]
I haven't hit this blocking issue in a month of using the merged master.  Closing this out, I'll reopen if I end up getting a lockup later.
