### ISSUE TITLE
Dropbox data on zfs dataset sometimes causes Dropbox app to never finish indexing of files

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#371]
I have my Dropbox data in a dataset and it usually works. But rarely (and I sadly can't reliably reproduce it) get the Dropbox app into a state where it is claiming that 2536 files need indexing (I don't know the number right now but it is everytime the exact same number). Closing the app and opening it again aleviates this, but as this didn't happen before having it on ZFS, it is somehow related.

Now I wanted to ask how I can help to find out the cause like with logs or anything like that?

**Comment by JMoVS** [comment]
I started using O3X as of 1.3.2 and it happened occasionally ever since

**Comment by emory** [comment]
Does the dataset containing your Dropbox folder have the required knobs adjusted to respect HFS+ metadata and attributes? I've seen this behavior before as well and it appeared to be related to Dropbox actually respecting file metadata (`kMDItemUserTags`) and me having my dataset configured incorrectly, so Dropbox would thrash itself silly trying to make it right.

**Comment by JMoVS** [comment]
doesn't seem to be happening anymore. Closing
