### ISSUE TITLE
Discuss: accessing past end of object panic

### ISSUE THREAD

**Issue by lundman** [openzfsonosx/zfs#38]
I did a temporary fix for the panic with commit https://github.com/zfs-osx/zfs/commit/698317b1b65b9ebce8d0a117a64e40b24660c8bb

Which relies on making sure that we only grow buffers by power of 2, as the code in `dmu_buf_hold_array_by_dnode()` splits based on this criteria. This fix will probably be removed in deference to fixing the non-power-2 `z_blksize` (`dn->dn_datablksz`) path.

But at the same time it is interesting to note that non-power-of-2 buffersizes do not panic on ZOL. With that in mind, I investigated was actually goes wrong for us.

It trickles down to this call;

```
#ifdef __APPLE__
            update_pages(vp, tx_bytes, uio, tx);
#else
            update_pages(vp, woff, tx_bytes, zfsvfs->z_os, zp->z_id, uio->uio_segflg, tx);
#endif
```

Which in this case is only called for mmapped writes, which is what I am currently tracking.

https://github.com/zfs-osx/zfs/blob/master/module/zfs/zfs_vnops.c#L363

Inside `update_pages()` we get the offset `woff` by calling `uio_offset(uid)`. It is interesting to note that they differ.

I added the output

```
            printf("Updatepage call %llu vs %llu\n", woff, uio_offset(uio));
```

which yields

```
Jul  3 10:30:44 Lundmans-Mac kernel[0]: Updatepage call 102056 vs 125096
```

right before panic. This is in fact, the reason we go "outside" the memory buffer, and induce a panic.

What would happen if we adjust this to match that of ZOL;

```
            uio_setoffset(uio, woff);
            update_pages(vp, tx_bytes, uio, tx);
```

```
Jul  3 10:28:47 Lundmans-Mac kernel[0]: Updatepage call 102056 vs 125096
Jul  3 10:28:47 Lundmans-Mac kernel[0]: update_pages 102056 - 23040 (adjusted 98304 - 28672)
Jul  3 10:28:47 Lundmans-Mac kernel[0]: accessing size=125440 access=102056+344
```

No more panics, and in fact, follows the output given in ZOL with the same debug prints. Possibly the mmap function has always been incorrect. 

But `fsx` now fail with a new error

```
Size error: expected 0x1e8a8 stat 0x1c23c seek 0x1c23c
```

The filesize is now incorrect, it would seem we need to update the `uio` struct as well.

Ie, 

```
#ifdef __APPLE__
            printf("Updatepage call %llu vs %llu\n", woff, uio_offset(uio));
            uio_setoffset(uio, woff);
            update_pages(vp, tx_bytes, uio, tx);
            uio_setoffset(uio, woff+tx_bytes);
            printf("New location %llu\n", uio_offset(uio));
#else
            update_pages(vp, woff, tx_bytes, zfsvfs->z_os, zp->z_id, uio->uio_segflg, tx);
#endif
```

which results in;

```
Jul  3 10:30:44 Lundmans-Mac kernel[0]: Updatepage call 102056 vs 125096
Jul  3 10:30:44 Lundmans-Mac kernel[0]: update_pages 102056 - 23040 (adjusted 98304 - 28672)
Jul  3 10:30:44 Lundmans-Mac kernel[0]: accessing size=125440 access=102056+344
Jul  3 10:30:44 Lundmans-Mac kernel[0]: accessing size=125440 access=102056+4096
Jul  3 10:30:44 --- last message repeated 4 times ---
Jul  3 10:30:44 Lundmans-Mac kernel[0]: accessing size=125440 access=102056+2216
Jul  3 10:30:44 Lundmans-Mac kernel[0]: New location 125096
```

No more incorrect file sizes either. `fsx` carries on much further until

```
data miscompare @ 70044
OFFSET     GOOD       BAD        LENGTH     BADOP#   Last: WRITE    TRUNC-   TRUNC+  
0x0001119c 0x0000001c 0x0000000c 0x00000754 12             28       27       -1 
```

which brings us back to the regular mmap inconsistencies.

I would think that it is more correct to use the `woff` offset than `uio_offset()` but I am wondering if the update of `tx_bytes` should be the `PAGE_SIZE` adjusted size. Although I suppose then that `fsx` would complain about the wrong size.

It would possibly be cleaner to put the `uio_offset` adjustments inside `update_pages()`, especially since we don't know if it will use the `uio_move()` path or not. (Which will also adjust the offset).

The `update_pages` function does not differ much between ZOL and OS-X.

Does anyone have any opinions on this?

**Comment by JMoVS** [comment]
@lundman I guess we can safely close this issue by now?

**Comment by JMoVS** [comment]
fixed by now
