### ISSUE TITLE
Unable to build from source with Xcode 7

### ISSUE THREAD

**Issue by mruepp** [openzfsonosx/zfs#382]
sunrise:zfs michael$ kextstat | grep lundman
  133    1 0xffffff80f3879400 0x36c      0x36c      net.lundman.kernel.dependencies.1.4.1 (12.5.0)
  135    0 0xffffff7f8246e000 0x37000    0x37000    net.lundman.spl (1.4.1) <133 7 5 4 3 1>
sunrise:zfs michael$ sudo kextload /System/Library/Extensions/zfs.kext

sunrise:zfs michael$ zpool status
Failed to load ZFS module stack.
Load the module manually by running '/sbin/kextload /System/Library/Extensions/zfs.kext' as root.
The /dev/zfs device is missing and must be created.
Try running 'udevadm trigger' as root to create it.
sunrise:zfs michael$

**Comment by ilovezfs** [comment]
As mentioned on the wiki here https://openzfsonosx.org/wiki/Install#Initial_installation_from_source

"Note: Xcode 7.0 (7A220) is (accidentally) missing the 10.10 SDK. You may unzip https://www.dropbox.com/s/hggp0zgn7hkz38m/MacOSX10.10.sdk.zip in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/ as a workaround."
