### ISSUE TITLE
Some applications don't recognize ZFS volumes

### ISSUE THREAD

**Issue by mauricev** [openzfsonosx/zfs#384]
Retrospect is one. Backblaze is another. The reason, at least in Retrospect's case is

"the statfs call does not give us a valid bsd name"

**Comment by mauricev** [comment]
This may be a duplicate of https://github.com/openzfsonosx/zfs/issues/116

**Comment by jmcintyre** [comment]
Retrospect will now backup the ZFS drives with the latest 1.8.1 release. This is probably due to the /dev/diskX work as that seemed to be the problem when we looked into it way back when. I can't speak for Backblaze.
