### ISSUE TITLE
panics during copy of many files

### ISSUE THREAD

**Issue by MarcoVF** [openzfsonosx/zfs#385]
I was copying many files to my zfs pool. I was using SyncTwoFolders, a simple donationware program, that I think involves the finder in the copy process.

Here come three panics:

Anonymous UUID:       9B7139D7-35D2-A986-F0B1-7BC7959B9DAE

Sun Sep 20 16:07:08 2015

*** Panic Report ***
panic(cpu 2 caller 0xffffff7fae07f917): "rwlock 0xffffff81e5f1c9f8 not initialised\n"@spl-rwlock.c:84
Backtrace (CPU 2), Frame : Return Address
0xffffff813830b5a0 : 0xffffff802d92ad21 
0xffffff813830b620 : 0xffffff7fae07f917 
0xffffff813830b640 : 0xffffff7fae0b9e3f 
0xffffff813830b670 : 0xffffff7fae135e99 
0xffffff813830b720 : 0xffffff7fae1262a7 
0xffffff813830bb80 : 0xffffff802db3979d 
0xffffff813830bcb0 : 0xffffff802db4d085 
0xffffff813830bd00 : 0xffffff802db25066 
0xffffff813830bf00 : 0xffffff802db1e257 
0xffffff813830bf50 : 0xffffff802de4b376 
0xffffff813830bfb0 : 0xffffff802da344a6 
      Kernel Extensions in backtrace:
         net.lundman.spl(1.3.1)[B4F958D8-B538-36E9-86E6-A9F7B89B422A]@0xffffff7fae076000->0xffffff7fae0aafff
         net.lundman.zfs(1.3.1)[969D7160-64A1-3420-9AFA-738C7D20A3AC]@0xffffff7fae0ab000->0xffffff7fae259fff
            dependency: com.apple.iokit.IOStorageFamily(2.0)[D0ABB996-2084-3A05-A166-5951D925EF80]@0xffffff7fae047000
            dependency: net.lundman.spl(1.3.1)[B4F958D8-B538-36E9-86E6-A9F7B89B422A]@0xffffff7fae076000

BSD process name corresponding to current thread: mdworker

Mac OS version:
14F27

Kernel version:
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Kernel UUID: 58F06365-45C7-3CA7-B80D-173AFD1A03C4
Kernel slide:     0x000000002d600000
Kernel text base: 0xffffff802d800000
__HIB  text base: 0xffffff802d700000
System model name: MacBookAir5,2 (Mac-2E6FAB96566FE58C)

System uptime in nanoseconds: 191958904722296
last loaded kext at 191377013115385: com.apple.iokit.SCSITaskUserClient	3.7.5 (addr 0xffffff7fb0458000, size 36864)
last unloaded kext at 191461508698711: com.apple.driver.AppleUSBCDC	4.3.3b1 (addr 0xffffff7fb03db000, size 16384)
loaded kexts:
com.intego.virusbarrier.kext.realtime	217
net.lundman.zfs	1.3.1
net.lundman.spl	1.3.1
com.apple.driver.AppleBluetoothMultitouch	85.3
com.apple.driver.AppleUSBDisplays	372.1
com.apple.filesystems.afpfs	11.0
com.apple.nke.asp-tcp	8.0.0
com.apple.filesystems.smbfs	3.0.2
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.driver.ApplePlatformEnabler	2.2.0d4
com.apple.driver.AGPM	110.19.6
com.apple.driver.X86PlatformShim	1.0.0
com.apple.iokit.IOBluetoothSerialManager	4.3.6f3
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.driver.AppleHDA	272.18.1
com.apple.driver.AppleMikeyDriver	272.18.1
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleIntelHD4000Graphics	10.0.6
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleSMCLMU	2.0.7d0
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.AppleIntelFramebufferCapri	10.0.6
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleThunderboltIP	2.0.2
com.apple.driver.AppleBacklight	170.7.4
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.driver.AppleUSBTCButtons	240.2
com.apple.driver.AppleUSBTCKeyboard	240.2
com.apple.driver.AppleUSBCardReader	3.5.5
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AirPort.Brcm4360	930.37.3
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.driver.IOBluetoothHIDDriver	4.3.6f3
com.apple.driver.AppleMultitouchDriver	264.6
com.apple.driver.AppleUSBHIDKeyboard	176.2
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.iokit.IOUSBHIDDriverPM	710.4.7
com.apple.driver.AppleUSBAudio	295.23
com.apple.security.SecureRemotePassword	1.0
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.DspFuncLib	272.18.1
com.apple.kext.OSvKernDSPLib	1.15
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.AppleHDAController	272.18.1
com.apple.iokit.IOHDAFamily	272.18.1
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.iokit.IOAcceleratorFamily2	156.16
com.apple.AppleGraphicsDeviceControl	3.10.25
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOSurface	97.4
com.apple.iokit.IOBluetoothFamily	4.3.6f3
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.AppleUSBMultitouch	245.2
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.driver.CoreStorage	471.30.1
com.apple.driver.AppleThunderboltDPInAdapter	4.0.6
com.apple.driver.AppleThunderboltDPAdapterFamily	4.0.6
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.AppleThunderboltNHI	3.1.7
com.apple.iokit.IOThunderboltFamily	4.2.2
com.apple.iokit.IO80211Family	730.60
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1
com.apple.kec.pthread	1
Model: MacBookAir5,2, BootROM MBA51.00EF.B03, 2 processors, Intel Core i5, 1.8 GHz, 8 GB, SMC 2.5f9
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE9), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM256E, 251 GB
USB Device: USB to ATA/ATAPI Bridge
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: Hub
USB Device: Apple LED Cinema Display
USB Device: Display iSight
USB Device: Display Audio
USB Device: Hub
USB Device: Internal Memory Card Reader
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus: MacBook Air, Apple Inc., 23.4

Second panic:

Anonymous UUID:       9B7139D7-35D2-A986-F0B1-7BC7959B9DAE

Sun Sep 20 16:07:08 2015

*** Panic Report ***
panic(cpu 2 caller 0xffffff7fae07f917): "rwlock 0xffffff81e5f1c9f8 not initialised\n"@spl-rwlock.c:84
Backtrace (CPU 2), Frame : Return Address
0xffffff813830b5a0 : 0xffffff802d92ad21 
0xffffff813830b620 : 0xffffff7fae07f917 
0xffffff813830b640 : 0xffffff7fae0b9e3f 
0xffffff813830b670 : 0xffffff7fae135e99 
0xffffff813830b720 : 0xffffff7fae1262a7 
0xffffff813830bb80 : 0xffffff802db3979d 
0xffffff813830bcb0 : 0xffffff802db4d085 
0xffffff813830bd00 : 0xffffff802db25066 
0xffffff813830bf00 : 0xffffff802db1e257 
0xffffff813830bf50 : 0xffffff802de4b376 
0xffffff813830bfb0 : 0xffffff802da344a6 
      Kernel Extensions in backtrace:
         net.lundman.spl(1.3.1)[B4F958D8-B538-36E9-86E6-A9F7B89B422A]@0xffffff7fae076000->0xffffff7fae0aafff
         net.lundman.zfs(1.3.1)[969D7160-64A1-3420-9AFA-738C7D20A3AC]@0xffffff7fae0ab000->0xffffff7fae259fff
            dependency: com.apple.iokit.IOStorageFamily(2.0)[D0ABB996-2084-3A05-A166-5951D925EF80]@0xffffff7fae047000
            dependency: net.lundman.spl(1.3.1)[B4F958D8-B538-36E9-86E6-A9F7B89B422A]@0xffffff7fae076000

BSD process name corresponding to current thread: mdworker

Mac OS version:
14F27

Kernel version:
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Kernel UUID: 58F06365-45C7-3CA7-B80D-173AFD1A03C4
Kernel slide:     0x000000002d600000
Kernel text base: 0xffffff802d800000
__HIB  text base: 0xffffff802d700000
System model name: MacBookAir5,2 (Mac-2E6FAB96566FE58C)

System uptime in nanoseconds: 191958904722296
last loaded kext at 191377013115385: com.apple.iokit.SCSITaskUserClient	3.7.5 (addr 0xffffff7fb0458000, size 36864)
last unloaded kext at 191461508698711: com.apple.driver.AppleUSBCDC	4.3.3b1 (addr 0xffffff7fb03db000, size 16384)
loaded kexts:
com.intego.virusbarrier.kext.realtime	217
net.lundman.zfs	1.3.1
net.lundman.spl	1.3.1
com.apple.driver.AppleBluetoothMultitouch	85.3
com.apple.driver.AppleUSBDisplays	372.1
com.apple.filesystems.afpfs	11.0
com.apple.nke.asp-tcp	8.0.0
com.apple.filesystems.smbfs	3.0.2
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.driver.ApplePlatformEnabler	2.2.0d4
com.apple.driver.AGPM	110.19.6
com.apple.driver.X86PlatformShim	1.0.0
com.apple.iokit.IOBluetoothSerialManager	4.3.6f3
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.driver.AppleHDA	272.18.1
com.apple.driver.AppleMikeyDriver	272.18.1
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleIntelHD4000Graphics	10.0.6
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleSMCLMU	2.0.7d0
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.AppleIntelFramebufferCapri	10.0.6
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleThunderboltIP	2.0.2
com.apple.driver.AppleBacklight	170.7.4
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.driver.AppleUSBTCButtons	240.2
com.apple.driver.AppleUSBTCKeyboard	240.2
com.apple.driver.AppleUSBCardReader	3.5.5
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AirPort.Brcm4360	930.37.3
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.driver.IOBluetoothHIDDriver	4.3.6f3
com.apple.driver.AppleMultitouchDriver	264.6
com.apple.driver.AppleUSBHIDKeyboard	176.2
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.iokit.IOUSBHIDDriverPM	710.4.7
com.apple.driver.AppleUSBAudio	295.23
com.apple.security.SecureRemotePassword	1.0
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.DspFuncLib	272.18.1
com.apple.kext.OSvKernDSPLib	1.15
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.AppleHDAController	272.18.1
com.apple.iokit.IOHDAFamily	272.18.1
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.iokit.IOAcceleratorFamily2	156.16
com.apple.AppleGraphicsDeviceControl	3.10.25
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOSurface	97.4
com.apple.iokit.IOBluetoothFamily	4.3.6f3
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.AppleUSBMultitouch	245.2
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.driver.CoreStorage	471.30.1
com.apple.driver.AppleThunderboltDPInAdapter	4.0.6
com.apple.driver.AppleThunderboltDPAdapterFamily	4.0.6
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.AppleThunderboltNHI	3.1.7
com.apple.iokit.IOThunderboltFamily	4.2.2
com.apple.iokit.IO80211Family	730.60
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1
com.apple.kec.pthread	1
Model: MacBookAir5,2, BootROM MBA51.00EF.B03, 2 processors, Intel Core i5, 1.8 GHz, 8 GB, SMC 2.5f9
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE9), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM256E, 251 GB
USB Device: USB to ATA/ATAPI Bridge
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: Hub
USB Device: Apple LED Cinema Display
USB Device: Display iSight
USB Device: Display Audio
USB Device: Hub
USB Device: Internal Memory Card Reader
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus: MacBook Air, Apple Inc., 23.4
 
Third panic:

Anonymous UUID:       9B7139D7-35D2-A986-F0B1-7BC7959B9DAE

Mon Sep 21 20:04:11 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff7fac87f917): "rwlock 0xffffff813cffd138 not initialised\n"@spl-rwlock.c:84
Backtrace (CPU 0), Frame : Return Address
0xffffff81355630f0 : 0xffffff802c12ad21 
0xffffff8135563170 : 0xffffff7fac87f917 
0xffffff8135563190 : 0xffffff7fac92fc4d 
0xffffff81355631e0 : 0xffffff802c3468f0 
0xffffff8135563260 : 0xffffff802c3463da 
0xffffff81355632b0 : 0xffffff802c3460c4 
0xffffff81355632e0 : 0xffffff802c33f75e 
0xffffff8135563370 : 0xffffff802c531462 
0xffffff8135563480 : 0xffffff802c5606d6 
0xffffff81355635e0 : 0xffffff802c568dfc 
0xffffff81355636d0 : 0xffffff802c371424 
0xffffff8135563740 : 0xffffff7faea5c211 
0xffffff8135563810 : 0xffffff802c387e67 
0xffffff8135563840 : 0xffffff802c55f148 
0xffffff8135563890 : 0xffffff802c36e427 
0xffffff81355638f0 : 0xffffff802c361f46 
0xffffff8135563990 : 0xffffff802c34d708 
0xffffff8135563bd0 : 0xffffff802c34e2e0 
0xffffff8135563f50 : 0xffffff802c64b376 
0xffffff8135563fb0 : 0xffffff802c2344a6 
      Kernel Extensions in backtrace:
         com.apple.AppleFSCompression.AppleFSCompressionTypeZlib(1.0)[0F346230-AB4E-3837-BD3D-1C1C91E00B3E]@0xffffff7faea5b000->0xffffff7faea60fff
         net.lundman.spl(1.3.1)[B4F958D8-B538-36E9-86E6-A9F7B89B422A]@0xffffff7fac876000->0xffffff7fac8aafff
         net.lundman.zfs(1.3.1)[969D7160-64A1-3420-9AFA-738C7D20A3AC]@0xffffff7fac8ab000->0xffffff7faca59fff
            dependency: com.apple.iokit.IOStorageFamily(2.0)[D0ABB996-2084-3A05-A166-5951D925EF80]@0xffffff7fac847000
            dependency: net.lundman.spl(1.3.1)[B4F958D8-B538-36E9-86E6-A9F7B89B422A]@0xffffff7fac876000

BSD process name corresponding to current thread: virusbarriers

Mac OS version:
14F27

Kernel version:
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Kernel UUID: 58F06365-45C7-3CA7-B80D-173AFD1A03C4
Kernel slide:     0x000000002be00000
Kernel text base: 0xffffff802c000000
__HIB  text base: 0xffffff802bf00000
System model name: MacBookAir5,2 (Mac-2E6FAB96566FE58C)

System uptime in nanoseconds: 63064599995081
last loaded kext at 52221024952547: com.apple.iokit.SCSITaskUserClient	3.7.5 (addr 0xffffff7faec4f000, size 36864)
last unloaded kext at 52292549518005: com.coriolis-systems.driver.OnlineHelper	509 (addr 0xffffff7faec47000, size 16384)
loaded kexts:
com.intego.virusbarrier.kext.realtime	217
net.lundman.zfs	1.3.1
net.lundman.spl	1.3.1
com.apple.driver.AppleBluetoothMultitouch	85.3
com.apple.driver.AppleUSBDisplays	372.1
com.apple.filesystems.smbfs	3.0.2
com.apple.driver.AppleUSBEthernet	2.4.13
com.apple.filesystems.autofs	3.0
com.apple.iokit.IOBluetoothSerialManager	4.3.6f3
com.apple.driver.ApplePlatformEnabler	2.2.0d4
com.apple.driver.AGPM	110.19.6
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.driver.AppleHDA	272.18.1
com.apple.driver.AppleMikeyDriver	272.18.1
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleIntelHD4000Graphics	10.0.6
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleSMCLMU	2.0.7d0
com.apple.driver.AppleLPC	1.7.3
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleThunderboltIP	2.0.2
com.apple.driver.AppleIntelFramebufferCapri	10.0.6
com.apple.driver.AppleBacklight	170.7.4
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.driver.AppleUSBCardReader	3.5.5
com.apple.driver.AppleUSBTCButtons	240.2
com.apple.driver.AppleUSBTCKeyboard	240.2
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AirPort.Brcm4360	930.37.3
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.driver.IOBluetoothHIDDriver	4.3.6f3
com.apple.driver.AppleMultitouchDriver	264.6
com.apple.driver.AppleUSBHIDKeyboard	176.2
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.driver.AppleUSBAudio	295.23
com.apple.iokit.IOUSBHIDDriverPM	710.4.7
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.DspFuncLib	272.18.1
com.apple.kext.OSvKernDSPLib	1.15
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.AppleHDAController	272.18.1
com.apple.iokit.IOHDAFamily	272.18.1
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.iokit.IOSurface	97.4
com.apple.iokit.IOBluetoothFamily	4.3.6f3
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOAcceleratorFamily2	156.16
com.apple.AppleGraphicsDeviceControl	3.10.25
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.driver.AppleUSBMultitouch	245.2
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.driver.CoreStorage	471.30.1
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.driver.AppleThunderboltDPInAdapter	4.0.6
com.apple.driver.AppleThunderboltDPAdapterFamily	4.0.6
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.AppleThunderboltNHI	3.1.7
com.apple.iokit.IOThunderboltFamily	4.2.2
com.apple.iokit.IO80211Family	730.60
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: MacBookAir5,2, BootROM MBA51.00EF.B03, 2 processors, Intel Core i5, 1.8 GHz, 8 GB, SMC 2.5f9
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE9), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB Ethernet, Ethernet, en3
Network Service: Thunderbolt Ethernet, Ethernet, en4
Serial ATA Device: APPLE SSD SM256E, 251 GB
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Hub
USB Device: Iomega eGo HDD
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: Hub
USB Device: Apple LED Cinema Display
USB Device: Display Audio
USB Device: Display iSight
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Internal Memory Card Reader
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.4

**Comment by lundman** [comment]
The `rwlock 0xaddy not initialised` is an interesting problem, but since so much as changed wrt to rwlocks, it would be better to see if you can make the same problem happen on 1.4.2. It should be out any time now, we hope.

**Comment by lundman** [comment]
Please try with the released1.4.2

**Comment by MarcoVF** [comment]
It worked with 1.4.2 on El Capitan beta
