### ISSUE TITLE
Panic during shutdown (leads to a reboot instead of halt)

### ISSUE THREAD

**Issue by mruepp** [openzfsonosx/zfs#387]
Anonymous UUID:       2EF2D1DB-89B8-2A4C-292D-F7E53661D49E

Sat Sep 26 09:44:02 2015

*** Panic Report ***
panic(cpu 2 caller 0xffffff8000416df2): Kernel trap at 0xffffff7f80a767c3, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000055e9e94b, CR3: 0x00000017c24fe001, CR4: 0x00000000000626e0
RAX: 0x0000000055e9e94b, RBX: 0x0000000000000000, RCX: 0x0000000053fa133e, RDX: 0x0000000055e9e94b
RSP: 0xffffff8b2d243ac0, RBP: 0xffffff8b2d243ac0, RSI: 0x0fffffffffffff01, RDI: 0x0000000055e9e94b
R8:  0x0000000000000000, R9:  0x0000000000000000, R10: 0xffffff80d78b03f0, R11: 0xffffff80d7933960
R12: 0x0000000000080000, R13: 0xffffff80ee5cc1e8, R14: 0xffffff80d0b58e20, R15: 0xffffff7f80c06d70
RFL: 0x0000000000010206, RIP: 0xffffff7f80a767c3, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000055e9e94b, Error code: 0x0000000000000000, Fault CPU: 0x2

Backtrace (CPU 2), Frame : Return Address
0xffffff8b2d243770 : 0xffffff800032ad21 mach_kernel : _panic + 0xd1
0xffffff8b2d2437f0 : 0xffffff8000416df2 mach_kernel : _kernel_trap + 0x8d2
0xffffff8b2d2439b0 : 0xffffff8000433ca3 mach_kernel : _return_from_trap + 0xe3
0xffffff8b2d2439d0 : 0xffffff7f80a767c3 net.lundman.spl : _avl_first + 0xd
0xffffff8b2d243ac0 : 0xffffff7f80b182bc net.lundman.zfs : _zfsctl_umount_snapshots + 0xbd
0xffffff8b2d243b40 : 0xffffff7f80b2c3f1 net.lundman.zfs : _zfs_vfs_unmount + 0xac
0xffffff8b2d243cb0 : 0xffffff800054b95c mach_kernel : _dounmount + 0x3bc
0xffffff8b2d243d50 : 0xffffff8000547263 mach_kernel : _vfs_addtrigger + 0x18e3
0xffffff8b2d243d80 : 0xffffff8000541fc4 mach_kernel : _vfs_iterate + 0x1f4
0xffffff8b2d243df0 : 0xffffff80007d54fe mach_kernel : _boot + 0x5de
0xffffff8b2d243ec0 : 0xffffff80007e6609 mach_kernel : _reboot + 0x119
0xffffff8b2d243f50 : 0xffffff800084b376 mach_kernel : _unix_syscall64 + 0x296
0xffffff8b2d243fb0 : 0xffffff80004344a6 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         net.lundman.spl(1.4.2)[A4583D8D-9529-3981-BE85-A4670049987E]@0xffffff7f80a76000->0xffffff7f80aacfff
         net.lundman.zfs(1.4.2)[7204DEDA-9B73-3654-BB3E-1901A9F6E9D2]@0xffffff7f80aad000->0xffffff7f80ce8fff
            dependency: com.apple.iokit.IOStorageFamily(2.0)[D0ABB996-2084-3A05-A166-5951D925EF80]@0xffffff7f80a47000
            dependency: net.lundman.spl(1.4.2)[A4583D8D-9529-3981-BE85-A4670049987E]@0xffffff7f80a76000

BSD process name corresponding to current thread: launchd
Boot args: npci=0x2000 nvda_drv=1 kext-dev-mode=1 keepsyms=y slide=0 

Mac OS version:
14F27

Kernel version:
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Kernel UUID: 58F06365-45C7-3CA7-B80D-173AFD1A03C4
__HIB  text base: 0xffffff8000100000
System model name: MacPro5,1 (Mac-F221BEC8)

System uptime in nanoseconds: 88043415728537
last loaded kext at 87629927613670: com.blackmagic-design.desktopvideo.iokit.framebufferdriver	10.4.1 (addr 0xffffff7f826f3000, size 20480)
last unloaded kext at 87701157367181: com.blackmagic-design.desktopvideo.iokit.framebufferdriver	10.4.1 (addr 0xffffff7f826f3000, size 20480)
loaded kexts:
com.wuala.WualaFS.filesystems.wualafs	2.9.10
com.paragon-software.filesystems.ntfs	313.2.12
com.nvidia.CUDA	1.1.0
net.lundman.zfs	1.4.2
net.lundman.spl	1.4.2
com.intel.driver.EnergyDriver	2.0
org.hwsensors.driver.GPUSensors	1058
com.Areca.ArcSAS	2.0.4
at.obdev.nke.LittleSnitch	4350
org.netkas.driver.FakeSMC	1058
org.voodoo.driver.VoodooTSCSync	1.1
org.hwsensors.driver.CPUSensors	1058
org.hwsensors.driver.FakeSMCKeyStore	1058
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AppleBluetoothMultitouch	85.3
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleTyMCEDriver	1.0.2d2
com.apple.driver.AGPM	110.19.6
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.GeForce	10.0.4
com.apple.driver.AppleOSXWatchdog	1
com.apple.iokit.IOBluetoothSerialManager	4.3.6f3
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.Apple16X50ACPI	3.2
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.iokit.SCSITaskUserClient	3.7.5
com.apple.driver.XsanFilter	404
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.iokit.AppleIntelI210Ethernet	2.2.0b1
com.apple.driver.AppleFWOHCI	5.5.2
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.driver.IOBluetoothHIDDriver	4.3.6f3
com.apple.driver.AppleMultitouchDriver	264.6
com.apple.kext.triggers	1.0
com.apple.iokit.IOSCSIMultimediaCommandsDevice	3.7.5
com.apple.iokit.IOBDStorageFamily	1.7
com.apple.iokit.IODVDStorageFamily	1.7.1
com.apple.iokit.IOCDStorageFamily	1.7.1
com.apple.iokit.IOAHCISerialATAPI	2.6.1
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOSurface	97.4
com.apple.nvidia.driver.NVDAGK100Hal	10.0.4
com.apple.iokit.IOAcceleratorFamily2	156.16
com.apple.nvidia.driver.NVDAResman	10.0.4
com.apple.AppleGraphicsDeviceControl	3.10.25
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f3
com.apple.iokit.IOBluetoothFamily	4.3.6f3
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.Apple16X50Serial	3.2
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleUSBHIDKeyboard	176.2
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.driver.AppleUSBAudio	295.23
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.iokit.IOEthernetAVBController	1.0.3b3
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IOFireWireFamily	4.5.8
com.apple.iokit.IOSCSIParallelFamily	3.0.0
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.AppleEFINVRAM	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1
com.apple.kec.pthread	1
Model: MacPro5,1, BootROM MP51.007F.B03, 16 processors, 2.60 GHz, 96 GB, SMC 1.39f11
Graphics: NVIDIA GeForce GTX 770, NVIDIA GeForce GTX 770, PCIe, 2048 MB
Memory Module: DIMM1, 8 GB, DDR3, 1600 MHz, Micron, 18JSF1G72PDZ-
Memory Module: DIMM2, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: DIMM3, 8 GB, DDR3, 1600 MHz, Micron, 18JSF1G72PDZ-
Memory Module: DIMM4, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: DIMM5, 8 GB, DDR3, 1600 MHz, Micron, 18JSF1G72PDZ-
Memory Module: DIMM6, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Memory Module: DIMM7, 8 GB, DDR3, 1600 MHz, Micron, 18JSF1G72PDZ-
Memory Module: DIMM8, 4 GB, DDR3, 1600 MHz, Micron, 18JSF51272PDZ
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: AppleIntelI210, Ethernet, Internal
Serial ATA Device: Crucial_CT500MX200SSD1, 500,11 GB
Serial ATA Device: Samsung SSD 840 Series, 250,06 GB
Serial ATA Device: TSSTcorp CDDVDW SH-224DB
USB Device: Hub
USB Device: Hub
USB Device: Hub
USB Device: Keyboard Hub
USB Device: BCM20702A0
USB Device: Apple Keyboard
USB Device: io|2
USB Device: PS/2+USB Mouse
USB Device: Hub
USB Device: USB2223
USB Device: Hub
USB Device: Logitech Camera
USB Device: My Book 1230
Thunderbolt Bus:

**Comment by ilovezfs** [comment]
https://github.com/openzfsonosx/zfs/issues/310

**Comment by ilovezfs** [comment]
Fixed here https://github.com/openzfsonosx/zfs/commit/a1fc4bb290c15e7f8df64740f3422e9e1b83ad71
