### ISSUE TITLE
Cannot backup HFS Volumes to Network Time Machine when openzfs is installed

### ISSUE THREAD

**Issue by jonasjonas** [openzfsonosx/zfs#389]
When openzfs (version 1.3.1-r2 or 1.4.2) is installed (on Mac OS X 10.10 and 10.11) Time Machine Backups would not start (stuck during prepare-phase).

The target Volume is to a ZFS pool on Mac OS X with Server.app on Mac OS X 10.10, which works fine when zfs is not installed on the source-machine.

There are a lot of repeated error messages in the system.log, when this happens. (The Time Machine Volume disk image is mounted at /dev/disk7):

Sep 27 17:02:22 aomame kernel[0]: disk7s2: 0xc023 (UNDEFINED).
Sep 27 17:02:22 --- last message repeated 51 times ---
Sep 27 17:02:22 aomame kernel[0]: *** kernel exceeded 500 log message per second limit  -  remaining messages this second discarded ***
Sep 27 17:02:23 aomame kernel[0]: disk7s2: 0xc023 (UNDEFINED).
Sep 27 17:02:23 --- last message repeated 498 times ---
Sep 27 17:02:23 aomame kernel[0]: *** kernel exceeded 500 log message per second limit  -  remaining messages this second discarded ***
Sep 27 17:02:24 aomame kernel[0]: disk7s2: 0xc023 (UNDEFINED).
Sep 27 17:02:24 --- last message repeated 498 times ---
Sep 27 17:02:24 aomame kernel[0]: *** kernel exceeded 500 log message per second limit  -  remaining messages this second discarded ***
Sep 27 17:02:25 aomame kernel[0]: disk7s2: 0xc023 (UNDEFINED).
Sep 27 17:02:25 --- last message repeated 498 times ---
Sep 27 17:02:25 aomame kernel[0]: *** kernel exceeded 500 log message per second limit  -  remaining messages this second discarded ***
Sep 27 17:02:26 aomame kernel[0]: disk7s2: 0xc023 (UNDEFINED).
Sep 27 17:02:26 --- last message repeated 395 times ---
Sep 27 17:02:26 aomame kernel[0]: disk7s2: 0xc023 (UNDEFINED).
Sep 27 17:02:26 --- last message repeated 102 times ---
Sep 27 17:02:26 aomame kernel[0]: *** kernel exceeded 500 log message per second limit  -  remaining messages this second discarded ***
Sep 27 17:02:27 aomame kernel[0]: disk7s2: 0xc023 (UNDEFINED).
Sep 27 17:02:27 --- last message repeated 484 times —

As soon as I uninstall openzfs on the source-machine, Time Machine works again.

There are currently no zfs-pools on the source machine mounted (just for testing) when this happens.

**Comment by brendonhumphrey** [comment]
Can I ask you to try again?

I don’t have this issue.

Cheers
Brendon

**Comment by jonasjonas** [comment]
Thanks for your feedback.

I had this problem every time a installed zfs on this machine.

I will try again in 2 days with a new pool and a new Time Machine backup to make sure.

**Comment by jonasjonas** [comment]
With the new pool and a new Time Machine backup, I could not reproduce the problem anymore.

Thanks.

**Comment by awein** [comment]
I experience the same issue since a long time - is there a way to debug this to find the actual cause?
(It happens only from time to time and can be fixed by a reboot but will show up again after some time)

**Comment by jonasjonas** [comment]
As a note:
I disabled Spotlight and fsevents on the target volume since then. Which gives me the (unscientific) feeling that also interrupted Network Backups are working with less problems.

**Comment by awein** [comment]
@jonasjonas: Thanks for the hint. I'll give it a try and will let you know if it fixed the issue for me as well.
