### ISSUE TITLE
Unable to install 1.4.2 el capitan release with zpool crash report

### ISSUE THREAD

**Issue by mruepp** [openzfsonosx/zfs#391]
Process:               zpool [1662]
Path:                  /usr/local/bin/zpool
Identifier:            zpool
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1661]
Responsible:           zpool [1662]
User ID:               0

Date/Time:             2015-10-01 12:19:44.778 +0200
OS Version:            Mac OS X 10.11 (15A284)
Report Version:        11
Anonymous UUID:        2EF2D1DB-89B8-2A4C-292D-F7E53661D49E

Time Awake Since Boot: 190 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libnvpair.1.dylib
  Referenced from: /usr/local/bin/zpool
  Reason: image not found

Binary Images:
    0x7fff66f20000 -     0x7fff66f56f5f  dyld (360.14) <DF977301-4A63-32ED-9939-1EE3122D18D4> /usr/lib/dyld

**Comment by ilovezfs** [comment]
This looks like a bad source install as opposed to 1.4.2 installer, which doesn't use /usr/local at all.
Are you using the latest zfsadm (https://gist.github.com/ilovezfs/7713854) or doing something else altogether?

**Comment by mruepp** [comment]
No, I removed source completely with the script. But I had 1.4.2 (working) installed, then updated to el capitan release. Then I tried to reinstall 1.4.2 dmg, but failes.

**Comment by ilovezfs** [comment]
OK, but you did not uninstall it completely since the path mentioned in the crash report "Path: /usr/local/bin/zpool" is part of 1.4.2 installer.

**Comment by mruepp** [comment]
I did uninstall with the 1.4.2 dmg scripts (used all of them) with sudo and sip disabled, but the /usr/local/bin zutilities stay all in place, i discovered now.

**Comment by ilovezfs** [comment]
Those are not installed by 1.4.2 or any previous installer, hence why the uninstall script would not remove them.

**Comment by mruepp** [comment]
Ok, but when I run the uninstall-make-install.sh they should be removed, right? I had a make install on the system before, then removed it by running uninstall-make-install.sh.

**Comment by ilovezfs** [comment]
Yup, I see the change on Jun 9 (https://gist.github.com/ilovezfs/7713854/revisions) means the uninstall-make-install.sh and uninstall-complete.sh scripts needs to be updated. Thanks for catching that. "make uninstall" is a current workaround until I update those.
