### ISSUE TITLE
el capitan support (system integrity protection)

### ISSUE THREAD

**Issue by Licenser** [openzfsonosx/zfs#393]
El Capitan introduces a feature called 'system integrity protection' which apparently messes with the current OS X installer.

A simple workaround is to turn it off by running `csrutil disable` (might need to be run in the recovery console).

From the bit of research I did it has to do with protecting files in `/usr/bin` and other system locations from write access (root included).

**Comment by ilovezfs** [comment]
Yes, we know. A new installer is on the way:
https://github.com/ilovezfs/openzfsonosx-installer/commit/fe930aa0add6cb4c709cbab4d828101ceed13889

**Comment by Licenser** [comment]
Cool :) thanks!

**Comment by ilovezfs** [comment]
SIP compliant version now in the wild:
https://twitter.com/openzfsonosx/status/656095561490132994
https://openzfsonosx.org/wiki/Downloads

Thanks for your patience.
