### ISSUE TITLE
Possible unresolved transaction race in iTunes

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#394]
Having an iTunes library on O3X dataset results in some log messages of:

```
01.10.15 22:09:51,376 iTunes[2827]: Possible unresolved transaction race -116/(iTunes/iTunes Music/Music/B.B. King/Blues On Top Of Blues,(null))
```

in console. This was a very drastic problem at a friend of mine whose logic board was changed and whose iTunes stalled for 5 minutes before it was responsive anymore (piece by piece these log messages flowing in). According to some apple suppot community threads, this is something only happening on HFS+ volumes (so far).
Is this a known behaviour? EDIT: Is known behavior (see link to other bug)

Some other log messages from iTunes around this one (only and pretty much 30 seconds to 1 minute after some but not all unresolved transaction race messages):

```
01.10.15 22:10:23,856 iTunes[2827]: Entered:_AMMuxedDeviceDisconnected, mux-device:64
01.10.15 22:10:23,857 iTunes[2827]: Entered:__thr_AMMuxedDeviceDisconnected, mux-device:64
01.10.15 22:10:23,857 iTunes[2827]: tid:118afb - Mux ID not found in mapping dictionary
01.10.15 22:10:23,857 iTunes[2827]: tid:118afb - Can't handle disconnect with invalid ecid
```

Love Github search :-/

Likely sort of the same as #339

**Comment by ilovezfs** [comment]
(cross posted on the forum, too)
Searching Google, this seems to be a generic problem that has variously affected iTunes, Finder, Spotlight, OmniGraffle, among others, on HFS+, on Tuxera NTFS, on ZFS, etc.

The common theme is that something is on an external or network drive.

I'm wondering if this happens in any of these cases:
1) the entire home directory is on ZFS
2) the entire home directory is on an HFS+ ZVOL
3) Both ~/Library and ~/Music/iTunes are on the same dataset
4) The ~/Music/iTunes folder is accessed only via SMB2 or AFP

**Comment by mruepp** [comment]
Can we merge #394 and #339?

**Comment by ilovezfs** [comment]
@mruepp can close one or the other as a duplicate. Which do you prefer we keep?

**Comment by mruepp** [comment]
Closed #339 
My use case is Itunes Library on ZFS ~/Library on HFS+
System 10.11.1, Itunes 12.3.1.23
It usually occurs when disable/enable Icloud music (formerly itunes match)

Did you see the traces I posted on the forum? Anything unusual?

**Comment by JMoVS** [comment]
media library on ZFS at ~/Music , ~/Library on HFS+. Every single file played/switched to results in a one liner in system console. No iTunes Match or iTunes in the Cloud or Apple Music enabled. Purely local library

**Comment by lundman** [comment]
Using RE to take a look at iTunes, it would appear that we have this situation:

    FileIDTreeBeginTransactionBridge:
    [push vars off stack]
    call       _FileIDTreeGetCachedPort
    call       __SCSessionUniverseGetUID
    call       _FileIDTree_BeginTransaction_rpc
    if (error) goto out:
    call       imp___stubs__strncpy
    cmp        byte [ss:rbp+var_49], 0x0
    je         0x45bfe [return OK]
        loop 20 times
        call       _FileIDTree_GetChildIDFromNameInternal
        call       imp___stubs__usleep
        repeat based on conditions
        call       imp___stubs__syslog
    [message is either "Possible unresolved transaction race"
    or "Had to sleep for %d milliseconds"]

Which suggests we enter into some condition where it repeatedly calls `FileIDTree_GetChildIDFromNameInternal` until it either gets fixed (Had to sleep message) or we give up with a timeout (Possible unresolved).

The trick is obviously in avoiding this code, which then comes down to
    `cmp        byte [ss:rbp+var_49], 0x0`

The only lines containing var_49 are:

    mov        byte [ss:rbp+var_49], 0x0
    lea        rdx, qword [ss:rbp+var_49]
    cmp        byte [ss:rbp+var_49], 0x0 

and the only call between those lines is
    `call       _FileIDTree_BeginTransaction_rpc`
or it is passed in by whatever calls `FileIDTreeBeginTransactionBridge` to start with.

**Comment by alexjarvis** [comment]
Seeing the same thing. iTunes locking up after I tried to enable iTunes Match. Had to turn it off to get the library to respond again.

**Comment by talios** [comment]
Was there any resolution to this issue? Am seeing the same thing with a iTunes media library on ZFS, ~Library on HFS+.

I did have `copies=2` set on that dataset, so dropped it back to `copies=1` for a test but that made no difference.

Using OpenZFSonOSX 1.5.2 here.
