### ISSUE TITLE
Fix getattrlistbulk(2) handling

### ISSUE THREAD

**Issue by derreisende77** [openzfsonosx/zfs#396]
I am the original author of the **"Excessive Finder CPU usage after mounting ZFS volume"** thread in the [forum](https://openzfsonosx.org/forum/viewtopic.php?f=26&t=2240).

Based on the posted spindumps I started tracking down the problem and found that applications using `getattrlistbulk(2)` are getting incredibly slow and will cause max CPU load. _The runtime will increase with the number of files affected and is not related to the file sizes within the directory!_

The problem started appearing with sparse bundles as finder is calculating the total file size for them by calling `getattrlistbulk(2)`. The same behaviour can be triggered with a plain directory filled with dummy data and using a program which calls `getattrlistbulk(2)` to calculate the total file size.
### Test case

Create directory _test_ on ZFS pool _DEMO_ and fill it with 20000 files. I used the following bash script:

``` bash
for i in $(seq 1 20000); do echo $i > $i.txt; done;
```

Next run my C++ test program ([source code](http://pastebin.ca/3185865)):

`./getattrlistbulk_test /Volumes/DEMO/test`

These are sample measured timings for calling `getattrlistbulk(2)` while calculating the total size of the directory:

```
getattrlistbulk seconds elapsed = 0.880
getattrlistbulk seconds elapsed = 0.090
getattrlistbulk seconds elapsed = 0.178
getattrlistbulk seconds elapsed = 0.258
getattrlistbulk seconds elapsed = 0.266
getattrlistbulk seconds elapsed = 0.331
getattrlistbulk seconds elapsed = 0.393
getattrlistbulk seconds elapsed = 0.459
getattrlistbulk seconds elapsed = 0.528
getattrlistbulk seconds elapsed = 0.591
getattrlistbulk seconds elapsed = 0.644
getattrlistbulk seconds elapsed = 0.714
getattrlistbulk seconds elapsed = 0.792
getattrlistbulk seconds elapsed = 0.874
getattrlistbulk seconds elapsed = 0.942
getattrlistbulk seconds elapsed = 0.978
getattrlistbulk seconds elapsed = 1.085
getattrlistbulk seconds elapsed = 1.172
getattrlistbulk seconds elapsed = 1.192
getattrlistbulk seconds elapsed = 1.304
getattrlistbulk seconds elapsed = 1.340
getattrlistbulk seconds elapsed = 1.440
getattrlistbulk seconds elapsed = 1.473
getattrlistbulk seconds elapsed = 1.552
getattrlistbulk seconds elapsed = 1.668
getattrlistbulk seconds elapsed = 1.721
getattrlistbulk seconds elapsed = 1.798
getattrlistbulk seconds elapsed = 1.849
getattrlistbulk seconds elapsed = 1.921
getattrlistbulk seconds elapsed = 2.116
getattrlistbulk seconds elapsed = 2.155
getattrlistbulk seconds elapsed = 2.150
getattrlistbulk seconds elapsed = 2.269
getattrlistbulk seconds elapsed = 2.339
getattrlistbulk seconds elapsed = 2.779
getattrlistbulk seconds elapsed = 2.645
getattrlistbulk seconds elapsed = 2.539
getattrlistbulk seconds elapsed = 2.673
getattrlistbulk seconds elapsed = 2.823
getattrlistbulk seconds elapsed = 3.084
getattrlistbulk seconds elapsed = 3.255
getattrlistbulk seconds elapsed = 3.279
getattrlistbulk seconds elapsed = 3.236
getattrlistbulk seconds elapsed = 2.591
getattrlistbulk seconds elapsed = 0.000

files = 20000 checked = 20000
grand total = 108894 checked = 108894
seconds elapsed = 68.399
```

**Calculating the total file size of 20k files takes 68 seconds on a ZFS volume!**
### Cause

AFAIK the slow performance is caused by calling `zap_value_search(...)` in `zfs_getattr_znode_unlocked(...)` in `zfs/zfs_vnops_osx_lib.c`. `zap_value_search(...)` is iterating every call through the attribute list using a cursor to find the required information causing the almost linear slowdown and blocking the programs.

**Comment by lundman** [comment]
There are a couple of things we should try here. One is to implement `getattrlistbulk`, we don't even use our `getattrlist` call as it needs fixing, so we rely on XNU internal compat code - ie, the kernel will simulate `getattrlist*` by iteratively calling `vnop_getattr` and packing it up for us. By implementing `getattrlist` we should speed that loop up, and by implementing `getattrlistbulk` we can speed it up more by avoiding such tight loops.

Then, we should also look into `vnop_getattr` itself, in particular, when called with `VA_NAME` to receive the name back. (Which seems to be nearly all the time). And naturally, the equivalent call in `getattrlist`. In particular, as finding the name is a non-trivial task, we have to search through the zap, as you have already seen.

In particular interest, is that to handle Finder and hardlinks, we store the "name" used, in the `vnop_lookup` call, so that a following `vnop_getattr(VA_NAME)` can return the name Finder expects. This is currently stored in the `znode` if the vtype is VLNK. We should explore changing this to always storing the name, and, thereby be able to avoid searching the zap in `vnop_getattr`, in most cases. 

File it under TODO :)

**Comment by derreisende77** [comment]
That basically means until then useful work with ZFS and sparse bundles is impossible unfortunately.
And a user should never turn on the Finder´s size calculation for all objects in his settings :(

Is this at least high on the TODO? ;)

**Comment by ilovezfs** [comment]
Given that we have plenty of users who use sparsebundles successfully for time machine backups, your assertion is empirically false. The question would be why you're more impacted than others.

**Comment by derreisende77** [comment]
My bundles are 600GB+. And given the fact that cpu usage is normally not shown and on a multi-core not that easily realized I "think" they simply don't see it.

**Comment by cbreak-black** [comment]
My biggest bundle is 3'573'046'824'960 bytes. It works, but finder still didn't manage to calculate the size of the bundle even after hours of trying. Oh, and I now have to kill finder because it uses 100% CPU :) (It didn't do that while trying to calculate the size, only now that I stopped it)

> cbreak@artefact:bands$ time ll -l | wc -l
>   425512
> real	4m21.845s
> user	0m14.477s
> sys	1m25.286s

**Comment by lundman** [comment]
Branch "issue396" has new checkin https://github.com/openzfsonosx/zfs/commit/6543b6d3fccb

If you are able, see if it improves your situation.

**Comment by derreisende77** [comment]
The improvement is HUGE!!!
For the testcase, the time is down from 68s to 0.102s :)

CPU utilization also went down significantly and size calculations are now enormously faster in Finder.

Very nice fix!

**Comment by lundman** [comment]
589a6552f9dad54a04f216e72b2ab93b93764b5d

**Comment by noberasco** [comment]
When is this scheduled to hit a stable release? :-)
