### ISSUE TITLE
Finder issues with the new name caching

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#403]
I installed @ilovezfs 's 1.4.4 build. I have my documents as a dataset that gets mounted to ~/Documents
This works great, never had problems.

So I have a git repo under ~/Documents/Development/some/path and use Tower 2 app (essentially just a git GUI). Now I stashed some changes on one branch, switched to another branch which had previously changed stashes and wondered why suddenly Tower would crash.

Then I looked at Finder and saw this:
![bildschirmfoto_2015-10-16_um_18_46_27](https://cloud.githubusercontent.com/assets/7354506/10547949/c6d84f60-7437-11e5-929e-b78b4ca46042.png)

This was the reproducability test. When I first looked at it, I had 6 or 7 development folders, and when I "opened" one, it was the very definition of recursion. Just showing the same folder again with 6 sub development folders.

I exported the pool, rebooted, everything looked great. I then tried to open Tower again and selected this git repo, and boom, now 3 development folders aqs described above.

I then downgraded to 1.4.2 and everything is back to normal and fine. If I can help somehow, please give me guidance, I am happy to provide additonally needed information.

**Comment by JMoVS** [comment]
ok, issue doesn't appear with commit: 16328e41aba9eff672741a43004c565586cf2ac1

**Comment by JMoVS** [comment]
ok, this is a bug, needs editing, reopening and editing right now

**Comment by ilovezfs** [comment]
This appears to be a reincarnation of https://github.com/openzfsonosx/zfs/issues/146 so I reverted the issue396 pull request https://github.com/openzfsonosx/zfs/pull/402 until we have a fix.

**Comment by lundman** [comment]
If you have the ability, see if fixing rename makes any difference

https://github.com/openzfsonosx/zfs/commit/694b4acbd8e9e27e0f2c82f947ff5458af775429

**Comment by JMoVS** [comment]
No, unfortunately have not set up source compile version yet. 

Are you sure it really is just a Finder bug? My whole git client was unable to open any git repo at all and it afaik doesn't open Finder calls...

**Comment by ilovezfs** [comment]
https://github.com/openzfsonosx/zfs/commit/694b4acbd8e9e27e0f2c82f947ff5458af775429 isn't sufficient to resolve the problems so nothing new for you to test on this yet.

**Comment by JMoVS** [comment]
Ok. As I said, I really wonder whether this is a just Finder bug and not something deeper. (Wondering about the title of this again...)

**Comment by ilovezfs** [comment]
It's already being worked on. Don't worry about the title lol

**Comment by JMoVS** [comment]
I don't doubt that- ;-) I just wondered (please honestly correct me if I'm wrong, I'm the newbie), that with this name, were such bug to occur again, I think it would make sense to better find it (espescially if other devs look at it) to give it a more technical/appropriate name. But as mentioned, I can be totally wrong on this, I just don't know

**Comment by lundman** [comment]
Those that can, could you pull the latest issue396 branch and test.

https://github.com/openzfsonosx/zfs/commit/5a5862e990a0c8455e32f9348b6f8c0a0deed121

**Comment by ilovezfs** [comment]
Unfortunately, still broken.
```
sudo zfs create myfoo/hltest
sudo chown -R ilovezfs:staff /Volumes/myfoo/hltest/
touch /Volumes/myfoo/hltest/foo0.txt
ln /Volumes/myfoo/hltest/foo0.txt /Volumes/myfoo/hltest/foo1.txt
```

Go to /Volumes/myfoo/hltest in Finder.
Try to rename foo0.txt foo2.txt
"The operation can't be completed. An unexpected error occurred (error code -8072)"

Also, try to copy paste foo0.txt within the directory leads to
"The items on the Clipboard can't be pasted to this location. One or more of the items may have been deleted or are no longer available."

mkdir  /Volumes/myfoo/hltest/subdir

Try to drag and drop foo0.txt into subdir.
"The operation can't be completed because an unexpected error occurred (error code -1407)."

**Comment by ilovezfs** [comment]
Using https://github.com/openzfsonosx/zfs/commit/47f3cc5e38511aa37a8456b4f39bed1f0ab26c00, when I rename a hard-linked file in FInder, the file disappears and then reappears. The same does not happen with HFS+ hard links. The disappear/reappear happens regardless of whether the hard links are in the same directory or different directories.

**Comment by ilovezfs** [comment]
And a repeatable way to trigger a Finder error:
```
mkfile 256m file.bin
sudo zpool create filepool `pwd`/file.bin
cd /Volumes/filepool
sudo chown -R "$(whoami)":staff .
touch 1.txt
ln 1.txt 2.txt
open -a finder .
Now select 1.txt in Finder
command+delete to move 1.txt to the Trash
Select 2.txt
Hit return to rename it. Type "1." Hit return.
Error dialog appears: The name "1" with extension ".txt" is already taken. Please choose a different name. Click OK.
Hit return again to try a different name. Type "3." Hit return.
And another error dialog appears: "The operation can't be completed. An unexpected error occured (error code -43).
```

Neither error occurs with HFS.

**Comment by ilovezfs** [comment]
Continuing the reproducer above, here's a third error:
```
sudo rm /Volumes/filepool/.Trashes/$(id -u)/1.txt
mkdir dir0
Then try to drag and drop 2.txt into dir0.
Error dialog appears: The operation can't be completed because an item with the name "2.txt" already exists.
```

**Comment by lundman** [comment]
The issue396 branch has what I hope is the complete version of caching, and hardlink issues, including a few more things we had missed of hardlinks and HFS.
