### ISSUE TITLE
nonexistent path /etc/zfs/zed.d (org.openzfsonosx.zed exited with code: 1)

### ISSUE THREAD

**Issue by grahamperrin** [openzfsonosx/zfs#423]
Spun off from https://openzfsonosx.org/forum/viewtopic.php?f=26&t=2365

I manually created  
/etc/zfs 
(for zsysctl.conf) and then 
/etc/zfs/zed.d
(to allow proper running of zed by launchd).

I guess that the required path (the two directories)  
/etc/zfs/zed.d
should be made automatically. 

    cces3e-gjp4:~ gjp22$ defaults read /Library/LaunchDaemons/org.openzfsonosx.zed
    {
        KeepAlive = 1;
        Label = "org.openzfsonosx.zed";
        ProgramArguments =     (
            "/usr/sbin/zed",
            "-vfF"
        );
        RunAtLoad = 1;
        StandardErrorPath = "/private/var/log/org.openzfsonosx.zed.err";
        StandardOutPath = "/private/var/log/org.openzfsonosx.zed.log";
    }
    cces3e-gjp4:~ gjp22$ sudo launchctl unload -w /Library/LaunchDaemons/org.openzfsonosx.zed.plist
    Password:
    cces3e-gjp4:~ gjp22$ which zed
    /usr/sbin/zed
    cces3e-gjp4:~ gjp22$ zed -vfF
    Must be run as root
    cces3e-gjp4:~ gjp22$ sudo zed -vfF
    Failed to open dir "/etc/zfs/zed.d": No such file or directory
    cces3e-gjp4:~ gjp22$ cd /etc/zfs
    cces3e-gjp4:zfs gjp22$ ls -l
    total 16
    -rw-r--r--  1 root  wheel  1152  4 Nov 21:17 zpool.cache.tmp
    -rw-r--r--  1 root  wheel    48  4 Nov 21:14 zsysctl.conf
    cces3e-gjp4:zfs gjp22$ sudo mkdir zed.d
    cces3e-gjp4:zfs gjp22$ sudo zed -vfF
    ZFS Event Daemon 1.4.5-1 (PID 1322)
    Processing events since eid=0
    load: 3.79  cmd: zed 1322 waiting 0.00u 0.01s
    ^CExiting
    cces3e-gjp4:zfs gjp22$ sudo launchctl load -w /Library/LaunchDaemons/org.openzfsonosx.zed.plist
    cces3e-gjp4:zfs gjp22$

**Comment by grahamperrin** [comment]
If it's relevant: the installation was performed with Pacifist.

**Comment by ilovezfs** [comment]
It is made automatically. Yes, it's going to be due to Pacificist.
