### ISSUE TITLE
org.macports.install for port … returned: sqlite error: disk I/O error (10)

### ISSUE THREAD

**Issue by grahamperrin** [openzfsonosx/zfs#425]
Spun off from [sqlite error: disk I/O error (10) with OpenZFS on OS X](https://openzfsonosx.org/forum/viewtopic.php?f=26&t=2368)

Two examples below. 

The I/O errors that are reported by MacPorts when using OpenZFS on OS X for /opt on OS X 10.9.5 are not reported when using HFS Plus for /opt on OS X 10.11.1, so I guess that this is a bug. 

**First example**

    :debug:install Using /usr/bin/tar
    :debug:install Using /usr/bin/bzip2
    :debug:install Creating gstreamer1-1.6.1_0.darwin_13.x86_64.tbz2
    :debug:install Environment: 
    CC_PRINT_OPTIONS='YES'
    CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/work/.CC_PRINT_OPTIONS'
    CPATH='/opt/local/include'
    LIBRARY_PATH='/opt/local/lib'
    MACOSX_DEPLOYMENT_TARGET='10.9'
    :debug:install Assembled command: 'cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/work/destroot" && /usr/bin/tar -cvf - . | /usr/bin/bzip2 -c9 > /opt/local/var/macports/software/gstreamer1/gstreamer1-1.6.1_0.darwin_13.x86_64.tbz2'
    :debug:install Executing command line:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/work/destroot" && /usr/bin/tar -cvf - . | /usr/bin/bzip2 -c9 > /opt/local/var/macports/software/gstreamer1/gstreamer1-1.6.1_0.darwin_13.x86_64.tbz2 
    :info:install a .
    :info:install a ./+CONTENTS
    :info:install a ./+DESC
    :info:install a ./+COMMENT
    :info:install a ./+PORTFILE
    :info:install a ./+STATE
    :debug:install Archive gstreamer1-1.6.1_0.darwin_13.x86_64.tbz2 packaged
    :debug:install removing file: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/work/destroot/+CONTENTS
    :debug:install removing file: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/work/destroot/+DESC
    :debug:install removing file: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/work/destroot/+COMMENT
    :debug:install removing file: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/work/destroot/+PORTFILE
    :debug:install removing file: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/work/destroot/+STATE
    :error:install org.macports.install for port gstreamer1 returned: sqlite error: disk I/O error (10)
    :debug:install Error code: registry::sqlite-error
    :debug:install Backtrace: sqlite error: disk I/O error (10)
        while executing
    "registry::write {
    
            set regref [registry::entry create $subport $version $revision $portvariants $epoch]
    
            if {[info exists user_options..."
        (procedure "portinstall::install_main" line 38)
        invoked from within
    "portinstall::install_main org.macports.install"
        ("eval" body line 1)
        invoked from within
    "eval $procedure $targetname"
    :info:install Warning: targets not executed for gstreamer1: org.macports.activate org.macports.install
    :notice:install Please see the log file for port gstreamer1 for details:
        /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/main.log
    sh-3.2$ clear ; date ; ls -@aelR /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gnome_gstreamer1/gstreamer1/work/destroot
    
    Thu  5 Nov 2015 04:53:00 GMT
    total 34
    drwxr-xr-x+ 2 macports  admin  2  5 Nov 04:46 .
     0: group:owner allow list,add_file,search,add_subdirectory,readattr,writeattr,readextattr,writeextattr,readsecurity,writesecurity,chown
     1: group:group allow list,search,readattr,readextattr,readsecurity
     2: group:everyone allow list,search,readattr,readextattr,readsecurity
    drwxr-xr-x+ 6 macports  admin  6  5 Nov 03:00 ..
     0: group:owner allow list,add_file,search,add_subdirectory,readattr,writeattr,readextattr,writeextattr,readsecurity,writesecurity,chown
     1: group:group allow list,search,readattr,readextattr,readsecurity
     2: group:everyone allow list,search,readattr,readextattr,readsecurity
    sh-3.2$

**Second example**

    cces3e-gjp4:~ gjp22$ sw_vers ; date ; sudo kextstat | grep zfs ; sudo port install gstreamer1
    ProductName:   Mac OS X
    ProductVersion:   10.9.5
    BuildVersion:   13F1134
    Thu  5 Nov 2015 18:15:23 GMT
    Password:
      128    1 0xffffff7f80854000 0x239000   0x239000   net.lundman.zfs (1.4.5) <127 15 7 5 4 3 1>
    --->  Computing dependencies for cairo
    --->  Installing cairo @1.14.4_0+quartz+x11
    Error: org.macports.install for port cairo returned: sqlite error: disk I/O error (10)
    Please see the log file for port cairo for details:
        /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_cairo/cairo/main.log
    Error: Unable to upgrade port: 1
    Error: Unable to execute port: upgrade gobject-introspection failed

**Environment**

    cces3e-gjp4:~ gjp22$ zpool status
      pool: gjp22
     state: ONLINE
    status: The pool is formatted using a legacy on-disk format.  The pool can
       still be used, but some features are unavailable.
    action: Upgrade the pool using 'zpool upgrade'.  Once this is done, the
       pool will no longer be accessible on software that does not support
       feature flags.
      scan: scrub repaired 0 in 116h26m with 0 errors on Sun Oct 25 17:30:48 2015
    config:

       NAME                                          STATE     READ WRITE CKSUM
       gjp22                                         ONLINE       0     0     0
         media-67095812-B5B2-4ECE-A0D5-E1721F71C279  ONLINE       0     0     0

    errors: No known data errors
    cces3e-gjp4:~ gjp22$ zfs mount
    gjp22                           /Users/gjp22
    gjp22/opt                       /opt
    cces3e-gjp4:~ gjp22$ zfs get all gjp22/opt
    NAME       PROPERTY               VALUE                  SOURCE
    gjp22/opt  type                   filesystem             -
    gjp22/opt  creation               Tue Aug  5 10:42 2014  -
    gjp22/opt  used                   19.2G                  -
    gjp22/opt  available              111G                   -
    gjp22/opt  referenced             4.93G                  -
    gjp22/opt  compressratio          1.69x                  -
    gjp22/opt  mounted                yes                    -
    gjp22/opt  quota                  none                   default
    gjp22/opt  reservation            none                   default
    gjp22/opt  recordsize             128K                   default
    gjp22/opt  mountpoint             /opt                   received
    gjp22/opt  sharenfs               off                    default
    gjp22/opt  checksum               on                     default
    gjp22/opt  compression            on                     local
    gjp22/opt  atime                  off                    inherited from gjp22
    gjp22/opt  devices                on                     default
    gjp22/opt  exec                   on                     default
    gjp22/opt  setuid                 on                     default
    gjp22/opt  readonly               off                    local
    gjp22/opt  zoned                  off                    default
    gjp22/opt  snapdir                visible                inherited from gjp22
    gjp22/opt  aclmode                discard                default
    gjp22/opt  aclinherit             restricted             default
    gjp22/opt  canmount               on                     local
    gjp22/opt  xattr                  on                     default
    gjp22/opt  copies                 1                      default
    gjp22/opt  version                5                      -
    gjp22/opt  utf8only               on                     -
    gjp22/opt  normalization          formD                  -
    gjp22/opt  casesensitivity        insensitive            -
    gjp22/opt  vscan                  off                    default
    gjp22/opt  nbmand                 off                    default
    gjp22/opt  sharesmb               off                    default
    gjp22/opt  refquota               none                   default
    gjp22/opt  refreservation         none                   default
    gjp22/opt  primarycache           all                    inherited from gjp22
    gjp22/opt  secondarycache         all                    inherited from gjp22
    gjp22/opt  usedbysnapshots        14.3G                  -
    gjp22/opt  usedbydataset          4.93G                  -
    gjp22/opt  usedbychildren         0                      -
    gjp22/opt  usedbyrefreservation   0                      -
    gjp22/opt  logbias                latency                default
    gjp22/opt  dedup                  off                    default
    gjp22/opt  mlslabel               none                   default
    gjp22/opt  sync                   standard               default
    gjp22/opt  refcompressratio       1.60x                  -
    gjp22/opt  written                458M                   -
    gjp22/opt  logicalused            23.8G                  -
    gjp22/opt  logicalreferenced      6.86G                  -
    gjp22/opt  filesystem_limit       none                   default
    gjp22/opt  snapshot_limit         none                   default
    gjp22/opt  filesystem_count       none                   default
    gjp22/opt  snapshot_count         none                   default
    gjp22/opt  snapdev                hidden                 default
    gjp22/opt  com.apple.browse       on                     default
    gjp22/opt  com.apple.ignoreowner  off                    default
    gjp22/opt  com.apple.mimic_hfs    off                    default
    gjp22/opt  redundant_metadata     all                    default
    gjp22/opt  overlay                off                    default
    cces3e-gjp4:~ gjp22$

**Comment by lundman** [comment]
It would be interesting to see the snippet from `/var/log/system.log` with debug output turned on. You can turn it on with 
```
sysctl -w kstat.zfs.darwin.tunable.vnop_debug=1
```
Turn it on as close to the problem as possible, as it is ridiculously verbose. Set it to =0 to disable.

**Comment by grahamperrin** [comment]
Thanks @lundman I'll try that when I next test the system. 

In the meantime, from #300: 

> … filenames that are valid in HFS+, but are too large to fit in ZFS …

– I thought of that yesterday, because I do sometimes see extraordinarily long *paths* with MacPorts.

**Comment by ilovezfs** [comment]
This is master HEAD built for you now: https://www.dropbox.com/s/iy3apygt33uhbwl/mav267bf64.pkg

Needs uninstall first, then reinstall because there's no version bump.
https://github.com/ilovezfs/openzfsonosx-installer/blob/master/scripts/dmg-scripts/uninstall-complete.sh

Please check that the issue still affects master.

**Comment by lundman** [comment]
Ok, this bug trickles down to sqlite using a fallocate call, with argument F_ALLOCSP. Currently only FREESP is supported in ZFS, as F_ALLOCSP is incompatible with COW filesystems. There were discussions regarding at least changing the error code to something more appropriate (ENOTSUP) so that the software can detect it better.

http://www.listbox.com/member/archive/182191/2013/20130425172312:536E2F02-ADEE-11E2-B2BD-AD5882B17FC9/
http://permalink.gmane.org/gmane.os.illumos.zfs/1483

We should definitely update to return ENOTSUP, and sqlite3 has already updated their sources to work around it http://www.sqlite.org/src/info/1bbb4be1a25

I think it is more a matter of waiting for MacPorts to update its sqlite3 compile

This could become a "wont.fix" issue, but I'll leave it open for a bit if we want to discuss it further.

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs/commit/4812cd1ec07823c2d78efe7fbe81291c4c00fa0a

**Comment by ilovezfs** [comment]
@lundman has commented here: https://trac.macports.org/ticket/39611#comment:3
