### ISSUE TITLE
ZTEST failing in FreeBSD 10.1-RC3.

### ISSUE THREAD

**Issue by sheetalsid** [openzfsonosx/zfs#431]
Hi,
I'm Sheetal Kumar from CloudByte Technologies, currently me and my team are  exploring FreeBSD 10.1-RC3, when we came across ZFS, we are not able to run ZTEST successfully, we are getting following error when we run ZTEST.

root@bsd10:~ #  ztest -t 1 -T 3600 -P 5 -VVVVVVVV                                            

 5 vdevs, 7 datasets, 1 threads, 3600 seconds...                                                   Assertion failed: (tq->tq_freelist != NULL), file /usr/src/cddl/lib/libzpool/../../../cddl/contrib/opensolaris/lib/libzpool/common/taskq.c, line 289.                                                
child died with signal 6

**Comment by brendonhumphrey** [comment]
Wrong OS!
