### ISSUE TITLE
Incorrect free space reporting in Finder

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#436]
Using the Finder to copy data to a dataset decreases the free space shown in Finder for said dataset after successfull copy process by the correct amount.
But if it so happens that this dataset is on a pool and other datasets on the same pool are present, their free space won't get updated. Also, if one puts something in the trash and empties the trash, not even the dataset where the item initally was gets an update to it's reported free space.

This update can be triggered for all datasets mounted of a pool by unmounting any (really, any) dataset in the pool) or mounting it. This then refreshes the free space reported in Finder.

zfs get all or zfs list always reports correct numbers, only the Finder app doesn't report correct values.

**Comment by ilovezfs** [comment]
Unmount/remount themselves are not related. It's most like the mkdir or rmdir of the mountpoint directory in the parent dataset that you're seeing trigger a refresh. You'll notice that if you move something else to the Trash after emptying the Trash that the Finder reported available space within that dataset and all datasets above it in the hierarchy will update, but datasets below or lateral to it in the hierarchy will not update.

In general, the Finder reported available space seems to update to what would have been the correct value before the given operation.

Make a 1g file, a 2g file, a 4g file, an 8g file, and a 16g file. Removing the 2g file appears to free nothing according to Finder. Then remove the 16g file, Finder reports 2g freed up. Remove the 1g file, Finder then reports an additional 16g freed up. Remove the 4g file, Finder then reports an additional 1g freed up. Make an empty file, Finder reports an additional 1g freed up.

**Comment by lundman** [comment]
08e4cbc5938f7e14a7be458c760da3306da93c0e

**Comment by ilovezfs** [comment]
Original fix reverted in 58973a1204a7e9693dd8ef6e64a1130ca35b2706

Some other approach will be needed.

On IRC, @lundman suggested, "We could probably remember the pool txg in vnop_remove, and a counter of 'bytes deleted.' Simply fudge getattr while txg is same, clear fudge once higher … Only interesting question is if you can looking up currect txg's affected-data-size , that would be something."

Also on IRC, @rottegift wondered whether the counter should be at vfs, dmu, or spa level.

**Comment by ilovezfs** [comment]
@lundman a5701f7eacd4a166985e1745936d9f070d9aed90 does not seem to improve the situation, so perhaps that should be removed from master.

**Comment by JMoVS** [comment]
I don't know what the current status is but to me this can be considered fixed and closed as it also works across users with separate datasets.

**Comment by lundman** [comment]
This was fixed with 45aaa7c8bfda7bcc882a78b962087e52ef9c4e9c and has no "users" concerns. :)

**Comment by BugraK** [comment]
I am having this problem too. If I copy some file to the dataset free space decreases, both in Finder and `zfs list`. But if I delete something free space doesn't change, again both in Finder and `zfs list`. I tried `zfs unmount/mount` and `zpool export/import` with no success. Am I missing something?

**Comment by JMoVS** [comment]
Depends on if you made snapshots or not. Snapshots can contain data that you deleted afterwards. Does that explain it for you?

Best regards
Justin Scholz

Sent from mobile

**Comment by BugraK** [comment]
You are right! I used `zfsnap.sh` to take and delete snapshots, but it didn't delete old snapshots, so they were taking space. Thanks for your help :)

**Comment by JMoVS** [comment]
Have a look at znapzend if you want more automated snapshot creation. Great to hear I was able to help you solve the mystery. 

Beste Grüße
Justin Scholz

Sent from mobile
