### ISSUE TITLE
Kernel Panic on setting zfs_arc_max

### ISSUE THREAD

**Issue by h0lzi** [openzfsonosx/zfs#441]
On Release Version 1.4.5

After using migration assistent (not sure if related) to a new mac with now 16 GB instead of 8 gig of ram.
On el cap 10.11.2 I get a Kernel panic. 
I had a setting for like 300MB arc size in /etc/zfs/zsysctl.conf.
It did not boot anymore:
Tue Dec 15 07:19:39 2015

*** Panic Report ***
panic(cpu 6 caller 0xffffff80095d155a): Kernel trap at 0xffffff7f8cf17dd1, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x00007fff50a1ad08, CR3: 0x0000000009fd101f, CR4: 0x00000000003627e0
RAX: 0x0000000000000000, RBX: 0x0000000000000000, RCX: 0x00007fff50a1ad08, RDX: 0x0000000000000000
RSP: 0xffffff91facc3d70, RBP: 0xffffff91facc3da0, RSI: 0x0000000000000000, RDI: 0xffffff802e8f1e00
R8:  0xffffff91facc3b70, R9:  0x0000000000000999, R10: 0x0000000000000000, R11: 0x0000000000000206
R12: 0xffffff91facc3eb0, R13: 0xffffff802e8f1e00, R14: 0x0000000000000000, R15: 0xffffff7f8d063180
RFL: 0x0000000000010246, RIP: 0xffffff7f8cf17dd1, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007fff50a1ad08, Error code: 0x0000000000000001, Fault CPU: 0x6 SMAP fault, PL: 0

Backtrace (CPU 6), Frame : Return Address
0xffffff91facc3a00 : 0xffffff80094de792 
0xffffff91facc3a80 : 0xffffff80095d155a 
0xffffff91facc3c60 : 0xffffff80095ef233 
0xffffff91facc3c80 : 0xffffff7f8cf17dd1 
0xffffff91facc3da0 : 0xffffff80099bbe94 
0xffffff91facc3e30 : 0xffffff80099bb421 
0xffffff91facc3f60 : 0xffffff8009a29ac1 
0xffffff91facc3fb0 : 0xffffff80095efa36 
      Kernel Extensions in backtrace:
         net.lundman.spl(1.4.5)[78831EE7-94AF-3E2D-B63A-612BA6ED8B5C]@0xffffff7f8cf0f000->0xffffff7f8cf45fff

BSD process name corresponding to current thread: zsysctl

Mac OS version:
15C50

Kernel version:
Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64
Kernel UUID: 17EA3101-D2E4-31BF-BDA9-931F51049F93
Kernel slide:     0x0000000009200000
Kernel text base: 0xffffff8009400000
__HIB  text base: 0xffffff8009300000
System model name: iMac17,1 (Mac-B809C3757DA9BB8D)

after removing the limit it works fine.

Setting manual 
sudo sysctl -w kstat.zfs.darwin.tunable.zfs_arc_max=3428843520
caused instant panic too.

Tue Dec 15 10:33:04 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff800fdd155a): Kernel trap at 0xffffff7f90484dd1, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x00007fff5cf2aba8, CR3: 0x000000040643b0fb, CR4: 0x00000000003627e0
RAX: 0x0000000000000000, RBX: 0x0000000000000000, RCX: 0x00007fff5cf2aba8, RDX: 0x0000000000000000
RSP: 0xffffff9227ff3d70, RBP: 0xffffff9227ff3da0, RSI: 0x0000000000000000, RDI: 0xffffff8034ee1000
R8:  0xffffff9227ff3b70, R9:  0x0000000000000999, R10: 0x0000000000000000, R11: 0x0000000000000206
R12: 0xffffff9227ff3eb0, R13: 0xffffff8034ee1000, R14: 0x0000000000000000, R15: 0xffffff7f905d0180
RFL: 0x0000000000010246, RIP: 0xffffff7f90484dd1, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007fff5cf2aba8, Error code: 0x0000000000000001, Fault CPU: 0x0 SMAP fault, PL: 0

Backtrace (CPU 0), Frame : Return Address
0xffffff9227ff3a00 : 0xffffff800fcde792 
0xffffff9227ff3a80 : 0xffffff800fdd155a 
0xffffff9227ff3c60 : 0xffffff800fdef233 
0xffffff9227ff3c80 : 0xffffff7f90484dd1 
0xffffff9227ff3da0 : 0xffffff80101bbe94 
0xffffff9227ff3e30 : 0xffffff80101bb421 
0xffffff9227ff3f60 : 0xffffff8010229ac1 
0xffffff9227ff3fb0 : 0xffffff800fdefa36 
      Kernel Extensions in backtrace:
         net.lundman.spl(1.4.5)[78831EE7-94AF-3E2D-B63A-612BA6ED8B5C]@0xffffff7f9047c000->0xffffff7f904b2fff

BSD process name corresponding to current thread: sysctl

Mac OS version:
15C50

Kernel version:
Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64
Kernel UUID: 17EA3101-D2E4-31BF-BDA9-931F51049F93
Kernel slide:     0x000000000fa00000
Kernel text base: 0xffffff800fc00000
__HIB  text base: 0xffffff800fb00000
System model name: iMac17,1 (Mac-B809C3757DA9BB8D)

without setting anything it seems to work.
don't know if I set it to low or to high?

sysctl kstat |grep arc
kstat.vmem.vmem.heap.search: 0
kstat.vmem.vmem.heap.contains_search: 0
kstat.vmem.vmem.vmem_metadata.search: 0
kstat.vmem.vmem.vmem_metadata.contains_search: 0
kstat.vmem.vmem.vmem_seg.search: 0
kstat.vmem.vmem.vmem_seg.contains_search: 0
kstat.vmem.vmem.vmem_hash.search: 0
kstat.vmem.vmem.vmem_hash.contains_search: 0
kstat.vmem.vmem.vmem_vmem.search: 11
kstat.vmem.vmem.vmem_vmem.contains_search: 0
kstat.vmem.vmem.kmem_metadata.search: 0
kstat.vmem.vmem.kmem_metadata.contains_search: 0
kstat.vmem.vmem.kmem_msb.search: 0
kstat.vmem.vmem.kmem_msb.contains_search: 0
kstat.vmem.vmem.kmem_cache.search: 194
kstat.vmem.vmem.kmem_cache.contains_search: 0
kstat.vmem.vmem.kmem_hash.search: 0
kstat.vmem.vmem.kmem_hash.contains_search: 0
kstat.vmem.vmem.kmem_log.search: 1
kstat.vmem.vmem.kmem_log.contains_search: 0
kstat.vmem.vmem.zfs_file_data.search: 0
kstat.vmem.vmem.zfs_file_data.contains_search: 0
kstat.vmem.vmem.zfs_file_data_buf.search: 0
kstat.vmem.vmem.zfs_file_data_buf.contains_search: 0
kstat.vmem.vmem.kmem_oversize.search: 0
kstat.vmem.vmem.kmem_oversize.contains_search: 0
kstat.vmem.vmem.kmem_va.search: 0
kstat.vmem.vmem.kmem_va.contains_search: 0
kstat.vmem.vmem.kmem_default.search: 0
kstat.vmem.vmem.kmem_default.contains_search: 0
kstat.vmem.vmem.taskq_id_arena.search: 0
kstat.vmem.vmem.taskq_id_arena.contains_search: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.buf_size: 200
kstat.unix.kmem_cache.arc_buf_hdr_t.align: 8
kstat.unix.kmem_cache.arc_buf_hdr_t.chunk_size: 200
kstat.unix.kmem_cache.arc_buf_hdr_t.slab_size: 524288
kstat.unix.kmem_cache.arc_buf_hdr_t.alloc: 6557
kstat.unix.kmem_cache.arc_buf_hdr_t.alloc_fail: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.free: 4690
kstat.unix.kmem_cache.arc_buf_hdr_t.depot_alloc: 28
kstat.unix.kmem_cache.arc_buf_hdr_t.depot_free: 36
kstat.unix.kmem_cache.arc_buf_hdr_t.depot_contention: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.slab_alloc: 1875
kstat.unix.kmem_cache.arc_buf_hdr_t.slab_free: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.buf_constructed: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.buf_avail: 746
kstat.unix.kmem_cache.arc_buf_hdr_t.buf_inuse: 1875
kstat.unix.kmem_cache.arc_buf_hdr_t.buf_total: 2621
kstat.unix.kmem_cache.arc_buf_hdr_t.buf_max: 2621
kstat.unix.kmem_cache.arc_buf_hdr_t.slab_create: 1
kstat.unix.kmem_cache.arc_buf_hdr_t.slab_destroy: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.vmem_source: 15
kstat.unix.kmem_cache.arc_buf_hdr_t.hash_size: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.hash_lookup_depth: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.hash_rescale: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.full_magazines: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.empty_magazines: 21
kstat.unix.kmem_cache.arc_buf_hdr_t.magazine_size: 7
kstat.unix.kmem_cache.arc_buf_hdr_t.reap: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.defrag: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.scan: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.move_callbacks: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.move_yes: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.move_no: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.move_later: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.move_dont_need: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.move_dont_know: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.move_hunt_found: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.move_slabs_freed: 0
kstat.unix.kmem_cache.arc_buf_hdr_t.move_reclaimable: 0
kstat.unix.kmem_cache.arc_buf_t.buf_size: 64
kstat.unix.kmem_cache.arc_buf_t.align: 8
kstat.unix.kmem_cache.arc_buf_t.chunk_size: 64
kstat.unix.kmem_cache.arc_buf_t.slab_size: 524288
kstat.unix.kmem_cache.arc_buf_t.alloc: 6545
kstat.unix.kmem_cache.arc_buf_t.alloc_fail: 0
kstat.unix.kmem_cache.arc_buf_t.free: 4680
kstat.unix.kmem_cache.arc_buf_t.depot_alloc: 10
kstat.unix.kmem_cache.arc_buf_t.depot_free: 20
kstat.unix.kmem_cache.arc_buf_t.depot_contention: 0
kstat.unix.kmem_cache.arc_buf_t.slab_alloc: 1880
kstat.unix.kmem_cache.arc_buf_t.slab_free: 0
kstat.unix.kmem_cache.arc_buf_t.buf_constructed: 5
kstat.unix.kmem_cache.arc_buf_t.buf_avail: 6315
kstat.unix.kmem_cache.arc_buf_t.buf_inuse: 1875
kstat.unix.kmem_cache.arc_buf_t.buf_total: 8190
kstat.unix.kmem_cache.arc_buf_t.buf_max: 8190
kstat.unix.kmem_cache.arc_buf_t.slab_create: 1
kstat.unix.kmem_cache.arc_buf_t.slab_destroy: 0
kstat.unix.kmem_cache.arc_buf_t.vmem_source: 15
kstat.unix.kmem_cache.arc_buf_t.hash_size: 0
kstat.unix.kmem_cache.arc_buf_t.hash_lookup_depth: 0
kstat.unix.kmem_cache.arc_buf_t.hash_rescale: 0
kstat.unix.kmem_cache.arc_buf_t.full_magazines: 0
kstat.unix.kmem_cache.arc_buf_t.empty_magazines: 7
kstat.unix.kmem_cache.arc_buf_t.magazine_size: 15
kstat.unix.kmem_cache.arc_buf_t.reap: 0
kstat.unix.kmem_cache.arc_buf_t.defrag: 0
kstat.unix.kmem_cache.arc_buf_t.scan: 0
kstat.unix.kmem_cache.arc_buf_t.move_callbacks: 0
kstat.unix.kmem_cache.arc_buf_t.move_yes: 0
kstat.unix.kmem_cache.arc_buf_t.move_no: 0
kstat.unix.kmem_cache.arc_buf_t.move_later: 0
kstat.unix.kmem_cache.arc_buf_t.move_dont_need: 0
kstat.unix.kmem_cache.arc_buf_t.move_dont_know: 0
kstat.unix.kmem_cache.arc_buf_t.move_hunt_found: 0
kstat.unix.kmem_cache.arc_buf_t.move_slabs_freed: 0
kstat.unix.kmem_cache.arc_buf_t.move_reclaimable: 0
kstat.zfs.misc.arcstats.hits: 26585
kstat.zfs.misc.arcstats.misses: 4054
kstat.zfs.misc.arcstats.demand_data_hits: 8231
kstat.zfs.misc.arcstats.demand_data_misses: 241
kstat.zfs.misc.arcstats.demand_metadata_hits: 18217
kstat.zfs.misc.arcstats.demand_metadata_misses: 3278
kstat.zfs.misc.arcstats.prefetch_data_hits: 18
kstat.zfs.misc.arcstats.prefetch_data_misses: 273
kstat.zfs.misc.arcstats.prefetch_metadata_hits: 119
kstat.zfs.misc.arcstats.prefetch_metadata_misses: 262
kstat.zfs.misc.arcstats.mru_hits: 7979
kstat.zfs.misc.arcstats.mru_ghost_hits: 0
kstat.zfs.misc.arcstats.mfu_hits: 18469
kstat.zfs.misc.arcstats.mfu_ghost_hits: 0
kstat.zfs.misc.arcstats.deleted: 42
kstat.zfs.misc.arcstats.recycle_miss: 0
kstat.zfs.misc.arcstats.mutex_miss: 0
kstat.zfs.misc.arcstats.evict_skip: 4
kstat.zfs.misc.arcstats.evict_l2_cached: 0
kstat.zfs.misc.arcstats.evict_l2_eligible: 434176
kstat.zfs.misc.arcstats.evict_l2_ineligible: 0
kstat.zfs.misc.arcstats.hash_elements: 1874
kstat.zfs.misc.arcstats.hash_elements_max: 1874
kstat.zfs.misc.arcstats.hash_collisions: 2
kstat.zfs.misc.arcstats.hash_chains: 2
kstat.zfs.misc.arcstats.hash_chain_max: 1
kstat.zfs.misc.arcstats.p: 2147483648
kstat.zfs.misc.arcstats.c: 4294967296
kstat.zfs.misc.arcstats.c_min: 536870912
kstat.zfs.misc.arcstats.c_max: 4294967296
kstat.zfs.misc.arcstats.size: 76983096
kstat.zfs.misc.arcstats.hdr_size: 495320
kstat.zfs.misc.arcstats.data_size: 74269184
kstat.zfs.misc.arcstats.metadata_size: 0
kstat.zfs.misc.arcstats.other_size: 2218592
kstat.zfs.misc.arcstats.l2_hits: 0
kstat.zfs.misc.arcstats.l2_misses: 0
kstat.zfs.misc.arcstats.l2_feeds: 0
kstat.zfs.misc.arcstats.l2_rw_clash: 0
kstat.zfs.misc.arcstats.l2_read_bytes: 0
kstat.zfs.misc.arcstats.l2_write_bytes: 0
kstat.zfs.misc.arcstats.l2_writes_sent: 0
kstat.zfs.misc.arcstats.l2_writes_done: 0
kstat.zfs.misc.arcstats.l2_writes_error: 0
kstat.zfs.misc.arcstats.l2_writes_hdr_miss: 0
kstat.zfs.misc.arcstats.l2_evict_lock_retry: 0
kstat.zfs.misc.arcstats.l2_evict_reading: 0
kstat.zfs.misc.arcstats.l2_free_on_write: 0
kstat.zfs.misc.arcstats.l2_abort_lowmem: 0
kstat.zfs.misc.arcstats.l2_cksum_bad: 0
kstat.zfs.misc.arcstats.l2_io_error: 0
kstat.zfs.misc.arcstats.l2_size: 0
kstat.zfs.misc.arcstats.l2_asize: 0
kstat.zfs.misc.arcstats.l2_hdr_size: 0
kstat.zfs.misc.arcstats.l2_compress_successes: 0
kstat.zfs.misc.arcstats.l2_compress_zeros: 0
kstat.zfs.misc.arcstats.l2_compress_failures: 0
kstat.zfs.misc.arcstats.memory_throttle_count: 0
kstat.zfs.misc.arcstats.duplicate_buffers: 0
kstat.zfs.misc.arcstats.duplicate_buffers_size: 0
kstat.zfs.misc.arcstats.duplicate_reads: 0
kstat.zfs.misc.arcstats.arc_meta_used: 2713912
kstat.zfs.misc.arcstats.arc_meta_limit: 1073741824
kstat.zfs.misc.arcstats.arc_meta_max: 2705168
kstat.zfs.misc.arcstats.arc_meta_min: 268435456
kstat.zfs.darwin.tunable.zfs_arc_max: 0
kstat.zfs.darwin.tunable.zfs_arc_min: 0
kstat.zfs.darwin.tunable.zfs_arc_meta_limit: 0
kstat.zfs.darwin.tunable.zfs_arc_meta_min: 0
kstat.zfs.darwin.tunable.zfs_arc_grow_retry: 60
kstat.zfs.darwin.tunable.zfs_arc_shrink_shift: 0
kstat.zfs.darwin.tunable.zfs_arc_p_min_shift: 0
kstat.zfs.darwin.tunable.zfs_arc_average_blocksize: 8192
kstat.zfs.darwin.tunable.l2arc_write_max: 8388608
kstat.zfs.darwin.tunable.l2arc_write_boost: 8388608
kstat.zfs.darwin.tunable.l2arc_headroom: 2
kstat.zfs.darwin.tunable.l2arc_headroom_boost: 200
kstat.zfs.darwin.tunable.l2arc_feed_secs: 1
kstat.zfs.darwin.tunable.l2arc_feed_min_ms: 200
kstat.zfs.darwin.tunable.arc_reduce_dnlc_percent: 3
kstat.zfs.darwin.tunable.arc_lotsfree_percent: 10
kstat.zfs.darwin.tunable.l2arc_noprefetch: 1
kstat.zfs.darwin.tunable.l2arc_feed_again: 1
kstat.zfs.darwin.tunable.l2arc_norw: 1

I don't want to use the 4GB it's set to by default. Would like to lower it.

Don't have the time to produce a panic with symbols atm. Will do later if needed

**Comment by h0lzi** [comment]
now with symbols:

Tue Dec 15 12:28:46 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff8004dd155a): Kernel trap at 0xffffff7f85484dd1, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x00007fff5ca8cba8, CR3: 0x000000032b9fb0f2, CR4: 0x00000000003627e0
RAX: 0x0000000000000000, RBX: 0x0000000000000000, RCX: 0x00007fff5ca8cba8, RDX: 0x0000000000000000
RSP: 0xffffff91ff57bd70, RBP: 0xffffff91ff57bda0, RSI: 0x0000000000000000, RDI: 0xffffff8029bc7600
R8:  0xffffff91ff57bb70, R9:  0x0000000000000999, R10: 0x0000000000000000, R11: 0x0000000000000206
R12: 0xffffff91ff57beb0, R13: 0xffffff8029bc7600, R14: 0x0000000000000000, R15: 0xffffff7f855d0180
RFL: 0x0000000000010246, RIP: 0xffffff7f85484dd1, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007fff5ca8cba8, Error code: 0x0000000000000001, Fault CPU: 0x0 SMAP fault, PL: 0

Backtrace (CPU 0), Frame : Return Address
0xffffff91ff57ba00 : 0xffffff8004cde792 mach_kernel : _panic + 0xe2
0xffffff91ff57ba80 : 0xffffff8004dd155a mach_kernel : _kernel_trap + 0x91a
0xffffff91ff57bc60 : 0xffffff8004def233 mach_kernel : _return_from_trap + 0xe3
0xffffff91ff57bc80 : 0xffffff7f85484dd1 net.lundman.spl : _kstat_handle_ui64 + 0x64
0xffffff91ff57bda0 : 0xffffff80051bbe94 mach_kernel : _kernel_sysctlbyname + 0x684
0xffffff91ff57be30 : 0xffffff80051bb421 mach_kernel : _sysctl + 0x1d1
0xffffff91ff57bf60 : 0xffffff8005229ac1 mach_kernel : _unix_syscall64 + 0x251
0xffffff91ff57bfb0 : 0xffffff8004defa36 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         net.lundman.spl(1.4.5)[78831EE7-94AF-3E2D-B63A-612BA6ED8B5C]@0xffffff7f8547c000->0xffffff7f854b2fff

BSD process name corresponding to current thread: sysctl
Boot args: keepsyms=y debug=0x144

Mac OS version:
15C50

Tried diffrend sizes. Even close to kstat.zfs.misc.arcstats.c_max: 4294967296
doesn't help.

**Comment by lundman** [comment]
As it is a SMAP fault, we should be using copyin()
https://github.com/openzfsonosx/spl/commit/afbfeec29406ed59eabb1194a367b16b57c6b8ee

Hopefully this will work.

**Comment by h0lzi** [comment]
that fixed that problem. Hope there is not much SMAP faults left :)
