### ISSUE TITLE
Decide on arc settings and fix the math

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#460]
As discussed with @ilovezfs , current arc settings can get quite ridiculous and should in my opinion be reverted to the previous behavior.

**Comment by rottegift** [comment]
Are you totally opposed to putting a line like

```
kstat.zfs.darwin.tunable.zfs_arc_max=3221225472
```
in your /etc/zfs/zsysctl.conf if the default calculation stays as it is ?

There is a substantial potential random I/O performance penalty for having a small ARC, and the ARC gets out of the way of user memory allocations.

What exactly justifies your use of the harsh word "ridiculous" ?

**Comment by ilovezfs** [comment]
@rottegift Would you be in favor of reverting https://github.com/openzfsonosx/zfs/commit/ae79d84688ffcb77fcc18ad77c7f1eb71e179b8d

If not, why not?

**Comment by rottegift** [comment]
Split the difference, set to 3/4 of allmem or allmem minus 3GiB, whichever is more.

Why not is simple: a small arc on a system with ample free memory is wasteful of unused resources with the direct consequence of more I/O both on reads *and* writes.    The latter directly leads to shortened media lifetimes on some devices.

If you have an argument that goes beyond the aesthetics of the Activity Monitor display or the like, perhaps you would care to share it ?

Note: for free, as always, I'll give you the special case of VMWare Fusion in the limit of a large-memory virtual machine starting up after ARC has heated up.     And as always, there's several workarounds that do not have to be compiled in and do not have to affect machines where VMWare Fusion is not going to be run at all.

**Comment by ilovezfs** [comment]
>Why not is simple
Reverting the commit would raise not lower.

**Comment by JMoVS** [comment]
@rottegift I'm sorry, I didn't mean to have a harsh word as ridicoulous (I'm not a native speaker and to me it isn't that harsh, sry). I was just wondering as my system recently did a little bit of swapping and I didn't have that before. But if what activity monitor is displaying inaccurate things, I am porbably mistaken here. Sorry for the confusion

**Comment by rottegift** [comment]
I know it would raise.   I'm fine with a complete revert.   I'm also fine with a split-the-difference new commit (keep 3GiB limit, revert 1/4 RAM limit).   The marginal impact on a machine where the allmem - 3GiB > 3/4 RAM will be small.

**Comment by rottegift** [comment]
@JMoVS : Ok.   Can you please quantify "swapping"?   If there's an actual bug here, it would be nice to fix it, rather than hide it.

**Comment by JMoVS** [comment]
@rottegift I will try to verify it first whether it only happens on long uptimes (15 days right now), but it has so far been almost always sth like 170 MB. Around that value. But let me try a reboot and see how it evolves over time. 

Was just comparing this to previous times where my system never swapped (I have 8GB at this laptop). But as said, want to confirm it first and will report back. Sorry again!

**Comment by ilovezfs** [comment]
@rottegift
>"If you have an argument that goes beyond the aesthetics of the Activity Monitor display or the like, perhaps you would care to share it?"

What was the point of that statement if you understood that reverting it would raise not lower?

**Comment by rottegift** [comment]
It was a misreading of the code in the diff, soz.

```
	if (allmem >= 1 << 30)
		arc_c_max = allmem - (3 << 30);
	else
		arc_c_max = arc_c_min;
	arc_c_max = MAX(allmem * 1 / 4, arc_c_max);
```

Setting arc_c_max twice is confusing.

**Comment by ilovezfs** [comment]
@rottegift You're forgiven.

Of course, I'm not looking forward to explaining to owners of 32 G machines why their setting went from 4  G to 31 G, but I don't think they're going to "feel" any better about 29 G. Oh wait, I take that back. It does start with a numeral "2" instead of a "3," so that should be more pleasing to the untrained eye.

**Comment by rottegift** [comment]
allmem is already deflated in spl-osx.c:

```
    real_total_memory = total_memory;
        total_memory = total_memory * 80ULL / 100ULL;
    physmem = total_memory / PAGE_SIZE;
```

**Comment by rottegift** [comment]
(as in arc.c we have "        uint64_t allmem = physmem * PAGESIZE;");

**Comment by rottegift** [comment]
kmem can't allocate more than physmem, therefore no user should see arc get above 80% of their system memory, unless there's a bug somewhere, even if you push arc_c_max way higher than that.

**Comment by rottegift** [comment]
Also, as we approach 90% of that 80% figure, we start telling ARC to stop growing and that memory is running short [spl_minimal_physmem_p_logic() in spl-kmem.c and spl_free_thread() below the comment that contains "leave slop".    

So, having actually thought about this, in principle there's no reason why we shouldn't set arc_c_max to physmem * PAGE_SIZE, which will be 80% of system memory, and I prefer that to just a revert of the commit.

**Comment by ilovezfs** [comment]
@rottegift @lundman side note: the current code is wrong <code>if (allmem >= 1 << 30)</code> should be <code>if (allmem >= 3 << 30)</code> assuming no other changes.

**Comment by ilovezfs** [comment]
@rottegift @lundman Oh boy, not good. The 1 or 3 or whatever we choose needs to be 1ULL or 3ULL or whateverULL:
```
1/19/16 9:25:30.000 AM kernel[0]: allmem - (3 << 30) : 0x373333000 : 14817636352
1/19/16 9:25:30.000 AM kernel[0]: allmem - (3ULL << 30) : 0x273333000 : 10522669056
```
Why doesn't this affect illumos? Clever define somewhere? compiler? something else?

We should either adopt their strategy or make sure all instances of missing ULLs following the arc.c replacement are found and fixed.

Our old code was correct but was "forgotten" after the switch to 25%.
https://github.com/openzfsonosx/zfs/commit/d30ef37ca3f296ffb77efb40d4d83511662aa59f
https://github.com/openzfsonosx/zfs/commit/c095c10ba04fc7af2e8972b6180b4030300b3359

Then when the illumos arc.c replaced ours it came in with the bug:
https://github.com/openzfsonosx/zfs/blob/7bc9d884e6014d442b0d17e3c013b398aaf468bb/module/zfs/arc.c#L5183-L5184

**Comment by ilovezfs** [comment]
https://github.com/openzfsonosx/zfs/commit/d55bf43e67f9b789e82aadd9f545dc44567b549d
https://github.com/openzfsonosx/zfs/commit/7e8d2cd39b2dd0d89a28e34fda37b587562cc692
https://github.com/openzfsonosx/zfs/commit/e90a0f0b755a64e7749482c30f0efeaba8dc517b
