### ISSUE TITLE
kernel.development and kernel.debug panic in vm_page_insert_internal 

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#461]
@brendonhumphrey @lundman 
```
assert(!VM_PAGE_WIRED(mem) || mem->private || mem->fictitious || (tag != VM_KERN_MEMORY_NONE));
```
Stack:
http://i.imgur.com/unssqPm.png

A development or debug kernel is required to use the hide_kernel_pointers sysctl, which is now needed since -show_pointers has been restricted to Apple Internal as of 10.11.2, so it would be good if O3X did not panic simply because OS X is running kernel.development.

**Comment by ilovezfs** [comment]
OK, as a workaround, the panic can be avoided by using assertions=0 in the nvram boot-args:
```
nvram boot-args='-v kcsuffix=development assertions=0 keepsyms=1 debug=0x144'
```
The hide_kernel_pointers sysctl is then registered and defaults to 0, so the pointers show up. Setting the sysctl to 1, they revert to <ptr> as you'd expect.

Alternatively, CSR can be disabled entirely by setting <code>csr-active-config=ff%00%00%00</code>. For a VM this can be achieved by booting to the Recovery partition, running <code>csrutil clear</code> to delete the <code>csr-active-config</code> variable entirely and <code>nvram Xsr-active-config=ff%00%00%00</code>. Then shutdown the VM, and use a hex editor to change X -> c in the nvram file. This will allow the <code>-show_pointers</code> boot-arg to work.

The same can apparently be achieved on bare metal using a Mavericks recovery partition to directly set <code>csr-active-config</code>. On new hardware that can only run >= 10.11, it may be possible to use an alternate boot loader either to set <code>csr-active-config=ff%00%00%00</code> or to include <code>kBootArgsFlagCSRActiveConfig + kBootArgsFlagCSRBoot</code> in the boot flags. Also, it may be possible to set csr-active-config in efivars from Linux in some way that hopefully doesn't corrupt your firmware.

Yet another option would be to compile a custom xnu, but that will probably break some things in the GUI.

**Comment by lundman** [comment]
a37c79bebb9274489d0a691229ec481d705666f3
