### ISSUE TITLE
Mail.app shows 11 unread messages although no unread messages present

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#465]
My Mails live in a zfs dataset and Mail displays there are "11" unread messages (in the sidebar) in my archive although there clearly aren't. When I click on the archive, the 11 vanishes. 

My guess is that it's related to ZFS because it started happening along some update to my zfs in the past (but I don't remember the specific HEAD when that started appearing). I tried mdutil -E, excluding it from indexing and reincluding it and I also tried marking all 30.000 email messages first as unread and then as read again.

It is also only ever 11 messages unread (plus some that really are unread.) But in general, it's 11 messages.

**Comment by emory** [comment]
Try Menu > Mailbox > Rebuild. I've had this happen before (on HFS+, mind you) and rebuilding the mailbox in Mail.app ameliorates.

**Comment by ilovezfs** [comment]
Is this still happening or can we close it out?

**Comment by JMoVS** [comment]
I haven't tested with latest master. So currently I don't know.

**Comment by JMoVS** [comment]
tested with 1.5.2 tagges master, still appearing.

**Comment by ilovezfs** [comment]
@JMoVS Did you try emory's suggestion?

**Comment by JMoVS** [comment]
I tried rebuilding, not with the tagged version but with master from like 28 days ago. But I highly doubt it helps with the problem. It seems to be that only if I get new email and/or have email in my GMail in my inbox, it sometime striggers the display of 11 unread messages for my archive (the one that subsumes all the different archive folders under itself) folder

**Comment by ilovezfs** [comment]
If you move the entire thing to HFS, does it go away?

**Comment by JMoVS** [comment]
that involves me fighting with mail.app (getting on 10.11.x was hard) so I'll probably try a rebuild first before moving it around.

**Comment by JMoVS** [comment]
Well, classic instance of _causation<=>correlation_

Some stupid app requested OTR with others on hangouts, which then show up in the inbox, but never in Mail.app... And as I'm never in the google web interface, I didn't notice.

Now I go into th corner of shame. Thanks everyone nevertheless!
