### ISSUE TITLE
Occasional unmount failures

### ISSUE THREAD

**Issue by lundman** [openzfsonosx/zfs#47]
ZFS can at time fail to unmount the file system, usually after a little usage.

It gets stuck in this part of dnode.c

```
dnode_special_close(dnode_handle_t *dnh)
{
    /*
     * Wait for final references to the dnode to clear.  This can
     * only happen if the arc is asyncronously evicting state that
     * has a hold on this dnode while we are trying to evict this
     * dnode.
     */
    while (refcount_count(&dn->dn_holds) > 0) {
        delay(hz);
        if (count++ > 9) {
            printf("dnode: ARC release bug triggered: %p (%lld)-- sorry\n", dn,
                   refcount_count(&dn->dn_holds));
```

For some reason the refcount is always 9.

**Comment by ilovezfs** [comment]
https://github.com/openzfsonosx/zfs/commit/89eaaafa0ebcd8eb8e6c1015b54407bfe42a1ce5 is not related to this issue.

**Comment by JMoVS** [comment]
Nowadays it seems like unmounts usually work but for some cases where I notices races with datasets mounted inside other dataset's mountpoints. But unmounting works usually even after some data transfer, therefore closing this issue.
