### ISSUE TITLE
[Question] Removing device from non-redundant zpool

### ISSUE THREAD

**Issue by ratson** [openzfsonosx/zfs#474]
I am certainly not [the first one](https://groups.google.com/forum/#!topic/comp.unix.solaris/0ED1Xi1jnOg) having this question, I am wondering if there is any changes since 2008.

If not, is there any issue tracking about this? Apparently, [it is doable with some limitation](https://rudd-o.com/linux-and-free-software/delphix-zfs-based-on-open-zfs-now-supports-device-removal), and it is good enough for my user case.

Thanks.

p.s. I know this may not be the best place, but I have no idea where I should post this kind of question.

**Comment by ilovezfs** [comment]
@ratson The most current discussion of the topic is this thread: https://www.listbox.com/member/archive/274414/2016/03/sort/time_rev/page/6/entry/14:142/20160302123137:9B872F62-E09C-11E5-BB67-227AF010038B/

Feel free to join that mailing list.

**Comment by ratson** [comment]
Awesome, good to know that it is still on the radar. Joined the mailing list :)

**Comment by ilovezfs** [comment]
@ratson cool. Don't be shy to share your thoughts on that thread.
