### ISSUE TITLE
Potential issue with destroy

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#477]
I've noticed that many tests are failing in an inconsistent manner - typically there is a sequence where a pool created and destroyed on the same device either repeatedly in a loop, or just in the normal progression of the tests where the create immediately follows the destroy.

The defect is that zpool create occasionally fails to open the device because it is busy (EBUSY).

Putting sleeps after destroys in the tests tends to eliminate this issue, but thats a workaround - there is no indication in the illumos tests that the destroy operation is anything by atomic i.e. one can create on return from the destroy.

**Comment by brendonhumphrey** [comment]
By way of example, the following script reliably runs to completion on freebsd, but fails within a few ~10 iterations on O3X. Obviously substituted a valid device name in the freebsd version. Both running in a vm on the same host.

#!/bin/csh

foreach i (`seq 1 1 100`)
echo $i
sudo zpool create tank disk3
sudo zpool destroy tank
end

**Comment by brendonhumphrey** [comment]
2080d0fe42b05c5472d4feda661f27a9fd4b7b27

**Comment by brendonhumphrey** [comment]
merge if change is acceptable!

**Comment by ilovezfs** [comment]
:8ball:

**Comment by brendonhumphrey** [comment]
yeah dont merge this, it kills the tests.

**Comment by brendonhumphrey** [comment]
All ok now. 

Results Summary
FAIL	 117
SKIP	  23
KILLED	   1
PASS	 580

Running Time:	02:42:40
Percent passed:	80.4%
Log directory:	/var/tmp/test_results/20160520T022637
