### ISSUE TITLE
defer_destroy property of snapshots is not working correctly

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#484]
running:

spl.kext_version: 1.5.0-15_ge755917
zfs.kext_version: 1.5.0-104_gc326176

zpool create tank disk1
zfs snapshot tank@1
zfs get all tank@1

does not list the defer_destroy property

zfs get defer_destroy tank@1

does not yield on or off

However, zfs destroy -d tank@1 in the presence of a clone does work.

this is the cause of multiple failures in the zfs_destroy tests.

**Comment by ilovezfs** [comment]
@lundman @brendonhumphrey e38742cbf369c21fd07e9b17d148275cdf997f56 fixes the bug, or we could cherry-pick zfsonlinux/zfs@962d524 and
zfsonlinux/zfs@09c0b8f (https://github.com/zfsonlinux/zfs/pull/2265) back in.

**Comment by brendonhumphrey** [comment]
Test: /Users/zfs-tests/Developer/zfs-test/test/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_010_pos (run as root) [00:06] [PASS]
Test: /Users/zfs-tests/Developer/zfs-test/test/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_011_pos (run as root) [00:04] [PASS]
Test: /Users/zfs-tests/Developer/zfs-test/test/zfs-tests/tests/functional/cli_root/zfs_destroy/zfs_destroy_012_pos (run as root) [00:04] [PASS]

good stuff.
