### ISSUE TITLE
zpool create invalid return code

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#490]
zpool_create_023_neg.sh verifies correct response to a range of incorrect zpool create commands.
One test case is:
zpool create -O recordsize=2M d1 d2 d3
fails because it exits with an on status on O3X, possibly aborting:

O3X: 
sudo zpool create -O recordsize=2M -f testpool.10710 /dev/disk1 /dev/disk2 /dev/disk3
internal error: Numerical argument out of domain
big-vm-mac-imac:dev zfs-tests$ echo $?
134

FreeBSD:
zpool create -O recordsize=2M da1 da2 da3
cannot create 'da1': record size invalid
root@free10:~ # echo $?
1

**Comment by lundman** [comment]
@behlendorf I noticed that the ZOL port has EDOM return code in `zfs_ioctl.c` for RECORDSIZE, but your `libzfs_pool.c` handler checks ERANGE.

**Comment by behlendorf** [comment]
@lundman thanks for noticing this, it looks like it's because we haven't yet picked up https://github.com/illumos/illumos-gate/commit/6de9bb5 which makes this fix.
