### ISSUE TITLE
MMAP_EXEC not honoured when zfs set exec=off

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#494]
Running:
spl.kext_version: 1.5.2-1
zfs.kext_version: 1.5.2-2_g9a08d98

Test Failed:
exec_002_neg.ksh

Reason:

	if (mmap(0, statbuf.st_size,
	    PROT_EXEC, MAP_SHARED, fd, 0) == MAP_FAILED) {
		perror("mmap");
		return (errno);
	}

The mmap should fail.

**Comment by lundman** [comment]
OK so mount filesystem with MNT_NOEXEC, and call `mmap( , PROT_EXEC)` should fail. It appears that this should be handled by XNU's vfs layer for us, but in an attempt to work around it, if we add a test to `zfs_vnop_mmap()` to return `EPERM` (The only error code not ignored, as shown in bsd/kern/ubc_subr.c `ubc_mmap`)


```
	if ((ap->a_fflags & PROT_EXEC) &&
		vfs_flags(zfsvfs->z_vfs) | MNT_NOEXEC) {
		dprintf("ZFS: exec=off and mmap(PROT_EXEC) - denied\n");
		ZFS_EXIT(zfsvfs);
		return (EPERM);
	}
```

results in panic:

```
panic(cpu 1 caller 0xffffff800188472e): /Library/Caches/com.apple.xbs/Sources/xnu/xnu-3248.30.4/osfmk/vm/vm_map.c:2730 Assertion failed: kr == KERN_SUCCESS
Backtrace (CPU 1), Frame : Return Address
0xffffff8c8003b950 : 0xffffff8001884837 mach_kernel : _panic + 0xe7
0xffffff8c8003b9d0 : 0xffffff800188472e mach_kernel : _Assert + 0x3e
0xffffff8c8003b9f0 : 0xffffff800190cde1 mach_kernel : _vm_map_enter + 0x2271
```

and as `VNOP_MMAP` is listed as **VNOP_MMAP is an advisory calldown to say that the system is mmap-ing a file.** there isn't much we can do here.

Testing this behaviour on hfs has the same result.

```
/dev/disk2s1 on /Volumes/hfs (hfs, local, noexec, journaled)
bash-3.2# ~/mmap_exec /Volumes/hfs/test
bash-3.2# echo $?
0
```

It would appear it is up to APPLE to support this case, as there appears to be nothing we can do.

**Comment by brendonhumphrey** [comment]
Disabled non-compatible with OSX test 404de1a9f8d83609ee1021a308a954c5093c36db
