### ISSUE TITLE
Panic on most recent build

### ISSUE THREAD

**Issue by ylluminate** [openzfsonosx/zfs#495]
I'm running OS X 10.11.5 (build 15F31a).  I thought I'd install the 1.5.2 pkg to see how that went and unfortunately experienced a panic right off the bat.  The kexts seem to load, but then the panic occurrs roughly a minute after.

I resorted to uninstalling via the `uninstall_complete.sh` script found in the `Docs & Scripts` folder and then built from source via `zfsadm` as I have in the past (but hadn't built for some months).  After doing this and installing it as per standard documentation on this, about a minute passed and boom, panic again.

Here is the redacted screenshot (I removed a lot of cruft from the build process that made it hard to read the panic output):
![Image of Panic](http://f.cl.ly/items/3G1d273Z3z3l0D0Z0m1M/IMG_0163.jpg)

**Comment by ilovezfs** [comment]
And if you revert to 1.4.5 it goes away?

**Comment by ilovezfs** [comment]
@ylluminate did this go away?

**Comment by ylluminate** [comment]
I've not had this with most of my volumes, but I have one more volume that is likely the culprit due to hardware failure.  I have yet to test it out in the VM as we discussed due to pressing projects.  I'll close this for now and then get back to it.
