### ISSUE TITLE
long history has extra decoration

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#496]
Running:
spl.kext_version: 1.5.2-1
zfs.kext_version: 1.5.2-2_g9a08d98

Test Failed:
history_010_pos.ksh

Consistent with ZoL, but not consistent with FreeBSD and tests we appear to be decorating the hostname portion of the long history data with the OS identity.

sudo zpool history -l tank
History for 'tank':
2016-05-06.15:33:31 zpool create tank disk1 [user 0 (root) on big-vm-mac-imac:OSX]

**Comment by ilovezfs** [comment]
Did ZoL adapt their test?

That extra decoration seems yucky.

**Comment by brendonhumphrey** [comment]
Our tests are based on a snapshot of the ZoL tests, so at least at that time, no.

**Comment by brendonhumphrey** [comment]
Looks like this might be the Zone name from spa_history_zone.
static char *
spa_history_zone(void)
{
#ifdef _KERNEL
#ifdef HAVE_SPL
	return ("OSX");
#else
	return (curproc->p_zone->zone_name);
#endif
#else
	return (NULL);
#endif
}

**Comment by brendonhumphrey** [comment]
088fc8013078011919df53fa1dce656181aa315b
