### ISSUE TITLE
zdb issue with child dataset

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#497]
Running:
spl.kext_version: 1.5.2-1
zfs.kext_version: 1.5.2-2_g9a08d98

Test Failed:
mmap_read_001_pos

zdb -cudi behavior is inconsistent with tests and FreeBSD.

OSX:

sudo zfs create tank/testfs
big-vm-mac-imac:zfs-test zfs-tests$ sudo zdb -cudi tank/testfs
zdb: can't open 'tank/testfs': No such file or directory

FreeBSD:
root@free10:~ # zpool create tank da1
root@free10:~ # zfs create tank/testfs
root@free10:~ # zdb -cudi tank/testfs
Dataset tank/testfs [ZPL], ID 41, cr_txg 6, 19.0K, 7 objects

**Comment by ilovezfs** [comment]
This is what happens when your cache file is missing.

```
Josephs-MacBook-Pro:~ joe$ sudo zdb -cudi internal/vms
Dataset internal/vms [ZPL], ID 42, cr_txg 40, 76.7G, 268 objects

    ZIL header: claim_txg 0, claim_blk_seq 0, claim_lr_seq 0 replay_seq 0, flags 0x0
Josephs-MacBook-Pro:~ joe$ sudo mv /etc/zfs/zpool.cache{,.foo}
Josephs-MacBook-Pro:~ joe$ sudo zdb
cannot open '/etc/zfs/zpool.cache': No such file or directory
Josephs-MacBook-Pro:~ joe$ sudo zdb -cudi internal/vms
zdb: can't open 'internal/vms': No such file or directory

```

What happened to the cache file? Is zed not running?

**Comment by brendonhumphrey** [comment]
For the moment, this has become non-reproducable. I will investigate further in a bit.
