### ISSUE TITLE
rsend tests are all broken

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#499]
Running:
spl.kext_version: 1.5.2-1
zfs.kext_version: 1.5.2-2_g9a08d98

Test Failed:
rsend_*

No idea what is going on, log fragment from 1st rsend test below. I dont think its a porting issue at this stage.

ASSERTION: zfs send -R send replication stream up to the named snap.
SUCCESS: eval /usr/local/bin/zfs send -R testpool.9914@final > /var/tmp/backdir-rsend/pool-final-R
Unmount successful for /testpool1.9914
Mount successful
ERROR: eval /usr/local/bin/zfs receive -d -F testpool1.9914 < /var/tmp/backdir-rsend/pool-final-R exited 1
Running process: '/usr/sbin/diskutil' 'unmount' '/testpool1.9914' 
 cannot receive incremental stream: dataset is busy
NOTE: Performing local cleanup via log_onexit (cleanu

**Comment by lundman** [comment]
Hmm I need to check more thoroughly how it creates the test pool, but setup.ksh seems to imply the receiving pool is empty `testpool1`

```
bash-3.2# ./cmd.sh zfs recv -vd -F DOOM < sendtest.bin
Running process: '/usr/sbin/diskutil' 'unmount' '/Volumes/DOOM'
Unmount successful for /Volumes/DOOM
receiving full stream of BOOM@today into DOOM@today
Mount successful
received 33.7MB stream in 1 seconds (33.7MB/sec)
receiving full stream of BOOM/two@today into DOOM/two@today
received 42.7MB stream in 1 seconds (42.7MB/sec)
Mount successful
```

Since it doesn't unmount due to being busy there could be a race there, assuming its not just spotlight in the way.

**Comment by brendonhumphrey** [comment]
Disabled spotlight for scope of the rsend tests, no change.

**Comment by rottegift** [comment]
"cannot receive incremental stream: dataset is busy"

What happens if you use the zfs recv -u (don't mount) option in these tests, and mount manually after the full replication stream has been received?

**Comment by lundman** [comment]
https://github.com/openzfsonosx/zfs-test/commit/1ef6af04fc34e2ca3db746344223d998d9e580a2

**Comment by brendonhumphrey** [comment]
looks good-ish, 8 and 9 are still failing, look like unique bugs.
