### ISSUE TITLE
1.5.x does not work on machines with 128GB of RAM

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#500]
Apparently the prereleleases didn't either. Works fine on same machine with 64GB installed. The 1.4.x series work fine in the 128G configuration.

https://openzfsonosx.org/forum/viewtopic.php?f=26&t=2798&p=6997#p6997

**Comment by lundman** [comment]
Please show the output of `sysctl hw.memsize` when booted 128GB RAM.

**Comment by lundman** [comment]
a0c6288cbee425f1f7788696d139202af60b6c27
