### ISSUE TITLE
Installer displays error message at the end

### ISSUE THREAD

**Issue by saerdnaer** [openzfsonosx/zfs#504]
OS X 10.11.3

<img width="732" alt="tmp" src="https://cloud.githubusercontent.com/assets/40266/15243800/36e00cf6-18fe-11e6-96d9-c423ee71279d.png">

**Comment by ilovezfs** [comment]
upgrade to 10.11.4 and it will go away

**Comment by saerdnaer** [comment]
Confirmed. Thanks for your help.

**Comment by ilovezfs** [comment]
@saerdnaer Great, and you're welcome. Sorry for the inconvenience. Apple changed the kext signing in a backwards incompatible way, so I'll need to sign 1.5.3 with OS X 10.11.3 to skirt the issue. *sighs*
