### ISSUE TITLE
Spotlight Privacy setting not respected

### ISSUE THREAD

**Issue by fumoboy007** [openzfsonosx/zfs#508]
I added some folders in my ZFS file system to the Spotlight Privacy list. They are still being searched. 😕

OS X El Capitan
O3X 1.5.2 and 1.4.5 (dunno about older versions)

**Comment by brendonhumphrey** [comment]
I dunno

 sudo zpool status
no pools available
big-vm-mac-imac:test_results zfs-tests$ sudo zpool create tank disk0
big-vm-mac-imac:test_results zfs-tests$ sudo mkdir /Volumes/tank/brendon
big-vm-mac-imac:test_results zfs-tests$ sudo chown zfs-tests:staff /Volumes/tank/brendon
big-vm-mac-imac:test_results zfs-tests$ cd /Volumes/tank/brendon/

Blocked indexing of /Volumes/tank/brendon using GUI.

big-vm-mac-imac:brendon zfs-tests$ echo "smith" > it
big-vm-mac-imac:brendon zfs-tests$ mdfind it

Unblocked using GUI

echo "jones" > it2
big-vm-mac-imac:brendon zfs-tests$ mdfind jones
/Volumes/tank/brendon/it2


Cheers
Brendon

**Comment by brendonhumphrey** [comment]
oops,

Just in case you noticed to typo below in the first mdfind…

With the privacy list set:

big-vm-mac-imac:brendon zfs-tests$ pwd
/Volumes/tank/brendon
big-vm-mac-imac:brendon zfs-tests$ echo "peter" > it3
big-vm-mac-imac:brendon zfs-tests$ mdfind peter
…

Cheers
Brendon

**Comment by fumoboy007** [comment]
Re-indexing seems to have fixed it.
