### ISSUE TITLE
flock: command not found - and checksum errors

### ISSUE THREAD

**Issue by talios** [openzfsonosx/zfs#510]
Hey all,

I'm relatively new to openzfs for osz ( and zfs in general ) but already since setting it up am in love - kudos!

Anyway, every so often I see the odd checksum error appear on my drives ( brand new baracudas ) but if I reboot the checksum errors all go away, I see this when I run `zpool status` on my pool:

```
    NAME                                          STATE     READ WRITE CKSUM
    orico                                         ONLINE       0     0     0
      media-B4A7A707-023F-9D44-B31B-8BECDC1B1CAA  ONLINE       0     0     0
      media-B3892C7B-DF73-4041-99FF-44514FAA3807  ONLINE       0     0     2
      media-40E96DD8-6737-C44F-BB34-23BEE12505A7  ONLINE       0     0     1

errors: No known data errors
```

When looking in `Console.app` for some other things, I happened upon the following log entry:

```
27/05/16 7:21:46.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 358479460 increased above 352216676 old_to_free (delta: 6262784)
27/05/16 7:26:47.919 PM zed[9870]: error: checksum-notify.sh: eid=14: failed to lock "/var/run/zed.zedlet.state.lock": /etc/zfs/zed.d/zed-functions.sh: line 128: flock: command not found
27/05/16 7:26:47.977 PM zed[9883]: error: checksum-notify.sh: eid=14: failed to unlock "/var/run/zed.zedlet.state.lock": /etc/zfs/zed.d/zed-functions.sh: line 166: flock: command not found
```

What is `flock` here, and should it have been installed by OpenZFS ( 1.5.2 ), and are my checksum errors merely a result of this `checksum-notify.sh` throwing an error?

Are these checksum errors _actual_ errors, or more errors in OpenZFS?

**Comment by lundman** [comment]
The zedlets (zed's scripts) are from Linux and have not all been ported, in this case, they try to run a Linux specific program `flock`. This script it run because you had CKSUM error, rather than the cause.

In this case, you can ignore the flock problem, we'll get to making the zedlets more OSX-y eventually. But you are left with the question as to why you get CKSUM errors..

**Comment by talios** [comment]
Is there anyway to tell _which_ files would be involved in those errors? The zpool is 3 4gb drives inside a [Orico 5bay USB enclosure](http://www.amazon.com/ORICO-9558RU3-Aluminum-Enclosure-Case-Black/dp/B011I61Q98) - so not sure there could be anything related there.  The only logs I see in Console.app from zfs are:

```
27/05/16 8:18:38.000 PM kernel[0]: ZFS: arc_reclaim_thread, (old_)to_free has returned to zero from 356771428
27/05/16 8:18:49.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 283391588 increased above 0 old_to_free (delta: 283391588)
27/05/16 8:18:50.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 288396900 increased above 283391588 old_to_free (delta: 5005312)
27/05/16 8:18:52.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 293168740 increased above 288396900 old_to_free (delta: 4771840)
27/05/16 8:18:53.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 308414052 increased above 293168740 old_to_free (delta: 15245312)
27/05/16 8:18:54.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 313534052 increased above 308414052 old_to_free (delta: 5120000)
27/05/16 8:18:55.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 319940196 increased above 313534052 old_to_free (delta: 6406144)
27/05/16 8:18:55.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 324585060 increased above 319940196 old_to_free (delta: 4644864)
27/05/16 8:18:57.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 333637220 increased above 324585060 old_to_free (delta: 9052160)
27/05/16 8:18:59.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 337303140 increased above 333637220 old_to_free (delta: 3665920)
27/05/16 8:19:17.000 PM kernel[0]: ZFS: arc_reclaim_thread, to_free == 351303268 increased above 337303140 old_to_free (delta: 14000128)
```

**Comment by lundman** [comment]
I believe `zpool status -v` is supposed to show you affected files, if it can

**Comment by talios** [comment]
The full output was:

```
 ~  zpool status -v
  pool: orico
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
	attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
	using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: none requested
config:

	NAME                                          STATE     READ WRITE CKSUM
	orico                                         ONLINE       0     0     0
	  media-B4A7A707-023F-9D44-B31B-8BECDC1B1CAA  ONLINE       0     0     0
	  media-B3892C7B-DF73-4041-99FF-44514FAA3807  ONLINE       0     0     2
	  media-40E96DD8-6737-C44F-BB34-23BEE12505A7  ONLINE       0     0     1

errors: No known data errors
```

Would it be worth doing a scrub of the zpool?

I am also noticing iTunes occasionally just stalling for 2-3 seconds occasionally ( the activity lights on the drives are blinking heavily and I'm currently in swap, so that might just be iTunes being... iTunes - time to reboot I think ).

**Comment by talios** [comment]
So the heavy disk activity and iTunes hanging was actually me copying 19gb of data to the zpool that I forgot I'd started ;p

**Comment by brendonhumphrey** [comment]
Pool orico has no redundancy?

**Comment by talios** [comment]
The top level pool hasn't, I have two additional pools inside it ( Music and Photos ) which has `copies` set to 2. But that's the only redundancy ( other than Crashplan backups, but I guess you'll be meaning just zfs related ).

scrub slowly slowly running now.

**Comment by talios** [comment]
I understand zpools can be do more proper redundancy/mirroring/raid stuff, but I've not investigated that side of ZFS yet. Just using the `copies` seemed to provide what I was wanting, but maybe I should look at that.

**Comment by brendonhumphrey** [comment]
For sure! A pool redundancy can [often] recover from damage cause by checksum errors.

However, it seems to me that you need to investigate the cause of the scum errors - bad drives, cables, controller etc

Cheers
Brendon
