### ISSUE TITLE
Uninstallation Script Requires Updated Location

### ISSUE THREAD

**Issue by Haravikk** [openzfsonosx/zfs#518]
So I wanted to uninstall OpenZFS to debug an issue I'm having but it looks like the `uninstall-openzfsonesx.sh` script requires an update for El Capitan as zpool and other binaries aren't installed into the expected `/usr/sbin` location anymore, but into `/usr/local/bin` instead.

**Comment by ilovezfs** [comment]
use uninstall all.

**Comment by Haravikk** [comment]
Oh I managed to uninstall it, I just wanted to point out that the problem.

**Comment by ilovezfs** [comment]
Thanks
