### ISSUE TITLE
scrub status should reflect current total allocated space, not amount from when started

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#520]
I have a pool which had roughly 1 TB of data on it and started a scrub. I then deleted 390 GB of datasets. `zpool list` correctly shows 700G as "allocated" space. 

Now I would expect running `zpool status` to reflect these 300GB and therefore show "x G scanne out of 700G" but it instead, even after pool export->import and after complete zfs/spl rebuild/reload still the original 1,07TB as total space.

**Comment by ilovezfs** [comment]
That sounds normal to me. That statistics are probably recorded at the beginning of scrub as they should be. If you run a fresh scan does it then show the values you're expecting to see?

**Comment by JMoVS** [comment]
well, it is now at a point in the scrub where it *shouldn*t, according to zpool list, have any data to scan. I have 702 GB on the pool right now and it is at "scanned 730 GB of 1.07T", so I don't know what it's doing but it is in itself consistent at least
