### ISSUE TITLE
uninstall-openzfsonosx.sh

### ISSUE THREAD

**Issue by churnd** [openzfsonosx/zfs#523]
When I run this, I get:

```
$ /Volumes/OpenZFS*/Docs\ \&\ Scripts/uninstall-openzfsonosx.sh
Checking for admin privileges
Please enter your password
Checking for admin privileges
Starting uninstall
Created uninstall log file.../Users/admin/zfsuninstaller.axBz7c
No pools should be imported
/usr/sbin/zpool does not exist.
You will need to export your pool(s) and unload zfs.kext manually before uninstalling.

```

I used the installer from the website & my binaries are in `/usr/local/bin`

I saw this issue as well:  https://github.com/openzfsonosx/zfs/issues/518#issuecomment-230357176

What do you mean by uninstall all on that comment?  Trying to uninstall so I can switch to homebrew cask.

**Comment by ilovezfs** [comment]
Please join the channel https://openzfsonosx.org/wiki/IRC_channel and I'll help you there.
