### ISSUE TITLE
Testing on Sierra kext gets "locked in"

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#529]
master/master @ 3 Sept - I've seen this twice or maybe three times now, after running some portion of the test suite, the kstat.zfs.\* sysctls dissapear, as does /dev/zfs. The kext appears to remain loaded.

I will go through the VM logs and add supporting info.

**Comment by lundman** [comment]
Oh yeah, we solved this.. it was kextunload not quite succeeding due to Sierra blocking when Classes still have references, so kextload would also fail.

We should solve why Sierra thinks we leak Class references when you do zpool-in-zvol.
