### ISSUE TITLE
Symbol not found: _zfs_flags

### ISSUE THREAD

**Issue by kim0** [openzfsonosx/zfs#530]
Trying to load pyzfs bindings on OSX, it gives error "Symbol not found". I reported this to pyzfs folks, who after some investigation say it's actually an OOO issue, so I'm reporting it here FYI

The original issue is at: https://github.com/ClusterHQ/pyzfs/issues/31#issuecomment-244717750

**Comment by lundman** [comment]
b750dd846598cb8c20d6f9ab1bb2e37d1109053d

Hopefully it helps.

**Comment by kim0** [comment]
Thanks a lot! I'll probably have to wait for this to land in a binary update. In the meantime, if any of the dev team is interested in exercising the basics of pyzfs, that would be great :) Thanks folks!

**Comment by lundman** [comment]
Closing this as a new version has been released which (presumably) fixes it :)
