### ISSUE TITLE
Circular header references in ldi_iokit.cpp

### ISSUE THREAD

**Issue by rejsmont** [openzfsonosx/zfs#532]
Hi,

there is an issue with building zfs.kext from ldi-boot branch on Sierra.

There seems to be a circular header reference in `ldi_iokit.cpp`. Included header `<IOKit/IOLib.h>` pulls at some point `<string.h>` that pulls `spl/include/sys/types.h` (and overrides system's <types.h>) that ends up pulling `<kern/kcdata.h>` which in turn includes `<string.h>`

This results an error of undeclared identifier 'strnlen' from `<string.h>`. This error occurs only in Sierra (possible something changed in Kernel.framework) - looking closer into that now.

**Comment by lundman** [comment]
I committed a fix for the strnlen in SPL today, I just wrapped the inclusion of debug.h in extern "C" inside spl-debug.h

https://github.com/openzfsonosx/spl/commit/a96831d3d32d04c01cb6ef48ba1c52ed7b52282b

**Comment by rejsmont** [comment]
awesome! will give it a test ride!

**Comment by rejsmont** [comment]
So i should use the master branch of `spa` and `ldi-boot` branch of zfs? Would that work fine? Should I update the wiki then?

**Comment by lundman** [comment]
You might have to cherry-pick it into SPL's ldi-boot branch

**Comment by lundman** [comment]
excellent!
