### ISSUE TITLE
Current ZFS git/head doesn't build on 10.9

### ISSUE THREAD

**Issue by RJVB** [openzfsonosx/zfs#533]
I've identified 2 issues (to date) which block building the current zfs git/master on OS X 10.9 :
- libzfs_mount.c should test the dir_is_empty_readdir() version  to use witt

`#if defined(MAC_OS_X_VERSION_10_10) && (MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_10)`

and not `#if  (MAC_OS_X_VERSION_MIN_REQUIRED >= MAC_OS_X_VERSION_10_10)`

because MAC_OS_X_VERSION_10_10 is not defined when using the 10.9 SDK (or earlier)
- ntohll() does not seem to exist on 10.9 (and earlier; cf. htonll() ); __DARWIN_OSSwapInt64() does exist though

**Comment by lundman** [comment]
These have all been addressed.
