### ISSUE TITLE
Beachball of death after some time writing data to a netshare sparsebundle using rsync

### ISSUE THREAD

**Issue by yangm97** [openzfsonosx/zfs#543]
Steps to reproduce:

- Make a HFS+ sparse bundle using Disk Utility and store it on a network share (I have used an Airport Time Capsule ac)
- Eject and re-attach without mounting the filesystem: `hdiutil attach -nomount /Volumes/Data/zpool.sparsebundle`
- Create the pool: `sudo zpool create zpool /dev/disk4s2`
- Try to rsync some data into it: `rsync -zaP --exclude-from=/Users/yan/.rsync-excludes --human-readable /Volumes/Samsung/ /Volumes/zpool/sammy/`

Fans go insane, write speeds are close or even better than a HFS+ sparse bundle, but the system stops responding after a while, fans speed down and the only way to regain control over the machine is forcing a shutdown.

**Comment by brendonhumphrey** [comment]
My first thoughts - don't do that.

**Comment by lundman** [comment]
can you run spindump when fans go crazy?

**Comment by brendonhumphrey** [comment]
I did try it for a brief period, it was pretty slow over wifi. Laptop warmed up a bit, but no particular CPU loads visible in top. Probably ran it for 5 minutes or so then the sparse bundle was full, so I stopped.

Maybe you can be a bit more specific about hardware etc.

**Comment by yangm97** [comment]
I wanted to work around my poor NAS choice by adding some ZFS to it ¯\_(ツ)_/¯ 

My machine is a MacBook Pro 13" Early 2011 with 8GB RAM and a Samsug 840 EVO SSD. Rsync was receiving data from a external USB2 hd Samsung S2 Portable formatted with HFS+. I used 5Ghz wifi N, whose max speed is 450Mbps. Sparsebundle size was 1 TB, rsync input was somewhere around 650GB, but the machine freezes after copying somewhere around 35GB or less, and transfer speed slowly goes down before beach ball'ing. 

I will try spindump. Is there any specific doc to look into?

**Comment by brendonhumphrey** [comment]
My laptop is similar 2011 15" quad. 8 GB. Copying from internal SSD. I might try a longer run with the Wifi not being clagged up by netflix tonight.

As for adding some ZFS to your NAS. I'm not sure what you are getting by doing this. Your data would be checksummed for sure. There would be no redundancy/self repair though. You'd have to think carefully about the ramifications in term of robustness or zfs over sparsebundle over smb/afp over whatever mechanisms your NAS has.

**Comment by yangm97** [comment]
It has a 2TB HD and is also my wifi router. I can't get rid of one without losing the other too... so I thought it would be reasonable to use 1TB for time machine backups and the other terabyte would be used for zfs syncing/rsyncing my external hd. That should give me the redundancy needed to protect my external hard drive, right?

**Comment by brendonhumphrey** [comment]
ZFS redundancy works by hosting the data on multiple devices (HDD). You can manage your own redundancy by keeping data in multiple locations. I imagine if this technique worked your house use the NAS as a portion of a ZFS mirror. At any rate when ZFS stores data on a single device, you get the checksumming but not much else.

**Comment by brendonhumphrey** [comment]
Speaking of TM corruption, I host my TM backups on a ZFS filesystem on a server. I snapshot those filesystems, and in the event of failure, just rollback to the most recent working ZFS snapshot.

**Comment by yangm97** [comment]
Like I said, a poor NAS choice 😂 

Only if I knew about ZFS earlier...

**Comment by brendonhumphrey** [comment]
Can confirm I can't get past about 10G written out (8G on first attempt). Machine dies with spinning beachball. Network apparently was alive - it responded to ping, but UI was hosed. This was running one of the new allocator builds.

**Comment by JMoVS** [comment]
in case this is still an issue, please feel free to reopen. But this is 2 years old, closing it for now.

**Comment by yangm97** [comment]
@JMoVS have you tried reproducing it?

**Comment by JMoVS** [comment]
I did not but I'm trying right now, but what you're describing symptom wise (insane fan, no control) sounds a lot like a memory leak and memory getting full, hence no control and slow death until forced shutdown. There were some problems like these in the past, specifically one similar case where writing to a zvol inside a zpool inside a zpool was leaking memory, making it initally fast and then slower and slower until system became unresponsive in direct correlation to amount of data written.

Right now I don't see high fan usage (5Ghz wifi to sparsebundle on a Synology NAS) and source is my internal SSD from my MacBook Pro 13" 2014, nor do I see an increase in memory usage at all (5GB written so far). If you can still reproduce it with 1.8.1 please tell us. ;-)
