### ISSUE TITLE
Attempting to import/create pools can cause a kernel panic (1.6.0 Sierra RC1)

### ISSUE THREAD

**Issue by brkirch** [openzfsonosx/zfs#551]
I cannot import my ZFS storage pool in 1.6.0 because attempting to do so results in a kernel panic (and yes, I did export my pool before upgrading to the new version). Downgrading back to 1.5.2 makes it possible again to import my pool. Here is a panic log from attempting to import my pool in 1.6.0:

*** Panic Report ***
panic(cpu 0 caller 0xffffff8005c05ecd): Kernel trap at 0xffffff8005b045d9, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x00007fa19da0d880, CR3: 0x000000082dbd0075, CR4: 0x00000000003627e0
RAX: 0x0000000000000016, RBX: 0x0000000000000000, RCX: 0x0000000000000018, RDX: 0x00007fa19da0d880
RSP: 0xffffff93b1a436b0, RBP: 0xffffff93b1a43790, RSI: 0x0000000000000000, RDI: 0x0000000000000073
R8:  0x0000000000000000, R9:  0x0000000000000000, R10: 0x0000000000000010, R11: 0x0000000000000008
R12: 0x000000007fffffff, R13: 0x0000000000000000, R14: 0xffffff7f875786e7, R15: 0x0000000000000016
RFL: 0x0000000000010246, RIP: 0xffffff8005b045d9, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007fa19da0d880, Error code: 0x0000000000000001, Fault CPU: 0x0 SMAP fault, PL: 1, VF: 0

Backtrace (CPU 0), Frame : Return Address
0xffffff93b1a43340 : 0xffffff8005af210c 
0xffffff93b1a433c0 : 0xffffff8005c05ecd 
0xffffff93b1a435a0 : 0xffffff8005aa3743 
0xffffff93b1a435c0 : 0xffffff8005b045d9 
0xffffff93b1a43790 : 0xffffff8005b04bc9 
0xffffff93b1a43830 : 0xffffff7f87501f28 
0xffffff93b1a438c0 : 0xffffff8005d2757c 
0xffffff93b1a43b20 : 0xffffff8005d28b15 
0xffffff93b1a43f10 : 0xffffff8005d28716 
0xffffff93b1a43f50 : 0xffffff80060273ea 
0xffffff93b1a43fb0 : 0xffffff8005aa3f46 
      Kernel Extensions in backtrace:
         net.lundman.zfs(1.6)[2B780F96-B012-3E6E-BB70-5081E7C8A9FB]@0xffffff7f87476000->0xffffff7f8771bfff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[3238C6A2-A948-378E-9C53-3883089C1B52]@0xffffff7f86250000
            dependency: net.lundman.spl(1.6.0)[AF614EF1-FE6C-3C64-BDF7-3EBB3FD2056C]@0xffffff7f86280000

BSD process name corresponding to current thread: zpool

Mac OS version:
16D32

Kernel version:
Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
Kernel UUID: C67A8D03-DEAC-35B8-8F68-06FF7B687215
Kernel slide:     0x0000000005800000
Kernel text base: 0xffffff8005a00000
__HIB  text base: 0xffffff8005900000
System model name: iMac17,1 (Mac-B809C3757DA9BB8D)

System uptime in nanoseconds: 21258835613
last loaded kext at 9156034164: com.apple.driver.AppleTopCaseHIDEventDriver	104 (addr 0xffffff7f89466000, size 57344)
loaded kexts:
net.lundman.zfs	1.6.0
net.lundman.spl	1.6.0
at.obdev.nke.LittleSnitch	4724
com.apple.driver.AppleTopCaseHIDEventDriver	104
com.apple.driver.AppleHSBluetoothDriver	104
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.driver.AGPM	110.23.14
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.filesystems.ntfs	3.13
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	127
com.apple.driver.AppleMikeyDriver	278.56
com.apple.driver.AppleHDAHardwareConfigDriver	278.56
com.apple.driver.AppleHDA	278.56
com.apple.driver.AppleGraphicsDevicePolicy	3.13.79
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.iokit.IOBluetoothSerialManager	5.0.3f1
com.apple.kext.AMDFramebuffer	1.4.8
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleIntelSKLGraphics	10.2.2
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelPCHPMC	1.1
com.apple.driver.AppleMuxControl	3.13.79
com.apple.AMDRadeonX4000	1.4.8
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	5.0.3f1
com.apple.driver.AppleBacklight	170.9.10
com.apple.driver.AppleIntelSKLGraphicsFramebuffer	10.2.2
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleSMCLMU	208
com.apple.driver.AppleMCCSControl	1.2.15
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.kext.AMD9000Controller	1.4.8
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.iokit.IOBluetoothUSBDFU	5.0.3f1
com.apple.driver.CoreStorageFsck	540.30.1
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	366.30.3
com.apple.iokit.IOAHCIBlockStorage	295.20.1
com.apple.driver.AppleFWOHCI	5.5.5
com.apple.driver.AppleSDXC	1.7.6
com.apple.iokit.AppleBCM5701Ethernet	10.2.7
com.apple.driver.AirPort.Brcm4360	1130.3.1a5
com.apple.driver.AppleAHCIPort	326
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	172
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleMultitouchDriver	368.7
com.apple.driver.AppleInputDeviceSupport	76.4
com.apple.driver.IOBluetoothHIDDriver	5.0.3f1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	278.56
com.apple.kext.OSvKernDSPLib	525
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleGraphicsControl	3.13.79
com.apple.iokit.IOFireWireIP	2.2.7
com.apple.iokit.IOSurface	153.3
com.apple.iokit.IOBluetoothHostControllerUSBTransport	5.0.3f1
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.3f1
com.apple.iokit.IOBluetoothFamily	5.0.3f1
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	513.1
com.apple.iokit.IOAcceleratorFamily2	289.32
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.AppleHDAController	278.56
com.apple.iokit.IOHDAFamily	278.56
com.apple.iokit.IOAudioFamily	205.12
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleIntelLpssUARTv1	3.0.60
com.apple.driver.AppleIntelLpssUARTCommon	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.kext.AMDSupport	1.4.8
com.apple.AppleGraphicsDeviceControl	3.13.79
com.apple.iokit.IOGraphicsFamily	513.1
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleThunderboltEDMSink	4.1.1
com.apple.iokit.IOSCSIArchitectureModelFamily	394.30.2
com.apple.driver.AppleHIDKeyboard	197
com.apple.driver.AppleThunderboltDPInAdapter	4.6.1
com.apple.driver.AppleThunderboltDPOutAdapter	4.6.1
com.apple.driver.AppleThunderboltDPAdapterFamily	4.6.1
com.apple.driver.AppleThunderboltPCIUpAdapter	2.1.1
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.1
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.driver.CoreStorage	540.30.1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IOFireWireFamily	4.6.5
com.apple.driver.AppleThunderboltNHI	4.1.8
com.apple.iokit.IOThunderboltFamily	6.3.3
com.apple.iokit.IOEthernetAVBController	1.0.3b4
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.DiskImages	444.41.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

**Comment by lundman** [comment]
Can you please turn on keepsyms for us, and panic, so we can see the stack fully

**Comment by brkirch** [comment]
Thanks for the quick response, here's the panic log after doing that:

*** Panic Report ***
panic(cpu 2 caller 0xffffff8011e05ecd): Kernel trap at 0xffffff8011d045d9, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x00007fefd9e1b500, CR3: 0x00000007290980f9, CR4: 0x00000000003627e0
RAX: 0x0000000000000016, RBX: 0x0000000000000000, RCX: 0x0000000000000018, RDX: 0x00007fefd9e1b500
RSP: 0xffffff83ac4936b0, RBP: 0xffffff83ac493790, RSI: 0x0000000000000000, RDI: 0x0000000000000073
R8:  0x0000000000000000, R9:  0x0000000000000000, R10: 0x0000000000000010, R11: 0x0000000000000008
R12: 0x000000007fffffff, R13: 0x0000000000000000, R14: 0xffffff7f974b16e7, R15: 0x0000000000000016
RFL: 0x0000000000010246, RIP: 0xffffff8011d045d9, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007fefd9e1b500, Error code: 0x0000000000000001, Fault CPU: 0x2 SMAP fault, PL: 1, VF: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff83ac493340 : 0xffffff8011cf210c mach_kernel : _panic + 0xec
0xffffff83ac4933c0 : 0xffffff8011e05ecd mach_kernel : _kernel_trap + 0x92d
0xffffff83ac4935a0 : 0xffffff8011ca3743 mach_kernel : _return_from_trap + 0xe3
0xffffff83ac4935c0 : 0xffffff8011d045d9 mach_kernel : ___doprnt + 0xf29
0xffffff83ac493790 : 0xffffff8011d04bc9 mach_kernel : _printf + 0xa9
0xffffff83ac493830 : 0xffffff7f9743af28 net.lundman.zfs : _zfs_vfs_mount + 0x273
0xffffff83ac4938c0 : 0xffffff8011f2757c mach_kernel : _vnode_should_flush_after_write + 0xedc
0xffffff83ac493b20 : 0xffffff8011f28b15 mach_kernel : ___mac_mount + 0x3f5
0xffffff83ac493f10 : 0xffffff8011f28716 mach_kernel : _mount + 0x36
0xffffff83ac493f50 : 0xffffff80122273ea mach_kernel : _unix_syscall64 + 0x24a
0xffffff83ac493fb0 : 0xffffff8011ca3f46 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         net.lundman.zfs(1.6)[2B780F96-B012-3E6E-BB70-5081E7C8A9FB]@0xffffff7f973af000->0xffffff7f97654fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[3238C6A2-A948-378E-9C53-3883089C1B52]@0xffffff7f92450000
            dependency: net.lundman.spl(1.6.0)[AF614EF1-FE6C-3C64-BDF7-3EBB3FD2056C]@0xffffff7f961b9000

BSD process name corresponding to current thread: zpool
Boot args: -v keepsyms=1

Mac OS version:
16D32

Kernel version:
Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
Kernel UUID: C67A8D03-DEAC-35B8-8F68-06FF7B687215
Kernel slide:     0x0000000011a00000
Kernel text base: 0xffffff8011c00000
__HIB  text base: 0xffffff8011b00000
System model name: iMac17,1 (Mac-B809C3757DA9BB8D)

System uptime in nanoseconds: 116617954360
last loaded kext at 74261161125: net.lundman.zfs	1.6.0 (addr 0xffffff7f973af000, size 2777088)
loaded kexts:
net.lundman.zfs	1.6.0
net.lundman.spl	1.6.0
at.obdev.nke.LittleSnitch	4724
com.apple.driver.AppleTopCaseHIDEventDriver	104
com.apple.driver.AppleHSBluetoothDriver	104
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.ntfs	3.13
com.apple.driver.AGPM	110.23.14
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	127
com.apple.driver.AppleMikeyDriver	278.56
com.apple.driver.AppleHDAHardwareConfigDriver	278.56
com.apple.driver.AppleHDA	278.56
com.apple.driver.AppleGraphicsDevicePolicy	3.13.79
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.kext.AMDFramebuffer	1.4.8
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	5.0.3f1
com.apple.driver.AppleIntelSKLGraphics	10.2.2
com.apple.driver.AppleMuxControl	3.13.79
com.apple.AMDRadeonX4000	1.4.8
com.apple.driver.AppleIntelPCHPMC	1.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleBacklight	170.9.10
com.apple.kext.AMD9000Controller	1.4.8
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleSMCLMU	208
com.apple.driver.AppleIntelSKLGraphicsFramebuffer	10.2.2
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	5.0.3f1
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleMCCSControl	1.2.15
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.iokit.IOBluetoothUSBDFU	5.0.3f1
com.apple.driver.CoreStorageFsck	540.30.1
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	366.30.3
com.apple.iokit.IOAHCIBlockStorage	295.20.1
com.apple.driver.AppleFWOHCI	5.5.5
com.apple.driver.AppleSDXC	1.7.6
com.apple.iokit.AppleBCM5701Ethernet	10.2.7
com.apple.driver.AirPort.Brcm4360	1130.3.1a5
com.apple.driver.AppleAHCIPort	326
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	172
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleMultitouchDriver	368.7
com.apple.driver.AppleInputDeviceSupport	76.4
com.apple.driver.IOBluetoothHIDDriver	5.0.3f1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	278.56
com.apple.kext.OSvKernDSPLib	525
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleGraphicsControl	3.13.79
com.apple.iokit.IOSurface	153.3
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.kext.AMDSupport	1.4.8
com.apple.iokit.IOFireWireIP	2.2.7
com.apple.iokit.IONDRVSupport	513.1
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleHDAController	278.56
com.apple.iokit.IOHDAFamily	278.56
com.apple.iokit.IOAudioFamily	205.12
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleIntelLpssUARTv1	3.0.60
com.apple.driver.AppleIntelLpssUARTCommon	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.iokit.IOSerialFamily	11
com.apple.AppleGraphicsDeviceControl	3.13.79
com.apple.iokit.IOAcceleratorFamily2	289.32
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	5.0.3f1
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.3f1
com.apple.iokit.IOBluetoothFamily	5.0.3f1
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.iokit.IOGraphicsFamily	513.1
com.apple.driver.AppleThunderboltEDMSink	4.1.1
com.apple.driver.AppleHIDKeyboard	197
com.apple.iokit.IOSCSIArchitectureModelFamily	394.30.2
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.driver.AppleThunderboltDPInAdapter	4.6.1
com.apple.driver.AppleThunderboltDPOutAdapter	4.6.1
com.apple.driver.AppleThunderboltDPAdapterFamily	4.6.1
com.apple.driver.AppleThunderboltPCIUpAdapter	2.1.1
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.1
com.apple.driver.CoreStorage	540.30.1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IOFireWireFamily	4.6.5
com.apple.driver.AppleThunderboltNHI	4.1.8
com.apple.iokit.IOThunderboltFamily	6.3.3
com.apple.iokit.IOEthernetAVBController	1.0.3b4
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBXHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.DiskImages	444.41.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

**Comment by lundman** [comment]
Best guess is that it matches this line:

```
    printf("%s: fspec '%s' : mflag %04x : optptr %p : optlen %d :"
        " options %s\n", __func__,
        mnt_args.fspec,
        mnt_args.mflag,
        mnt_args.optptr,
        mnt_args.optlen,
        options);
```

**Comment by brkirch** [comment]
Now that I actually have some time available to test things, I've found the issue isn't just my pool - zpool create also crashes (and the crash occurs at the printf line in zfs_vfsops.c every time). The zpool I have is definitely from 1.6.0 since I uninstalled 1.5.2 before installing 1.6.0 and made sure all the files were removed. To be safe I even extracted the files in the installer manually and used diff to compare them to the installed files and everything was the same. Also running "which zpool" in the Terminal returns /usr/local/bin/zpool so there is no possibility the shell is using the wrong zpool.

The crashing seems to be limited to my iMac for some reason - I tried installing 1.6.0 on my MacBook Pro and there were no issues with zpool create or importing my existing pool. The only non-Apple kext I have loaded other than O3X is from Little Snitch, so I tried uninstalling Little Snitch but that didn't help either.

**Comment by lundman** [comment]
So its a SMAP fault, which makes me think you have a new cpu in your box, and clearly we have a copyin problem with that printf

**Comment by brkirch** [comment]
Building from source I found that I still have the same issue, and that `mnt_args.fspec` appears to be the culprit.

The original code that you posted causes a crash, as well as this:
```C
	printf("%s: fspec '%c' : mflag %04x : optptr %p : optlen %d :"
	    " options %s\n", __func__,
	    mnt_args.fspec[0],
	    mnt_args.mflag,
	    mnt_args.optptr,
	    mnt_args.optlen,
	    options);
```
On the other hand, this does not:
```C
	printf("%s: fspec '%p' : mflag %04x : optptr %p : optlen %d :"
	    " options %s\n", __func__,
	    mnt_args.fspec,
	    mnt_args.mflag,
	    mnt_args.optptr,
	    mnt_args.optlen,
	    options);
```

Here's what the above code displayed when I imported a pool with `log stream --source` running:
```
    <zfs`zfs_vfs_mount (zfs_vfsops.c:2075)> zfs_vfs_mount: fspec '0x7ffb71409d10' : mflag 0100 : optptr 0x7fff5387b050 : optlen 4096 : options
```

**Comment by lundman** [comment]
Excellent, I believe then the problem is:

```
            if ( (error = ddi_copyin((void *)data,
                (caddr_t)&mnt_args, sizeof(mnt_args), 0)) ) {
```

That will copy in the whole struct from userland into kernel, except the string ptr.

        if ( (error = ddi_copyinstr((const void *)mnt_args.fspec, osname,
            MAXPATHLEN, &osnamelen)) ) {

This will copy in the string in `fspec` into kernel space, into variable `osname`. Which means we are allowed to use `osname` (and we do) but not `fspec` which we use in one printf.

The printf should be replaced to use `osname`, or removed entirely.

Thanks for your assistance.

**Comment by brkirch** [comment]
Glad to be of help! I can confirm that your commit resolved the issue:
```
      <zfs`zfs_vfs_mount (zfs_vfsops.c:2075)> zfs_vfs_mount: fspec 'testpool' : mflag 0100 : optptr 0x7fff5ba31050 : optlen 4096 : options
```
Thank you!
