### ISSUE TITLE
git/master `zpool import` assert or crash on 10.9.5

### ISSUE THREAD

**Issue by RJVB** [openzfsonosx/zfs#554]
I've built and installed spl 76277fb205c9e2966006e586a7c87672b3f9d97c and zfs 0610c34369c8e384ff5d7a574d4e69c061277aaf on Mac OS X 10.9.5 (self-signing the kexts) and run into an assert or downright crash trying to run `zpool import`.

The assert prints this on the terminal:
```
> zpool import -d /dev
../../module/nvpair/fnvpair.c:395: fnvlist_lookup_uint64: Assertion `nvlist_lookup_uint64(nvl, name, &rv) == 0 (0x2d == 0x0)` failed.
> zpool import -d /dev
../../module/nvpair/fnvpair.c:395: fnvlist_lookup_uint64: Assertion `nvlist_lookup_uint64(nvl, name, &rv) == 0 (0x2d == 0x0)` failed
> zpool import -d /dev
../../module/nvpair/fnvpair.c:395: fnvlist_lookup_uint64: Assertion `nvlist_lookup_uint64(nvl, name, &rv) == 0 (0x16 == 0x0)` failed.
```

I'm attaching the log for the downright crash which is the result of a null-ptr dereference.

It looks like this is a regression that was introduced after the 1.6.1 release (which works fine for me).

**Comment by RJVB** [comment]
[zpool_2017-02-25-135055_Portia.crash.txt](https://github.com/openzfsonosx/zfs/files/801213/zpool_2017-02-25-135055_Portia.crash.txt)

**Comment by ilovezfs** [comment]
Thanks for the report. I'd highly recommend staying on the release tags since master is back to bleeding edge state for the time being.

**Comment by RJVB** [comment]
On Saturday February 25 2017 05:25:31 ilovezfs wrote:
> Thanks for the report. I'd highly recommend staying on the release tags since master is back to bleeding edge state for the time being.

Looks that way indeed, judging from the commit log somebody's been overhauling the undercarriage!

**Comment by lundman** [comment]
So we disabled DEBUG in userland in normal build, so did you use --enable-debug when you built it? 
Since you are triggering ASSERTS.

Kernel death is in `_platform_strcmp` which would imply a NULL string, perhaps even the same problem. I do wonder which string it is looking up.

**Comment by RJVB** [comment]
On Saturday February 25 2017 21:44:31 Jorgen Lundman wrote:
>So we disabled DEBUG in userland in normal build, so did you use --enable-debug when you built it? 
>Since you are triggering ASSERTS.

I wondered about that too, but no. That line has a VERIFY statement which remains active in release builds.

>Kernel death is in `_platform_strcmp` which would imply a NULL string, perhaps even the same problem. I do wonder which string it is looking up.

Fortunately these are regular crashes and aborts, not KPs. At least, whatever goes wrong does so while still in userland.

**Comment by lundman** [comment]
720d15c

**Comment by RJVB** [comment]
On Monday February 27 2017 19:10:46 Jorgen Lundman wrote:
>720d15c

"zpool import with NULL reference"

meaning `zpool import [-d dir]` to obtain the list of available pools? If so, isn't it surprising that wasn't caught before committing? It's always the first thing I try after upgrading ZFS, under the assumption that at least I won't bork a pool trying to import it if something's really wrong. (And possibly that's also why I only got a userland crash and not a KP?)

**Comment by lundman** [comment]
Not surprising at all, commits from openzfs go through heavier testing than we do, so they are assumed to be good, until proven guilty.

**Comment by RJVB** [comment]
On Tuesday February 28 2017 02:52:09 Jorgen Lundman wrote:
>Not surprising at all, commits from openzfs go through heavier testing than we do, so they are assumed to be good, until proven guilty. 

Are they merged automatically then, without something like a CI system which could perform certain basic tests?

**Comment by lundman** [comment]
luckily, setting up a tester VM isn't too bad, so if you want to run tests for the project that would be great.

**Comment by RJVB** [comment]
On Tuesday February 28 2017 03:33:52 Jorgen Lundman wrote:
>luckily, setting up a tester VM isn't too bad, so if you want to run tests for the project that would be great.

Exactly what do you have in mind?

FWIW, even if I had unlimited ressources to allocate, certain public remarks and actions made at my expense not that long ago make me a bit reluctant...

That said, I should still have a Parallels VM config for OS X 10.9 that works with a clone of my boot disk. I haven't fired it up for years now so I'm not even sure Parallels still works.

**Comment by brendonhumphrey** [comment]
@RJVB Lundman is merely suggesting that anybody that takes code from Master in such an early stage of a development cycle is taking a significant risk, and should be mature enough to run their own QA - i.e. check it out, manually or with the test suite, and report any issues.

Its so early in the cycle that I don't think many of the minor developers have even run that code, or it has been put through the automated test machine - in fact I think Lundman is waiting for me to relocate the tests into a new location to facilitate merging of upstream changes from Illumos.

Having said that its a rather amusing regression.

FWIW You should never have attempted to do what you did without coordinating with us. I had an issue with you packaging code in development when you have little or no insight into the status of the codebase and whether the code was suitable for use. However well intentioned, you risked our reputation by your actions. You risked peoples data by your actions. The fact that private requests made to macports regarding your efforts were rebuffed required me to act strongly in public. 

If you think that means I have something against you, that is not actually the case.

**Comment by RJVB** [comment]
What I don't get is how untested commits can end up in an official repo. One could expect that the person making the commit would have test it first. OpenZFS code may be well tested, but not on Mac so there must be almost any number of reasons why it could fail (to build or otherwise).

>FWIW You should never have attempted to do what you did without coordinating with us. I had an issue with you packaging code in development when you have little or no insight into the status of the codebase and whether the code was suitable for use. However well intentioned, you risked our reputation by your actions. You risked peoples data by your actions. The fact that private requests made to macports regarding your efforts were rebuffed required me to act strongly in public. 

Water under the bridge and I'm not particularly interested in retracing who said what, but do not ever think that I make packaging attempts available publicly without having tested the result in daily use. Especially if it concerns a product that I've had issues with myself. IIRC the port always had "-devel" in its name, which in principle is a sufficient indication to MacPorts users that installing it is to be done only if you're aware of the potential risks. But above all, this was only a proposal (I have no commit rights to the ports tree) and if some MacPorts members "rebuffed" you in a private exchange that should never have been an excuse to attack *my* reputation the way it was. That happened behind my back, I have no idea what was said or by who.

**Comment by brendonhumphrey** [comment]
You are inferring that top of tree should always be stable - we have made no such statement. Generally speaking master is pretty good, but from time to time regressions will appear.

Thanks for your bug report. I don't think anything more needs to be said on this topic.

**Comment by lundman** [comment]
I must have last word!

**Comment by RJVB** [comment]
Did I leave you enough time for those famous last words? :)

Just wondering: a number of you core developers must have a pretty good idea when master is more or less stable enough and has sufficient improvements compared to the latest stable release that it could be made accessible for more wide-spread testing in the wild?

Would it be an idea to maintain a "testing" branch, synced with master whenever appropriate and receiving revert commits where necessary? I realise it's (a bit?) of extra work but it might also generate some useful feedback.

Or maybe there already exist snapshot builds somewhere that should be relatively safe for testing by users who know what they're getting into?

**Comment by ilovezfs** [comment]
>Would it be an idea to maintain a "testing" branch, synced with master whenever appropriate and receiving revert commits where necessary?

No.

>Or maybe there already exist snapshot builds somewhere that should be relatively safe for testing by users who know what they're getting into?

No.

**Comment by RJVB** [comment]
Can someone please expand on the 1st "no"?

**Comment by lundman** [comment]
You need to disable SIP, or have own certificate to compile, it isn't really expected that people do that unless they are into developing and keep an eye on the commits. For that there are binary releases, and tagged milestones.

As for how I work, new code go in branches and are tested before going into master. There is a shortcut for openzfs commits since they have heavier testing than us, so they are assumed to be "good". But since we are different platforms, that goes wrong sometimes. Whomever finds problems report them and we work on it. Every now and then we run tester to confirm it works.  

Soon tester framework will be in the actual zfs repo, which may mean we can do automatic testing even better.

**Comment by RJVB** [comment]
Let's assume that people interested in following "bleeding edge" on a bit of a safe distance know how to build and use this kind of software - they may not even be concerned by SIP. Knowing when master is really bleeding edge or not is a different matter and that has been used as an argument against my MacPorts port proposition. I accept that, just keeping an eye on commits doesn't mean you understand all their possible implications unless you're heavily involved in ZFS development. That's a different kind of involvement than one where you just keep an eye on commits and the useful features or fixes they introduce. That's an aspect that's a lot easier to understand and it's how I follow ZoL and ZoO development.  

I understand that the binary releases are supposed to be stable enough not to discourage people from using them for production, but they aren't very frequent. On Linux I do stick with releases because I run off ZFS but my use of ZFS is completely different on Mac. There I'm interested in any development that might increase performance or reduce memory footprint with a reasonable assurance that my data is safe and KPs shouldn't happen (where that "reasonable assurance" could come from automated testing or personal observation by core devs). Maybe those tagged milestones can provide the indication I'm looking for. Alternatively I could just ask but that's a bit cumbersome since I was kicked off the IRC channel ...

FWIW: The main pool I use on Mac sits on an SD card inside the card reader on which I keep a number of huge git repos that I don't need to have around continuously. My MBP cannot use the latest and fastest SD cards and enabling lz4 compression gives both a nice space gain AND makes the SD card bearably slow.

**Comment by ilovezfs** [comment]
You are now unbanned.
