### ISSUE TITLE
1.6.1 Boot issue with pools created on FreeBSD

### ISSUE THREAD

**Issue by evansus** [openzfsonosx/zfs#555]
Since FreeBSD sets the 'wholedisk' flag on all vdevs (for better or worse), we wind up skipping over these devices when updating IORegistry boot information.
While you can boot from the pool, kextcache will not automatically update the boot helper volume.

Should be easily resolved by dropping the wholedisk check here:
https://github.com/openzfsonosx/zfs/blob/zfs-1.6.1/module/zfs/zfs_boot.cpp#L2159
https://github.com/openzfsonosx/zfs/blob/zfs-1.6.1/module/zfs/zfs_boot.cpp#L2257

**Comment by lundman** [comment]
Seems reasonable, since its a zfs_boot.cpp, isn't it a file you added? Certainly no zfs_boot upstream :)

**Comment by evansus** [comment]
Yes indeed, just wanted to document the issue for anyone else with FreeBSD pools who may run into this, since it is supported as of 1.6.1 release.

**Comment by ilovezfs** [comment]
Closed via #556.
