### ISSUE TITLE
Unable to set file flags

### ISSUE THREAD

**Issue by evansus** [openzfsonosx/zfs#561]
chflags on a file appears to succeed, but the flag is not set. Tested with xattr=on and xattr=sa.

Inability to set uchg, schg, and other flags mean files are left writable when they should be locked down. Lots of files and directories have the restricted flag set in the /System folder.

Could be a cause of #544, as all the fonts in /System/Library/Fonts have the restricted flag set on HFS.

**Comment by evansus** [comment]
On further review, the /System/Library/Fonts files have restricted set, but /Library/Fonts contents do not (only have the compressed flag set on HFS) - and yet some of the /Library fonts still fail to validate.

**Comment by evansus** [comment]
user flags do work: uchg, uappend, hidden, opaque, nodump. Super user flags do not: schg, sappend, archived, restricted.

**Comment by lundman** [comment]
zfs_vnop_osx_lib.c has convert between xnu flags and bsd flags, I'm not sure if I mapped the system flags?

**Comment by evansus** [comment]
Ah interesting - testing on freebsd and comparing the vnops code, only schg is supported, not uchg.

```
[evansus@host ~]$ touch test-u test-s
[evansus@host ~]$ chflags uchg test-u
chflags: test-u: Operation not supported
[evansus@host ~]$ sudo chflags uchg test-u
chflags: test-u: Operation not supported
[evansus@host ~]$ chflags schg test-s
chflags: test-s: Operation not supported
```
(as expected)

```
[evansus@host ~]$ sudo chflags test-s
[evansus@host ~]$ ls -alo test-s
-rw-r--r--  1 evansus  wheel  schg,uarch 0 Mar  5 19:29 test-s
```

And same for uappend/sappend. So it seems we just have the opposite is all. And of course 'restricted' is macOS-specific. FreeBSD has quite a few other flags, differentiates hidden from uhidden, etc. etc.

**Comment by evansus** [comment]
and btw uarch was default, `chflags nouarch` works, but `chflags uappend` and uchg still fail.

**Comment by ilovezfs** [comment]
Are there flags that hfs/apfs handle that we're not handling?

**Comment by lundman** [comment]
57da731214fbf89543726eb147b2f25edeedb802
