### ISSUE TITLE
spl VMEM_INITIAL is too small?

### ISSUE THREAD

**Issue by lundman** [openzfsonosx/zfs#564]
The ASSERT is `spl-vmem.c` is triggered;

```
	if (vmp->vm_cflags & VMC_POPULATOR) {
		ASSERT(vmem_populators < VMEM_INITIAL);
```

`VMEM_INITIAL` is currently set to `21` but we appear to create more areas these days. This means that 

```
		vmem_populator[atomic_inc_32_nv(&vmem_populators) - 1] = vmp;
```

will scribble outside allocated area.

**Comment by rottegift** [comment]
> we appear to create more [arenas] these days

???

They are enumerated in the comments in vmem_init().   I re-counted and do not see a wrong count, and as I run with debugging and asserts I cannot understand why you're getting it and not me...

**Comment by rottegift** [comment]
Oh, you're doing windows stuff.  Have you changed the vmem_create flags in spl-kmem.c?

They should not be trying to use the early segments, as they should be coming into existence with their vmem_source values pointing to an active arena.

Once vmem_vmem arena exists, the VMEM_INITIAL logic is no longer used.

(vmem_vmem is arena 21)

```
: smd ; sysctl -h kstat.vmem|grep vmem_source | cat -n
     0 NULL
     1	kstat.vmem.vmem.spl_default_arena_parent.vmem_source: 0
     2	kstat.vmem.vmem.spl_default_arena.vmem_source: 1
     3	kstat.vmem.vmem.bucket_4096.vmem_source: 1
     4	kstat.vmem.vmem.bucket_8192.vmem_source: 1
     5	kstat.vmem.vmem.bucket_16384.vmem_source: 1
     6	kstat.vmem.vmem.bucket_32768.vmem_source: 1
     7	kstat.vmem.vmem.bucket_65536.vmem_source: 1
     8	kstat.vmem.vmem.bucket_131072.vmem_source: 1
     9	kstat.vmem.vmem.bucket_262144.vmem_source: 1
    10	kstat.vmem.vmem.bucket_524288.vmem_source: 1
    11	kstat.vmem.vmem.bucket_1048576.vmem_source: 1
    12	kstat.vmem.vmem.bucket_2097152.vmem_source: 1
    13	kstat.vmem.vmem.bucket_4194304.vmem_source: 1
    14	kstat.vmem.vmem.bucket_8388608.vmem_source: 1
    15	kstat.vmem.vmem.bucket_16777216.vmem_source: 1
    16	kstat.vmem.vmem.bucket_heap.vmem_source: 1
    17	kstat.vmem.vmem.heap.vmem_source: 16
    18	kstat.vmem.vmem.vmem_metadata.vmem_source: 2
    19	kstat.vmem.vmem.vmem_seg.vmem_source: 18
    20	kstat.vmem.vmem.vmem_hash.vmem_source: 18
    21	kstat.vmem.vmem.vmem_vmem.vmem_source: 18
    22	kstat.vmem.vmem.kmem_metadata.vmem_source: 17
    23	kstat.vmem.vmem.kmem_msb.vmem_source: 22
    24	kstat.vmem.vmem.kmem_cache.vmem_source: 22
    25	kstat.vmem.vmem.kmem_hash.vmem_source: 22
    26	kstat.vmem.vmem.kmem_log.vmem_source: 22
    27	kstat.vmem.vmem.kmem_oversize.vmem_source: 17
    28	kstat.vmem.vmem.kmem_va.vmem_source: 17
    29	kstat.vmem.vmem.kmem_default.vmem_source: 28
    30	kstat.vmem.vmem.taskq_id_arena.vmem_source: 0
    31	kstat.vmem.vmem.zfs_file_data.vmem_source: 16
    32	kstat.vmem.vmem.zfs_metadata.vmem_source: 16
```
(taskq_id_arena is legit 0 because it's an ID arena that just serves up numbers not memory)

(everything whose vmem_source is 1 has special logic for the allocator/freer)

**Comment by lundman** [comment]
Yeah, I quickly tried the same assert on osx and it died, so I created the ticket, but then realised I had my test the wrong way around, so OSX is fine. It is just looping too many times on windows, it finishes the vmem_init (LOWBITS->HIGHBITS) at about 29, which is a few more than 21. I'll step through it today, and everyone just ignore this issue :)
