### ISSUE TITLE
Installation failure on macOS 10.12.3

### ISSUE THREAD

**Issue by tiennou** [openzfsonosx/zfs#567]
I upgraded recently to Sierra, and wanted to update my "old" (1.5.3 it seems) Yosemite installation to the newest 1.6.1 release. I ran the installer pkg, which failed with an error.

Relevant [except](https://gist.github.com/tiennou/24a106559d7babd1f90239fc92513b2e) from /var/log/install.log

What I can understand is that the scripts first [uninstall](https://gist.github.com/tiennou/24a106559d7babd1f90239fc92513b2e#file-install-log-L56) binaries, then tries to [unload kexts](https://gist.github.com/tiennou/24a106559d7babd1f90239fc92513b2e#file-install-log-L262), which failed for me, with the following error message :
```
# kextunload -b net.lundman.zfs
(kernel) Can't unload kext net.lundman.zfs; classes have instances:
(kernel)     Kext net.lundman.zfs class net_lundman_zfs_zvol has 1 instance.
Failed to unload net.lundman.zfs - (libkern/kext) kext is in use or retained (cannot unload).
```

Now, I'm forced to reboot, because I have no user-land tools left to check what might be wrong (eg. `zpool` and `zfs` are gone from `/usr/local/bin`).

Maybe changing the order to "unload kexts", "uninstall" would be better ? I'm not even sure how the system would react to a husked filesystem bundle...

**Comment by ilovezfs** [comment]
After rebooting and running the installer again, I assume it's fine now?

**Comment by tiennou** [comment]
Expectedly, it did.

**Comment by ilovezfs** [comment]
Great.
