### ISSUE TITLE
sharenfs=rw=@127.0.0.1/32 results in nfsd error on el capitan

### ISSUE THREAD

**Issue by simt2** [openzfsonosx/zfs#570]
I'm using openzfs 1.6.1 on OSX 10.11.6 with the stock nfsd. Creating a dataset exported via nfs like this:
`sudo zfs create -o quota=1G -o reservation=1G -o sharenfs=rw=@127.0.0.1/32 test/pv-1`

Results in the following nfsd error:
```
Apr 28 09:52:39 simons-mbp nfsd[34263]: Bad net: 127.0.0.1/
Apr 28 09:52:39 simons-mbp nfsd[34263]: exports:6: error processing options: -network 127.0.0.1/ -mask 0.0.0.0
```

The generated line in `/etc/exports`: 
```
"/Users/simt/src/go/src/project/test/pv-1"	-network 127.0.0.1/ -mask 0.0.0.0`
```

Also reproduced with other Networks like `192.168.0.0/16`.

**Comment by lundman** [comment]
So any input of notation "ip.ip.ip.ip/mask" will leave a "/" ?

**Comment by simt2** [comment]
Yes, it appears like that. Is it possible that the nsfd of MacOS Sierra ignores the slash? The only odd thing about my setup is that im still using El Capitan.

**Comment by ilovezfs** [comment]
Assuming this is fixed now due to https://github.com/openzfsonosx/zfs/commit/5c1b9e532309ce1ef478aa598fc4a6fd145c1ca3.
