### ISSUE TITLE
zfs.fs prevents Kobo from auto-mounting

### ISSUE THREAD

**Issue by cbreak-black** [openzfsonosx/zfs#571]
When zfs.fs is present, attaching a Kobo ebook reader does not result in it being mounted. Instead it has to be manually mounted via diskutil or the Disk Utility application. Removing the .fs and rebooting allows auto-mounting to take place. This was verified with fdaec6a57.

[diskutil.txt](https://github.com/openzfsonosx/zfs/files/969413/diskutil.txt)
[metadata.txt](https://github.com/openzfsonosx/zfs/files/969414/metadata.txt)

**Comment by cbreak-black** [comment]
I changed the whole volume probe order to 20000 from 2000, this resolved this particular issue. In a first attempt I tried to change it to 200, but that stopped even HFS+ volumes in CoreStorage encryption from auto-mounting.

`
                        <key>FSProbeOrder</key>
                        <integer>20000</integer>
`

**Comment by lundman** [comment]
0b2232a
