### ISSUE TITLE
zfstester running zfs_change-key/zfs_change-key_location wait for input

### ISSUE THREAD

**Issue by lundman** [openzfsonosx/zfs#604]
When tester runs, and it gets to `zfs_change-key/zfs_change-key_location` it will timeout and be KILLED after 10 mins, unless you push return on the console.

Which comes from this line
```
log_mustnot zfs change-key -o keylocation=foobar $TESTPOOL/$TESTFS1
```

and it outputs:

```
Key change error: invalid keylocation
Key change error: Failed to add salt to properties.
```

Tracking the code down, it appears that this code:

<details>
  <summary> libzfs_crypto:zfs_crypto_verify_rewrap_nvlist </summary>
  <p>

```
	new_props = zfs_valid_proplist(zhp->zfs_hdl, zhp->zfs_type, props,
	    zfs_prop_get_int(zhp, ZFS_PROP_ZONED), NULL, zhp->zpool_hdl,
	    B_TRUE, errbuf);

	if (new_props == NULL) 
		goto error;

```
</details>

---

The call to `zfs_valid_proplist()` returns `NULL` and we exit, but `ret` is not updated, so we return 0.  ZOL has `ret` uninitialised. (oh dear)

Making sure `ret` is set to an error code, or, adding `ret = EINVAL;` before the `goto error;` both work.  

There will be two error codes emitted;

```
Key change error: invalid keylocation
Key change error: encryption failure
```

but it no longer waits for input for no reason.

**Comment by lundman** [comment]
This this should probably be corrected in ZOL, I'm hoping @tcaputi will take a look at it when he has time. :)

**Comment by tcaputi** [comment]
I have already fixed this locally as part of fixing some coverity defects. The PR for ZOL should be ready by the end of this week. Right now I am fighting some ztest issues that have come up since the patch also enables ztest to create encrypted datasets. You can follow the WIP here: https://github.com/zfsonlinux/zfs/pull/659

**Comment by lundman** [comment]
Superb, thanks.

**Comment by lundman** [comment]
f2e3bf1ac16cc25f5ab4050db6c8b756c5bb7775
