### ISSUE TITLE
ruby DIr.glob return dataset name not the dir name.

### ISSUE THREAD

**Issue by chunlinyao** [openzfsonosx/zfs#611]
When I have a dataset `foo`  mounted on `/bar`  execute `ruby -e 'print Dir.glob("/bar");printf "\n"'` will return  `["/foo"]`

Enviroment:
macOS high sierra 10.13
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
OpenZFS on OS X 1.6.2 RC1 for High Sierra.pkg

I don't known which system call ruby using, maybe it's a bug of ruby.

**Comment by lundman** [comment]
When you have hfs mounted as /foo, what does it return? Oh you are talking about the name, not the leading slash.

If you use `dtruss -f ruby ...` it'll tell you which system call, but I can look into it

**Comment by chunlinyao** [comment]
I created an zvol and formated as apfs, mounted on an folder, `Dir.glob` can get correct folder name.

**Comment by ilovezfs** [comment]
Right. zvols are just vanilla block storage.

**Comment by lundman** [comment]
a44e8a2dda33b19fd35f56c671c4d1dd982b844f
