### ISSUE TITLE
Spotlight needs re-indexing after reboots on High Sierra 10.13.0 and O3X 1.6.2 RC1

### ISSUE THREAD

**Issue by crayonshin** [openzfsonosx/zfs#613]
If I re-index my ZFS volumes by adding them to Spotlight Privacy tab and removing them, they get indexed and I can find things using Spotlight without issue. However, if I reboot, I can no longer find anything on my ZFS volumes unless I re-index. The mds_stores process appears after a reboot so perhaps it would eventually finish and work again but I waited a few hours and it did not so I just force a re-index again which gets it working quickly.

As a reminder Lundman, you wrote "Hmm maybe we somehow broke the "last mounted time" that spotlight uses" in a thread about this on the O3X forums. Here are the links to that thread and a separate one I had created in the Hackintosh section. Thank you!

https://openzfsonosx.org/forum/viewtopic.php?f=26&t=2826&p=8321#p8321

https://openzfsonosx.org/forum/viewtopic.php?f=15&t=3079

**Comment by lundman** [comment]
Does the mds rescan trigger if you do

```
zfs umount $dataset
zfs mount $dataset
```
?

It does not appear to trigger when I try it on master, if someone with the problem could check that as well, would be good.

**Comment by crayonshin** [comment]
I can try it. How will I know if it it triggered?

Is it just the presence of the mds_stores process in Activity Monitor? Because I see that process even now but still can’t find anything in my ZFS volumes. I rebooted a few hours ago but did not force a rescan the way I know how (adding volumes to Spotlight Privacy tab and removing them again). If a rescan started upon reboot I think I would be able to search by now. Please let me know what to look for after unmount/remount and I will report back. Thanks!

**Comment by lundman** [comment]
Ah well, if you have lots of data, sitting in `top -o -cpu` should show the mds process taking a long time as it scans your mount. You could turn on debug printing, but that would get really noisy. Perhaps `mdutil -s /Volumes/$mount` would tell you if it really is reindexing everything

**Comment by crayonshin** [comment]
I have one zpool with one dataset. When I run mdutil -s on both I get “Indexing Enabled”.

When I unmount and then remount my dataset, I see a new process in top called “mdworker”. Starts at 99% CPU for a second, then goes to 50% and then just drops off. I don’t hear the 4 hard drives working like I should when it’s indexing. I now see I have 3 separate mdworker processes in Activity Monitor but all have CPU 0%. Two have “User” as me and the third “_spotlight”.

**Comment by crayonshin** [comment]
The only way I know to force a reindex is by adding my zpool and dataset to the Spotlight Privacy tab in System Preferences.

As soon as I remove them from from Privacy, I hear my 4 disks grinding away because it’s indexing. A bunch of new mds related processes start up and I can start finding stuff deep in my ZFS dataset even after just a minute. Here’s what Activity Monitor looks like seconds after I’ve removed the ZFS volumes from the Spotlight Privacy tab:

**Comment by lundman** [comment]
If you add it to the "ignore list" in Spotlight Privacy Tab, then remove it, it has to rescan everything - so that is a normal thing

**Comment by crayonshin** [comment]
Yeah but I don’t know of another way to get indexing started. 

It does finish indexing really quickly though. I only hear the disks for maybe 5 minutes then everything I try to find on my ZFS volumes is found quickly. I have 3TB of data but it’s mostly static and does not change much so maybe it’s quick because Spotlight can see it’s data already on the volumes and knows most folders have been unchanged since the last index.
