### ISSUE TITLE
zdb crashes when trying to run

### ISSUE THREAD

**Issue by spitfire** [openzfsonosx/zfs#614]
I'm using ZFS (installer version 1.7.0) on macOS 10.13.1 beta 4 and ddb crashes whenever I try to run it:

➜  ~ zdb -l
[1]    40673 segmentation fault  zdb -l
➜  ~ zdb
[1]    40795 segmentation fault  zdb

**Comment by lundman** [comment]
Confirmed, looks like zdb from the installer dies very early in main. Compiled from master is fine however. Researching further

**Comment by lundman** [comment]
ced236a5da6e72ea7bf6d2919fe14e17cffe10f1
