### ISSUE TITLE
Deleting files doesn't free up space

### ISSUE THREAD

**Issue by BugraK** [openzfsonosx/zfs#619]
I wrote under some related issue, but it seems closed so I opened a new one.

If I copy some file to the dataset free space decreases, both in Finder and zfs list. But if I delete something free space doesn't change, again both in Finder and zfs list. I tried zfs unmount/mount and zpool export/import with no success. Am I missing something?

Thanks.

**Comment by BugraK** [comment]
After further research I stumbled upon [this](https://github.com/zfsonlinux/zfs/issues/1548) issue on OpenZFS on Linux page. It is suggested to create a new dataset using `xattr=sa` instead of `xattr=on`. I was wondering if `xattr=sa` could cause me any trouble with Finder tags or Spotlight? I understand that xattrs are necessary for them to operate. Is creating a dataset with `xattr=sa` suitable for a standart Mac OS X enviroment?

**Comment by BugraK** [comment]
I used zfsnap.sh to take and delete snapshots, but for some reason it didn't delete old snapshots, so they were taking space. Maybe this helps some other noob like me :)

**Comment by ericdarwin** [comment]
Same thing just happened to me. I just deleted around 5TB on 60TB pool and cleared all snapshot, but no space reclaimed.
