### ISSUE TITLE
[enhancement] warn about write-locked media

### ISSUE THREAD

**Issue by RJVB** [openzfsonosx/zfs#620]
I got this message about the pool on an SD card that I had removed and reinstalled into my MBP's SD slot:

```
zpool import -d /dev nif64
cannot import 'nif64': I/O error
        Destroy and re-create the pool from
        a backup source.
```

That pool still worked less than a week ago, and a dd of the entire device didn't show the tell-tale events of a dead flash storage device in the System.log .

The pool imported fine under Linux (nothing of its actual content showed up except a few -empty- directories, very weird). Only when I tried to mount the tiny additional partition on the card did I see a warning about it being write-locked.

Turns out the SD card lock slider had been moved just enough to trip the sensor in the card reader; putting it the open position gave me my pool back.

IOW, it'd be helpful if this kind of situation could be detected and reported in the error message. It's not the 1st thing you think to check when you see the error message above.

**Comment by lundman** [comment]
Ah that does seem like a bug, we should probably trickle down the EROFS error properly, then display the correct error message.

**Comment by RJVB** [comment]
Or import the pool read-only and warn about that? I'm not sure if I'd like that; I usually don't (on Linux) when I realise a FS was mounted in RO mode without having asked for it explicitly, but with media that have a physical write lock (remember floppies? :)) it *would* make sense.

**Comment by ilovezfs** [comment]
The less magic, the better. It should just be an error.

**Comment by RJVB** [comment]
Unless an explicit option was given to import the pool RO maybe? I'll try to remember later today to check if this already works, in fact.

**Comment by ilovezfs** [comment]
I could so mentioning the availability of `import -o readonly=on` in the error message but not actually doing it automatically.

**Comment by RJVB** [comment]
> -o readonly=on

Works, too. No errors when I write-lock my SD card, and all pool content is there.

**Comment by brendonhumphrey** [comment]
https://github.com/openzfsonosx/zfs/commit/ae9eec4ce71bc0d08c2fd1cfa34dec81c9d5ed5e
