### ISSUE TITLE
libcompression not present in 10.10.5? 

### ISSUE THREAD

**Issue by alanruttenberg** [openzfsonosx/zfs#624]
Commit afff6a36366b7be2f13054e50b3d27a81b026419 looks like it isn't compatible with 10.10.5. Compiling spl yields

```
Making all in KernelExports
./kextsymboltool -arch x86_64 -import allsymbols -export zfs.exports -output KernelExports_64
exported name not in import list: _decmpfs_cnode_alloc
exported name not in import list: _decmpfs_cnode_free
```

**Comment by lundman** [comment]
Ah oops, it was fixed, but those two functions was accidentally left in `zfs.exports`. You can remove them, or git pull SPL again for my fix.

**Comment by alanruttenberg** [comment]
fixed, thanks!
