### ISSUE TITLE
Hardlinked Files Produce Zombies

### ISSUE THREAD

**Issue by ajdudman** [openzfsonosx/zfs#627]
OpenZFS on OSX fails GNU libtool version 2.4.6 in function func_extract_an_archive() doing file locking.
I found this bug building macports glib2 on High Sierra by running:
`port build glib2 +universal`
+universal variant uses hardlinked lock files producing the failure.
It is followed by another failure upon cleaning after the first:
`port clean glib2`
${worksrcpath}/libtool becomes a zombie.

spl-1.7.0-1-g9f0861d
zfs-1.7.0-15-g57da73121

`sw_vers`
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47

`uname -v`
Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64

GNU libtool puts lockfiles in deep subdirectories.  One will suffice here.
This can be simplified as follows:
```
set -e
cd /private/var/tmp
mkfile -n 100m diskimage1
mkfile -n 100m diskimage2
vdisk1=$(hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount diskimage1 | awk '{print $1;}')
vdisk2=$(hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount diskimage2 | awk '{print $1;}')
zpool create -f -o ashift=12 -O casesensitivity=insensitive -O normalization=formD tank mirror ${vdisk1:?} ${vdisk2:?}
zfs create -o mountpoint=/var/tmp/bug -o canmount=on tank/bug
show() { ls -ale@O s ; stat -x s ; }
cd /private/var/tmp/bug
date > s
show
mkdir a
ln s a/b.lock
rm a/b.lock
rmdir a
show
set +e
# This fails.
# Expect "ln: d.lock: Operation not permitted".
ln s d.lock
# Expect "1".
echo $?
show
# This fails too.
# Expect "rm: s: File exists"; then with repetition "rm: s: No such file or directory"
rm s
# Expect "1".
echo $?
show
````

This runs successfully on APFS and JHFSX filesystems on the same MacPro.
This runs successfully on ZFS in SmartOS January 18, 2018.

I think corruption occurs when the last files hardlinked are in different directories and one is removed.
The remaining file now relies on the parent directory of the other.
When that is removed, the file becomes a zombie.
It can be seen by ls(1) and stat(1).
In a straightforward manner, it cannot be linked by ln(1) nor unlinked by rm(1) or unlink(1).
The zombie file, s, can be unlinked after unmounting and mounting its filesystem, tank/bug.

Please fix hardlinks, so we may use OpenZFS on OSX for software development.

**Comment by ilovezfs** [comment]
`+universal` is too dated for us to be concerned about at this point, sorry.

**Comment by lundman** [comment]
Could be the cache entry for the hardlink lingers

**Comment by ilovezfs** [comment]
```
bash-3.2# ./script.sh 
+ set -e
+ cd /private/var/tmp
+ mkfile -n 100m diskimage1
+ mkfile -n 100m diskimage2
++ hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount diskimage1
++ awk '{print $1;}'
+ vdisk1=/dev/disk4
++ hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount diskimage2
++ awk '{print $1;}'
+ vdisk2=/dev/disk5
+ zpool create -f -o ashift=12 -O casesensitivity=insensitive -O normalization=formD tank mirror /dev/disk4 /dev/disk5
+ zfs create -o mountpoint=/var/tmp/bug -o canmount=on tank/bug
+ cd /private/var/tmp/bug
+ date
+ show
+ ls -ale@O s
-rw-r--r--  1 root  wheel  - 29 Feb 10 02:21 s
+ stat -x s
  File: "s"
  Size: 29           FileType: Regular File
  Mode: (0644/-rw-r--r--)         Uid: (    0/    root)  Gid: (    0/   wheel)
Device: 49,14   Inode: 14    Links: 1
Access: Sat Feb 10 02:21:56 2018
Modify: Sat Feb 10 02:21:56 2018
Change: Sat Feb 10 02:21:56 2018
+ mkdir a
+ ln s a/b.lock
+ rm a/b.lock
+ rmdir a
+ show
+ ls -ale@O s
-rw-r--r--  1 root  wheel  - 29 Feb 10 02:21 s
+ stat -x s
  File: "s"
  Size: 29           FileType: Regular File
  Mode: (0644/-rw-r--r--)         Uid: (    0/    root)  Gid: (    0/   wheel)
Device: 49,14   Inode: 14    Links: 1
Access: Sat Feb 10 02:21:56 2018
Modify: Sat Feb 10 02:21:56 2018
Change: Sat Feb 10 02:21:56 2018
+ set +e
+ ln s d.lock
+ echo 0
0
+ show
+ ls -ale@O s
-rw-r--r--  2 root  wheel  - 29 Feb 10 02:21 s
+ stat -x s
  File: "s"
  Size: 29           FileType: Regular File
  Mode: (0644/-rw-r--r--)         Uid: (    0/    root)  Gid: (    0/   wheel)
Device: 49,14   Inode: 14    Links: 2
Access: Sat Feb 10 02:21:56 2018
Modify: Sat Feb 10 02:21:56 2018
Change: Sat Feb 10 02:21:56 2018
+ rm s
+ echo 0
0
+ show
+ ls -ale@O s
ls: s: No such file or directory
+ stat -x s
stat: s: stat: No such file or directory
bash-3.2# 
```
Cannot reproduce it either.

**Comment by ilovezfs** [comment]
We'll leave it open till someone has a chance to test master on High Sierra

**Comment by lundman** [comment]
Seems quote broken
```
 panic(cpu 0 caller 0xffffff80081fd235):
/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4570.20.62/bsd/vfs/vfs_syscalls.c:4764 Assertion failed: retry_count < MAX_AUTHORIZE_ENOENT_RETRIES
KBY: getparent(0xffffff800f5127c0) != parent_vp(0xffffff801438c5d0)
```
seems to do with links in not-the-parent-dir

**Comment by lundman** [comment]
81c6857644d2d24b2356c5e51d8ebe3e4459df9b

We would fail to set the correct `parentid` once a hardlink went back to being a regular file.

```
bash-3.2# date > s
bash-3.2# show() { ls -ale@O s ; stat -x s ; }
bash-3.2# show
bash-3.2# mkdir a
bash-3.2# ln s a/b.lock
bash-3.2# rm a/b.lock
bash-3.2# rmdir a
bash-3.2# show
bash-3.2# set +e
bash-3.2# ln s d.lock
bash-3.2# echo $?
0
bash-3.2# rm s
bash-3.2# echo $?
0
bash-3.2# rm d.lock
```

**Comment by ajdudman** [comment]
Thank you very much.  With this fix, both `port build glib2 +universal` and subsequent `port clean glib2` macports commands succeed.

**Comment by lundman** [comment]
excellent, thanks for reporting back.
