### ISSUE TITLE
Spotlight broken with dev/disk

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#637]
When switching the pool property com.apple.devdisk to on for a dataset, spotlight not longer works on that dataset.

To reproduce:

switch it to on and check indexing status with mdutil -E

**Comment by lundman** [comment]
```
# zpool create -f BOOM mirror disk2 disk1
/dev/disk5s1   19Gi   31Ki   19Gi     1%      17            39616306    0%   /Volumes/BOOM
# mdutil -E /Volumes/BOOM/
/Volumes/BOOM:
	Indexing enabled.

# ./cmd.sh zfs create -o com.apple.devdisk=on BOOM/lower
/dev/disk5s2   19Gi   31Ki   19Gi     1%      17            39615071    0%   /Volumes/BOOM/lower
# mdutil -E /Volumes/BOOM/lower/
/Volumes/BOOM/lower:
	Indexing enabled.
```

It is well known (to me) that changing the value can be done at any time, but the dataset needs to be remounted by hand. No automatic remounting is done, yet.
