### ISSUE TITLE
com.apple.devdisk breaks zfs_is_mounted

### ISSUE THREAD

**Issue by cbreak-black** [openzfsonosx/zfs#646]
zfs_is_mounted checks if a dataset is mounted by searching mtab for the zfs_name. This happens in zfs_is_mounted -> is_mounted -> libzfs_mnttab_find -> getmntany.
There, the expected name in the mnt_special field, which is filled with the dataset name, is compared against f_mntfromname, which contains a /dev/diskX entry if devdisk is enabled.

This causes zfs_is_mounted to return false incorrectly.

**Comment by cbreak-black** [comment]
This fixes the problem: https://github.com/cbreak-black/zfs/commit/ada20ab9ffd93cb525a9cfb89f7ec08026d58b81, but I'm not sure if it's fixed in the correct way.

**Comment by cbreak-black** [comment]
I'm not sure if it is related to mimic_hfs, but I don't think so because I didn't turn that on. It however does relate to com.apple.devdisk, which seems to be enabled by default for root datasets. If it is enabled, the zfs_is_mounted function returns false even if the root dataset is mounted. ZetaWatch uses this call to check if a dataset is mounted, and the result for devdisk enabled datasets is always false because the dataset isn't found in mnttab.

**Comment by cbreak-black** [comment]
I call it like this:

https://github.com/cbreak-black/ZetaWatch/blob/20249fa7fcaaf602812ddf326f38491f079bad23/ZFSWrapper/ZFSUtils.cpp#L91-L94

When I use "mount" on the command line, normal datasets are listed differently than those with devdisk. They don't have a /dev/disk entry but list the full dataset name, and zfs_is_mounted finds them. But for devdisk datasets, a fake /dev/disk file is listed instead and the dataset isn't found in the mount list and not considered mounted. (At least this is what happens when I step through the library code with LLDB)

**Comment by lundman** [comment]
Ah I see the problem now. OK, this should fix things:

ed02f938095a5cfb52f9cd0993649220ddb2af58

**Comment by cbreak-black** [comment]
That code looks a lot more compact than my attempt at a solution :)

**Comment by lundman** [comment]
I couldn't figure out what you meant, since we already "expand" all /dev/disk paths, for "all mounts".  Turns out that was not true when passing in a name to search for :)

**Comment by JMoVS** [comment]
sounds like it's fixed ;-)
