### ISSUE TITLE
High Sierra + current versions of O3X == Spotlight problems

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#649]
Hi,

ever since I upgraded to High Sierra, I've been observing obscure problems where spotlight randomly stops reporting results. This manifests as Mail.app not searching through my Emails anymore (I store `~/Library/Mail` on ZFS). This is mitigated by killing the processes `mds` and `mds_stores` in activity monitor.

Recently, I got aware that I'm not the only person with this problem as a podcast host, running the current version of OpenZFS + High Sierra experienced the same problem.

**Comment by lundman** [comment]
If that happens, could you run `spindump` and check if any/those dead processes are stuck inside ZFS stack?  Are they eating CPU? (Ie stuck in a circular loop of lookups)

**Comment by JMoVS** [comment]
I will try, yes, or try and send the spindump result here

**Comment by JMoVS** [comment]
Spindump is available here:
https://cl.ly/sxAU

**Comment by JMoVS** [comment]
still happening every so often

**Comment by JMoVS** [comment]
apparently, maybe, possibly, we're lucky
"The original report on this issue, Bug ID 38382859, is closed as resolved in macOS 10.14 betas."

**Comment by JMoVS** [comment]
com.apple.mimic_hfs is needed to get spotlight to work inside apps accessing spotlight search, which is weird, but seems like an issue in Mac OS as spotlight search itself on a normal dataset works
