### ISSUE TITLE
Scrub relative prioritization

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#65]
In #mac-zfs venture37:
loaded new kext & imported pool, now waiting for scrub to finish but CPU is pegged at 100%
fan is going crazy too
"kernel_task" at 105%
reads in/sec 163, out 8
86.0G scanned out of 480G at 25.8M/s, 4h20m to go
USB 3.0 my passport, standalone disk

My understanding is that scrub is supposed to be a low priority thread, but venture37's description makes it sound like scrub doesn't know it's supposed to yield mostly.

**Comment by JMoVS** [comment]
scrubbing works without insane CPU loads, so I'm closing this now
