### ISSUE TITLE
Time Machine

### ISSUE THREAD

**Issue by fumoboy007** [openzfsonosx/zfs#66]
Time Machine does not see any mounted ZFS volumes (even though I enabled TMShowUnsupportedVolumes). It does when ZEVO is used.

**Comment by jeff-dagenais** [comment]
I've just setup a zvol which I formatted hfs+ using diskutil. (1.3.1-rc5) I confirm that the newly formatted drive is not offered as a choice of TM target in the preferences GUI.

I forced time-machine to use it by saying `sudo tmutil setdestination /Volumes/My\ TM\ Partition`. Seems to be working quite well.

Aside from the recovery scenario which might require a bit of improvising, does anyone see any issues with working like this?

Did the infamous zvol rework from zol late last year ever make it to mac? I seem to be getting decent performances on zvols...

**Comment by JMoVS** [comment]
I would guess this works now with issue116lite being merged
