### ISSUE TITLE
aes-ccm fail on ZVOLs.

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#670]
ZVOLs right now don't work in native encrypted environments it seems.

I have a pool where the pool's root dataset is encrypted and trying to create a zvol always results in 

`cannot open 'zfsintern/zvoltesting': I/O error`

It afterwards lists it in zfs list but never creates it so that I would see it in diskutil list.

Additionally, this action makes zpool status show errors on the pool (that go away after a zpool clear and zpool scrub).

**Comment by lundman** [comment]
Confirmed
```
# ./cmd.sh zfs create -V 1G -o encryption=on -o keyformat=passphrase BOOM/vol
Enter passphrase:
Re-enter passphrase:
cannot open 'BOOM/vol': I/O error
```

**Comment by JMoVS** [comment]
workaround: use `-o encryption=aes-256-gcm` at creation time.

**Comment by lundman** [comment]
Only aes-ccm appears to fail when creating a ZVOL, aes-gcm works ok. If I `git revert` the assembler commits, aes-ccm also works. (Can we have a ./configure --disable-assembler please).

Most likely it is due to that zvol will encrypt a dnode with `enc_len == 0` (but nonce and aad is set). We had to put in that len=0 was valid in the C code, so possibly the assembler equivalent is missing.

**Comment by cbreak-black** [comment]
I shall take a look at this. I wonder if Linux also has this problem. Since it doesn't appear to happen with the C version, there's likely either a difference between the C and ASM version, or some issue in the glue code.

**Comment by lundman** [comment]
If ZOL had this problem, we would know about it, reasonably sure it is an OSX issue only. I think perhaps bisect might be an idea, as it definitely was working in the past.

it is just odd that it is only ccm.

**Comment by cbreak-black** [comment]
I tried to bisect it, and the results seem to point to 17d90445310db49b7235cdfabbbd15e9504fe8bc as a possible culprit. This commit was the first one to panic when creating a zvol in an aes-ccm encrypted pool. Later commits don't panic anymore, but still produce an error.

**Comment by lundman** [comment]
```
		ccm_ctx->ccm_pt_buf = kmem_alloc(ccm_ctx->ccm_data_len,
		    kmflag);
		if (ccm_ctx->ccm_pt_buf == NULL) {
			rv = CRYPTO_HOST_MEMORY;

(lldb) p ccm_ctx->ccm_data_len
(size_t) $1 = 0
```
illumos/OSX/Windows kmem does not allow len=0, ZOL's does.

**Comment by lundman** [comment]
85a50c658102d5b9fbe9ad9424892dcf8e4463f2 45484ea320a0e0496740bb79aa2b2ec9de533ad1
