### ISSUE TITLE
Memory leak with zvol

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#672]
I'm using a zvol that I created with ` -o encryption=aes-256-gcm -o volblocksize=4096`Under a root that is created with standard encryption. 

Now that I'm writing with ddrescue to rdiskX whereas X is the disk of the zvol, somewhere we're leaking memory as kernel physical memory just grows and grows and grows until my computer runs out of memory. Usually after around 45 minutes to 60 minutes of running ddrescue

**Comment by lundman** [comment]
5570d011320c7af5d1da06ec92ec5310efa83800

**Comment by JMoVS** [comment]
could this result in
