### ISSUE TITLE
zfs pools not importing on boot

### ISSUE THREAD

**Issue by kiva113** [openzfsonosx/zfs#682]
I have a mac running Mojave where there are 3 pools, on disks that are SATA connected.

Sometimes all 3 pools import on boot and Regularly I will have only 1 of the 3 pools import automatically. 

A manual zpool import -a will import them all. 

On my mac
Mojave - 10.14.3 currently, but have seen it on earlier revs 
Over multiple versions of the git branch  
currently zfs 1.8.1-16-g47ca57040) & spl 1.8.1-4-g9fb091e

Is this a known issue? If so, is there something I can create in the boot up process where it will import all pools to prevent issues with Applications starting, but missing their storage?

**Comment by JMoVS** [comment]
@kiva113 Can I close this issue or do you still experience the problem?

**Comment by kiva113** [comment]
I'm not exporting the pools on shutdown. 

Looking at the zpool import all script 
Does not the following line accomplish the same thing there already?
"${ZPOOL}" import -a -d /var/run/disk/by-id

I had suspected that the wait time on the ${INVARIANT_DISKS_IDLE_FILE} was part of the issue, but after adding some lines in there to confirm that contents of the zpool.cache and the devices, the problem ultimately went away. Now it just seems to take a very long time to import the pools at startup, but it is importing them all.

You can close this out, since I can no longer recreate the issue consistently.

**Comment by JMoVS** [comment]
@kiva113 Thank you for reporting this nevertheless. If it bubbles up again, feel free to reopen or file a new bug
