### ISSUE TITLE
zfs clone does not restore Factor.app

### ISSUE THREAD

**Issue by tgunr** [openzfsonosx/zfs#687]
I have rolling snapshots created by Sanoid. Today somehow I killed my Factor.app binary and so I created a clone but the clone does not contain the MacOS folder with the binary.

This is running 
https://openzfsonosx.org/w/images/3/30/OpenZFS_on_OS_X_1.8.2.dmg

**Comment by JMoVS** [comment]
Could you please specify more what the problem is, what you're snapshotting, which locations on disk you are talking about, which system you're using?

If you "somehow" killed your factor.app binary, are you sure it should be present in the snapshot that you cloned?

**Comment by tgunr** [comment]
Well crap, I can’t seem to duplicate. Just tried a snapshot and clone of the snapshot and it worked as expected. 
Close as can’t duplicate I suppose.

**Comment by JMoVS** [comment]
maybe you cloned the dataset and not a snapshot by accident? Anyway, thx for the follow-up
