### ISSUE TITLE
sending from bookmark is broken

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#701]
As of ~https://github.com/openzfsonosx/zfs/commit/eda681b5045fd1510704a031abb618b614bf3465~ instead cec1a66ea128736343741b7e83dae788629d9e , sending from bookmarks is broken and fails with a ZFS error:

`internal error: Unknown error: -1029`

~Reverting https://github.com/openzfsonosx/zfs/commit/eda681b5045fd1510704a031abb618b614bf3465 and the subsequent https://github.com/openzfsonosx/zfs/commit/3dd6e94c9516f097a05a1bfd126af73e18c5ee45 solve this issue~

See comments below

**Comment by JMoVS** [comment]
Reproducing it is easy:

2 Pools needed. `PoolA` and `PoolB`

```

zfs snap PoolA@start
zfs bookmark PoolA@start PoolA#start
zfs send -R PoolA@start | zfs recv -u PoolB/PoolA

zfs destroy PoolA@start

zfs snap PoolA@second
zfs send -i PoolA#start PoolA@second | zfs recv -u PoolB/PoolA

```

results in 

```
internal error: Unknown error: -1029
```

**Comment by martellini** [comment]
>< JMoVS> we're (OpenZFSonOSX) are running into a problem with zfs sends from boomarks as of the deferred resilver commits, can someone running master on ZOL quickly check if incremental sending from bookmarks works? https://github.com/openzfsonosx/zfs/issues/701
>< JMoVS> or not "quickly" but at least check it? ;-)

```
root@zol-gd93d4b1:~# cat /proc/sys/kernel/spl/gitrev
zfs-0.8.0-rc3-141-gd93d4b1
root@zol-gd93d4b1:~# 
root@zol-gd93d4b1:~# zfs snap pool/dataset1@start
root@zol-gd93d4b1:~# zfs bookmark pool/dataset1@start pool/dataset1#start
root@zol-gd93d4b1:~# zfs send -Lcev pool/dataset1@start | zfs recv -u pool/testing/dataset1
full send of pool/dataset1@start estimated size is 12.6K
total estimated size is 12.6K
TIME        SENT   SNAPSHOT pool/dataset1@start
root@zol-gd93d4b1:~# 
root@zol-gd93d4b1:~# zfs destroy pool/dataset1@start
root@zol-gd93d4b1:~# 
root@zol-gd93d4b1:~# zfs snap pool/dataset1@second
root@zol-gd93d4b1:~# zfs send -i pool/dataset1#start pool/dataset1@second | zfs recv -u pool/testing/dataset1
root@zol-gd93d4b1:~# zfs list -t all -r pool/testing/dataset1
NAME                           USED  AVAIL     REFER  MOUNTPOINT
pool/testing/dataset1           24K  55.2M       24K  none
pool/testing/dataset1@start      0B      -       24K  -
pool/testing/dataset1@second     0B      -       24K  -
root@zol-gd93d4b1:~# 
```

**Comment by JMoVS** [comment]
thx @martellini ! Looks like it's a porting issue then ;-)

**Comment by JMoVS** [comment]
I did some more bisecting and figured out that my first bisect was wrongly marked as "working", so the commit in question should be fine.

I now nailed it down to cec1a66ea128736343741b7e83dae788629d9e60 - Add basic zfs ioc input nvpair validation

**Comment by JMoVS** [comment]
I cannot cleanly revert cec1a66ea128736343741b7e83dae788629d9e60 in master though because apparently 29e8f741bb37ac82cffe3a127dc6cd2825232270 touches the same area

**Comment by JMoVS** [comment]
fixed in `async_zget3` after the great ioctl change.
