### ISSUE TITLE
issue with parallel zfs create/send

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#717]
Eversince commit 8d7a713e91f7f4594c63e9c851fe926faee3d6d5 there is a problem where many parallel zfs create don't reliably error out anymore. The offending commit is 8d7a713e91f7f4594c63e9c851fe926faee3d6d5. Could you please check, if you find any obvious mismerges or sth like that?

**Comment by JMoVS** [comment]
Causes https://github.com/zrepl/zrepl/issues/179

**Comment by aabc123** [comment]
Will zrepl work on Linux?  Could you try this on ZOL 0.8.0/0.8.1?

**Comment by JMoVS** [comment]
@aabc123 in general zrepl woke on linux, I'm not sure though if I can test it. Don't know if @problame tested it on ZOL 0.8 or 0.8.1 though

**Comment by problame** [comment]
I run zrepl between 2 ZoL 0.8.1 installations, but the dev setup is still on 0.7.

**Comment by aabc123** [comment]
Can you build head of master but revert that commit just to be sure?

**Comment by JMoVS** [comment]
I tried with @lundman - causes other issues on master. But I verified it by running 0460c3c83df323dfbf451453779e28d92d02b23c - which is the last known good commit and works.

Then compiling with 8d7a713e91f7f4594c63e9c851fe926faee3d6d5 and the problem appears.

Spindump for when compiling only with the first known-bad-commit 8d7a713e91f7f4594c63e9c851fe926faee3d6d5:

https://d.pr/free/f/5cQSob

**Comment by JMoVS** [comment]
compiled master with #define HAVE_LARGE_STACKS in dmu_send.c results in no improvement and this spindump:
https://d.pr/free/f/W7Ha1Q

**Comment by JMoVS** [comment]
it looks like this https://d.pr/free/i/Q8bx9b

**Comment by JMoVS** [comment]
@problame Can you maybe help us and tell us what's happening? zrepl tries to send to the dataset? Or does it try to create it first? What exactly is erroring out here when it prints 
```
ocean                                                 STEP-ERROR (step 0/1, 1.4 MiB/1.3 MiB)                                                                                                                                                            
            server error: zfs exited with error: exit status 1                                                                                                                                                                                                    
            stderr:                                                                                                                                                                                                                                               
            cannot create 'zfssnaps': missing dataset name                  
```

**Comment by problame** [comment]
Yes, it's trying to create `zfssnaps`, which is the pool on your system that is not always imported IIRC.
See https://github.com/zrepl/zrepl/issues/179#issuecomment-500158994 for the relevant code paths.

**Comment by JMoVS** [comment]
yep, exactly. So it's trying to `zfs create` the top level datase?

**Comment by problame** [comment]
Yes. This will be fixed at some point, just don't have the time ATM.
The fix will be to abort placeholder creation if the first component of the dataset path doesn't exist, and return an error like `pool %q not imported`.
