### ISSUE TITLE
Encryption commands should print error reason

### ISSUE THREAD

**Issue by athre0z** [openzfsonosx/zfs#724]
Commands surrounding encryption fail silently when used incorrectly. e.g.

```
dd if=/dev/zero bs=512m count=1 of=/tmp/throwaway
sudo zpool create throwaway /tmp/throwaway
sudo zfs create -o encryption=on -o keyformat=passphrase throwaway/enc
>> meow
```

Will fail (due to the password being to short, I guess?) and have the command return an error code, but won't print any reason on why it failed. The same thing applies for `change-key`.

I think that printing the reason to `stderr` would increase usability immensely.

**Comment by aabc123** [comment]
Is this with the 1.9.0 release?  There's a bug in that where zfs doesn't print out errors.  It's fixed in 1.9.1-rc1.

**Comment by athre0z** [comment]
Yes. Sorry, I should have clarified the version I'm using and didn't realize there was an RC. I'll upgrade and see if it resolves this.

Also, I'm glad that the MacPro monitor stand [is finally supported](https://openzfsonosx.org/wiki/Changelog#OpenZFS_on_OS_X_1.9.1_2019-0.3F-.3F.3F). I nearly wet my pants when reading the changelog :D

**Comment by athre0z** [comment]
Thanks, 1.9.1 indeed resolved the issue!
