### ISSUE TITLE
ZFS volumes excluded from Time Machine

### ISSUE THREAD

**Issue by mauricev** [openzfsonosx/zfs#731]
I can't backup ZFS volumes even with com.apple.mimic_hfs set to on with Time Machine under Mojave. It seems this was an issue in the past that had been addressed, but it's back.

**Comment by JMoVS** [comment]
you cannot backup volumes that are enabled with com.apple.devdisk=on if I remember correctly. Does that solve it for you?

**Comment by Fnuxus** [comment]
> I can't backup ZFS volumes even with com.apple.mimic_hfs set to on with Time Machine under Mojave. It seems this was an issue in the past that had been addressed, but it's back.

You may find this solution helpful: https://openzfsonosx.org/forum/viewtopic.php?f=11&t=3408
