### ISSUE TITLE
Hardware-accelerated AES encryption/decryption

### ISSUE THREAD

**Issue by fumoboy007** [openzfsonosx/zfs#765]
I am experimenting with encrypted datasets. The performance of `aes-256-ccm` has been abysmal.

Does ZFS use the AES-NI CPU instructions if available? If so, how can I tell?

**Comment by cbreak-black** [comment]
The code is in `module/icp/asm-x86_64/aes/aes_aesni.S`. By default, the fastest is supposed to be selected, among generic x86_64 aesni. There is `sysctl kstat.zfs.darwin.tunable.icp_aes_impl`, which should tell you that. Trying to change it gave me a KP :).

I benchmarked performance quickly, here's what BlackMagic speed test gave me (on an SSD that could be quite a bit faster), using aes-256-gcm (which is the recommended cipher I think).

<img width="778" alt="zfs-aes-gcm" src="https://user-images.githubusercontent.com/227017/79901015-71645c80-840f-11ea-9233-9ab524965aa2.png">
