### ISSUE TITLE
how can i create block dev as on linux

### ISSUE THREAD

**Issue by FishyFine** [openzfsonosx/zfs#800]
on linux,the block dev will be under /dev/zvol/ and it’s name is as same as which is shown follow command ‘zfs list’.
but on Mac os, it‘s will be /dev/disk*.How can i make the openZFS create zvol as linux?

**Comment by lundman** [comment]
The same way, yes, it is /dev/disk* but we also create symlinks in /var/run/zfs/ that point to the /dev/disk*. These are side-effects to how macOS does block devices.
