### ISSUE TITLE
2.1.99: `zsysctl` sets tunable incorrectly

### ISSUE THREAD

**Issue by dmzimmerman** [openzfsonosx/zfs#801]
In implementing the solution presented in #799, using the latest build of 2.1.99 available from the OpenZFS forums, I discovered that when I run `sudo /usr/zfs/bin/zsysctl -f /etc/zfs/zsysctl.conf`, I don't get the results I expect. The contents of my `/etc/zfs/zsysctl.conf` are:
```
kstat.zfs.darwin.tunable.zfs_arc.max=8589934592

```
and I had set that tunable by hand on the command line before trying `zsysctl` (my motivation for trying it manually in the first place is that it was not setting the tunable on boot). When I run `zsysctl`, I get:
```
kstat.zfs.darwin.tunable.zfs_arc.max: 8589934592 -> 0
```
If I then run it again, I get:
```
kstat.zfs.darwin.tunable.zfs_arc.max: 0 -> 0
```

Whereas, what I was expecting was for it to set the tunable to 8589934592.

**Comment by dmzimmerman** [comment]
This is no longer an issue in current versions, so I'm going to close it.

**Comment by lundman** [comment]
Oh yeah, I forgot to mention i fixed it, thanks for reporting it
