### ISSUE TITLE
zio_add_child, spl_mutex_enter panic

### ISSUE THREAD

**Issue by ilovezfs** [openzfsonosx/zfs#87]
This one has been reported at least twice now.

brendon:
http://bpaste.net/raw/Cl8y24jgS6Auc7JQU9AJ/

Kyahx:
https://gist.github.com/Kyahx/50577072eb5a5f8b43e4

**Comment by sbytnar** [comment]
16 GB RAM, 10.10.5, openzfsonosx 1.3.1 (Mar 31, 2015 binaries installed.)
Randomly occurs. Longest uptime in the last week or so: 21 hours. Shortest: 3 minutes.

Tue Aug 25 21:57:45 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff7fb007f460): "mutex_enter: locking against myself!"@spl-mutex.c:233
Backtrace (CPU 0), Frame : Return Address
0xffffff822b423ad0 : 0xffffff802f92ad21 mach_kernel : _panic + 0xd1
0xffffff822b423b50 : 0xffffff7fb007f460 net.lundman.spl : _spl_mutex_enter + 0x25
0xffffff822b423b70 : 0xffffff7fb013b415 net.lundman.zfs : _zio_add_child + 0x4f
0xffffff822b423bb0 : 0xffffff7fb013b85e net.lundman.zfs : _zio_create + 0x372
0xffffff822b423c10 : 0xffffff7fb013c1ab net.lundman.zfs : _zio_ioctl + 0x14f
0xffffff822b423cb0 : 0xffffff7fb013c13c net.lundman.zfs : _zio_ioctl + 0xe0
0xffffff822b423d50 : 0xffffff7fb013c6cf net.lundman.zfs : _zio_flush + 0x29
0xffffff822b423d70 : 0xffffff7fb01397eb net.lundman.zfs : _zil_commit + 0x792
0xffffff822b423e90 : 0xffffff7fb012aa8a net.lundman.zfs : _zfs_fsync + 0x88
0xffffff822b423ec0 : 0xffffff802fb5c34d mach_kernel : _vfs_purge + 0x632d
0xffffff822b423f50 : 0xffffff802fe4b376 mach_kernel : _unix_syscall64 + 0x296
0xffffff822b423fb0 : 0xffffff802fa344a6 mach_kernel : _hndl_unix_scall64 + 0x16
      Kernel Extensions in backtrace:
         net.lundman.spl(1.3.1)[B4F958D8-B538-36E9-86E6-A9F7B89B422A]@0xffffff7fb0076000->0xffffff7fb00aafff
         net.lundman.zfs(1.3.1)[969D7160-64A1-3420-9AFA-738C7D20A3AC]@0xffffff7fb00ab000->0xffffff7fb0259fff
            dependency: com.apple.iokit.IOStorageFamily(2.0)[D0ABB996-2084-3A05-A166-5951D925EF80]@0xffffff7fb0047000
            dependency: net.lundman.spl(1.3.1)[B4F958D8-B538-36E9-86E6-A9F7B89B422A]@0xffffff7fb0076000

BSD process name corresponding to current thread: mds_stores
Boot args: -v keepsyms=y

Mac OS version:
14F27

Kernel version:
Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
Kernel UUID: 58F06365-45C7-3CA7-B80D-173AFD1A03C4
Kernel slide:     0x000000002f600000
Kernel text base: 0xffffff802f800000
__HIB  text base: 0xffffff802f700000
System model name: Macmini5,2 (Mac-4BC72D62AD45599E)

System uptime in nanoseconds: 2530833182349
last loaded kext at 314736208989: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7fb30e7000, size 69632)
last unloaded kext at 396267656296: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7fb30e7000, size 61440)
loaded kexts:
com.sonnettech.SonnetSATABlockStorage	2.2.9
net.lundman.zfs	1.3.1
net.lundman.spl	1.3.1
com.sonnettech.driver.SonnetSATA	2.2.9
... the rest are Apple kexts.
