### ISSUE TITLE
homedir on zfs: Applications sometimes lose size and position persistence data

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#89]
I see this quite frequently - open your favourite application - mail.app, terminal, safari (probably others). The application will open in a position on the screen that is not the last saved position. It can be half offset off the screen for instance. Oftentimes it will have the wrong size or partially incorrect widget layout (again, possibly from size info).

Generally speaking closing the application and restarting will restore it to proper (default?) position and size.

Chance of reproducing is probably <5% for any open/close cycle of an app. Nevertheless I have seen this a fair bit.

**Comment by JMoVS** [comment]
@rottegift @brendonhumphrey If this is still the case, feel free to reopen but if I remember the IRC chat correctly, it usually works nowadays
